### ISSUE TITLE
What is snap relative to ?

### ISSUE THREAD

**Issue by jide** [taye/interact.js#1]
I do not understand to what element snap coordinates are relative.

There are 2 ways to define snap : By directly setting interact.snap or interact(element).snap. Does the first one sets a global snap, whereas the second one sets the snap for the element ? (I guess so).

When setting a snap, we can set "x" and "y" coordinates for each point, but are these coordinates relative to the document ? To the first positioned parent from the element ? To the element itself ?

Thanks for your help, interact.js is a really good work, doing just what it should.

**Comment by taye** [comment]
Snapping can now be relative to different points on the target element. See #133 and http://interactjs.io/docs/snapping/#relativepoints.
