### ISSUE TITLE
Issue on dropzones with 1.10.20 release

### ISSUE THREAD

**Issue by jules-w2** [taye/interact.js#1016]
Hey @taye 

I found a problem on dropzones with the new version (1.10.20).
We detect an interaction but it is not the correct zone which is selected in the event.

I'm sure it comes from this update, because it's working well on 0.10.19  and lower.

Just change https://unpkg.com/interactjs@1.10.20/dist/interact.js by https://unpkg.com/interactjs@1.10.19/dist/interact.js and this jsfiddle and it this will work as it should

Do you know what's the problem ?

https://jsfiddle.net/nasmj1dc/6/

Bests

**Comment by bartvermeulen1** [comment]
I'm having the same issue. Switching back to version 1.10.19 and it works again.

**Comment by xiaoqingb** [comment]
the same case, rollback to 1.10.19 will be ok

**Comment by jurjanpaul** [comment]
Same.

**Comment by JustinWingChungHui** [comment]
I'm also having the same issue

**Comment by daniyal4v** [comment]
Same here, it drops only in the first element.

**Comment by jules-w2** [comment]
thanks @taye 
It's working
