### ISSUE TITLE
(interactjs.io) JS / HTML / CSS / Demo only-tabs/toggles occasionally fail

### ISSUE THREAD

**Issue by petetnt** [taye/interact.js#109]
There's a small (non-fatal) issue on the http://interactjs.io site: On the demo elements, the JS / HTML / CSS  / Demo only- tabs/toggles sometimes (non-permanently) fail to open the correct section.

Steps to produce: 
1. Open http://interactjs.io/
2. Start switching between JS/HTML/CSS/Demo only-tabs
3. Occasionally the tab gets highlighted, but doesn't show the correct section. Eventually the tabs recover and the correct section is shown again

Happens on: Firefox 33, Chrome 38, IE11 on WP8.1 (so most likely on all platforms)

**Comment by taye** [comment]
I can no longer reproduce this issue. The tabs are changed with JS using interact.js' `tap` event. There was probably a bug in interact.js that's since been fixed.
