### ISSUE TITLE
Improving Code Quality / Approachability 

### ISSUE THREAD

**Issue by Ceane** [taye/interact.js#110]
I really like this library, however it's just 1 file and well over 5000 lines long. Do you have plans to break things up into Common JS modules, add JSDoc comments and code quality tools?

It'd be really nice also there were natural hooks for other frameworks and libraries (i.e custom mixin for React or Angular module).

**Comment by Ceane** [comment]
@tedvanderveen  I have not. With Angular 2 changes, I would like to work on something that can be used between the newer and older versions. Starting with services would be the right way and then in the future adding directives for specific animations would be good. Maybe ignoring that Angular exists would be the way to go.

**Comment by tedvanderveen** [comment]
Indeed, that's exactly what I ended up doing, an Angular service with all Interactjs specific implementations, using Angular for the initial one-way binding of the template. Thanks!

**Comment by stephen-james** [comment]
@taye firstly thanks for an awesome library, really really good and has helped me loads.  I would be keen to help split it up into microlibraries / modules to allow for devs to only require the bits they need, so please ping me if you are wanting to go this direction and would like a hand.  I'm @stephenhjames on twitter.

**Comment by taye** [comment]
@stephen-james Thank you! I'd really appreciate it. I should have time to discuss it with you this some time this weekend. I think a private chat on [Gitter](https://gitter.im) would be the easiest way. I'll let you know when I'm free.

**Comment by stephen-james** [comment]
@taye, great!  I'm signed in to Gitter app so hopefully will get notifications when you shout
