### ISSUE TITLE
How to test draggable object programmatically

### ISSUE THREAD

**Issue by hellochar** [taye/interact.js#129]
I'm trying to unit test some functionality related to dragging on my site; I use interact like this:

`interact(element).draggable({ onstart: functionToTest })`

I'm trying to simulate a drag by manually triggering events with jQuery:

`$(element).mousedown(); ...`

But it seems that interact doesn't respond to these manual triggers at all. Am I doing something wrong here?

**Comment by vishnupriyagali** [comment]
on using fire method, events are not triggering.

On clicking button, a dynamic image should be appended and should auto drop on base image/div.
`
        $('.mobule-box').click(function () {

               $('#blocks').append('<img class="draggable drag-drop"  id="imageId" src = "assets/img  /SVG/image.png" ></div>');

                     interact("#imageId") 
                                .on('dragstart', function (event) {
                                      alert(1);
                                });
                              .fire("dragstart");
       })
`

When the image is appended to HTML page, how to trigger dragstart, dragenter, dragleave events without dragging an element?

**Comment by derwaldgeist** [comment]
The fire() approach does not seem to work, as the object created via interact(element) in the unit testing code seems to be a different object than that that is created in the tested code.

**Comment by derwaldgeist** [comment]
I also tried the approach manually triggering events. But these won't trigger the listeners either.

**Comment by derwaldgeist** [comment]
I got the event to be fired via interact#fire() by storing the interact() in a variable and read this via the unit testing script. However, the event fired by fire() does not seem to implement all event methods that are typically available. My code breaks because stopPropagation() is not available.

**Comment by dmo-odoo** [comment]
@taye Hello,

I can't use interactable.fire since the point of our testing framework is to test the behavior of the software from the outside so I don't have any reference to the interactable object at that point, so I'm trying to simulate a user drag using pure javascript MouseEvents. 

I have tried firing MouseEvents for mouseenter, mousedown then mousemove events on the element on which I set draggable, but onstart and onmove are never called. Am I missing something ?

**Comment by dmo-odoo** [comment]
@taye and others who might be trying the same thing, I found out how to do it.
Interact.js actually listens to PointerEvents, not MouseEvents, and it listens for them on document, not the element itself, so it needs to bubble.
```
var pointerDownEvent = new PointerEvent("pointerdown", {
    bubbles: true,
    // any mouseEvent contructor value
});
el.dispatchEvent(pointerDownEvent);
```
```
var pointerMoveEvent = new PointerEvent("pointermove", {
    bubbles: true,
    // any mouseEvent contructor value
});
el.dispatchEvent(pointerMoveEvent);
```
```
var pointerUpEvent = new PointerEvent("pointerup", {
    bubbles: true,
    // any mouseEvent contructor value
});
el.dispatchEvent(pointerUpEvent);
```
