### ISSUE TITLE
Snap options for Grid X and Y should support percentage

### ISSUE THREAD

**Issue by tedvanderveen** [taye/interact.js#130]
The grid matrix should support values relative to the container height/width for responsive setups or other situations where the actual container size is not fixed to pixels.
For example, I need to able to snap to a timaline that has 24 hours. The timeline container div takes all available space in the page layout. So the X value in the snap grid options setup should be set to 4.16667%

**Comment by homerjam** [comment]
How would one go about this now - it seems the `paths` option is removed? Thanks

**Comment by taye** [comment]
@homerjam https://interactjs.io/docs/snapping/#targets-option
