### ISSUE TITLE
Hold event triggers click/touch event in iOS safari

### ISSUE THREAD

**Issue by nikolac** [taye/interact.js#138]
I'm using the "hold to start drag" model on touch devices. When I drop an element, a touch/click event is triggered at the x y coord of the start of the hold. I've tried preventDefault() and stopPropagation() from the hold callback, but I can't seem to stop the click.

Any help or workaround would be greatly appreciated.

Thank you

**Comment by tomber** [comment]
I'm having the same issue when using hold to start drag. To use `preventDefault` on the `down` event solves this problem but breaks scroll of the target div. Any ideas of how to work around this would be much appreciated. The scrolling div has `overflow-y: scroll;`and `-webkit-overflow-scrolling: touch;`

**Comment by taye** [comment]
*I think* that calling `preventDefault` on the first `move` event after going `down` also prevents scrolling. So something like this might work for you:

```javascript
interact(target)
  .draggable({ manualstart: true })
  .on('hold', function (event) {
    var interaction = event.interaction;

    if (!interaction.interacting()) {
      interaction.start({ name: 'drag' },
                        event.interactable,
                        event.currentTarget);
    }
  })
  .on('move', function (event) {
    if (event.interaction.interacting()) {
      event.preventDefault();
    }
  });;
```

**Comment by tomber** [comment]
This prevents scroll of the div while dragging which is great, thanks!. Unfortunately it doesn't solve the original problem of the initial click/touch event triggered on `hold`. Any ideas for workaround to improve this solution to prevent the initial click event?

**Comment by taye** [comment]
You could use interact.js' `tap` events instead of native `click` events. Other than that, I don't think there's anything that can be done.

**Comment by taye** [comment]
Actually, you could also add a `click` event listener with `useCapture` which calls `preventDefault` and `stopImmediatePropagation`.

```javascript
interact(target).on('click', function (event) {
  event.prevetnDefault();
  event.stopImmediatePropagation();
}, /* useCapture */ true);

**Comment by tomber** [comment]
It was actually the context menu on tap hold that was causing my problem since drag was interrupted when the 'contextmenu' event fired. Disabling the context menu solves the problem:

    $(document).bind('contextmenu',function(e){
        e.preventDefault();
    });

 It all works perfectly when combined with the suggested solution for scroll on drag:

    .on('move', function (event) {
        if (event.interaction.interacting()) {
            event.preventDefault();
        }
    })

Thank you @taye !
