### ISSUE TITLE
bug: mouse pointer changes on drop

### ISSUE THREAD

**Issue by tomByrer** [taye/interact.js#142]
1 Hover mouse over a dragable element.
2. Mouse pointer changes to + 4-directon arrows
3. Move element
4. Left Mouse Button Up, but **do not move mouse**
5. Pointer changes to text-edit 'I-beam' (see below)
6. You can still Left Mouse Button Down & drag the element with an 'I-beam' mouse cursor.

It was a text-only element.  But this is the bug; should remain 4-directon arrows since what the mouse is hovering is still dragable.  If you move the mouse, cursor will return to the correct 4-direction arrows.

**Comment by razvanphp** [comment]
+1 for resizable too, it seem a little bit flanky.

**Comment by taye** [comment]
The situation has improved a bit. The cursor goes back to the default when the mouse is released but it's corrected on the next movement. Keeping the cursor after mouseup is complicated right now so I'll consider this issue resolved.
