### ISSUE TITLE
Rotation and Pinch-to-zoom examples don't work

### ISSUE THREAD

**Issue by alex-pl** [taye/interact.js#146]
I tried to implement `interact(...).gesturable(...)` in my project but it seems to be broken in the new 1.2.0 version.

My code (and test case) looks like this:

```javascript
function gesturemove(event) {
    console.log(event);
}

interact('svg')
    .gesturable({})
    .on('gesturemove', gesturemove)
    .on('gestureend', gesturemove);
```

The event listener doesn't get called if I interact with the element and two fingers.

Instead I get an `TypeError: snap is undefined` exception in `interact.js:1609:16`.

The examples Rotation and Pinch-to-zoom on http://interactjs.io/ don't work ether.
I've tested it with Firefox for Android (Stable and Nightly) and Chrome (Stable) on a tablet and Firefox for Android (Nightly) on a LG G3 smart phone.

**Comment by taye** [comment]
Thanks for reporting this!

**Comment by fonko** [comment]
is it possible to use pinch to zoom and rotate with same object? (im using images)
