### ISSUE TITLE
After remove class ".draggable" I still can drag object once

### ISSUE THREAD

**Issue by ezhkov** [taye/interact.js#150]
1. I have block with absolute positioned overlay in it.
2. By clicking trigger I'm removing ".draggable" class and showing overlay block
3. I expect that parent block won't be draggable, but it does. If mouse cursor stays inside parent block, I still can drag it once. After dragging it becomes undraggable as expected.
You can see it in action [here](http://codepen.io/anon/pen/VYpZbY)

**Comment by taye** [comment]
You can download the fixed version from https://raw.githubusercontent.com/taye/interact.js/master/interact.js. The fix will be included in the next release.
