### ISSUE TITLE
event.dropzone and event.draggable affect all interactables

### ISSUE THREAD

**Issue by warrickbayman** [taye/interact.js#153]
I have a bunch of DIV elements that are draggable and are all dropzones. They can each be dropped onto any other DIV. In the `ondrop` event, I create a NEW div and place both the dragged element and the dropzone into the new DIV. Kind of like a group, I suppose. So I have this:

```javascript
interact('.card').draggable({
    ...
});
```

so that any element with the `card` class will be an interactable. This works perfectly. The problem, however is now I want to STOP the dragged and dropzone elements from reacting, so I've added this:

```javascript
.dropzone({
    ondrop: function(event)
    {
        event.dropzone.draggable(false);
        event.draggable.draggable(false);
    }
});
```

This works for the two interactables involved, but is also seems to affect ALL of the divs that were not being interacted with. I've tried with `unset()` as well but I get the same results.

Not sure if there is a better way to do this.

**Comment by taye** [comment]
If you change your target selector to `.card:not([blocked])`, then you can prevent dragging and dropping by adding a `blocked` attribute to elements.

```javascript
.dropzone({
    ondrop: function(event)
    {
        event.target.setAttribute('blocked', '');
        event.target.setAttribute('blocked', '');
    }
});
```

Then remove the `blocked` attribute when you want to "reactivate" those elements.

```javascript
element.removeAttribute('blocked');
```

**Comment by warrickbayman** [comment]
Thanks. Thats way simpler than my current solution.

**Comment by taye** [comment]
Glad I could help!
