### ISSUE TITLE
All elements snapping to same grid

### ISSUE THREAD

**Issue by martenpalsson** [taye/interact.js#154]
Hi,

Is it possible to have several draggable elements snap to the same grid?

I have several draggable elements that should snap according to this code: 
snap: {
            targets: [
                interact.createSnapGrid({ x: 20, y: 20 })
            ],
            range: Infinity,
            endOnly:true,
            elementOrigin: { x: 0, y: 0 },
            offset: {x:0,y:0}
        }

I thought they would all snap to the same grid but when I drag them around they never line up, instead they are always of by a little bit. This offset seems to be related to the position of the mouse pointer at the beggining of the drag. I thought  that elementOrigin would make sure that every elements snap grid started at the same place but it apparently does not....

**Comment by taye** [comment]
Snapping can only work with a single target element so unfortunately you would need to implement the behaviour that you've described yourself.

**Comment by markusdrake** [comment]
@martenpalsson did you ever implement this? I'm in the same boat - I'm trying to define a grid to snap to but all elements should snap to that grid.

In a perfect world I would give interact a specific DOM element, and within that elements coords create the grid so on drag over it begins to snap, and drag out it stops snapping.

**Comment by m4r71n** [comment]
:+1:

**Comment by martenpalsson** [comment]
No sorry, I gave up and implemented my own grid solution instead. It was too much of a hassle digging through and trying to understand the source code, and my implementation became much smaller and more light weight. Of course it is also much simpler with less features but it serves my purposes better.

**Comment by markusdrake** [comment]
Makes sense. I'm right were you were. 

My project is so custom that I either need to jimmy custom grid / snapping into interact.js or scratch my work so far (drag and drop is working right now) and go back to the drawing board. I'd hate to lose a week of progress just to go back to dragging and dropping but I'm not sure if I got the time (or know-how) to successfully dig through the source and implement this myself.

**Comment by sbulink** [comment]
@markadrake  in the same boat, please let me know if you got snapping to grid working fine, thanks.

**Comment by Joeao** [comment]
I snap all elements to the nearest 20 pixels of the parent element, I do this inside the end function rather than using a snap grid.

**Comment by sbulink** [comment]
not sure if im following, but here is my snap function, what do you pass for your x and y/ or set as your target, element


 snap: {
                    targets: [
                        interact.createSnapGrid({ x: row, y: col })

                    ],
                    range: Infinity,
