### ISSUE TITLE
Drag and drop, duplicates clone on drop

### ISSUE THREAD

**Issue by sciolini** [taye/interact.js#156]
Is it possible to clone a div during the drag and drop?

Example in jQuery UI: http://jsfiddle.net/franco13/vLSZf/1/

**Comment by taye** [comment]
It's possible but there's no direct API to do it. You can use [`Interaction#start`](http://interactjs.io/api/#Interaction.start) to change the target of an interaction to any element that you create.

```javascript
interact('.item').on('dragmove', function (event) {
    var interaction = event.interaction;

    // if the pointer was moved while being held down
    // and an interaction hasn't started yet 
    if (interaction.pointerIsDown && !interaction.interacting()) {
      var original = event.currentTarget,
          // create a clone of the currentTarget element
          clone = event.currentTarget.cloneNode(true);

      // insert the clone to the page
      // TODO: position the clone appropriately
      document.body.appendChild(clone);

      // start a drag interaction targeting the clone
      interaction.start({ name: 'drag' },
                        event.interactable,
                        clone);
    }   
  }); 
```

**Comment by magnum79** [comment]
I can't make this work in jsfiddle - http://fiddle.jshell.net/dryjkmxp/

It looks like `interaction.interacting()` always returns true, because `'dragstart'` event already happened and `interaction.dragging` is set to true;

Maybe you can correct the sample, taye.

Meanwhile i have my own approach to make the clone and drag it.

    var dragTarget;
    interact('.item')
        .draggable({})
        .on('dragstart', function (event) {
            if (!event.target.dragOrigin) {
                var clone = event.target.cloneNode(true);
                clone.dragOrigin = event.target;
                event.interaction.element = clone;
                event.interaction.dragging = false;
                dragTarget = clone;
                document.body.appendChild(clone);
                console.log('clone created');
            } else {
                dragTarget = event.target;
            }
        });

Demo: http://fiddle.jshell.net/3kxtejae/

**Comment by taye** [comment]
@magnum79 Yeah, the sample I gave is incorrect. I copied it [from the FAQ](http://interactjs.io/docs/faq/#clone-target-draggable) so I'll have to fix it there as well. Thanks for mentioning this and providing an alternate solution. I've now corrected my previous answer by using `manualStart: true` and listening for a `move` instead of `dragmove`.

```javascript
interact('.item').on('dragmove', function (event) {

**Comment by magnum79** [comment]
taye, thank you very much! This one works like a charm, here's the demo: http://fiddle.jshell.net/dryjkmxp/1/

**Comment by taye** [comment]
I've updated the FAQ with the correct code. Thanks again.

**Comment by nayfin** [comment]
So... I had this working perfectly in 1.2.4 but with 1.2.6 I have to click to clone then click again to drag the clone. Ideas? Also nothing happens in Firefox regardless of version used.

**Comment by frzsombor** [comment]
@taye: Yes, _nayfin_ is right, I also can't get it work with 1.2.6, even @magnum79 's JSFiddle demo fails. Any plans to fix this?

**Comment by taye** [comment]
It seems to be fixed in the latest [unstable](https://rawgit.com/taye/interact.js/unstable/dist/interact.js) version.

**Comment by Aterxerxes** [comment]
I've tried this as well, but it does not seem to work anymore. The fiddle @magnum79 posted on Feb 24, 2015 doesn't work, Further, if I replace the interact.js 1.2.6 with the unstable version that @taye mentioned, I get the same result, which is that the div will clone properly, but not start the interaction with the new cloned object. Any help would be much appreciated.

**Comment by taye** [comment]
@frzsombor, @Aterxerxes You need code to actually move the element on `dragmove` events. Try using this function from the homepage demos:

```javascript
function dragMoveListener (event) {
  var target = event.target,
      // keep the dragged position in the data-x/data-y attributes
      x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
      y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

  // translate the element
  target.style.webkitTransform =
  target.style.transform =
    'translate(' + x + 'px, ' + y + 'px)';

  // update the posiion attributes
  target.setAttribute('data-x', x);
  target.setAttribute('data-y', y);
}
```

**Comment by Aterxerxes** [comment]
@taye The way I implemented it was using what you have and below it (but in the same function) putting the following:
`// start a drag interaction targeting the clone
      interaction.start({ name: 'drag' },
        event.interactable,
        clone);`

**Comment by aptxwang** [comment]
Update JSFiddle based on @magnum79 's demo and add code to actually move cloned element :
http://fiddle.jshell.net/dryjkmxp/26/

![image](https://user-images.githubusercontent.com/1040391/35023943-fdac2f56-fb77-11e7-9e9d-47af2e42a389.png)

**Comment by SunboX** [comment]
new link: http://jsfiddle.net/dryjkmxp/26/

**Comment by jordanboston** [comment]
> new link: http://jsfiddle.net/dryjkmxp/26/

This does not seem to be working currently.

**Comment by UIHUT-FAYSALKHAN** [comment]
> Is it possible to clone a div during the drag and drop?
> 
> Example in jQuery UI: http://jsfiddle.net/franco13/vLSZf/1/

without jqury how to implement in react ?

**Comment by UIHUT-FAYSALKHAN** [comment]
> I can't make this work in jsfiddle - http://fiddle.jshell.net/dryjkmxp/
> 
> It looks like `interaction.interacting()` always returns true, because `'dragstart'` event already happened and `interaction.dragging` is set to true;
> 
> Maybe you can correct the sample, taye.
> 
> Meanwhile i have my own approach to make the clone and drag it.
> 
> ```
> var dragTarget;
> interact('.item')
>     .draggable({})
>     .on('dragstart', function (event) {
>         if (!event.target.dragOrigin) {
>             var clone = event.target.cloneNode(true);
>             clone.dragOrigin = event.target;
>             event.interaction.element = clone;
>             event.interaction.dragging = false;
>             dragTarget = clone;
>             document.body.appendChild(clone);
>             console.log('clone created');
>         } else {
>             dragTarget = event.target;
>         }
>     });
> ```
> 
> Demo: http://fiddle.jshell.net/3kxtejae/

404 please solve this problem
