### ISSUE TITLE
Temporarily disable draggable

### ISSUE THREAD

**Issue by tehmaestro** [taye/interact.js#157]
Hey, congratulations on building this library, it's really cool.
  Any way I could temporarily disable the draggable object? For example, I want to execute a promise, during which the draggable object should not be moved or interacted with (I'm going to animate it), and when the promise resolves, then I want to reenable it.
 LE : I found the `enabled` option, but how can I dynamically set it?
  Thanks.

**Comment by taye** [comment]
Thanks!

You can pass `true`/`false` to the `draggable` method to enable or disable dragging.

```javascript
interact(target)
  .draggable(false) // disable dragging
  .draggable(true)  // enable dragging
```

Or you could pass an object with it's `enabled` property set to `true`/`false`

```javascript
interact(target)
  .draggable({})    // no `enabled: false` prop, dragging is enabled
  .draggable({
    enabled: false  // explicitly disable dragging
  });
```

**Comment by tehmaestro** [comment]
Awesome, I'll try it ASAP.

**Comment by innovaat** [comment]
I am trying to accomplish this, but I encounter a problem with the selector. If I, for example, enable a draggable using `interact('.draggable').draggable();` Later, I want to be able to disable only one element of those elements, by using `interact('#specificElement').draggable(false);`

This does not seem to work, is there something I am missing?

**Comment by innovaat** [comment]
Right now I have solved this by using a for loop, but it is not optimal I guess.

    angular.forEach($('.draggable'), function(value, key){
        interact(value).draggable(true)
    });

And then to unset only one of them:

    elem.attr('id', 'resizeDraggable');
    elem.css('border', '2px solid red');
    interact('#resizeDraggable').unset();

**Comment by taye** [comment]
@innovaat There's a solution to an identical issue to yours in https://github.com/taye/interact.js/issues/153#issuecomment-70659687

>If you change your target selector to `.card:not([blocked])`, then you can prevent dragging and dropping by adding a `blocked` attribute to elements.

**Comment by innovaat** [comment]
Thanks, but I can't get this to work, perhaps I don't understand it well enough. I have a draggable and resizable on one element, and I only want to disable the resizable. Right now I just run .unset() and add the draggable again.

I don't really understand how the interact() works. I can pass a list of elements to initialize, but I cannot get a reference to the interact element of an individual element after that? Are they grouped somehow?

**Comment by taye** [comment]
I didn't notice that you were passing two different parameters to the `interact` function. By doing that, you're creating a different `Interactable` each time. If you had

```html
<div class="draggable"></div>
<div class="draggable" id="resizeDraggable"></div>
```

```javascript
interact('.draggable');
interact('#resizeDraggable');
interact('#resizeDraggable.draggable');
interact(document.getElementById('resizeDraggable'));
```

Each of those calls to `interact` would return different `Interactable` objects even though they can all target the `#resizeDraggable` element. If you make the `'.draggable'` one draggable but not the `'#resizeDraggable'` one, then the element would still be dragged because the `'.draggable'` `Interactable` says so.

To enable/disable resizing for just one element which matches the selector passed to `interact`, you can enable dragging and resizing then use a custom `actionCecker` function to prevent resizing on some condition. This is the solution I gave [recently on gitter](https://gitter.im/taye/interact.js?at=54d48e1749ddbbee4d7bb5d3):

>... use an actionChecker function to change the action from resize to drag if the element has no [rs] attribute.
I've updated the plunker demo http://plnkr.co/edit/1FrFn9whMx9lJe7nvD8t?p=preview

```javascript
  // custom action checker
  .actionChecker(function (event, action, interactable, element) {
    // if the default checker got a resize action,
    // change it to a drag if the element doesn't have [rs] attribute
    if (action.name === 'resize' && (!element.hasAttribute('rs'))) {
      action.name = 'drag';
    }

    // return the action
    return action;
  })
```

**Comment by innovaat** [comment]
Thanks. I don't have the time to rewrite my current code, it is working now. But this would be a better idea for a later project!

**Comment by kelvin4incubit** [comment]
I am having issue with resize, when i resize and i move, the resize comes back to it default position when i move the object, do you know why am having this issue?

**Comment by phuwin** [comment]
@kelvin4incubit I think you modified the code and your modification makes those not work.

**Comment by akinzeman** [comment]
> Thanks!
> 
> You can pass `true`/`false` to the `draggable` method to enable or disable dragging.
> 
> ```js
> interact(target)
>   .draggable(false) // disable dragging
>   .draggable(true)  // enable dragging
> ```
> 
> Or you could pass an object with it's `enabled` property set to `true`/`false`
> 
> ```js
> interact(target)
>   .draggable({})    // no `enabled: false` prop, dragging is enabled
>   .draggable({
>     enabled: false  // explicitly disable dragging
>   });
> ```

unfortunately, this did not work.
but I temporarly removed class and add later worked..
<div id="target" class="gesture-area" > ...
interact('.gesture-area') ...
$("#target").removeClass("gesture-area")
..then added when necessary
