### ISSUE TITLE
Multi touch on canvas not working

### ISSUE THREAD

**Issue by remko** [taye/interact.js#158]
When I go to the example from the README http://codepen.io/taye/pen/YPyLxE with an iPad, and I use 2 fingers simultaneously going in a different direction, I get:

TypeError: undefined is not an object (evaluating 'e[t+"X"]')

I'm trying to develop a canvas-based UI where 2 fingers can drag different objects at the same time, but it seems this does not work with interact.js?

**Comment by taye** [comment]
It looks like there's a bug with multiple interactions on the same element. I'm looking into it.
