### ISSUE TITLE
restrict larger than parent interactable

### ISSUE THREAD

**Issue by rikkertkoppes** [taye/interact.js#159]
When setting up an interactable that is larger than its parent (a draggable canvas in a viewport), restriction does not work as expected. I added:

```
        restrict: {
            restriction: "parent",
            endOnly: true,
            elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
        },
```

expecting the top, bottom, left and right of the interactable (canvas) to always stay on or outside the parent boundaries. This would be the opposite of when the interactable is smaller (boundaries always stay within the parent boundaries)

If I interpret the elementRect property correctly, to fix this, it should be something like:

```
{
    left: (width - parentWidth)/width,
    top: (height - parentHeight)/height,
    bottom: parentHeight/height,
    right: parentWidth/width
}
```

Which works, but is a bit cumbersome. Furthermore, the widths of the element as well as the parent may change, in which case I have to update the elementRect

Is there a proper way to do this?
##

**Comment by taye** [comment]
I can't get the solution that you gave to work. Can you make a demo?

**Comment by rikkertkoppes** [comment]
Sure

http://jsfiddle.net/mg1b03Lj/

**Comment by taye** [comment]
That's pretty cool. I'll see if I can implement a way to do this automatically. Thanks for bringing this up :)

**Comment by tomtomau** [comment]
+1 Would be a really useful feature to have built in. The behaviour is similar to background-size: cover; in that the draggable should be always cover/fill the parent.

**Comment by tomtomau** [comment]
Here's what I ended up doing in a onEnd snap fix - you'll need to define parent externally or rewrite to find the parent within the callback but the logic is still here.
```
var onend = function(event){
    var target = event.target,
        x = (parseFloat(target.getAttribute('data-x')) || 0),
        y = (parseFloat(target.getAttribute('data-y')) || 0),
        targetWidth = target.offsetWidth,
        targetHeight = target.offsetHeight,
        parentWidth = parent.offsetWidth,
        parentHeight = parent.offsetHeight,
        updatedX = false,
        updatedY = false;

    if(targetWidth >= parentWidth){
        if(x < 0 && (x + targetWidth) < parentWidth){
            // Risk of showing some white on the right #rhyming
            updatedX = -1 * (targetWidth - parentWidth);
        }else if(x > 0){
            // Risk of showing some white on the left
            updatedX = 0;
        }
    }
    if(targetHeight >= parentHeight){
        if(y < 0 && (y + targetHeight < parentHeight)){
            // At risk of showing some white on the bottom
            updatedY = -1 * (targetHeight - parentHeight);
        }else if(y > 0){
            // At risk of showing some white on the top
            updatedY = 0;
        }
    }

    if(false !== updatedX || false !== updatedY){
        updatedX = false === updatedX ? x : updatedX;
        updatedY = false === updatedY ? y : updatedY;

        // translate the element
        target.style.webkitTransform = 'translate(' + updatedX + 'px, ' + updatedY + 'px)';
        target.style.transform = 'translate(' + updatedX + 'px, ' + updatedY + 'px)';

        // update the position attributes
        target.setAttribute('data-x', updatedX);
        target.setAttribute('data-y', updatedY);
    }
}
```
