### ISSUE TITLE
options.resize.square is broken when options.resize.edges is specified

### ISSUE THREAD

**Issue by Thristhart** [taye/interact.js#162]
Compare [this Codepen with edges and square](http://codepen.io/Thristhart/pen/ZYRqEy) to [this Codepen using only square](http://codepen.io/Thristhart/pen/QwxVmW). Specifically, `deltaRect.height` seems to be negative, and when only resizing in one direction, the `deltaRect` does not stay square. It does behave as expected when resizing from the bottom-right corner, however.

I believe the origin of this issue lies in [this block](https://github.com/taye/interact.js/blob/2319094de3056b99bf60f589aca982f2299e46b5/interact.js#L3380-L3388):
```js
            if (options.resize.square) {
                if (interaction.resizeAxes === 'y') {
                    this.dx = this.dy;
                }
                else {
                    this.dy = this.dx;
                }
                this.axes = 'xy';
            }
```
With some minor experimentation I discovered that `interaction.resizeAxes` is null at this point when `resize.edges` is specified. I don't know enough about the structure of interact to identify why this is the case, but it is not null when `edges` is not specified.

**Comment by Thristhart** [comment]
I did some research and discovered that interaction.resizeAxes would normally get set [here](https://github.com/taye/interact.js/blob/2319094de3056b99bf60f589aca982f2299e46b5/interact.js#L3596), but resizeAxes of just "x", "y" or "xy" doesn't actually make sense for the four-edged resize. Perhaps something needs to happen based on interaction.prepared.edges?

**Comment by taye** [comment]
Thanks. I'm working on a fix for it.
