### ISSUE TITLE
Right clicking and tap?

### ISSUE THREAD

**Issue by youssefdetovernickr** [taye/interact.js#164]
Is there an ability to make 'right clicking' an event too, instead of tap, which currently happens on any mouse button? (left, middle and right mouse button)

It's really annoying that you can't really check which mouse button you're pressing. Set tapping to all mouse buttons but add 'leftmouse' 'rightmouse' events too.

**Comment by taye** [comment]
The `MouseEvent` interface has a [button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) property which specifies which button was pressed/released to trigger the event. This and all other properties are copied to interact.js' `pointerEvents` (tap, move, hold, etc.). The `TouchEvent` interface doesn't have a `button` property.

```javascript
interact('body').on('tap hold', function (event) {
  console.log(event.type, event.button);
});
```
