### ISSUE TITLE
Make a div resizable AND draggable.

### ISSUE THREAD

**Issue by youssefdetovernickr** [taye/interact.js#166]
Is this possible, because I can't seem to achieve this.

**Comment by taye** [comment]
As I said [earlier today on Gitter](https://gitter.im/taye/interact.js?at=5506ef8363b7fd687a6ce38a), yes, it is possible. It would be helpful if you provided a concise working demo that shows *how* you are trying to achieve this.

**Comment by taye** [comment]
The resizing demo on http://interactjs.io#resizing shows resizing and dragging:

```javascript
  function dragMoveListener (event) {
    var target = event.target,
        // keep the dragged position in the data-x/data-y attributes
        x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
        y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

    // translate the element
    target.style.webkitTransform =
    target.style.transform =
      'translate(' + x + 'px, ' + y + 'px)';

    // update the posiion attributes
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
  }

interact('.resize-drag')
  .draggable({
    onmove: window.dragMoveListener
  })
  .resizable({
    edges: { left: true, right: true, bottom: true, top: true }
  })
  .on('resizemove', function (event) {
    var target = event.target;
        x = (parseFloat(target.getAttribute('data-x')) || 0),
        y = (parseFloat(target.getAttribute('data-y')) || 0);

    // update the element's style
    target.style.width  = event.rect.width + 'px';
    target.style.height = event.rect.height + 'px';

    // translate when resizing from top or left edges
    x += event.deltaRect.left;
    y += event.deltaRect.top;

    target.style.webkitTransform = target.style.transform =
        'translate(' + x + 'px,' + y + 'px)';

    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
    target.textContent = event.rect.width + '×' + event.rect.height;
  });
```

**Comment by francescoagati** [comment]
Hi,
i notice that when interact.js is used with draggable and resizable drag events aren't fired.
if i use .on('dragmove resizemove')  only resizemove is fired but not dragmove.

**Comment by taye** [comment]
The following works fine for the [resizing demo](http://interactjs.io/#resizing) on the project homepage:

```javascript
interact('.resize-drag').on('dragmove resizemove', function (e) {
  console.log(e.type);
})
```

Drag happens when the pointer is in the middle of the element and resize at the edges.

**Comment by francescoagati** [comment]
I think that in my case the resize zone is over the drag zone.

**Comment by taye** [comment]
I've added a resize margin option so you have some more control over how close to the edges the pointer must be for a resize to happen. That might help.

```javascript
interact(target).resizable({ margin: 10 });
```

**Comment by francescoagati** [comment]
thanks. i'm try it now

**Comment by kenborge** [comment]
I had this same issue when having a item in a dropzone that was both draggable and droppable. But for me the resize events where never triggered. Using margin: 10 did fix the issue for me.

**Comment by DRSDavidSoft** [comment]
@taye Exactly what I was looking for. Thanks.

**Comment by taye** [comment]
@DRSDavidSoft You're welcome!

**Comment by 93prabhatp93** [comment]
dd

**Comment by sikirumoshood** [comment]
@taye  Just what i was looking for. Works for me like charm 😊😊
