### ISSUE TITLE
The script failed on IE10 (10.0.9200.17228)

### ISSUE THREAD

**Issue by dkosasih** [taye/interact.js#168]
Hello...

I tried to combine some jquery and svg, and make it dragable.
It works fine in Chrome, but for some reasons when I run the same code in IE10. I get:
SCRIPT5007: Unable to get property 'pageX' of undefined or null reference 
interact.js, line 3396 character 17

Have anyone have the same problems like this?

Thanks guys.

**Comment by taye** [comment]
I don't think I've seen that error at that point in the code before. Can you provide a minimal demo that produces this bug?

**Comment by dkosasih** [comment]
Thanks for the quick response Taye.

please find below is the cut down version of html code. I cannot replicate the error in jsfiddle (didn't work at all). 
I suspect it has got something to do with the dropzone because the error message stopped when I was trimming the code down to dropzone part.

Thank you very much :) 
<!DOCTYPE html>
<html lang="en" >
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width">
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script src="http://code.interactjs.io/interact-1.2.4.min.js"></script>
		<style type="text/css" media="all">
			.dropzone {
				background-color: #ccc;
				border: dashed 4px transparent;
				border-radius: 4px;
				margin: 10px auto 30px;
				padding: 10px;
				width: 80%;
				transition: background-color 0.3s, border-color 0.3s;
			}

			.drop-active {
				border-color: #666;
			}

			.drop-target {
				fill: #29e;
			}
			
			.drag-drop {
				display: inline-block;
				min-width: 40px;
				padding: 2em 0.5em;
				background-color: #99e;
				border: solid 2px white;
				-webkit-transform: translate(0px, 0px);
				transform: translate(0px, 0px);
				transition: background-color 0.3s;
			}
		</style>
		
		<script type="text/javascript" id="interact">
        var isDroped = false;

        $(document).ready(function () {
            // target elements with the "draggable" class
            interact('.draggable')
              .draggable({
                  // enable inertial throwing
                  inertia: true,
                  // keep the element within the area of it's parent
                  restrict: {
                      restriction: "parent",
                      endOnly: true,
                      elementRect: { top: 0, left: 0, bottom: 0, right: 0 }
                  },

                  // call this function on every dragmove event
                  onmove: function (event) {
                      var target = event.target,
                          // keep the dragged position in the data-x/data-y attributes
                          x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
                          y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

                      // translate the element
                      target.style.webkitTransform =
                      target.style.transform =
                        'translate(' + x + 'px, ' + y + 'px)';

                      // update the posiion attributes
                      target.setAttribute('data-x', x);
                      target.setAttribute('data-y', y);

                      if ($('#' + event.target.id).parent()[0].id == "OrphanedNode") {
                          $('#' + event.target.id).parent()[0].setAttribute("width", "1700")
                      }
                  },
                  // call this function on every dragend event
                  onend: function (event) {
                      var textEl = event.target.querySelector('p');
                      textEl && (textEl.textContent =
                        'moved a distance of '
                        + (Math.sqrt(event.dx * event.dx +
                                     event.dy * event.dy) | 0) + 'px');

                      //if ($('#' + event.target.id).parent()[0].id == "OrphanedNode") {
                          
                      //}
                  }
              });

            interact('.dropzone').dropzone({
                // only accept elements matching this CSS selector
                accept: '.yes-drop',
                // Require a 75% element overlap for a drop to be possible
                overlap: 0.6,

                // listen for drop related events:

                ondropactivate: function (event) {
                    // add active dropzone feedback
                     event.relatedTarget.classList.add('drop-active');
                },
                ondragenter: function (event) {
                    var draggableElement = event.relatedTarget,
                        dropzoneElement = event.target;
                    if (!dropzoneElement.classList.contains('seat-occupied')) {
                        // feedback the possibility of a drop
                        dropzoneElement.classList.remove('seat-available');
                        dropzoneElement.classList.remove('seat-occupied');
                        dropzoneElement.classList.add('seat-dragin');
                    }
                    //draggableElement.classList.add('can-drop');
                    //draggableElement.textContent = 'Dragged in';
                },
                ondragleave: function (event) {
                    if ((event.target.classList.contains('seat-occupied') && event.target.id == event.relatedTarget.getAttribute("seatid")) || event.target.classList.contains('seat-dragin')) {
                        // remove the drop feedback style
                        event.target.classList.remove('seat-dragin');
                        event.target.classList.remove('seat-occupied');
                        event.target.classList.add('seat-available');
                    }
                },
                ondrop: function (event) {
                    if (!event.target.classList.contains('seat-occupied')) {
                        event.target.classList.remove('seat-available');
                        event.target.classList.remove('seat-dragin');
                        event.target.classList.add('seat-occupied');

                        isDroped = true;
                    }
                },
                ondropdeactivate: function (event) {
                    // remove active dropzone feedback
                    //event.target.classList.remove('available-seat-dragIn');
                    event.relatedTarget.classList.remove('drop-active');
                }
            });
        });
    </script>
    </head>
    <body> 
    <div class="content-wrapper main-content clear-fix">
<svg width="1180" height="600" id="Mainsvg">
   <g transform="translate(0,0)" id="abc"><path id="1" d="M1068 14 L1108 14 L1108 57 L1068 57 Z" class="dropzone"></path><text transform="translate(1088,36)" style="fill: grey;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="SeatQuickRef">     <tspan>1</tspan></text></g>
    <g transform="translate(0,0)" id="def">
    <g id="1" seatid="1" stroke="white" stroke-width="2" fill="white" data-x="1073" data-y="14" transform="translate(1073,14)" style="transform:translate(1073,14);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Deddy</tspan>     <tspan x="0" dy="1.2em">Kosasih</tspan>     <tspan x="0" dy="1.2em">237</tspan></text></g><g id="2" seatid="2" stroke="white" stroke-width="2" fill="white" data-x="1136" data-y="14" transform="translate(1136,14)" style="transform:translate(1136,14);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Robert</tspan>     <tspan x="0" dy="1.2em">Sells</tspan>     <tspan x="0" dy="1.2em">214</tspan></text></g><g id="4" seatid="4" stroke="white" stroke-width="2" fill="white" data-x="1136" data-y="90" transform="translate(1136,90)" style="transform:translate(1136,90);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Gary</tspan>     <tspan x="0" dy="1.2em">Murphy</tspan>     <tspan x="0" dy="1.2em">235</tspan></text></g><g id="11" seatid="11" stroke="white" stroke-width="2" fill="white" data-x="989" data-y="199" transform="translate(989,199)" style="transform:translate(989,199);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:aquamarine;"></path><circle style="fill:aquamarine;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Paul</tspan>     <tspan x="0" dy="1.2em">Khurana</tspan>     <tspan x="0" dy="1.2em">255</tspan></text></g></g>    
</svg>
        </div>
</body></html>

**Comment by taye** [comment]
You can find my email address on [my Github profile](https://github.com/taye).

By the way, using [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) should let you paste HTML code correctly on Github.

**Comment by dkosasih** [comment]
Sorry for my lack of experiece in GitHub. Please find below if the html code.

```
<!DOCTYPE html>
<html lang="en" >
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width">
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script src="http://code.interactjs.io/interact-1.2.4.min.js"></script>
		<style type="text/css" media="all">
			.dropzone {
				background-color: #ccc;
				border: dashed 4px transparent;
				border-radius: 4px;
				margin: 10px auto 30px;
				padding: 10px;
				width: 80%;
				transition: background-color 0.3s, border-color 0.3s;
			}

			.drop-active {
				border-color: #666;
			}

			.drop-target {
				fill: #29e;
			}
			
			.drag-drop {
				display: inline-block;
				min-width: 40px;
				padding: 2em 0.5em;
				background-color: #99e;
				border: solid 2px white;
				-webkit-transform: translate(0px, 0px);
				transform: translate(0px, 0px);
				transition: background-color 0.3s;
			}
		</style>
		
		<script type="text/javascript" id="interact">
        var isDroped = false;

        $(document).ready(function () {
            // target elements with the "draggable" class
            interact('.draggable')
              .draggable({
                  // enable inertial throwing
                  inertia: true,
                  // keep the element within the area of it's parent
                  restrict: {
                      restriction: "parent",
                      endOnly: true,
                      elementRect: { top: 0, left: 0, bottom: 0, right: 0 }
                  },

                  // call this function on every dragmove event
                  onmove: function (event) {
                      var target = event.target,
                          // keep the dragged position in the data-x/data-y attributes
                          x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
                          y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

                      // translate the element
                      target.style.webkitTransform =
                      target.style.transform =
                        'translate(' + x + 'px, ' + y + 'px)';

                      // update the posiion attributes
                      target.setAttribute('data-x', x);
                      target.setAttribute('data-y', y);

                      if ($('#' + event.target.id).parent()[0].id == "OrphanedNode") {
                          $('#' + event.target.id).parent()[0].setAttribute("width", "1700")
                      }
                  },
                  // call this function on every dragend event
                  onend: function (event) {
                      var textEl = event.target.querySelector('p');
                      textEl && (textEl.textContent =
                        'moved a distance of '
                        + (Math.sqrt(event.dx * event.dx +
                                     event.dy * event.dy) | 0) + 'px');

                      //if ($('#' + event.target.id).parent()[0].id == "OrphanedNode") {
                          
                      //}
                  }
              });

            interact('.dropzone').dropzone({
                // only accept elements matching this CSS selector
                accept: '.yes-drop',
                // Require a 75% element overlap for a drop to be possible
                overlap: 0.6,

                // listen for drop related events:

                ondropactivate: function (event) {
                    // add active dropzone feedback
                     event.relatedTarget.classList.add('drop-active');
                },
                ondragenter: function (event) {
                    var draggableElement = event.relatedTarget,
                        dropzoneElement = event.target;
                    if (!dropzoneElement.classList.contains('seat-occupied')) {
                        // feedback the possibility of a drop
                        dropzoneElement.classList.remove('seat-available');
                        dropzoneElement.classList.remove('seat-occupied');
                        dropzoneElement.classList.add('seat-dragin');
                    }
                    //draggableElement.classList.add('can-drop');
                    //draggableElement.textContent = 'Dragged in';
                },
                ondragleave: function (event) {
                    if ((event.target.classList.contains('seat-occupied') && event.target.id == event.relatedTarget.getAttribute("seatid")) || event.target.classList.contains('seat-dragin')) {
                        // remove the drop feedback style
                        event.target.classList.remove('seat-dragin');
                        event.target.classList.remove('seat-occupied');
                        event.target.classList.add('seat-available');
                    }
                },
                ondrop: function (event) {
                    if (!event.target.classList.contains('seat-occupied')) {
                        event.target.classList.remove('seat-available');
                        event.target.classList.remove('seat-dragin');
                        event.target.classList.add('seat-occupied');

                        isDroped = true;
                    }
                },
                ondropdeactivate: function (event) {
                    // remove active dropzone feedback
                    //event.target.classList.remove('available-seat-dragIn');
                    event.relatedTarget.classList.remove('drop-active');
                }
            });
        });
    </script>
    </head>
    <body> 
    
       
    <div class="content-wrapper main-content clear-fix">
<svg width="1180" height="600" id="Mainsvg">
    
    <g transform="translate(0,0)" id="abc"><path id="1" d="M1068 14 L1108 14 L1108 57 L1068 57 Z" class="dropzone"></path><text transform="translate(1088,36)" style="fill: grey;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="SeatQuickRef">     <tspan>1</tspan></text></g>
    <g transform="translate(0,0)" id="def">
    <g id="1" seatid="1" stroke="white" stroke-width="2" fill="white" data-x="1073" data-y="14" transform="translate(1073,14)" style="transform:translate(1073,14);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Deddy</tspan>     <tspan x="0" dy="1.2em">Kosasih</tspan>     <tspan x="0" dy="1.2em">237</tspan></text></g><g id="2" seatid="2" stroke="white" stroke-width="2" fill="white" data-x="1136" data-y="14" transform="translate(1136,14)" style="transform:translate(1136,14);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Robert</tspan>     <tspan x="0" dy="1.2em">Sells</tspan>     <tspan x="0" dy="1.2em">214</tspan></text></g><g id="4" seatid="4" stroke="white" stroke-width="2" fill="white" data-x="1136" data-y="90" transform="translate(1136,90)" style="transform:translate(1136,90);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:green;"></path><circle style="fill:green;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Gary</tspan>     <tspan x="0" dy="1.2em">Murphy</tspan>     <tspan x="0" dy="1.2em">235</tspan></text></g><g id="11" seatid="11" stroke="white" stroke-width="2" fill="white" data-x="989" data-y="199" transform="translate(989,199)" style="transform:translate(989,199);" class="draggable yes-drop"> <path d="M2 24 C0 18 30 18 28 24 L28 35 L2 35 Z" style="fill:aquamarine;"></path><circle style="fill:aquamarine;" id="pointC" cx="15" cy="15" r="8"></circle><text style="display:none;fill: black;stroke:none;font-size:10px;font-family:calibri;font-weight:bold;text-anchor:middle;text-align:center;" class="QuickRef">     <tspan x="0" dy="1.2em">Paul</tspan>     <tspan x="0" dy="1.2em">Khurana</tspan>     <tspan x="0" dy="1.2em">255</tspan></text></g></g>    
</svg>
        </div>
</body></html>
```

**Comment by taye** [comment]
The problem seems to be that `Element.classList` doesn't exist for `SVGElement`s in IE10.
![capture](https://cloud.githubusercontent.com/assets/1679746/6871125/6d68eeec-d498-11e4-8651-e88410626822.PNG)

The error breaks interact.js' event firing procedure and causes other errors. You should use jQuery to change the classes.

**Comment by dkosasih** [comment]
Thanks for finding that out Taye.
It works. I am closing the issue.
