### ISSUE TITLE
Preserve aspect ratio with resizing?

### ISSUE THREAD

**Issue by chanpory** [taye/interact.js#169]
I am resizing an image using your library. It works great, except that I can't preserve the original aspect ratio. If I set `square: true` it just transforms the image into a square.

**Comment by chanpory** [comment]
```
interact('img')
  .resizable({
    edges: {right: true, bottom: true}
  })
  .on('resizemove', function (event) {
    var target = event.target;

    // update the element's style
    target.style.width  = event.rect.width + 'px';
  });
```

**Comment by taye** [comment]
This feature doesn't exist (yet) and I won't have time for developing new features for a while. For the moment, you will have to implement this yourself in your resize event listeners.
