### ISSUE TITLE
Textarea inside draggable

### ISSUE THREAD

**Issue by toniorush** [taye/interact.js#170]
Hello
when I put a textarea inside a draggable div, it's not possible to click the textarea to get focus. I can get the focus by tapping the "TAB" key and the textarea works.
The click is probably catched by interact. How can I prevent this ?

**Comment by taye** [comment]
Focusing on `<input>` and `<textareas>` and `<a>` is normally *not* prevented unless you called [`Interactable#preventDefault('always')`](http://interactjs.io/api/#Interactable.preventDefault).

If you want to prevent dragging if the pointer is over the textarea, use [`Interactable#ignoreFrom`](http://interactjs.io/api/#Interactable.ignoreFrom).

**Comment by toniorush** [comment]
That's id, thank you !
