### ISSUE TITLE
ondrop event not working in FF if draggable and dropzone are in the same SVG

### ISSUE THREAD

**Issue by lukaMis** [taye/interact.js#171]
Hi

If i define drag and drop zones within one big SVG it does not fire ondrop event in Firefox. 
It works in Chrome/Safari.

Here is example:
http://demo.irokus.si/irokusplus/bio9uc/bio9_02_01_0__github_EXAMPLE/

Check in FF and Chrome/Safari and look for DROP console message and also black rectangle changes color upon drop success in Chrome but  there is no success in FF. :(

**Comment by taye** [comment]
This is due to a [bug 1066435](https://bugzilla.mozilla.org/show_bug.cgi?id=1066435) of Firefox: *getBoundingClientRect() doesn't take CSS transform into account for SVG elements*.

To avoid it, you can use SVG transform attributes instead of CSS.

**Comment by lukaMis** [comment]
@taye Yo mean i should move draggable item with custom dragMoveListener that uses svg transform instead of css transforms?
Will than ondrop fire in FF also?

**Comment by taye** [comment]
Yep :)

**Comment by taye** [comment]
I'm closing this since this is a Firefox bug.
