### ISSUE TITLE
problems when draggable + resizable is both enabled at the same time

### ISSUE THREAD

**Issue by oddmarthon-lende** [taye/interact.js#172]
```javascript
interact(this)
                        .draggable(true)
                        .resizable(Array.isArray(v) ? {
                            edges: { left: true, right: true, bottom: false, top: false }
                          } : false)
                        .on('resizestart', start)
                        .on('resizemove', function (event) {})
                       .on('resizeend', end)
                        .on("dragstart", start)
                        .on("dragend", end)
                        .on("dragmove",  function (event) {})
```
i just upgraded to 1.2.4 and when enabling draggable and trying to resize the cursor changes when hovering the edge, but when i mousedown and start moving the cursor it starts the dragging behaviour and the 'resizemove' function is never called. if i disable draggable it works fine.

**Comment by taye** [comment]
Can you make a demo that reproduces this issue?

**Comment by oddmarthon-lende** [comment]
I tried to reproduce this, but i haven't really spent much time on it. I could not reproduce the issue with my first attempt. My second attempt i copied the HTML that was generated by my application and just and the only javascript that was added was this code to interact with the rectangle and did not reproduce. 

Where is the first entry point (in the code) after the button is clicked ? So i can set a breakpoint a have a look when its running.

**Comment by taye** [comment]
`Interaction#selectorDown` at line `1457` and `Interaction#pointerDown` at line `1551`.

`defaultActionChecker` at line `3613` is where the actions are determined.

**Comment by oddmarthon-lende** [comment]
I've made a demo with the issue reproduced [here] (http://codepen.io/anon/pen/bNPjbq)

It looks to me like the problem occurs because there is an element further up the DOM tree that also has interact attached and there is some event bubbling happening.

```html
<div id="container0">
      <div id="container1">
        <div id="box"></div>
      </div>
    </div>
```

In the demo #container0 and #box are intractable.

When debugging, clicking on the edge of the element i want to resize triggers mousedown twice, the second time it has the element further up the tree as the current event target and returns a drag action instead.

My first thought is to just stop the bubbling from happening, but  what do i know :) ?

**Comment by taye** [comment]
>My first thought is to just stop the bubbling from happening, but what do i know :) ? 

That sounds like it would fix it. I'll do it when I have the time or you can have a go at it if you'd like. For now, you can work around it by passing a selector to `interact` instead of an element https://codepen.io/taye/pen/xbvZMd

```javascript
interact("#container0, #box")...
```

instead of

```javascript
d3.selectAll("#container0, #box")
  .each(function (_, i) {
  	interact(this)...
```

**Comment by oddmarthon-lende** [comment]
#container0 represents a dialog box and is a different story, so using a selector like that would not be usable. You can work around it in the demo, but not in the application...

**Comment by oddmarthon-lende** [comment]
This little hack fixes it, but ive only seen a fraction of the code, so i dont know if it breaks anything else
