### ISSUE TITLE
I got a little movment when i set interact.createSnapGrid({ x: 30, y: 30 })

### ISSUE THREAD

**Issue by nightost** [taye/interact.js#173]
it also appears in http://interactjs.io/ 's Snapping demo.
The first step is less than x value in my settings.

**Comment by taye** [comment]
I don't understand what the problem is. Could you explain it a bit more.

**Comment by nightost** [comment]
Forgive my poor english~
For example,i set x value to 30 using createSnapGrid.
As expected,the dragable element's every  step on x-axis  will be 30.
But ,the first step is less than 30(always about 5) when i draged.

**Comment by taye** [comment]
You need to use `'startCoords'` as the `snap.offset`. http://interactjs.io/docs/snapping/#offset
