### ISSUE TITLE
There are few artefacts after drag'n'drop on iPad mini with Retina display (Safari)

### ISSUE THREAD

**Issue by prumyantsev** [taye/interact.js#175]
When I look at the demos of drag'n'drop at your site I see, that few artefacts are created (you can see result at image below). That happens when I click on draggable element and start moving it form top to bottom with moving element to the right side of wrapper.
![jbqmkb6ggbu](https://cloud.githubusercontent.com/assets/5354873/7347272/ad020e48-ecef-11e4-84f8-a2027f943257.jpg)

**Comment by taye** [comment]
This has something to do with hardware acceleration and optimisation of CSS transforms or something. Other than using `top`, `left`, forcing hardware acceleration with `-webkit-transform: translate3d(0,0,0);` might help and [this trick](http://stackoverflow.com/a/17822836/2280888) might also work.

**Comment by prumyantsev** [comment]
It works! Thank you!
