### ISSUE TITLE
draggables bihind dropzone when they are inside overflowing container

### ISSUE THREAD

**Issue by kongaraju** [taye/interact.js#176]
Hi,

I have list draggables inside overflowing container, when am trying to drag they are invisible behind the dropzone.

Please give some work around for it.

Referring to existing demo http://jsfiddle.net/Venkatrao/9jse5ybe/2/

**Comment by taye** [comment]
You can increase the z-indexes of the dropzones so that they appear above the dropzone or change the DOM hierarchy so that the draggables appear over the dropzone.

**Comment by kongaraju** [comment]
can u please give example, I tried to increase the z-index when dragging but no use.

**Comment by taye** [comment]
Add this piece of CSS:

```css
.draggable { z-index: 1; }
```
