### ISSUE TITLE
Add an ondragrelease event?

### ISSUE THREAD

**Issue by vmasto** [taye/interact.js#179]
Hey, great plugin, I have been playing around with it and I have an issue which can be demonstrated in the following demo:

http://codepen.io/anon/pen/rVVeME

The functionality is simple, we have 1 big dropzone on the left (`.dropzone-1`) and various slots on the right. The user can drag each `.block` to any slot and he can then "deactivate" them by dragging them to `.dropzone-1` again. 

So far it works great but there's an irritating UX problem: `snap` coordinates are calculated when the `draggable` element is ondragenter the dropzone, so if a user hovers a `.block' on top of a `.slot` there's no way for him to change his mind and not "activate" that draggable (its snap coords are already calculated and the element is predetermined where it will drop no matter what the user does).

Simple steps to reproduce:

1. Drag a block from the left.
2. Hover it over a `.slot` on the right (do not release).
3. "Change your mind", and drag the extension outside of a `.slot'.
4. Drop. It will snap on the last `.slot` that the draggable was hovered upon.

Desired behaviour on step 4 would be for the draggable to go back to its original place in `.dropzone-1`.

For this reason, and other caveats, it would be excellent if we could have an ondragrelease event (just like jQuery UI draggable has) so that we can include user intend and calculate snap coordinates based upon it. In other words, ondragenter is not reliable.

Thoughts or workarounds?

**Comment by taye** [comment]
That would be very useful. However, In your case it might not be necessary. You can use [interactable#dropChecker](http://interactjs.io/api/#Interactable.dropChecker) to change how a drop is determined. That way you can prevent a `dragenter` from happening when your application shouldn't allow a drop.

I won't have much time to implement a proper `dragrelease` event but I've made a [quick change](https://github.com/taye/interact.js/commit/f7df92c) to allow the following workaround:

```javascript
// add 'dragrelease' event type
interact.debug().eventTypes.push('dragrelease');

// when the pointer is released
interact(document).on('up', function (event) {
  var interaction = event.interaction;

  if (interaction.currentAction() === 'drag') {
    var eventCopy = {}, 
        dragRelease = {}, 
        prop;

    // make a copy of the previous interaction event
    for (prop in event) { dragRelease[prop] = interaction.prevEvent[prop]; }

    dragRelease.type = 'dragrelease';
    interaction.target.fire(dragRelease);

    // make a copy of the pointerEvent
    for (prop in event) { eventCopy[prop] = event[prop]; }
    // modify clientX so that the
    // move event isn't ignored as a duplicate
    eventCopy.clientX += 0.000001;

    // manually handle the move
    interaction.pointerMove(eventCopy, event.originalEvent, event.target, event.currentTarget);
  }
});

// add event as usual
interact('.block').on('dragrelease', function (event) {
  console.log('dragrelease');
  
  // always snap to the start
  event.interactable.draggable({snap: { targets: [startPos] } });
});
```

**Comment by taye** [comment]
http://codepen.io/taye/pen/KpdRMg

**Comment by taye** [comment]
You can now use the [Interaction.doMove](https://rawgit.com/taye/interact.js/unstable/dist/docs/#Interaction.doMove) method to fire a new `[action]move` event after changing snap/restrict settings.

```javascript
interact(target)
  .draggable(...)
  // when the pointer is released
  .on('up', function (event) {
    // if dragging
    if (event.interaction.currentAction() === 'drag') {
      // change the snap settings
      event.interactable.draggable({ snap: ... });
      // make a move with the new snap settings
      event.interaction.doMove();
    }
  });
```

I think this pretty much removes the need for `[action]release` events.
