### ISSUE TITLE
Auto-scroll when draggable goes beyond viewport.

### ISSUE THREAD

**Issue by vmasto** [taye/interact.js#180]
Is there any way to simulate the functionality provided by jQuery UI's auto-scroll (https://jqueryui.com/draggable/#scroll) ?

It would be a great addition.

**Comment by taye** [comment]
There's an [autoScroll setting](http://interactjs.io/docs/#autoscroll) but it might be a bit buggy as I've neglected it for some time.

**Comment by vmasto** [comment]
The autoScroll setting seems completely non-functional in touch (mobile/tablet) devices (even when inspecting with Chrome Dev Tools in device mode). Is there any quick fix for this?

**Comment by taye** [comment]
autoScroll should now be working on mobile devices.

**Comment by Nic128** [comment]
Tested the latest commit, the autoScroll works now on mobile devices. What's your release schedule?

**Comment by taye** [comment]
I don't have access to enough devices to test with to be confident enough to release and I can't say when I will. I would like to think that a release is likely to happen some time within the next two weeks.
