### ISSUE TITLE
Multitouch is blocked when holding touch inside an iframe.

### ISSUE THREAD

**Issue by tommywang** [taye/interact.js#181]
Hello, great plugin. 
I have a world map. User open a pop-up by clicking on a country. It's an iframe inside the pop-up. I use tap event to handle the click and pop-ups are draggable. 
```
interact(document)
      .on('tap', function (e) {
         if ($(e.target).hasClass('.country')){
            //open a pop up
         }
});

 interact($popup)
      .draggable({
         autoScroll: false,
        // call this function on every dragmove event
        restrict: {
          restriction: {
            left: 67,
            right: 1008,
            top: 65,
            bottom: 1855
          },
          elementRect: { left: 0, right: 1, top: 0, bottom: 1 }
        },


        onmove: function (event) {
        },
        // call this function on every dragend event
        onend: function (event) {
        }
      });
```

When an user interacts with the content of the iframe inside the pop up, like scrolling text, click on buttons, another user can not click on the map to open another pop up or drag one.
How can I fix this? Thanks a lot.

**Comment by taye** [comment]
Could you provide a minimal working demo?

**Comment by tommywang** [comment]
Hello, here are a minimal demo: http://codepen.io/tommywang/pen/rVLBbq
If you put one finger in the iframe to scroll the page, you can not drag the others any more.
Thanks for your help!

**Comment by taye** [comment]
The problem might be that browsers makes it impossible to interact with both content of iFrames and the parent window simultaneously. You might have to avoid using iFrames.

**Comment by taye** [comment]
I'll try to investigate a bit more if I have time later.

**Comment by tommywang** [comment]
Thanks a lot for your help! :)

**Comment by taye** [comment]
I looked into it a bit more and it seems like there's definitely no way to get touch events from different frames at the same time.
