### ISSUE TITLE
not able to edit input text inside draggable

### ISSUE THREAD

**Issue by kongaraju** [taye/interact.js#182]
http://jsfiddle.net/hf27hn0c/13/ 

Hi am trying to edit text input content inside draggable but its not happening, can u plz give me a workaround for it

**Comment by taye** [comment]
You can use [ignoreFrom](http://interactjs.io/api/#Interactable.ignoreFrom) to prevent actions starting from certain elements.

```javascript
interact(target).ignoreFrom('input, textarea');
```

**Comment by kongaraju** [comment]
Thanks you are awesome, 
Sorry I missed it.
