### ISSUE TITLE
sometime fails on dragstart with  TypeError: Cannot read property 'target' of undefined at getDraggable

### ISSUE THREAD

**Issue by mogadanez** [taye/interact.js#183]
not have guarantee reproduce

 TypeError: Cannot read property 'target' of undefined at getDraggable
```
   var getDraggable = function (interactable, selector, context) {
                                    var elements = ie8MatchesSelector
                                        ? context.querySelectorAll(selector)
                                        : undefined;

                                    if (interactable === this.target) { return; }
```

http://i.imgur.com/Mwkyucu.png

**Comment by taye** [comment]
Are you removing any elements from the DOM in a mouse/pointer/touch move event listener?

**Comment by mogadanez** [comment]
No, problem fixed if call .bind(this) for this function

**Comment by taye** [comment]
All right. I'll close this issue then.

**Comment by mogadanez** [comment]
I mean if I modify sorce code with bind method.

**Comment by taye** [comment]
Oh, sorry. I didn't notice the problem with `this`. I should have looked at the screenshot more carefully.
