### ISSUE TITLE
overflowing container issue

### ISSUE THREAD

**Issue by kongaraju** [taye/interact.js#184]
I have container with overflowing elements while dragging they are hidden. Please have a look at the demo http://jsfiddle.net/hf27hn0c/14/ 

is there anyway to make it visible?

**Comment by freepowder** [comment]
add class clearfix to visualizer-panel

**Comment by taye** [comment]
Make the overflowing child elements of the container visible by using CSS `overflow: visible` or give the child elements absolute positioning.
