### ISSUE TITLE
Snap outside a dropzone

### ISSUE THREAD

**Issue by kikki** [taye/interact.js#186]
Hello taye, interact.js is a great library, I like it..
and I habe a question...
Example:
Two dropzones (dropzone A and B) 
Two draggable elements (1 and 2)

==>Situation start: draggable elements (1 & 2) in dropzone  A
==>User drag element 1 in dropzone  B
==>User drag element 2 in dropzone  B 
==>interact.js: element 1 snap in dropzone  A so that in dropzone  B is only element 2.

So I like to use snap function for element 1 without a drag mouse 
event on it when dropzone B finish event for element 2?  

It is possible and how?

**Comment by taye** [comment]
You would have to implement this behaviour yourself. Snapping by interact.js is only done to the element that is being dragged.
