### ISSUE TITLE
fail on server side

### ISSUE THREAD

**Issue by kastigar** [taye/interact.js#187]
Hi!

I'm building isomorphic app and i have problems with `interact.js` on server side. The reason is it uses `window` from global scope.
My proposition is to wrap your module:
```javascript
if (typeof window !== "undefined") {
  // your module here
}
```

What do you think?

**Comment by taye** [comment]
It's a small change but I'd prefer not to do it. I would think it better for you to be able to stub modules out rather than have them all able to run without any errors in environments that they have no use in. Is stubbing out interact.js possible in your set-up?

**Comment by kastigar** [comment]
Thank you for the answer. I understand you doubts about this patch. I'm investigating question about stubbing module. But i can't find any solution for this now. That's why I've proposed this patch )))

**Comment by taye** [comment]
I was going to deny this request but then I found out that [jQuery handles Node][1] pretty nicely. I'll do just a basic fix to make it not throw an exception now and maybe do something more useful later.

[1]: http://bugs.jquery.com/ticket/13768

**Comment by kastigar** [comment]
Good. Interesting solution with factory for window object. Glad to see, that you care about this issue :)
