### ISSUE TITLE
Resizing with an iframe

### ISSUE THREAD

**Issue by canyondellomo** [taye/interact.js#189]
Is it possible to use the resizing ability with an iframe? The size adjustment "grabbers" show up for me in preview like normal, but when I try to adjust the size it doesn't work.

**Comment by taye** [comment]
The pointer events are probably being captured by the contents of the iFrame. You'll probably have to use elements to cover the iFrame edges and resize using those. See #188.

**Comment by canyondellomo** [comment]
@taye thanks for the response.  Just tried that, and it still goes away once the elements are resized.  Is there a sort of redraw feature?

**Comment by taye** [comment]
No, there's no redraw feature.
