### ISSUE TITLE
Snap to fixed position after inertia

### ISSUE THREAD

**Issue by mathew-kurian** [taye/interact.js#19]
How do we snap to a certain position once the drag position reaches some distance away from the snap point?

i.e. In the drag progress bar example you have, if you reach near 0 - 5%, then it will snap to 0% after the inertia bounce. Is it possible to have multiple snap points each snap point consisting of a position and a radius (around the position for which element will be snapped into the position)

If this is not a feature already, I can try and add it in.

**Comment by sbulink** [comment]
Hi @taye, ive been trying to rerun the snap to grid function, after performing a drag move with a new element to the grid, so that all elements (children of parent div), align to grid. As now elements stack on top of each other not only next to each other,

**Comment by sbulink** [comment]
++great lightweight library by the way,
