### ISSUE TITLE
gesturable strucks on windows8 touch devices and not able to move again.

### ISSUE THREAD

**Issue by senthilkumarpn** [taye/interact.js#190]
Hi Taye, 
I use interactJS for dragging(on single touch drag) and rotating (on double Touch). 
 I have issue that gesturable strucks on windows8 touch devices and not able to move again.
It seems PointerUp not triggered after rotation since while i drag with single touch it rotates instead of dragging. 
i have tried changing the inertia:(true /false) , Restriction  option (endOnly:true/false),

query1: if suppose strucks means how to re-initate the interactables.
query2: How to fire Manually dragEnd event while crossing the boundary. and set last postion while crossing boundary. (interact.fire('dragend')) does not work as expected.
Thanks..

function initRuler()
{
 try{scaleInteractable.unset();}catch(e){}
 scaleInteractable = interact('#scaleimage')
  .draggable({
	inertia:true,
	onstart:function(event){
		var target = event.target,
		x = (parseFloat(target.getAttribute('data-x')) || 358) + event.dx,
		y = (parseFloat(target.getAttribute('data-y')) || 215) + event.dy;
		target.style.left = x +'px';
		target.style.top = y +'px';
		target.setAttribute('data-x', x);
		target.setAttribute('data-y', y);
		console.log("touchStart")
	},
	onmove: function(event){
		var scaleCont =$("#canvasHolder")
		var xPos = event.pageX-scaleCont.offset().left;
		var yPos = event.pageY-scaleCont.offset().top;
		var Left = $("#canvasHolder").position().left,
		Right = Left+$("#canvasHolder").width(),
		Top = $("#canvasHolder").position().top,
		Bottom = $("#canvasHolder").height();
		if (xPos<Left || xPos>Right || yPos < Top || yPos>Bottom) {
			console.log("out of Boundary");
			//scaleInteractable.fire("dragleave");
			
		}
		var target = event.target,
		x = (parseFloat(target.getAttribute('data-x')) || 358) + event.dx,
		y = (parseFloat(target.getAttribute('data-y')) || 215) + event.dy;
		target.style.left = x +'px';
		target.style.top = y +'px';
		target.setAttribute('data-x', x);
		target.setAttribute('data-y', y);
	},
  }).inertia({
    resistance     : 16,
    minSpeed       : 200,
    endSpeed       : 20,
    allowResume    : true,
    zeroResumeDelta: false,
    smoothEndDuration: 300,
    actions        : ['drag', 'resize']
	})
  .restrict({
		drag: 'parent',
		endOnly: true,
		elementRect: { top: 0.50, left: 0.89, bottom: 0.50, right: 0.08 } //if Horizontal Scale
		//elementRect: { top: 0.90, left: 0.45, bottom: 0.08, right: 0.50 } // if Vertical Scale
  }).gesturable({
		max: 2,
		maxPerElement: 1,
		onmove: function (event) {
			var arrow = document.getElementById('scaleimage');
			angle += event.da;
			scaleAngle = Math.abs(Math.round(angle));
			if (scaleAngle == 360) {
				scaleAngle = 0
			}
			else if (scaleAngle>=360) {
				scaleAngle = Math.abs(scaleAngle%360);
			}
			else if (scaleAngle == -360) {
				scaleAngle = 0;
			}
			else if (scaleAngle <= -360) {
				scaleAngle = Math.abs(scaleAngle%360);
			}
			arrow.style.webkitTransform = arrow.style.transform = 'rotate(' + angle + 'deg)';
		},
		onend:function(event){
			//setRestriction(scaleAngle);
		}
	});
}
function setRestriction(scaleAngle) {
		if ((scaleAngle>=0 && scaleAngle<10  || scaleAngle>175 && scaleAngle<184 || scaleAngle >352 && scaleAngle<359.9)) {
				interact('#scaleimage').restrict({
				elementRect: { top: 0.50, left: 0.89, bottom: 0.50, right: 0.095 } //if Horizontal Scale
				});
			}
			else if ((scaleAngle>70 && scaleAngle <110) || (scaleAngle>240 && scaleAngle<296)) {
				interact('#scaleimage').restrict({
				elementRect: { top: 0.90, left: 0.45, bottom: 0.08, right: 0.50 } // if Vertical Scale
				});
			}
			else if ((scaleAngle>10 && scaleAngle <70) || (scaleAngle >110 && scaleAngle<340)) {
				interact('#scaleimage').restrict({
				elementRect: { top: 0.50, left: 0.45, bottom: 0.50, right: 0.50 } // if Vertical Scale
				});
			}
			else{
				interact('#scaleimage').restrict({
				elementRect: { top: 0.50, left: 0.89, bottom: 0.50, right: 0.095 } //if Horizontal Scale
				});
			}
}

**Comment by taye** [comment]
>if suppose strucks means how to re-initate the interactables.

I don't understand the question.

It's possible that there is an error in one of your event listeners that breaks interact.js. Check the console for any such errors. If not, update to the latest version from https://raw.githubusercontent.com/taye/interact.js/master/interact.js.

>How to fire Manually dragEnd event while crossing the boundary. and set last postion while crossing boundary. (interact.fire('dragend')) does not work as expected.

Stopping actions isn't supported.

**Comment by senthilkumarpn** [comment]
- thanks for your responce.
what i mean to say is  Sometimes while i drag and rotate repeatedly in windows8 , draggable element not able to move ,only it can be rotatable in single touche. i guess there might be pointer up event not triggered. 
that is why i asked , how to trigger event manually in that case.?

**Comment by taye** [comment]
That might be because of an uncaught exception in one of your listener functions. Check the console to see if there are any such errors. In either case, try updating interact.js to the current [master version](https://raw.githubusercontent.com/taye/interact.js/master/interact.js).

**Comment by senthilkumarpn** [comment]
thanks  let me check it out.
