### ISSUE TITLE
iPad 1, iOS 5.1.1 error "undefined is not a function" when autoScroll is set to true

### ISSUE THREAD

**Issue by fczuardi** [taye/interact.js#194]
I am testing a sortable list on a project here, and the drag move was giving me errors…

After some debugging I found that on the function getElementRect at https://github.com/taye/interact.js/blob/master/interact.js#L699 the call for element.getClientRects() was throwing because element was DOMWindow and the window doesn't have the getClientRects method…

My workaround was to patch this function to test if the element is window and if so, use document.body instead, here is the patched version:

```javascript
    function getElementRect (element) {
        var scroll = isIOS7orLower
                ? { x: 0, y: 0 }
                : getScrollXY(getWindow(element));
        if (element === window){
            console.log('hack while a better fix doesnt land');
            element = document.body;
        }
        var clientRect = (element instanceof SVGElement)?
                element.getBoundingClientRect():
                element.getClientRects()[0];


        return clientRect && {
            left  : clientRect.left   + scroll.x,
            right : clientRect.right  + scroll.x,
            top   : clientRect.top    + scroll.y,
            bottom: clientRect.bottom + scroll.y,
            width : clientRect.width || clientRect.right - clientRect.left,
            height: clientRect.heigh || clientRect.bottom - clientRect.top
        };
    }

```

**Comment by taye** [comment]
I don't have an iOS 5.1.1 device to test with. Could you paste one or two stack frames where `window` is passed to `getElementRect`?

**Comment by fczuardi** [comment]
I don't think mobile safari have stack frames for it's errors, the best I can get is a console screen not very informative with errors:

```
Javascript Error
undefined
TypeError: 'undefined' is not a function
```

I've created a simplified testcase here http://codepen.io/fczuardi/pen/oXZewv and the full page here http://s.codepen.io/fczuardi/debug/oXZewv where this error occurs on drag move. 

I can spread a bunch of ```console.log```s on interact.js source and paste them here instead of an error stack if you want :)

**Comment by fczuardi** [comment]
Ok, I created a new codepen here: http://s.codepen.io/fczuardi/debug/XbMaqG that uses this modified version of interact.js that adds this extra line for debugging: https://github.com/fczuardi/interact.js/commit/4b662a97e160e877e428614dc09f6872c79dcf16

The output I get now when moving on iPad1 is:

```
Javascript: Log on Line 699
https://raw.githubusercontent.com/fczuardi/interact.js/debug-issue194/interact.js
getElementRect [object DOMWindow]
```
```
Javascript: Error
undefined
TypeError: 'undefined' is not a function
```

**Comment by taye** [comment]
Could you try instead of changing `getElementRect` to change the line in `autoScrollMove` that checks for a `Window` container:

```javascript
if (isWindow(container)) {
```
to
```javascript
if (isWindow(container) || container === window) {
```

I think that that might work as a better fix.
