### ISSUE TITLE
Error from pointer down event

### ISSUE THREAD

**Issue by kongaraju** [taye/interact.js#197]
while checking 'testIgnore' its throwing error

'Cannot read property 'options' of undefined'

at that moment interactable is undefined. its failing to get indexof the currentElement.

**Comment by taye** [comment]
Can you paste a full stack trace?

**Comment by kongaraju** [comment]
![capture](https://cloud.githubusercontent.com/assets/2101638/11888689/5ada7328-a566-11e5-953d-36889699b2b5.PNG)
