### ISSUE TITLE
Resize not working properly with iframe content within a div

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [taye/interact.js#200]
My resizable container has an iframe with an external document within and it would let me resize from right to left without issues but when i try to bring it back from left to right, i have to resize very slowly, so slow that the mouse pointer has to keep up with the resize edge. If i move even a little fast the resize stops. When i remove the iframe from within, it acts normally and lets me resize left to right and right to left without any issues.

**Comment by rizwanhussain-vteams** [comment]
It might not be an iframe issue at all. When i remove 100% height, it works fine. But when i add back width:100% in css it causes same issue.

**Comment by rizwanhussain-vteams** [comment]
Turns out the iframe was the issue. Whenever my mouse pointer would come over the iframe while dragging, the resize would stop. I found a workaround by using a div with a large z-index and 0 opacity with absolute positioning to show up when resize starts and hide it when it stops. What it does is that it effectively covers the iframe so that dragging mouse over it does not cause the resize to stop. 
I know it's a dirty hack but will do until there is a better solution.

**Comment by taye** [comment]
I don't think that there's any better solution if you don't have permission to enter the iFrame document. In fact, even if you did have permission there would probably be some jumping of the reported coordinates since you would be switching between the coordinate space of the main document and that of the iFrame.

**Comment by ssijak** [comment]
@rizwanhussain-vteams thank you for that hack, I was loosing hair for a few hours on why my drag was behaving like that with iframe as a child
