### ISSUE TITLE
The scroll event does not follow the 'rotate' transformation.

### ISSUE THREAD

**Issue by tommywang** [taye/interact.js#201]
Hello,

When I apply a rotation on a div. The orientation for scrolling the content of the div does not change. 
For example, when I do a 90 deg rotation. Normally, I should scroll horizontally the content. But I still have to scroll vertically to see the content moves horizontally. 
Is there a way to fix this with Interact.js?
There is a codepen: http://codepen.io/tommywang/pen/eNRzav

Thank you for you help

**Comment by taye** [comment]
No, this isn't really a problem for interact.js to solve.
