### ISSUE TITLE
Can't drag element after resize (svg)

### ISSUE THREAD

**Issue by Manelma** [taye/interact.js#202]
Hello, 
I want to thank you for this amazing library.
I intend to use interact.js for a new project with SVG elements , in order to be able to drag and resize Svgs but i faced some problems.
I used the same code  <a href="http://interactjs.io/">here</a>.
When i drag the element then resize it, it stuck at resize event and can't drag it anymore ,even the move cursor won't show up .
So i searched for a solution in Google but i found nothing unfortunately ... 
I tried to change some code ... but nothing worked :(
Here a <a href="http://jsfiddle.net/Manelma/d6swom64/">demo</a>

Please any help will be appreciated.
Sorry for my english :d and thanks in advance.

**Comment by taye** [comment]
The code from the resizing demo on the homepage can only work for HTML elements. You need to change the `resizemove` listener function so that instead of changing `target.style.width/height` it changes the width and height attributes of the `<rect>` element (not the `<g>` element) in your demo.
