### ISSUE TITLE
manualStart Resize issue

### ISSUE THREAD

**Issue by futurist** [taye/interact.js#206]
See this example with resizable:
http://1111hui.com/test/svg01.html

But if I changed to manualStart, there's problem:
http://1111hui.com/test/svg01-manual.html

What I want to do is user can freely resize & drag regardless of the stack order of svg shape, if the pointer moved to some shape's handler, activate that shape and user can instantly resize.

**Comment by taye** [comment]
You need to specify `action.edges` in adition to `action.name`

```javascript
      interaction.start({ name: 'resize',
                          edges: { right: true, bottom: true }},
                        event.interactable,
                        event.currentTarget);
```
