### ISSUE TITLE
Increasing resize area/border

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [taye/interact.js#207]
I want to increase the resize container border to make it easy for iPad users to grab and work with it. Currently if i increase the border to 30 pixels, it still feels like the resizable border remains stuck at 15 pixels and resize indicator does not appear after those 15 pixels. Is there any such restriction in plugin js that would limit the border to be no more than 15 px?

**Comment by taye** [comment]
if you are using `interact.margin(30);`, there shouldn't be any restriction on the margin.

**Comment by taye** [comment]
In the latest [master version](https://raw.githubusercontent.com/taye/interact.js/master/interact.js), you can set the resize margin for individual Interactables in the `resizable` options object.

```javascript
interact(target).resizable({  margin: 30 });
```
