### ISSUE TITLE
Dragging into non-visible objects

### ISSUE THREAD

**Issue by holbrookab** [taye/interact.js#209]
Hi,

See the following codepen: http://codepen.io/anon/pen/RPZZym

If I drag below or above the dropzone area, the dragged object turns green, despite the dropzone being hidden.

Note, I don't think I can use restrictions, as I have multiple dropping locations.  Can you have multiple restrictions?

**Comment by taye** [comment]
You can use a [dropChecker](http://interactjs.io/api/#Interactable.dropChecker) function to add additional requirements for drops. In that function, you could check for visibility or anything else that you need and return true/false.

No, you can't have multiple restrictions.
