### ISSUE TITLE
Gesturable Pinch / Rotation transform-origin is always the center

### ISSUE THREAD

**Issue by fabiocaccamo** [taye/interact.js#211]
I'm mixing pinch, rotation and dragging, everything work fine except the fact that the pinch / rotation is always the center of the target and not the center of the gesture. How to solve this?

**Comment by taye** [comment]
Here is how I did it in a project from a few years ago: https://github.com/biographer/biographer/blob/0b04fe1/bui/src/main/javascript/graph.js#L83-109. You'll need to have `transform-origin: 0 0`.

**Comment by fabiocaccamo** [comment]
I'm mixing rotation too, but I'll try as you did.

**Comment by NexxLuo** [comment]
I also have this problem? Can you provide an example on the official website demo? This is a very common scenario?
