### ISSUE TITLE
Can't trigger events on interactive elements

### ISSUE THREAD

**Issue by arielpontes** [taye/interact.js#212]
Maybe I am missing something, but I have a draggable `div` restricted to the parent on `dragEnd` that by default is positioned at the bottom of its container and whose text is updated from a `textarea` elsewhere in the page. As new lines are added the draggable `div` grows and the lower edge comes out of the container. I tried to trigger `dragmove` and `dragend` on the draggable `div` on `textarea` changes but there's no effect. I just want it to reposition itself back inside the parent, just like it does when I drag it manually. It seems like a bad solution to duplicate this behavior on my end when it's already somewhere in the library. I just need a clean way to access it through the API.

**Comment by taye** [comment]
Exposing internal methods is planned and is currently being worked towards as part of #110, but for now, duplication is the only solution.

**Comment by taye** [comment]
It would be difficult to open the modifier functions to be usable externally. It might happen eventually but probably a long time from now if at all so I'll close this issue and leave duplication as the best solution.

**Comment by taye** [comment]
@arielpontes I've added a new method that let's you simulate actions and re-apply modifiers. See #610.
