### ISSUE TITLE
Delay Option for drag and resize

### ISSUE THREAD

**Issue by razvanphp** [taye/interact.js#214]
After successfully implemented your library, the client pointed out that some small usability changes need to be made.

To be precise, on a draggable and resizable element on mobile phones or touch devices, you can easily and unintentionally drag the element when you scroll.

I tried to use `manualStart` option but this seems a little bit over engineered, given that I only want to add a delay to the action (btw, hold delay is not configurable).

The next problem was that this becomes tricky when you also have resizable, because for some reason, the event I get in `resizeMove` does not contain `rect` property so it's kinda useless. Also one has to check for the target to know if he should drag or resize.

So, maybe it's easy to implement this delay option for both actions, this would also add a lot more flexibility.

PS: there is also a small bug that cursor still changes when `manualStart` is true.

Thank you!

**Comment by taye** [comment]
>I tried to use manualStart option but this seems a little bit over engineered, given that I only want to add a delay to the action (btw, hold delay is not configurable).

It's not documented but you can change the hold delay with 

```javascript
interact.debug().defaultOptions._holdDuration = timeInMilliseconds;
```

>The next problem was that this becomes tricky when you also have resizable, because for some reason, the event I get in resizeMove does not contain rect property so it's kinda useless.

If you mean that you don't get `event.rect` with `manualStart` resize, the solution is to add an `edges` object to the action object passed to `Interaction#start`. See #206.

>Also one has to check for the target to know if he should drag or resize.

Again not documented, but you can use [`Interaction#getAction`](https://github.com/taye/interact.js/blob/86932d7ca5abb5f5fa36471bbb405b25762c4f5e/interact.js#L4544)  to make things a little easier.

>So, maybe it's easy to implement this delay option for both actions, this would also add a lot more flexibility.

This sounds like a good idea and I don't think it should be difficult. However, I won't be able to work on it for a few weeks so you'll have to use `manualStart` for now.

**Comment by taye** [comment]
>PS: there is also a small bug that cursor still changes when manualStart is true.

You can use the [`Interactable#styleCursor`](http://interactjs.io/api/#Interactable.styleCursor) method to enable/disable the cursor styles. I think it's better not to disable it by default when `manualStart` is `true`.

**Comment by razvanphp** [comment]
Thank you for your answer, I will try. Are pull requests welcome? I can try to implement this myself.

Currently on each `onDragMove` I can check if `event.dt === event.duration` so that I know it's the first interaction, but I don't know how to prevent that move, I can return false, but the `onDragEnd` event still contains the full movement, I can't prevent some steps that I consider illegal.

**Comment by razvanphp** [comment]
> You can use the Interactable#styleCursor method to enable/disable the cursor styles. I think it's better not to disable it by default when manualStart is true.

I did that for now, but my suggestion was not to disable it by default, but to enable it only AFTER `Interaction#start`

**Comment by taye** [comment]
>Thank you for your answer, I will try. Are pull requests welcome? I can try to implement this myself.

I'm working on refactoring the codebase so I can't take pull requests for features at the moment.

>Currently on each onDragMove I can check if event.dt === event.duration so that I know it's the first interaction, but I don't know how to prevent that move, I can return false, but the onDragEnd event still contains the full movement, I can't prevent some steps that I consider illegal.

I'm not sure that I understand what you're trying to do. Are you trying to cancel an action after it has started? There's no stable API for that.

>I did that for now, but my suggestion was not to disable it by default, but to enable it only AFTER Interaction#start

That would be convenient in some cases but I expect that the cursor style would be desirable before the action is started and I don't see a good way of making this optional.

**Comment by taye** [comment]
The "delay" option has been renamed to "hold".
