### ISSUE TITLE
Demo code not working on touchscreen IE 11

### ISSUE THREAD

**Issue by razvanphp** [taye/interact.js#216]
I isolated the demo code from the homepage in [this jsfiddle](http://jsfiddle.net/6z137trz/), after my code was working perfect in all browsers, except IE 11 touchscreen, Windows 7. It does not work with the touch, but works with the mouse.

What dazzles me is that if I go directly on http://interactjs.io then IT WORKS with touch too! I can't understand the difference..

Can anybody reproduce this?

**Comment by taye** [comment]
You probably need to use the [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS property.

**Comment by razvanphp** [comment]
Geez, works now, maybe this should be somewhere in the documentation.

Thank you!

**Comment by taye** [comment]
I've added a note to the [FAQ](http://interactjs.io/docs/faq/#touch-input-on-internet-explorer).
