### ISSUE TITLE
Issue with resize from top and left sides/corners

### ISSUE THREAD

**Issue by ejrudy** [taye/interact.js#218]
Has anyone seen this behavior before? It seems random when it happens, but it probably occurs about 50% of the time. The div is both draggable and resizeable.

https://youtu.be/AUC3fZ1S2Vc

**Comment by taye** [comment]
Could you paste the `resizemove` listener function here? At least the part that changes the target's position and size.

**Comment by ReklatsMasters** [comment]
@ejrudy You have error in resize listener. You should not to add `event.dx` and `event.dy`. Use this:

```
var x = +target.getAttribute('data-x') || 0; // NO event.dx
var y = +target.getAttribute('data-y') || 0; // NO event.dy
```

**Comment by ejrudy** [comment]
.on('resizemove', function(event) {
          var target, x, y;
          target = event.target;
          x = parseFloat(target.getAttribute('data-x') || 0);
          y = parseFloat(target.getAttribute('data-y') || 0);
          target.style.width = event.rect.width + 'px';
          target.style.height = event.rect.height + 'px';
          x += event.deltaRect.left;
          y += event.deltaRect.top;
          target.style.webkitTransform = target.style.transform = 'translate(' + x + 'px,' + y + 'px)';
          target.setAttribute('data-x', x);
          return target.setAttribute('data-y', y);
        });

**Comment by ejrudy** [comment]
.on('resizemove', function(event) {
          var target, x, y;
          target = event.target;
          x = parseFloat(target.getAttribute('data-x') || 0);
          y = parseFloat(target.getAttribute('data-y') || 0);
          target.style.width = event.rect.width + 'px';
          target.style.height = event.rect.height + 'px';
          x += event.deltaRect.left;
          y += event.deltaRect.top;
          target.style.webkitTransform = target.style.transform = 'translate(' + x + 'px,' + y + 'px)';
          target.setAttribute('data-x', x);
          return target.setAttribute('data-y', y);
        });

**Comment by ejrudy** [comment]
i will try that @ReklatsMasters

**Comment by ReklatsMasters** [comment]
@ejrudy I use same code. I haven`t bugs.

**Comment by ejrudy** [comment]
@ReklatsMasters can you show me your 'resizemove' event function?

**Comment by kelvin4incubit** [comment]
.on('resizemove', function (event) {
    console.log('Event: ');
    console.log(event);
    var target = event.target.parentElement,
        x = (parseFloat(target.getAttribute('data-x')) || 0),
        y = (parseFloat(target.getAttribute('data-y')) || 0);
    // update the element's style
    target.style.width  = event.rect.width + 'px';
    target.style.height = event.rect.height + 'px';
    // translate when resizing from top or left edges
    x += event.deltaRect.left;
    y += event.deltaRect.top;

    target.style.webkitTransform = target.style.transform =
        'translate(' + x + 'px,' + y + 'px)';
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
    target.textContent = Math.round(event.rect.width) + '×' + Math.round(event.rect.height);
  });

**Comment by kelvin4incubit** [comment]
This having bugs
