### ISSUE TITLE
How to find original location of an image

### ISSUE THREAD

**Issue by HerrimanCoder** [taye/interact.js#219]
I am using raw images instead of divs as my draggable objects and this seems to work fine:

`<img id="drag4" src="images/SVG/ksTire.svg" class="draggable js-drag" style="width:85px">`

I cannot figure out how to return an image back to its original starting point before the drag began. I need to store the original coords in a js variable, and depending on certain events, return the image back to its exact original starting locations. I read on one of your other posts that there's no built-in way to do this, and then you described a little custom way to make it happen. I tried that and other things. I experimented with various x/y coords on the event, and tried getElementById also, with no luck. Whenever I try to return the image back to its original location, some approaches will bring it back the first time, but then when I begin to drag it again, it's way off in a strange place, not under the mouse pointer anymore.

Could you please provide a bit of sample code showing how to snap a draggable object back to it's initial location? I already figured out the places in code *where* to call this, all I need is how to get images back to the right place, and then to continue to behave properly after that occurs. Thank you.

**Comment by taye** [comment]
This is discussed in issue #79.

**Comment by HerrimanCoder** [comment]
I found the solution and posted it here: http://stackoverflow.com/questions/31038489/how-to-find-original-location-of-an-image/31083232#31083232
