### ISSUE TITLE
Cancel the dragging movement when mouse goes outside certain area 

### ISSUE THREAD

**Issue by PengfeiWeng** [taye/interact.js#220]
Hi, I'm new to interact.js and really wish to get some help from here.

My Case:
our product embeds a Host WebBrowser inside a Win APP. We saw an issue: when you drag an item outside the browser scope and then release your mouse, the item will be still attached to your mouse. 

Current plan:
we want to fire an event to force terminate the dragging action when detect "mouseleave" the container.

Problem:
I tried to fire "dragend" event, which can be caught by the draggable element, but the element is not really dropped. Also tried interact.stop(null), not working either.
I dig into the source code a little bit. It looks like, if i can fire a "pointerup" event or a "blur" event and make them caught by interact.js, problem will be resolved. But i tried every way I know to fire these two events and no expected results,

I tried $(window).blur(); $(document).blur(); $('.theContainer').blur() (also ".trigger('pointerup')" on the above three objects). None of these calls can be caught.

Besides, when I normally click anywhere inside the container, interact.pointerUp listener is called.

I wonder how do interact attach the pointerup or blur listener? 

Hope to hear from you.

thanks a lot,

Jason

**Comment by PengfeiWeng** [comment]
The way I fire "dragend" event is:

var dragendEvent: InteractEvent = <InteractEvent>{ type: 'dragend' };
this.dragInteractable.fire(dragendEvent);

This can be caught be the dragendHandler I attach in .draggable(onend: dragendHandler() )

**Comment by PengfeiWeng** [comment]
Hi guys, I figure it out. InteractJs is tracking pointer events on the document.

Thus, trigger on HTML Element is not working.

you should call on the document, like:
var event = document.createEvent('MouseEvents');
event.initEvent('blur', true, true);
document.dispatchEvent(event);

**Comment by chanpory** [comment]
@PengfeiWeng, can you elaborate on the solution? I'm running into the same issue, and not quite understanding your implementation.  How are you firing the `dragend` event?

**Comment by chanpory** [comment]
Ah I was able to fire your suggested code on mouseleave, like this:

```
    // Cancel dragging if mouse leaves the editor container.
    $('.element-container').on('mouseleave', function(){
      var event = document.createEvent('MouseEvents');
      event.initEvent('blur', true, true);
      document.dispatchEvent(event);
    });

**Comment by taye** [comment]
In the latest `unstable` build you can use `event.interaction.stop()` to stop a drag, resize or gesture.

**Comment by tylercubell** [comment]
@taye Would adding `eventMap.mouseleave     = listeners.pointerUp; ` here solve the problem?

https://github.com/taye/interact.js/blob/c05a05ccadfe2125fb5736a64cce7d900c13985c/src/interactions.js#L35

**Comment by davismj** [comment]
Thanks @taye, worked great.
