### ISSUE TITLE
Resize second element moves first element

### ISSUE THREAD

**Issue by mikeyc1030** [taye/interact.js#221]
https://jsfiddle.net/xo3zzq1c/1/
In the above jsfiddle example, I have 2 div elements with drag and resize, if you resize the right hand box by dragging the bottom right corner up, the left hand box moves up with it.
I'm planning to have multiple boxes within the same parent but would like the resize ability to be independent of all other elements.
Is there a setting I've missed perhaps. (Loving all the other features by the way)

**Comment by ReklatsMasters** [comment]
@mikeyc1030 just add `position: absolute` to block. https://jsfiddle.net/xo3zzq1c/2/

**Comment by mikeyc1030** [comment]
Amazing, thanks ReklatsMasters for the tip - works perfectly...

**Comment by anithaiyer** [comment]
I first position a lot of draggable elements to be dropped into drop zone
Using position:absolutes , makes all elements stack up.. Any suggestions for this?

**Comment by sberney** [comment]
Yeah, I don't want to use `position: absolute`. I have the same issue as anithaiyer, in that they don't layout correctly when the page loads if the widgets are positioned absolutely.

[Demo](https://iocarbon.sohalion.com/abc/)

**Comment by Shmacked** [comment]
I haven't tried it, but I wonder if you change the elements css after the page loads if it will be different... maybe use jQuery to select all the elements and change with the .css method? May not be the most effective way of doing it, but its a thought.

**Comment by sberney** [comment]
@Shmacked If I change the CSS after it is laid out, the layout will change, as if I never laid them out in the first place. The widgets don't stay stationary when you change the CSS, they are positioned according to it.

The issue I have is that I want to use relative positioning, so that my widgets are confined to an area of the screen, so that they have collision with my navigation. I want my widgets to be relative to their container. iframes would be a solution if they could still animate and bounce outside of the frame, but that's not possible.

**Comment by Shmacked** [comment]
That would seem like a fair assessment and one that you'd rightfully expect. I have been playing with similar libraries and from my experience with them, some of them load extra elements and additional css via javascript that doesn't take place till after the page loads. I am new to this library and don't know if that is a reasonable expectation or not. Let me think for a minute tho. We have to keep position: absolute; but when you do that, elements stack on top of each other. If you load the elements dynamically via javascript, you could get their widths and heights and offset them like that, if that makes sense. It might be a stackoverflow question. I might look into how to position child elements relative to one another with position: absolute; or something like that. I wish I could be of more help, but I am not a css expert. I am an amateur at best.

**Comment by Abdullah-Shamhan** [comment]
Still having the same issue, anyone managed to fix it?
