### ISSUE TITLE
Don't understand restriction: 'self'

### ISSUE THREAD

**Issue by blackChef** [taye/interact.js#222]
>  'self' – restrict to the target element’s rect

I don't understand what this mean. I can still drag around when setting this option. 
Can any one provide some demos please?

**Comment by taye** [comment]
It is useful when the drag event listeners do not move the target element but move or draw something else instead.

http://rawgit.com/taye/interact.js/v1.2.4/demo/snap.html
http://codepen.io/taye/pen/GgpxNq
