### ISSUE TITLE
"dragend" not working when mouse goes out of an embedded WebBrowser

### ISSUE THREAD

**Issue by PengfeiWeng** [taye/interact.js#226]
Hi Taye,
Firstly, thank you for writing this tool. We love it!

Recently, we face such a problem:
We embed a webbrowser in a .NET app (by using C# WebBrowser class). Inside the webbrowser, we visit pages that applying interact.js for their draggable elements.

This issue is: when you drag a element, move the mouse out of the embedded browser and then release the mouse, the element would not be released. It will still be attached to you mouse.

Some details that might be helpful:
1. This is only for embedded browser. For normal IE, the same pages work perfectly without such issue.
2.  only "dragend" is not caught. "dragmove" works well when mouse goes out of the embedded browser.

thanks,

Jason

**Comment by taye** [comment]
Hi Jason,

I don't know how the WebBrowser class works but I would guess that you need to listen for a `mouseup` (or equivalent) event on the .NET app outside the WebBrowser and then manually dispatch a corresponding `mouseup` event to the `document` of the WebBrowser's content.

**Comment by taye** [comment]
Manually dispatching a `blur` event is probably better as that results in all interactions being cancelled.
