### ISSUE TITLE
Initialize dropzone with draggable item. 

### ISSUE THREAD

**Issue by d3ep4k** [taye/interact.js#227]
Hello, 

I've looked at issues and FAQ. They helped a great deal to add some features like copy and snapping.
As this seems the best place to get any issue resolved. I want to know if there is
a way to drop a draggable item to a dropzone using code at start.

```
interact(".draggable").drop(".dropzone");
```

Once initialized the dragging, dropping and snapping will work as usual.

Thanks,
Deepak Mishra

**Comment by taye** [comment]
You can use the [`Interactable#fire`](http://interactjs.io/api/#Interactable.fire) method.

```javascript
interact('.draggable').fire({
  // the type and target properties are mandatory
  type: 'drop',
  target: document.querySelector('#initialDraggable'),

  // add whatever other properties your event listeners will use
});
```

I suggest, however, that you avoid using this method to "initialize" elements and objects. The code in the event listeners that does the initialization should be separated into one or more independent functions that you can call without having to create fake user interactions.
