### ISSUE TITLE
How to get multiple fire events for hold?

### ISSUE THREAD

**Issue by alexiskattan** [taye/interact.js#228]
I have a "hold" event setup to fire for a div.  I want to keep getting events as long the user is holding the button.  However, hold is only called once.  Is there a way to make this called multiple time?
##

**Comment by Joeao** [comment]
Couldn't you run your own function on a setInterval when the hold event is started, then cancel the interval when it ends?

**Comment by taye** [comment]
Yep, that's roughly how it would work internally anyway. Here's a solid workaround that adds an `enableHoldRepeat` method to Interactables which enables you to listen to `'holdrepeat'` events on those Interactables:

```javascript
var interactDebug = interact.debug(),
    Interactable = interactDebug.Interactable;

// add 'holdrepeat' to interact.js' list of known event types
interactDebug.eventTypes.push('holdrepeat');

// add an enableHoldRepeat method to Interactables
Interactable.prototype.enableHoldRepeat = function (intervalTime) {

  // set the interval time in the interactable's options
  this.options.holdRepeatInterval = intervalTime;
  
  this.on('hold holdrepeat', function (event) {
    var nextRepeat = {};

    event.count = event.count || 0;

    // copy the properties of the previous hold event object into the new one
    for (var prop in event) {
      nextRepeat[prop] = event[prop];
    }

    // update the count and event type
    nextRepeat.count++;
    nextRepeat.type = 'holdrepeat';
  
    // set a timeout to fire the holdrepeat event
    setTimeout(function () {
      // if the pointer was released between now and the previous hold[repeat]
      // then return early and don't fire anymore repeat events
      if (nextRepeat.interaction.holdStopTime > event.timeStamp) {
          return;
      }

      nextRepeat.interactable.fire(nextRepeat);
    },
      // timeout delay is taken for the interactable's options
      nextRepeat.interactable.options.holdRepeatInterval);
  })
  .on('move up cancel blur', function (event) {
      // set the interaction's releaseTime property
      // to stop further holdRepeat events
      event.interaction.holdStopTime = event.timeStamp;
  });

  return this;
};
```

With that, you can do:

```javascript
interact('*')
  .enableHoldRepeat(600)
  .on('hold holdrepeat', function (event) {
      console.log(event.type, event.currentTarget.nodeName, event.count);
  });
```

Here is a demo: http://codepen.io/taye/pen/xGjvby?editors=001.

**Comment by taye** [comment]
You will need to use the current [`master`](https://raw.githubusercontent.com/taye/interact.js/master/interact.js) version.

**Comment by kristianmandrup** [comment]
@taye Would this enable dragging multiple elements at once? Why not make this a standard feature of the library? Cheers :)

**Comment by kristianmandrup** [comment]
I just tried the Codepen demo but I can't see anything working. No matter how I click, hold and try to drag the elements, nothing happens!?

**Comment by taye** [comment]
@kristianmandrup multiple interactions should be enabled by default in `v1.2.6`.

The link to the interact.js script in the codepen demo was broken. I've fixed it now. The demo won't work with the latest `unstable` build.
