### ISSUE TITLE
get related zone from where the element was dragged out.

### ISSUE THREAD

**Issue by iAmShorty** [taye/interact.js#229]
hi,

first i have to say that i'm really happy with interact.js. i love it and it's so easy to implement, thanks for that great tool :+1: 

i have (maybe) a stupid question. is it possible to get the zone from where the element was dragged out? i need to compare the zones and if the zone where the element was dragged and dropped, is the same where it comes from, the action should be canceled. the action should only start when the dropzone is different from dragzone. can't find anything about it.

thx

**Comment by taye** [comment]
I would keep the information of which items are dropped into what in javascript objects so that I could check the objects that correspond to the element being dragged and the relevant dropzone elements.

For example, for each draggable element, there would be an object like:

```javascript
{
  element: document.querySelector('#draggable0'),
  droppedInto: null, // update this on drop or dragend events
  // other useful info
}
```

If there are multiple draggable elements, then they could all be stored in an array. Then in your event listeners listeners, you can find the item object that has that element by comparing each `item.element` to `event.target` and access/update the information when you've found the right object.

```javascript
var items = [...];

function getItemFromElement (element) {
  for (var i = 0; i < items.length; i++) {
    if (items[i].element = element) { return items[i]; }
  }
};

interact('.dropzone')
  .on('drop', function (event) {
    var item = getItemFromElement(event.relatedTarget);

    // if the item's previous dropzone is the same as this drop target, do nothing
    if (item.droppedInto === event.target) { return; }

    // update item.droppedInto
    item.droppedInto = event.target;

    // continue the drop event procedure...
  });
```

You could also keep only a list of items corresponding to the dropzones if you prefer, or you could have both.

**Comment by iAmShorty** [comment]
ok, got that. but i'm not sure where to set the initial info from where the element is dragged out.

**Comment by iAmShorty** [comment]
next one driving me crazy is the <code>ondrop</code> event. i added alertify to ask the user if the element should be saved or not. if the user clicks "NO", the element should go back to the position before answering the question. if the user confirmed with "YES", the element should stay in the desired dropzone.

i tried with several variables from the draggable element.

```
console.log("X: " + event.relatedTarget.getAttribute('data-start-x'));
console.log("Y: " + event.relatedTarget.getAttribute('data-start-y'));
```
writes down the correct coordinates for the selected item.

X: 509.75
Y: 400.1499938964844

but 
```
event.draggable.snap({ anchors: [{x: event.relatedTarget.getAttribute('data-start-x'), y: event.relatedTarget.getAttribute('data-start-y')}] });
```
or
```
event.interactable.snap({ anchors: [{x: event.relatedTarget.getAttribute('data-start-x'), y: event.relatedTarget.getAttribute('data-start-y')}] });
```
doesn't fire any event and the item remains where i dropped it instead of snapping back to it's position.


here is the complete ondrop function with alertify plugin for user confirmation.

```javascript
    ondrop: function (event) {
        
    	alertify.confirm('Are you sure?', function(e) {
            if (e) {
                var delete_promise = $.ajax({
                    url: "http://localhost/test.aspx",
                    dataType: "text",
                    type: "POST",
                    data: "",
                    error: function(xhr, status, error) {
                        alertify.log('error', 'error');
                        return false;
                    },
                    success: function(data) {
                        alertify.log('success', 'success');
                        return false;
                    },
                    complete: function(data) {
                        console.log(data.status);
                    }
                });
            } else {
                console.log("X: " + event.relatedTarget.getAttribute('data-start-x'));
                console.log("Y: " + event.relatedTarget.getAttribute('data-start-y'));
                

                // snapping back to original position if user clicks cancel
                //event.draggable.snap({ anchors: [{x: event.relatedTarget.getAttribute('data-start-x'), y: event.relatedTarget.getAttribute('data-start-y')}] });
                //event.interactable.snap({ anchors: [{x: event.relatedTarget.getAttribute('data-start-x'), y: event.relatedTarget.getAttribute('data-start-y')}] });
            }
    	});

    },
```

**Comment by taye** [comment]
>ok, got that. but i'm not sure where to set the initial info from where the element is dragged out.

There's not any convenient API for doing this with interact.js. I feel that that information should be determined by your application before any drag events. If you know where the elements will be rendered initially, then you should be able to determine the dropzone, if any, that they are in before the first drag event starts. That would depend on how the HTML is being generated and how the objects are set up.

>next one driving me crazy is the ondrop event. i added alertify to ask the user if the element should be saved or not. if the user clicks "NO", the element should go back to the position before answering the question. if the user confirmed with "YES", the element should stay in the desired dropzone.

interact.js only maintains information about an element during an interaction. By the time the `drop` event is fired, the end coordinates have already been calculated and won't be affected by changing the snap targets.

You should move the element "manually" by changing its style and also updating the displacement position that your application stores (eg. with `element.setAttribute('data-x/y')`).

By the way, you should use the updated snapping API:

```javascript
interactable.<action>able({
  snap: {
    targets: [...]
  }
});
```
as described at http://interactjs.io/docs/snapping/. The old API (`interactable.snap({...})`) will be removed in the near future.

**Comment by iAmShorty** [comment]
hmm, means that i can not use the snap method to move the element back to it's start position even if i have the coordinates before moving to the dropzone?

**Comment by iAmShorty** [comment]
got it sorted and is working now, thx for info :)
