### ISSUE TITLE
count items in each zone and disallow drop when limit is reached

### ISSUE THREAD

**Issue by iAmShorty** [taye/interact.js#230]
Is there an easy way to count all items and deny a drop to the zone if max item count is reached?

or the smarter way, remove the item where the new one is dragged over and place the old one in a defined standard zone or drop it into the place where the new item comes from. tried both, but can't get it to work :(

**Comment by taye** [comment]
This use case is not directly addressed by interact.js but it should be possible with API methods described at http://interactjs.io/docs/ and http://interactjs.io/api/.

**Comment by iAmShorty** [comment]
too bad :(

would be nice if you could point me to the right direction, i can't get it to work :(

thx

**Comment by taye** [comment]
The best advice that I can think of is this:

Even though interact.js says that a drop has happened, your application doesn't have to believe it. You don't need to configure your draggables and dropzones such that a drop event is fired only when the application is willing to accept that action. You can ignore the drop event by returning early from your event listener if the state of your application says that the drop isn't actually possible.

For example: 
```javascript
interact(dropzoneTarget).on('drop', function (event) {
  var dropzoneItem = getItemFromElement(event.target);

  if (dropzoneItem.isFull()) {
    event.relatedTarget.style.transition = 'transform: 0.3s';
    event.relatedTarget.style.transform = /* bring the draggable element back to the start position */;
    //...
    return;
  }

  // otherwise accept the drop...

  dropzoneItem.contents.push(event.relatedTarget);
  //...
});
```

**Comment by iAmShorty** [comment]
solved it, thanks dude :+1:
