### ISSUE TITLE
Implicitly declared global variable

### ISSUE THREAD

**Issue by demis-palma** [taye/interact.js#233]
The code inspector raises the warning "Implicitly declared global variable" for the variable "exports" at the following line:

exports = module.exports = interact;

As a consequence, the JavaScript minifier at http://javascript-minifier.com/ generates bad code on that statement.
Isn't there a better way to reference the global variable exports?

**Comment by taye** [comment]
That's sort of the standard way of doing it and I don't think it's possible any other way. You should report the problem to the maintainers of that tool.

**Comment by demis-palma** [comment]
It's a pity. The library itself seems powerful, clean and well written except for this piece of code, which I understand has been copied from another snippet.

I've explained badly the problem, I'll try to do better this time.
The problem is not limited to my compressor. The minified version released with the project itself is affected as well.

Inspecting the file interact.js, the problem appear as a simple warning: "variable export implicitly declared". Nothing to worry about.

![screenshot01](https://cloud.githubusercontent.com/assets/1609992/8758936/c3d5936e-2ce2-11e5-9244-4e8f4e7c7eda.png)

However, inspecting the file interact.min.js bundled with this package, the "warning" has turned into an "error" due to the code manipulation. See the following screenshots, now it is reported in red.

![screenshot02](https://cloud.githubusercontent.com/assets/1609992/8758963/2e6e8a82-2ce3-11e5-8a2f-4b1966db0236.png)

The error message has changed into "Unresolved variable or type". While the other occurrences, including "module" are still underlined in blue, the variable "exports" is marked in red instead.

![screenshot03](https://cloud.githubusercontent.com/assets/1609992/8758970/4b7dcd36-2ce3-11e5-88da-e7942a57bbfb.png)

Are you sure that this piece of code has been tested even in the minified version? Based on the inspector, the problem seems quite severe.

A possible solution may be, as the code refers to the global variable "exports", to call it explicitly using windows.exports
I'm quite sure that this will solve the problem. Would the code works the same using windows.exports?

What do you think?

**Comment by demis-palma** [comment]
Additional information: seems to be related with both
"use strict";
and the comment /* global exports: true, module, define */
If I remove "use strict"; then the error disappear, and returns a warning
If I put /* global exports: true, module, define */ the error returns to be only a warning.

As the minifier wipes out all the comments, that explains why the warning becomes an error.
So the code should be safe?

**Comment by taye** [comment]
The `if typeof exports !== 'undefined'` condition ensures that `exports` had previously been defined *before* attempting to use it's value. I added `/ * global exports: true, module, define * /` so that JSHint would understand that those should be treated as global variables defined outside the module's scope.

Using `window.exports` is a bad idea because the correct `exports` variable might not be there but instead floating in a scope somewhere above the module.

I am at least 98% sure that it's safe :). I suppose that ES6 `let` could potentially [cause problems](http://es-discourse.com/t/why-typeof-is-no-longer-safe/15) but I don't feel that this is something to worry about at all.
