### ISSUE TITLE
adding classList to cloned element

### ISSUE THREAD

**Issue by iAmShorty** [taye/interact.js#238]
Hi,

is it possible to add classList to a cloned element?

```
draggableElement.classList.add('can-drop-content');
```
will add other background color to an element, but that doesn't work with cloned elements. is there a chance to use the cloned element like this?

```
        var draggableElement = event.relatedTarget,
            dropzoneElement  = event.target,
            cloneElement = event.cloneTarget
```

**Comment by taye** [comment]
>is it possible to add classList to a cloned element?

Probably. That depends on how you're doing the cloning.

>draggableElement.classList.add('can-drop-content');
will add other background color to an element, is there a chance to use the cloned element like this?

I don't understand what you're asking for exactly.

**Comment by iAmShorty** [comment]
if i move the element to a dropzone, it changes the background color, depending on the dropzone. but that doesn't work with cloned elements.

**Comment by taye** [comment]
Cloning isn't something that interact.js does itself so you'll have to show what you're doing to create these cloned elements.

**Comment by iAmShorty** [comment]
got that from here.

```
    onstart: function (event) {
        clone = $(event.target).clone();
        clone.appendTo('body');
        clone.css('position','absolute')
        .offset($(event.target).offset())
```
works fine, only applying styles to the cloned element is not working.

**Comment by taye** [comment]
You should use `Interaction#start` in the cloning process to make `event.target` be the clone instead of the original element as [described in the FAQ](http://interactjs.io/docs/faq/#clone-target-draggable).

**Comment by iAmShorty** [comment]
thx for info. 

found an easier method without rewriting the target. Only adding an attribute to the clone which i use later for manipulating the cloned object.
```
clone.attr('clone', 'active');
``` 
in "ondragenter" i use
```
clonedElement    = $("[clone='active']"),
```
and after that
```
clonedElement.removeClass("can-drop-available can-drop-security").addClass('can-drop-content');
```
works and i'm happy now, thank you :)
```
