### ISSUE TITLE
dragging in iframe

### ISSUE THREAD

**Issue by sstefansgit** [taye/interact.js#239]
How to prevent iframes from capturing the mousemove events during a drag. If an element is dragged on top of an iframe and the mouse is leaving the area of the draggable, then the element stops moving.

I know jQuery UI has an option 'iframeFix', is there a similar fix for this problem in interact.js?

**Comment by taye** [comment]
>How to prevent iframes from capturing the mousemove events during a drag.

This is discussed in issue #200.

>I know jQuery UI has an option 'iframeFix', is there a similar fix for this problem in interact.js?

There's not one built in but you can likely find out how jQuery UI's 'iframeFix' does and do something similar in your application.
