### ISSUE TITLE
Rotate div via mouse action

### ISSUE THREAD

**Issue by SerjoPepper** [taye/interact.js#241]
Can I rotate div via mouse action, like in jquery-ui?
example here: http://godswearhats.com/jquery-ui-rotatable/demo.html

**Comment by taye** [comment]
There's no built-in API for doing that but it is possible if you use [`Math.atan2`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2) to get the angle of the vector from the center of the target element to `(event.pageX, event.pageY)` and apply a corresponding rotate transformation to the target element's style. You can use `event.interactable.getRect(event.target)` to get the target element's rect and use that to calculate the center.

**Comment by dsslimshaddy** [comment]
How to do this ???

**Comment by Jeremboo** [comment]
This codepen can be useful:  https://codepen.io/taye/pen/wrrxKb
