### ISSUE TITLE
how to synthetically start drag and drop interactions?

### ISSUE THREAD

**Issue by D1plo1d** [taye/interact.js#242]
Hey, I read in the docs that I can start a interaction using `manualStart` and `interaction.start` but that seems to be only possible if you already have an event with an interaction object.

For my purposes I need the dom element I'm creating to be dragging from the moment it is created and then dropped once the mouse is clicked (after which point it becomes a normal drag and drop mouse down to drag / mouse up to drop-type thing).

Is there any way to do this with interact.js?

**Comment by taye** [comment]
The pointer needs to be held down for an interaction to start. You can fake that by manually [creating and triggering a `mousedown`](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#Triggering_built-in_events).

**Comment by D1plo1d** [comment]
Thanks!
