### ISSUE TITLE
draggable onmove ff button bug

### ISSUE THREAD

**Issue by Denni007** [taye/interact.js#243]
I register the draggable option on my elements:
```javascript
interact('.module').draggable({
  onmove: e => {
    console.log(e.button);
  }
});
```

The button value is in Firefox 0 but it must be 2 (right mouse button). The original event is also wrong but it have a buttons (with s at the end) that contains the correct value 2. Can you fix it?

**Comment by taye** [comment]
Which version of Firefox are you using?

**Comment by Denni007** [comment]
38.0.1 and 39 testet

**Comment by Denni007** [comment]
```javascript
        this.pageX     = page.x;
        this.pageY     = page.y;
        this.clientX   = client.x;
        this.clientY   = client.y;

        this.x0        = interaction.startCoords.page.x;
        this.y0        = interaction.startCoords.page.y;
        this.clientX0  = interaction.startCoords.client.x;
        this.clientY0  = interaction.startCoords.client.y;
        this.ctrlKey   = event.ctrlKey;
        this.altKey    = event.altKey;
        this.shiftKey  = event.shiftKey;
        this.metaKey   = event.metaKey;
        this.button    = event.button;

        // Changes from me
        if(event.buttons)
            this.button = event.buttons;

        this.target    = element;
        this.t0        = interaction.downTimes[0];
        this.type      = action + (phase || '');

        this.interaction = interaction;
        this.interactable = target;

        var inertiaStatus = interaction.inertiaStatus;

        if (inertiaStatus.active) {
```

**Comment by Denni007** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons says
> The MouseEvent.buttons read-only property indicates which buttons were pressed on the mouse to trigger the event.
> 
> Each button that can be pressed is represented by a given number (see below). If more than one button is pressed, the value of the buttons is combined to produce a new number. For example, if the right button (2) and the wheel button (4) are pressed, the value is equal to 2|4, which is 6.

And it work correctly in ff

**Comment by taye** [comment]
According to [this article](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#Return_value) `event.button` (without "s") seems to be working correctly – `0` for the left button and `2` for the right button.

I'll still add the `buttons` property in addition to `button`.

**Comment by Denni007** [comment]
You can try this behavior your self by visit the following codepen: http://codepen.io/anon/pen/PqgmrV
Press the right button and move. Try it in different Browsers. Firefox didn't work the same as chrome.

![image](https://cloud.githubusercontent.com/assets/6861243/9245096/69f44a74-41a1-11e5-9a3b-c00ce2e386f1.png)

![image](https://cloud.githubusercontent.com/assets/6861243/9245099/6d8ffa8e-41a1-11e5-8bba-f225e13d80ef.png)

When came the version with the buttons attribute? I need it realy quickly. And by the way interact.js is very nice :)

**Comment by taye** [comment]
You can use it from the `master` version now.

**Comment by Denni007** [comment]
When can I use this interact.js with npm? Can you add the original event to?

**Comment by taye** [comment]
You can use it if you use `"interact.js": "taye/interact.js#master"` in your package.json file.

I don't think it's a good idea to add an `originalEvent` property to `InteractEvent`s because in the case of inertia and possibly other things in future there's no original event that caused the `InteractEvent`.
