### ISSUE TITLE
move dropzone after snap

### ISSUE THREAD

**Issue by loverdrive** [taye/interact.js#246]
Hi. In some cases my dropzone moved from their orignal position (moved after a DOM rewrite, not manually). In that case, if i previous snap a draggable element into that dropzone, the snapped element remain in his fixed position. 
I'd like to have snapped element follow the moved dropzone associated.
My idea to achieve this, is to call a new snapping function when dropzone moves (as event). Is there any event that occurs in that situation?
Something like: ondropactivate, ondropenter, etc...

Or have you any alternative idea how to achieve this?

Thank you very much!

**Comment by taye** [comment]
>Hi. In some cases my dropzone moved from their orignal position (moved after a DOM rewrite, not manually).

Hello! What do yo mean by DOM rewrite?

>I'd like to have snapped element follow the moved dropzone associated.
>My idea to achieve this, is to call a new snapping function when dropzone moves (as event). Is there any event that occurs in that situation?
>Something like: ondropactivate, ondropenter, etc...

There's no event like that. After interactions end, interact.js stops keeping track of the elements. If you know when the dropzone will move and the distance that it moves, then you should be able to move the draggable element in the same direction.

I might have misunderstood your problem. If so, a demo would be helpful.

**Comment by loverdrive** [comment]
for DOM rewrite i mean when, for example, i have a hidden element above dropzone. I drop a draggable element. Then, i show (in some interaction, button clicking) the hidden element. So, elements placed below the hidden element, shift to the bottom. The dropzone shift, but dropped element no, because they have a fixed position when i drop them.

Another example, is when i open the web page in a tablet. I dropped elements. After that, i rotate the tablet. Elements position/sizing (include dropzone) in the page changes, due to the responsive design, but dropped elements remain in the fixed position.

But also when i resize the browser window on the computer.

For the rotation of the screen, i think to use CSS media-query. When i dropped an element, i assign it a class (droppped-landscape, for example. In order to know which elements are dropped, and in which orientation). And in media query for the portrait orientation i set a translation of the element. (the distance from dropzone should be static, so it could works).

**Comment by taye** [comment]
I think the easiest thing to do might be to make the draggables children of the dropzones that they are dropped into and adjust the transformation so that the dropzones don't "jump".

```javascript
.on('drop', function (event) {
  // append draggable to dropzone element
  event.target.appendChild(event.relatedTarget);
  var dropzoneRect = interact.getElementRect(event.target);

  // subtract the dropzone's offset (probably needs some adjustment)
  x = (parseFloat(target.getAttribute('data-x')) || 0) - dropzoneRect.left,
  y = (parseFloat(target.getAttribute('data-y')) || 0) - dropzoneRect.right;

   // translate the element
    target.style.webkitTransform =
    target.style.transform =
      'translate(' + x + 'px, ' + y + 'px)';

    // update the position attributes
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
}
```

**Comment by loverdrive** [comment]
Hi @taye , thank you for the answer!
I don't understand that code. Why are you translating the element after dropped it? I think it should be translated after the rotation of screen, not on drop.
Other point i think i don't understand, is target's data-x attribute. I get "null" as value. I think target (target should be dropzone, not draggable element, right?) has not data-x attribute.

**Comment by taye** [comment]
>Why are you translating the element after dropped it?

When you move one element to another the position may change if the new parent has a different offset to the old one (CSS absolute, fixed and relative positioning change how this behaves). So you might need to find the difference in coordinates of the previous and new parents and use that to correct the child's position so that it appears unchanged.

> I think it should be translated after the rotation of screen, not on drop.

If the draggable element is a child of the dropzone, then after changing the page dimensions by resizing or changing device orientation, the the element should follow the dropzone.

> Other point i think i don't understand, is target's data-x attribute. I get "null" as value. I think target (target should be dropzone, not draggable element, right?) has not data-x attribute.

Yeah, I think you're right. You would need `event.relatedTarget`.

**Comment by taye** [comment]
@loverdrive I've added a new method that let's you simulate actions and re-apply modifiers. See #610.
