### ISSUE TITLE
Programmatically drop a draggable element onto a certain dropzone upon page load

### ISSUE THREAD

**Issue by HerrimanCoder** [taye/interact.js#248]
I need to be able to capture (and re-apply) the state of which elements were dropped onto which dropzones. Capturing the x/y coords (and which elements are on which dropzones) upon drop was easy and I have it working. What I cannot figure out is, when the browser page is reloaded, how to:

1- Move an element to an x/y coord of my choosing using interactjs properties.
2- Trigger the drop event for that element, as if the user had dragged and dropped the element to that zone.

If I brute-force the element to the x/y coords I have stored, it's not good. Although I can place the part where I want it (via javascript or jquery), any future drags of that element are very screwed up in that the mouse pointer is no longer over the element. Additionally, the drop event is not triggered for that element. However, if I could set the following interact properties upon page load, all would be well:

```
evt.target.style.left
evt.target.style.top
evt.interaction.x
evt.interaction.y
```

And I have some draggable elements on the page, for example:
`<img id="drag1" src="Tank.png" class="draggable js-drag SelectedPartTransparent" />`

So upon page load, how do I get a handle/reference to that draggable element and set the 4 properties noted above so it moves to the coords (and dropzone) of my choosing, as well as triggering the drop event for that element?

Any help would be much appreciated.

**Comment by taye** [comment]
You should read my response to a very similar request here: https://github.com/taye/interact.js/issues/227#issuecomment-120759864.

The things that you're describing are very specific to the way you've designed your application. interact.js is not concerned with the state of your application at all and you shouldn't rely on it to prepare your UI without real user interactions.

>I need to be able to capture (and re-apply) the state of which elements were dropped onto which dropzones. Capturing the x/y coords (and which elements are on which dropzones) upon drop was easy and I have it working.

>What I cannot figure out is, when the browser page is reloaded, how to:
>
>1- Move an element to an x/y coord of my choosing using interactjs properties.

There's no need to involve interact.js. It is the code in *your* `dragmove` listeners that moves elements during drag interactions. If you want to move an element without the user doing anything, use some of the code in your `dragmove` listener that does the styling to specific coordinates. If you're using the sample code from the homepage then this is the part that you need:

```javascript
    // translate the element
    target.style.webkitTransform =
    target.style.transform =
      'translate(' + x + 'px, ' + y + 'px)';

    // update the posiion attributes
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
```

>2- Trigger the drop event for that element, as if the user had dragged and dropped the element to that zone.

Again, you don't need to fake an event. Perform the key operations that are done in your drop event listeners instead.

>If I brute-force the element to the x/y coords I have stored, it's not good. Although I can place the part where I want it (via javascript or jquery), any future drags of that element are very screwed up in that the mouse pointer is no longer over the element.

Assuming you're using the sample code from the project homepage, you also need to `// update the posiion attributes` as is done in the `dragMoveListener` function.

>Additionally, the drop event is not triggered for that element.

There is no drag interaction by the user so there can't be a drop event.

>So upon page load, how do I get a handle/reference to that draggable element and set the 4 properties noted above so it moves to the coords (and dropzone) of my choosing, as well as triggering the drop event for that element?

Use jQuery or `document.querySelector[All]` to find the elements. You shouldn't need to do anything with interact.js yet. Just style the elements and restore your application's state as you see fit.

**Comment by HerrimanCoder** [comment]
This makes sense, except that I cannot get a handle to my draggable element's `interaction` property nor `target` property outside the `.on('dragmove, ...')` handler. Here is my dragmove code:

```
.on('dragmove', function (event) {
	event.interaction.x += event.dx;
	event.interaction.y += event.dy;

	if (transformProp) {
		event.target.style[transformProp] =	'translate(' + event.interaction.x + 'px, ' + event.interaction.y + 'px)';
	}
	else {
		event.target.style.left = event.interaction.x + 'px';
		event.target.style.top = event.interaction.y + 'px';
	}
			
	toggleDropZones(true);
})
```

Inside that handler [I think] I can do everything I need to position my draggable element on top of a drop zone, but I need to make that happen upon **initial page load**. So outside that handler, I don't know how to access my draggable element's `event.interaction` nor `event.target`. How can I do this?

**Comment by HerrimanCoder** [comment]
Also, you said:

>> Use jQuery or document.querySelector[All] to find the elements. You shouldn't need to do anything with interact.js yet. Just style the elements and restore your application's state as you see fit.

I found that if I simply move the element to where I want it (via javascript or jquery), internal interact x/y properties are now out of whack, and when I try to drag the element again, the element is inches away from the mouse pointer and everything is really botched up. The interact's xy properties, including `interaction.x` and `interaction.y` (and possibly also `event.target.style.left` and `event.target.style.top`) must be set the same as the position x/y via jquery, but I don't know how to get to the interaction object/property of an element upon initial page load. How is this done?

**Comment by taye** [comment]
Interactions do not normally have `x/y` properties. These are properties that you are adding. By setting `interaction.x/y` you're attaching your application's state information to objects controlled by interact.js. This is not a very good idea especially since you expect the information to persist across different interaction event sequences. Store this information in independent variables that you create and manage instead. In the demos on http://interactjs.io I never add new properties to `event.interaction` in any event listeners. You should follow those examples.

>Inside that handler [I think] I can do everything I need to position my draggable element on top of a drop zone, but I need to make that happen upon initial page load.

Then take out the code inside that handler and put it in a separate function outside of a `dragmove` handler so that you can call that new function both on page load and from a `dragmove` listener function without having to create fake events.

If you were looking at your problem from my view, you would see that asking for "how to access my draggable element's `event.interaction` [and] `event.target`" makes no sense. Elements don't have events. Interactions fire events and these events have target elements. If there's no interaction, there can't be an event and so this non existent event cannot have a target element. Refactor your application so that you don't depend on non existent interactions and you should be able to find a good solution by following the advice that I've given you.

>The interact's xy properties, including interaction.x and interaction.y (and possibly also event.target.style.left and event.target.style.top) must be set the same as the position x/y via jquery

No, the `x/y` values that your application stores for each element must be updated, as must the style of the elements themselves. You don't need an event in order to find these elements if you follow the advice that I've given above.

**Comment by HerrimanCoder** [comment]
You wrote:

>> Then take out the code inside that handler and put it in a separate function outside of a dragmove handler so that you can call that new function both on page load and from a dragmove listener function without having to create fake events.

That will only work if I can access the target property outside all the event listeners. I have carefully read everything you wrote, but still don't see how to do this. Again, if I simply position my draggable elements via javascript (not touching interact.js), the element will indeed move--**but the moment I try to drag it elsewhere, the cursor is inches away from the draggable element and now things are really screwed up**.

How can I get a reference to the `target` property of a draggable element? Or otherwise, how can I position elements independent of interact.js **without screwing up the mouse pointer position relative to the element** thereafter? Thank you.

**Comment by HerrimanCoder** [comment]
Solved here: https://github.com/taye/interact.js/issues/253
