### ISSUE TITLE
star.js: many polygons

### ISSUE THREAD

**Issue by raphaelbastide** [taye/interact.js#252]
I thy to make the script star.js work with a drawing containing multiple polygon. This script is amazing and a project of mine is based on this script. A little help or a demo would be awesome!

**Comment by taye** [comment]
What problems are you having?

**Comment by LucasLeBihan** [comment]
Well I have a .svg file with multiple polygons in it. I want each of my polygons to be editable (like in your star.js demo). But I can make the script work only for one polygon. Maybe it is not its purpose or I'm doing something wrong but I can't figure it out.

**Comment by taye** [comment]
The [star.js](https://github.com/taye/interact.js/blob/master/demo/js/star.js) file only sets things up for one polygon.

For example:

```javascript
    var sns="http://www.w3.org/2000/svg",
        xns="http://www.w3.org/1999/xlink",
        root = document.getElementById('svg-edit-demo'),
        star = document.getElementById('edit-star'),
        rootMatrix,
        originalPoints = [],
        transformedPoints = [];
```

Only one "star" element, one set of originalPoints and transformedPoints. You would need to change much of the code to do set-up for each polygon that you want.
