### ISSUE TITLE
ManualStart from mouseDown/touchStart

### ISSUE THREAD

**Issue by DennisFrostlander** [taye/interact.js#257]
This is more of a question rather than an issue. It is possible to lazy-initialize the interactable on mouseDown/touchStart event? 
For example, I have hundreds of objects displayed on the screen. But only few of them might (or might not at all) be dragged by the user. Therefore I was thinking to make a node interactable when the user actually performs a mouseDown/touchStart event on the node.

I did find an excellent property called manualStart, but all the docs mention only the examples of starting the interaction on a subsequent hold event, which already has an instance of the Interaction object.

In my case, however, I cannot write .on('mouseDown', startInteractable) because I am already inside mouseDown handler... 
Is there any supported way of creating an instance of the Interaction object when inside the mouseDown handler for the DOM node so that I could call the start() function on it?

**Comment by taye** [comment]
It's better to just use a CSS selector as a target. Then it doesn't really matter how many potential target elements exist. Event listeners are added only to the `document` and the elements that the pointer hits will be checked against the CSS selector and if a match is found then the interaction can start on that element.

>Is there any supported way of creating an instance of the Interaction object when inside the mouseDown handler for the DOM node so that I could call the start() function on it?

You could do `interact(document).on('down', startInteractable)` and create the element-specific Interactable there if one of the elements in the event path is suitable but that's essentially the same as using a selector Interactable.
