### ISSUE TITLE
How to stop dragging element on ESC?

### ISSUE THREAD

**Issue by hyzhak** [taye/interact.js#259]
I need to stop dragging element and return it to default state on ESC keypress. I'm using `interact.stop()` but it has bug https://github.com/taye/interact.js/pull/258 and even with this fix it doesn't trigger `dragend` event. So I need to trigger it manually. Is it ok? Maybe there other more convenient way to cancel/stop dragging on-a-fly?

**Comment by taye** [comment]
I've merged #258.

Manually [creating and triggering](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) a `blur` event on the window is probably the best way.

**Comment by hyzhak** [comment]
@taye thanks :). Why don't you think that interact.js should have such function?

**Comment by taye** [comment]
I think it should have it and I'm working on this in #231 but it will take some time.

**Comment by hyzhak** [comment]
@taye great, wish you good luck

**Comment by salzhrani** [comment]
@taye now that #231 is merged, is such functionality available ?

**Comment by taye** [comment]
@hyzhak @salzhrani In the latest `unstable` build you can use `event.interaction.stop()` to stop a drag, resize or gesture.

**Comment by koutsenko** [comment]
@taye I get error at the line 
5895  return element[prefixedMatchesSelector](selector);

when execute event.interaction.stop() at drag start.

I have a draggable that in some cases must not be draggable.
But this case must be calculated in the time when user starting dragging.
So I cant disable draggable before..

**Comment by spierala** [comment]
Hi @taye , when would you call `event.interaction.stop()` ? If you are dragging and then stop moving the mouse, then there is no event that I could use... 
ESC should cancel the drag also if there is no mouse movement.

**Comment by mila76** [comment]
like @spierala i can get how to implement this..
i do a document event on keypress but interactions is not present and in some cases element.target is not the element currently drag but body (even if i currently moving a draggable)
