### ISSUE TITLE
Possibility to prevent more than one draggable to be dropped on specific dropzone?

### ISSUE THREAD

**Issue by Trovats** [taye/interact.js#263]
Hey,

the title already says what I'd like to do.
I have a soccer field with position dropzones, where I can drag the players onto.

But of course it shouldn't be possible to drop more than one player at one position at a time. Is it possible to implement sth like that? Or if it is already implemented, how can I get it to work like this?

Would really much appreciate your help!

Best wishes
Marcel
![issue](https://cloud.githubusercontent.com/assets/6311379/9344012/f92abd5a-4605-11e5-957e-27351fac198e.jpg)

**Comment by taye** [comment]
See https://github.com/taye/interact.js/issues/230.
