### ISSUE TITLE
Iphone 4 dropzone displacement issue

### ISSUE THREAD

**Issue by dobromir-hristov** [taye/interact.js#264]
I have an issue with Iphone 4 and only it where when I scroll the page, the dropzone area (be it position:fixed or not) does not change its zone screen pixels so to speak.
Meaning: If i do not scroll, the drop place is where the html element is on the screen. But when I scroll the page the element moves up, but when dragged over, it does not register an event. If I try to imagine where the dropzone was on the screen before scroll, and I drag the element there, THEN it registers a dragover event. 
I tried to recreate this on jsfiddle but without luck... I will continue to try so I can show what I mean.

**Comment by taye** [comment]
Try doing the following with your dropzone Interactable(s) and see if it helps:

```javascript
interact(dropzoneSelector).rectChecker(function (element) {
  return element.getClientRects()[0];
});
```

**Comment by dobromir-hristov** [comment]
Shouldn't this function be called quite often?
Because 
```javascript
 interact('.zone').rectChecker(function (element) {
                    console.log(element.getClientRects());
                    return element.getClientRects()[0];
                })
               .dropzone({
                      \\dragEvents
               });
``
I dont get a single console log.

**Comment by dobromir-hristov** [comment]
So removing the isIOS7orLower check and getting Scroll values fixed the issue.
```javascript
 interact('.zone').rectChecker(function (element) {
                    var scroll = {
                            x: window.scrollX || window.document.documentElement.scrollLeft,
                            y: window.scrollY || window.document.documentElement.scrollTop
                        },
                        clientRect = (element instanceof SVGElement)?
                            element.getBoundingClientRect():
                            element.getClientRects()[0];

                    return clientRect && {
                            left  : clientRect.left   + scroll.x,
                            right : clientRect.right  + scroll.x,
                            top   : clientRect.top    + scroll.y,
                            bottom: clientRect.bottom + scroll.y,
                            width : clientRect.width || clientRect.right - clientRect.left,
                            height: clientRect.heigh || clientRect.bottom - clientRect.top
                        };
                });
```
I had to copy the whole function from the source because I dont want to mess with the core of the plugin. 
Ofcourse this is not a good idea, because like this, I miss the `getWindow()` function but it gets the job done.

**Comment by taye** [comment]
What version of iOS and what browser are you using? Can you try testing on both Chrome and Firefox?

**Comment by dobromir-hristov** [comment]
IOS 6.1.2 with Safari on Iphone 4. I cannot update it to 7.1.2 because its an Iphone ofc.... and nothing works as it should ... 
I will try to test under Chrome.

**Comment by taye** [comment]
Have you tried the other browsers yet?

**Comment by dobromir-hristov** [comment]
Yes. When I changed the dropzone overlap to 0.1 everything got fixed :smile: I have no idea why... 
I removed my rectChecker implementation and left the default one, and Iphone and Ipad are good.
Thank you for guiding me.

**Comment by taye** [comment]
Haha that makes sense. When overlap is used the rects of the draggable and dropzone are compared so it doesn't matter if both of them are wrong by the same amount :D

I guess `Element.getClientRects` is wrong only in iOS7 so I'll replace `isIOS7orLower` with just `isIOS7`.

Thanks for your help!
