### ISSUE TITLE
Set up draggable for touch support

### ISSUE THREAD

**Issue by jeron-diovis** [taye/interact.js#266]
I chose Interact because it seems to easily support touch events. First demo in http://interactjs.io/ works great and looks simple.
So I'm trying to implement one primitive thing:
http://jsfiddle.net/hrmyop9w/3/
And it somehow does not work on iOS, neither 8 nor 7. 
I really don't see anything touch-specific in your example configuration. It just works. 
What am I doing wrong in my sandbox?

**Comment by taye** [comment]
You need to use the `-webkit-` vendor prefix with CSS transforms on Safari.

```javascript
inner.style.webkitTransform =
inner.style.transform =
  "translate(" + translate + "px)";
```

**Comment by jeron-diovis** [comment]
Strange, it does not work in fiddle, but works in my project.
Don't understand this, but ok.
