### ISSUE TITLE
drag only within the parent zone

### ISSUE THREAD

**Issue by bikrambebarta** [taye/interact.js#268]
Hi taye,
   I am using this Interact js newly.How can an element be dragged within its parent area only. I mean if its being dragged out of the parent zone it will not even be dragged at non droppable area. it will be movable only within the parent.
Please help asap.

Thank You..
Bikram

**Comment by martemorfosis** [comment]
Found this on documentation http://interactjs.io/docs/restriction

**Comment by bikrambebarta** [comment]
Hi martemorfosis I have given parent as the restriction : restriction: "parent".  Upon dragging to non dropable one and leaving there it drops back to the drppble area. But my requirement is let it not even be dragged to non dropbale area means out of parent zone. it should be movable inside the parent area. and as soon as it is dragged out of parent zone the element ll be back to its original position...

**Comment by taye** [comment]
@bikrambebarta Can you show the behaviour that you would like with a demo or diagram?

**Comment by bikrambebarta** [comment]
Hi @martemorfosis Please see the pic below.

![pic1](https://cloud.githubusercontent.com/assets/13950271/9484915/15e48744-4bd0-11e5-8cfe-e6744bef4b02.png)

In the pic the time slot should be draggable inside the red mard zone which is set as "parent" in restriction. So it is working fine. in the sense if i dragged ut of the red mark parent zone it is reverting back into the parent zone. But I want when the user is going to drag out of the zone it ll not allow to do . either it ll cancel the drag from that point where it is leaving the parent zone. or can we anyway strict it to drag only horiozntally...

Thank You,

**Comment by taye** [comment]
I still don't understand what you're describing. A video might make things clearer.

Anyway, you don't have to use the restriction or snapping APIs to control movement. You can for example only use the `event.dx` property to move horizontally and ignore `event.dy`.

**Comment by bikrambebarta** [comment]
Hi Taye, 
   I have two divs. One is prent and one is inside it. So what attributes i will give so that it will scroll only horizontally in the parent div only.

 here i am giving attributes like this.
  restrict: {
              restriction: "parent",
              endOnly: true,
              elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
            }

Please reply quick.

Thank You.
