### ISSUE TITLE
Mootools <1.3 and Interacts.js Resizing

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [taye/interact.js#271]
The resizing is not working when used with Mootools <1.3.  Here is a fiddle with the demo : http://jsfiddle.net/2vkw52bk

**Comment by rizwanhussain-vteams** [comment]
It seems to work fine with mootools 1.3+

**Comment by taye** [comment]
This is a problem with mootools/jsfiddle and not interact.js.
