### ISSUE TITLE
Detecting changes to snap targets

### ISSUE THREAD

**Issue by randalpinto** [taye/interact.js#273]
Hello,
I am implementing a resizable element with a snap grid and I need a way to detect when the threshold between one snap target and another is crossed, in other words, when I cross a boundary that means that the resize will now snap to a different grid target if the mouse is let go. 
Is there a way to detect that from the events that are issued?
Thanks!

**Comment by taye** [comment]
There's no way yet but I plan on implementing an `[action]release` event. This is discussed in #179 and I provided a workaround that implements the events. With that, you can change the snap targets on `dragrelease` and snapping is calculated and a move happens before the end event.

**Comment by randalpinto** [comment]
My use case is more like the dragenter event but for a resizable Interactable. 
In my case, an interactable has to completely redraw on certain snap targets so I'd like to know when I am crossing into a new snap "zone" so I could potentially redraw it before the user releases the mouse. For now, I am just using the resizemove event and checking whether the size of the rect is more/less than a given snap target + an arbitrary threshold but it is a lot of boilerplate to calculate for multiple snap targets in both directions. Would be a nice addition to have a "snapenter" event to know when I am entering a new snap target area. Thoughts?

**Comment by taye** [comment]
This will change soon but for now you can use in your move listeners:

`event.interaction.snapStatus.changed` and `event.interaction.snapStatus.locked`

Some other (better) solution will be available when this method no longer is.

**Comment by taye** [comment]
The snap status object has been moved to `event.interaction.modifierStatuses.snap`. I think it will stay like this so I'm closing this issue. The final solution is to check:

`event.interaction.modifierStatuses.snap.changed` and `event.interaction.modifierStatuses.snap.locked`

in your move listeners.
