### ISSUE TITLE
Restrict to parent - draggable edges instead of draggable center

### ISSUE THREAD

**Issue by w3bappd3v** [taye/interact.js#274]
Hi Taye,

Thanks for your help on the last question I posted, have another.

So current behavior for draggable restriction within parent seems to be based on the draggable elements center and half of the element on any of 4 sides can leave the parent container.

Is there a happy path that you can think of to restrict so that none of the draggable elements area can pass beyond the parents edges?

**Comment by taye** [comment]
The following [elementRect](http://interactjs.io/docs/restriction/#elementrect) should work:

```javascript
{ left: 0, right: 0, top: 1, bottom: 1 }
```

**Comment by taye** [comment]
P.S. I gave the wrong `elementRect` but I've edited it to be correct now.
