### ISSUE TITLE
Interact js and duel.js

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [taye/interact.js#276]
The resize does not work if i include duel.js before interact.js. See the fiddle here please : http://jsfiddle.net/2vkw52bk/2/
It says 'interact' is undefined.  Duel js is included by Godaddy site builder so i have no control over it. Could you please have a look at what could be wrong here?

**Comment by taye** [comment]
That fiddle works fine for me in both Chrome and Firefox.

**Comment by rizwanhussain-vteams** [comment]
I just tested it on Chrome and Firefox on Windows and Linux. Not working. For a more practical example please go to http://www.nplva.org/ and see on the right side there is an 'Open' button. Click that and try to resize the container from left to right. Or use the 'Resize' button. In the console you will see interact not found error.

**Comment by rizwanhussain-vteams** [comment]
I replicated the same thing in the fiddle. Just removed all things unnecessary.

**Comment by taye** [comment]
Duel seems to come with RequireJS or something similar so interact.js defines itself through that. You need to then require `'interact'`. This should work for you whether Duel is there or not:

```javascript
if (window.interact) {
  useInteract(window.interact);
}
else {
  require(['interact'], useInteract);
}

function useInteract (interact) {
  interact('*').on('tap', function (e) {
    // put the code that uses interact.js in here
    console.log(e.type, e.currentTarget.nodeName);
  });
}
```

**Comment by rizwanhussain-vteams** [comment]
Awesome. This seems to work. Thank you. Any other possibilities where you think this object might not be available i.e. it's not a window object but does not fall into the else part in the above code? I'm actually thinking of other frameworks that might use the object different way. Sorry i'm not very fluent with js and it's frameworks.

**Comment by taye** [comment]
I guess there's also a chance that there's a CommonJS/Node style require instead. I think that the following should cover most cases:

```javascript
// available globally
if (window.interact) {
  useInteract(window.interact);
}
// check for AMD
else if (typeof 'define' === 'function' && define.amd) {
  require(['interact'], useInteract);
}
// finally try CommonJS
else {
  useInteract(require('interact'));
}
```

**Comment by rizwanhussain-vteams** [comment]
Ok. Thanks man. Really appreciate you helping out.
