### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead.

### ISSUE THREAD

**Issue by lookfirst** [taye/interact.js#277]
Seeing this in Chrome 45.0.2454.85 (64-bit) dev tools console.

**Comment by taye** [comment]
All the properties of events are copied for interact.js' `move`, `tap`, `hold`, etc. event objects including deprecated properties. You can safely ignore that warning.

**Comment by lookfirst** [comment]
@taye Lame. I don't want to see that in my dev tools console.

**Comment by baptistebriel** [comment]
@lookfirst you could edit the `extend` function
https://github.com/taye/interact.js/blob/0b94aace680199b6261989363dfc102532c49a5d/interact.js#L547

```javascript
function extend (dest, source) {
  for (var prop in source) {
      dest[prop] = source[prop];
  }
  return dest;
}
```
```javascript
function extend (dest, source) {
  for (var prop in source) {
      if(prop != 'webkitMovementY' && prop != 'webkitMovementX')
        dest[prop] = source[prop];
  }
  return dest;
}
```

**Comment by lookfirst** [comment]
@baptistebriel Perfect... submit a PR. =)

**Comment by lookfirst** [comment]
@taye How many duplicate issues will you close before fixing this?

**Comment by taye** [comment]
Checking for those property names whenever the `extend` function is being used on any object wasn't a good solution. I created and used a new `pointerExtend` function instead.

**Comment by taye** [comment]
@lookfirst 

> Perfect... submit a PR. =)

That solution was far from perfect.

> How many duplicate issues will you close before fixing this?

You would have done better to give me reasons to prevent those warnings from showing up. You didn't write anything before that clearly meant that you were looking for a change in interact.js to remove the warnings.

**Comment by lookfirst** [comment]
@taye Thanks for fixing things.

**Comment by taye** [comment]
You're welcome :)

**Comment by lookfirst** [comment]
@taye New release time? =)

**Comment by taye** [comment]
Very soon, probably before the end of the week. [And this time I mean it](https://github.com/taye/interact.js/issues/180#issuecomment-108134918).

**Comment by lookfirst** [comment]
#releaseearlyreleaseoften

**Comment by taye** [comment]
There aren't proper tests though so I didn't have the confidence to release and I was too busy to deal with potential bug reports. I'm working on the testing problem but it's a lot of work.
