### ISSUE TITLE
Tern plugin for interact.js

### ISSUE THREAD

**Issue by angelozerr** [taye/interact.js#280]
It should be cool if we could have a tern plugin for interact.js. I could help you if you need to start something. But it should be very better to generate it from the API.  Could you explain me if http://interactjs.io/api/ is generated from JS sources or something?

**Comment by taye** [comment]
I currently use [Dr.js](https://github.com/adobe-webplatform/dr.js) to generate the API page. I don't think it would be worth the effort to try to use it for this. I actually started some time ago to write a definition file manually. Would a complete definitions file be enough or do you think it would be very beneficial to also use Tern's plugin API?
