### ISSUE TITLE
Use inertia slide feature to move back dragging element to the initial position 

### ISSUE THREAD

**Issue by VladyslavKurmaz** [taye/interact.js#281]
Hi.
I need to implement next scenario:
* user start dragging element
* then user dropped element outside the drop zone
* element slides back to the initial position, like when library move any elements back to the restriction area.

How can I implement this behavior?
What methods should I call inside one or more event handlers dropactivate, dropdeactivate, dragenter, dragleave, dropmove, drop?

Thanks in advance.

**Comment by taye** [comment]
You should read through the discussion in issue #79 and also read https://github.com/taye/interact.js/issues/265#issuecomment-133676030.
