### ISSUE TITLE
Google warning Touch.webkitRadiusX

### ISSUE THREAD

**Issue by martinaudet** [taye/interact.js#282]
I've just seen this warning in Google "'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead." Have you plan to fix this?

**Comment by mto0815** [comment]
Also still having deprecated warnings after update to version 1.2.5

![interact-depr-message](https://cloud.githubusercontent.com/assets/7868018/9848344/8df9aed4-5ae0-11e5-9a6c-9d3da8e69527.png)

**Comment by taye** [comment]
Now (8d13746) you can also choose which pointer properties to avoid. Eg:

```javascript
var prefixedPropREs = interact.debug().prefixedPropREs;

// ignore all moz, ms, webkit prefixed properties
prefixedPropREs.moz = prefixedPropREs.ms = prefixedPropREs.webkit = /./;
```
