### ISSUE TITLE
Problems with unset

### ISSUE THREAD

**Issue by thodgens** [taye/interact.js#283]
I was noticing that I was leaking the elements for interactables that had been created and destroyed.  I found the unset function, but it doesn't appear to work.  unset calls events.remove, which in turn tries to find the element using indexOf on the elements array.  Unfortunately, the element object based into remove is the interactable, not it's _element.  Shouldn't unset actually look like:

        unset: function () {
            events.remove(this._element, 'all');

instead of

        unset: function () {
            events.remove(this, 'all');

I made that change and it got rid of my leaks of the detached DOM tree objects.  Does the change seem correct?  Is it complete enough?

Thanks,

Tom Hodgens

**Comment by taye** [comment]
Yeah, that seems good. Thanks!

**Comment by taye** [comment]
This is already fixed in the latest version (1.2.5). See commit c4817af.
