### ISSUE TITLE
Blurred text after resizing or dragging few times in Chrome

### ISSUE THREAD

**Issue by radiart** [taye/interact.js#285]
I created div with dragging and resizing option, when I use one of them few times text in Chrome becomes blurred. 

When I remove "transform" param in css it's becomes sharp again, but position of div is backing to default. Do you know how to fix it?

![Image](http://s24.postimg.org/qkw5zvzg5/text.jpg)

**Comment by Joeao** [comment]
I believe that this is to do with Chrome itself (Specifically Chrome for Desktop). When applying transforms on Chrome for Android, the text isn't blurry. I have the same issue with scaling an element via Transform.

**Comment by taye** [comment]
@Joeao is right. One thing that you can do is remove the translation on `dragend` and use it as `top` and `left` offsets. The element should be positioned `relative` or `absolute`. If you store the dragged offset in data-X/Y attributes, it would go something like this:

```javascript
...
.on('dragend', function (event) {
  var target = event.target,
    dragX = parseInt(target.dataset.x, 10) || 0,
    dragY = parseInt(target.dataset.y, 10) || 0,
    offsetX = parseInt(target.style.left) || 0,
    offsetY = parseInt(target.style.top) || 0;

  target.dataset.x = 0;
  target.dataset.y = 0;
  target.style.transform = '';
  target.style.left = offsetX + dragX + 'px';
  target.style.top  = offsetY + dragY + 'px';
});
```

**Comment by Joeao** [comment]
I've found another reason for blurring can be that a pixel value could be a really long/obscure float, rounding to the nearest whole or half pixel will fix it.
