### ISSUE TITLE
Subscribing to events of existing interactions

### ISSUE THREAD

**Issue by itmaor** [taye/interact.js#288]
Let's say I have the following code:
```javascript
<p id="first"> First </p>
<p id="second"> Second </p>
<p id="third"> Third </p>
```
Now I create a drag interaction for each element separately since each requires something different:
```javascript
interact('#first').draggable({startdrag: function........});
interact('#second').draggable({startdrag: function........});
```
I then want to do the same action when each element is dragged so I want to listen to all three:
```javascript
interact('p').on('move', function(event) {......});
```
That, however, doesn't work. If I understand correctly, I cannot listen to <p> elements in general and expect to be subscribed to interactions that were created for particular elements.

Is that true? is there a way to accomplish what I tried above?

**Comment by taye** [comment]
If you meant '*drag*move' in the last code block, no that won't work. Each interactable has it's own distinct configuration and set of listeners for InteractEvents..

If you declare the listener function outside the call to `on` then you can use it for interactables.

```javascript
var dragMoveListener (event) { ... };

interact('#first').on('dragmove', dragMoveListener);
interact('#second').on('dragmove', dragMoveListener);
```
