### ISSUE TITLE
Gesture does not work in 1.2.5

### ISSUE THREAD

**Issue by JulienBier** [taye/interact.js#289]
Hi there,
It seems that the gesture feature does not work anymore with the 1.2.5 update in a Angular app. (tested on iOS9, iOS8 and android devices)
Here is the interactjs code:

```javascript
var eventCallbacks = {
	dragstart: onDragStart,
	dragmove: ctrl.onMove,
	dragend: onDragEnd,
	gesturemove: ctrl.onGestureMove,
	gesturestart: ctrl.onGestureStart,
	gestureend: ctrl.onGestureEnd,
	wheel: ctrl.onMouseWheel,
	doubletap: ctrl.onDoubleTap
};
var gestureArea = element.get(0); // DOM element
window.interact(gestureArea)
	.styleCursor(false)
	.draggable(true)
	.gesturable(true)
	.on(eventCallbacks);
```
The `ctrl.onGestureStart`, `ctrl.onGestureMove` and `ctrl.onGestureEnd` methods are never called. 
Everything else works well.

When I get back the 1.2.4 version, everything is fine.

Any idea about a change which could break the gesture in the 1.2.5 update ?

Thanks.

**Comment by taye** [comment]
It was caused by 4ba212c which fixed another bug. You can workaround the bug by using a CSS selector as the interactable target instead of an actual DOM elmeent. I'll try to make a proper fix soon.

**Comment by JulienBier** [comment]
Thanks for the help.
Any idea when it will be fixed?

**Comment by taye** [comment]
Most likely before Sunday of this week.
