### ISSUE TITLE
Recalculate the snapping point when resizing the browser window

### ISSUE THREAD

**Issue by zzwt** [taye/interact.js#290]
Hi, i am new to interact.js and don't know where to put my question. I am trying to keep a draggable div stay in the same position "relatively" to the parent div width. I am using a target function to calculate the nearest snapping point on an "dragmove" event based on parent div width for a draggable div. When i resize the browser window,however, the draggable div will stay still and then out of the view as the window shrinks. I am wondering, is there an easy way to recalculate the snapping point when the window is resized so i can keep the div moving accordingly?

**Comment by taye** [comment]
You could listen for a window [`resize` event](https://developer.mozilla.org/en-US/docs/Web/Events/resize) and then call your snapping function with the `x`, `y` coordinates of the element to get what should be the new position for the element.

**Comment by chloeleichen** [comment]
but dragmove will not be called on window resizing? Is there a way to manually called `snap`? Thanks
