### ISSUE TITLE
Error with setEventXY when attempting to manually start interaction

### ISSUE THREAD

**Issue by si13b** [taye/interact.js#292]
Following the example in the FAQ for making a clone target draggable http://interactjs.io/docs/faq/#clone-target-draggable, I get a JS error in the 1.2.6 development build:

```
setEventXY	@	interact.js:606
Interaction.setEventXY	@	interact.js:1319
Interaction.start	@	interact.js:1751
```

`setEventXY` expects the second parameter `pointers` to be array-like, but the `Interaction#start` function is not supplying that argument.

**Comment by si13b** [comment]
Checking the latest source, this looks to already be fixed.

**Comment by taye** [comment]
For anyone who isn't ready to update to the latest `unstable` version, the following workaround should fix this problem wherever you're using the `Interaction.start` method:

```javascript
    if (interaction.pointerIsDown && !interaction.interacting()) {
      ...
      var action = { name: 'drag' };

      // -- workaround for a bug in v1.2.6 of interact.js
      interaction.prepared.name = action.name;
      interaction.setEventXY(interaction.startCoords, interaction.pointers);
      // --
      // start a drag interaction targeting the clone
      interaction.start(action, event.interactable, clone);
    }
```
