### ISSUE TITLE
How to preserve snapping while disabling sliding inertia?

### ISSUE THREAD

**Issue by HerrimanCoder** [taye/interact.js#293]
I have my draggables doing a nice little animated snap into dropzones, which I like. But I need to disable the functionality that triggers different behavior when moving the mouse while releasing the mouse button. When the user releases the mouse button while the mouse is still moving, I get unwanted behaviors. How can I disable this while still allowing snapping? In other words, when the user lets go of the mouse button while the mouse is still moving, I'd like identical behavior as if the mouse were being held still. How is it done? Here is what I believe to be my relevant code:

~~~
interact('.js-drag')
    .draggable({
        max: Infinity,
        snap: {
            targets: [],
            range: Infinity,
            relativePoints: [{
                x: 0.75,
                y: 0.45
            }], 
            endOnly: true
        }
    })
    .on('dragstart', function(event) {
        validDrop = false;

        event.interaction.x = parseInt(event.target.getAttribute('data-x'), 10) || 0;
        event.interaction.y = parseInt(event.target.getAttribute('data-y'), 10) || 0;

        if (event.target.id == "drag5" || event.target.id == "drag6" || event.target.id == "drag7") {
            var drop1AWidth = parseFloat($("#drop1A").css("width"));
            var drop2AWidth = parseFloat($("#drop2A").css("width"));

            if (drop1AWidth < underCabPixelWidth)
                $("#drop1A").css("width", underCabPixelWidth);

            if (drop2AWidth < underCabPixelWidth)
                $("#drop2A").css("width", underCabPixelWidth);

            if (drop1AWidth < underCabPixelWidth || drop2AWidth < underCabPixelWidth) {
                specialComponentGripped = true;
                resizeRemainingZones();
            }
        }

        showPartRules(event.target.attributes["category"].value);
    })
    .on('dragmove', function(event) {
        event.interaction.x += event.dx;
        event.interaction.y += event.dy;

        if (transformProp) {
            event.target.style[transformProp] = 'translate(' + event.interaction.x + 'px, ' + event.interaction.y + 'px)';
        } else {
            event.target.style.left = event.interaction.x + 'px';
            event.target.style.top = event.interaction.y + 'px';
        }

        toggleDropZones(true);
    })
    .on('dragend', function(event) {
        event.target.setAttribute('data-x', event.interaction.x);
        event.target.setAttribute('data-y', event.interaction.y);
        toggleDropZones(false);
    })
    .inertia(true)
    .restrict({
        drag: "",
        endOnly: true,
        elementRect: {
            top: 0,
            left: 0,
            bottom: 1,
            right: 1
        }
    })
~~~

Thanks in advance.

**Comment by taye** [comment]
Try setting the inertia resistance to `Infinity`

```javascript
interact('.js-drag').draggable({
  inertia: { resistance: Infinity }
});
```

**Comment by HerrimanCoder** [comment]
Unfortunately that didn't work. The behavior was modified a bit, but not solved. It seems that a different event handler gets triggered (or at least a different codepath somewhere) when the slide-while-releasing occurs. Do you know where I can tap into that? If so, I should be able to solve it.

**Comment by HerrimanCoder** [comment]
I found something else, when it goes down the codepath I don't want, the inertiaFrame function gets called. Line 2595 (approx) in interact.js file (version 1.2.4). When it behaves the right way (no slide-while-release-button), this function never gets called. Knowing this, what's the best way to handle the problem?

**Comment by taye** [comment]
Please describe the issue as concisely as you can. Just the exact behaviour at present and the exact behaviour that you would prefer. No other details.
