### ISSUE TITLE
Tap does not work

### ISSUE THREAD

**Issue by zeeshanjan82** [taye/interact.js#294]
I am trying to implement Tap event and it does not work. I am able to make other events fire. I have created a plunk
http://plnkr.co/edit/lDSlKaAWPDhZwm5Lh8sT?p=preview

**Comment by craigsketchley** [comment]
Hey, check the console. You're getting a `404` for `https://rawgit.com/taye/interact.js/master/interact.js`.

**Comment by zeeshanjan82** [comment]
Thanks I have fixed it
