### ISSUE TITLE
Interactions are not destroyed with unset()

### ISSUE THREAD

**Issue by marian-r** [taye/interact.js#295]
When `unset()` is called while element is being dragged, it does not remove the drag interaction. If the dragged element is then removed from DOM an error is thrown because `dropCheck` is still being performed and both the dragged element and dropzone do not exist.

I may try contribute with a PR for this.

**Comment by taye** [comment]
Do you think that an `[action]end` event should first be fired if an interactable is unset while an action is active on it?

**Comment by taye** [comment]
The new implementation doesn't fire an end event (similar to the PR that you provided).

**Comment by marian-r** [comment]
Thank you for this. I was thinking about your question (about firing `[action]end`) and in theory it is not a bad idea, but it makes things easier, at least for me, if it doesn't fire the event. So, your current solution is fine for me. I hope I will try it shortly.
