### ISSUE TITLE
Drag Offset when autoscroll

### ISSUE THREAD

**Issue by zeeshanjan82** [taye/interact.js#298]
My issue is very similar to this https://github.com/taye/interact.js/issues/38
I have defined a auto scroll container which is a div tag and have set its CSS property overflow-y:scroll
I have defined the autoscroll on the div tag using the following code:
```js
   interact('.drag-drop')
    .draggable({
    inertia: true,
    restrict: {
          restriction: "#test",
          endOnly: true,
          elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
        },
    autoScroll: {
          container: document.getElementById('test'),
          margin: 0,
          distance: 5,
          interval: 10
        },

```
In the above code, 'test' is the id for my auto scroll container. With this setup when I try to drag the 'draggable' object towards the bottom edge of the autoscroll container, I am able to have the scrolling happening on the autoscroll container which is what I need, however I have noticed that the  draggable object stops moving and this results in my mouse pointer/finger to move ahead of the draggable object which results in an offset.
I would think that the issue is coming when the draggable object hits the bottom edge and then it stops moving even though the auto scroll container has scrolled which results in an offset.

**Comment by taye** [comment]
If you want the target to stay in the same position during auto scroll, then either follow the [workaround in #38](https://github.com/taye/interact.js/issues/38#issuecomment-48610674) or set the target element's  CSS `position` to `fixed` on `dragstart` then change it back to what it was before and figure out what the correct offset is at the end of the drag.
