### ISSUE TITLE
Drag Event interrupting the Context Menu

### ISSUE THREAD

**Issue by zeeshanjan82** [taye/interact.js#299]
I have created a fiddle to explain my point: http://jsfiddle.net/zeeshanjan/oqdvhLd5/
In this example we can notice that when we try to right click using the mouse then we are able to see 2 options in the context menu which appears on either of the boxes. However when I try to do the same on a touch device like a tablet, I am able to notice that 'hold' event does not really fire and instead any event which is related to the Context Menu gets interupted by the Drag event and the context menu is not displayed. 
Is there any example of the Context Menu implementation using Interact.js

**Comment by taye** [comment]
Use the [Interactable.preventDefault](http://interactjs.io/api/#Interactable.preventDefault) method:

```javascript
interact(target)
  .preventDefault('never')
  .on('move', function (event) {
    if (event.interaction.interacting()) {
    ;
```

**Comment by zeeshanjan82** [comment]
I have tried the solution but after I tap the red box with 2 fingers I can see the context menu and till here everything seems fine but then the move event does not work if I try moving the red box. Please suggest. I have updated the fiddle here: http://jsfiddle.net/oqdvhLd5/1/

**Comment by taye** [comment]
I think you need to prevent the `contextmenu` event. See https://github.com/taye/interact.js/issues/138#issuecomment-69726016.
