### ISSUE TITLE
Dropzone won't accept draggable element after dropzone moves

### ISSUE THREAD

**Issue by SouthJordanDev** [taye/interact.js#302]
My dropzones have no problem receiving draggable elements when the dropzone's size stays the same as it was at page load. But my dropzones are very dynamic and have to change sizes sometimes due to business rules. So there's a scenario in which a dropzone shrinks down so narrow (height is unchanged) that nothing can be successfully dragged onto it. So in this case I dynamically enlarge the dropzone so it's plenty big to receive a draggable element--yet it still doesn't work. In stepping through the code I can see that `interact(el).on('drop')` never fires, but `interact(el).on('dropdeactivate')` does fire. The firing of 'drop' is essential. Drop always fires on a successful drop (most the time this happens for me), but in the scenario with the very narrow dropzone that I dynamically expand at runtime, 'drop' never fires.

Is there anything I can do to solve this problem?

**Comment by taye** [comment]
http://interactjs.io/docs/faq/#changing-dropzones-while-dragging
