### ISSUE TITLE
pointerMoveTolerance execute failed

### ISSUE THREAD

**Issue by faller** [taye/interact.js#303]
see http://jsfiddle.net/8nn4ctqq/1/

in the code
```
            if (this.pointerIsDown && !this.pointerWasMoved) {
                dx = this.curCoords.client.x - this.startCoords.client.x;
                dy = this.curCoords.client.y - this.startCoords.client.y;

                this.pointerWasMoved = hypot(dx, dy) > pointerMoveTolerance;
            }
```

`this.startCoords.client.x` and `this.startCoords.client.y` always return 0.
I've test in `chrome 46.0.2490.80 m` on win7 and `newest safari` on osx.

**Comment by taye** [comment]
This is fixed in the latest `unstable` version. You can download the built file from https://rawgit.com/taye/interact.js/unstable/dist/interact.js.

**Comment by faller** [comment]
thanks.
