### ISSUE TITLE
touch sometime doesn't work on ipad

### ISSUE THREAD

**Issue by loverdrive** [taye/interact.js#304]
Hi, I'm using interact.js into a webapp, and compile it with cordova, to run it on ipad.
On ipad, sometimes the draggable elements doesn't drag, doesn't move..while on desktop it seems to work all the time! I tryed to link ipad on mac to see console log, and also when draggable don't move, it gives no error in console log.

Have you any idea which could be the cause?

Thank you very much, and for this great library! :)
##

**Comment by taye** [comment]
Can you try the build from the `unstable` branch? https://rawgit.com/taye/interact.js/unstable/dist/interact.js.

**Comment by loverdrive** [comment]
I'm testing unstable, but it return me an error:

i use:
    var rect = document.getElementById('id');
    var pos = {x: rect.offsetLeft + rect.offsetWidth / 2, y: rect.offsetTop + rect.offsetHeight / 2};

In order to get the position of draggable element, but the unstable branch return me:

    TypeError: Cannot read property 'offsetLeft' of null
    Uncaught TypeError: Cannot read property 'pageX' of null (on interact-unstable.js:227)
    Uncaught TypeError: Cannot read property 'options' of undefined (on interact-unstable: 4324)

**Comment by loverdrive** [comment]
Hi, i tested unstable branch, and the problem is the same.
Usually occours when i move more times the draggable element.. So, to "reset" it, i need to close the app and reopen it. Change page and return to the page with drag&drop, without close the app, don't solve the problem

**Comment by taye** [comment]
The new errors should now be fixed.

**Comment by taye** [comment]
@loverdrive can you confirm if this is issue if fixed?

**Comment by loverdrive** [comment]
i'll test in these days

**Comment by loverdrive** [comment]
@taye, i tryed it and now in browser-desktop it works.
In these days i'll try to test also on tablet

**Comment by loverdrive** [comment]
Hi @taye, i've test dev version on ipad, and doesn't work...

**Comment by taye** [comment]
Can you check if you can reproduce the bug on a regular web page in Chrome or Safari?

**Comment by loverdrive** [comment]
i tryed some minutes on Safari from ipad, and it seems work correctly.

**Comment by loverdrive** [comment]
Update: sometimes the problem occurs also in Safari (on ipad).

**Comment by datom** [comment]
Hi,
i have also the same problem. I tried something out and i think i know where it comes from.
This only appears if the system think i want to do scrolling instead of dragging an element. Every time the  dragging was not working, i was able to scroll the page.

@loverdrive can you confirm my behavior?

**Comment by loverdrive** [comment]
@datom the problem occurs also when i try to drag horizzontally, where there is no scroll.

**Comment by abelricaurte** [comment]
Same problem here:
Links inside a 'rezisable' element, are not 'clickable' on touchscreen.
Tested in Chrome on Ipad.

**Comment by cheungkonghou** [comment]
Occasionally on Chrome, the tap event doesn't work at all. However if open the developer console and emulate as mobile touch screen, it works. The problem doesn't go away even reloaded the page.
Windows 7 Chrome 47

**Comment by cheungkonghou** [comment]
Moreover, the tap event is fired twice on version 1.2.6. However there's no such problem on version 1.2.4.

**Comment by taye** [comment]
@loverdrive, @datom Could you make a small demo for this issue?

@abelricaurte you're describing a different issue. See https://github.com/taye/interact.js/issues/58.

@cheungkonghou This issue is about problems on iPad. If you can reproduce the problem that you're having on the latest `unstable` branch (https://rawgit.com/taye/interact.js/unstable/dist/interact.js), please open a new issue about it.

**Comment by cheungkonghou** [comment]
I cannot reproduce the issue every time but it seems it's related to the detection of touch in Chrome (https://code.google.com/p/chromium/issues/detail?id=467934)

**Comment by taye** [comment]
@cheungkonghou try using the [latest unstable build](https://rawgit.com/taye/interact.js/unstable/dist/interact.js). If you're still having problems then open a [new Github issue](https://github.com/taye/interact.js/issues/new) for that problem.

**Comment by kardanov** [comment]
@cheungkonghou this info could be helpful:
http://stackoverflow.com/questions/33033089/interact-js-1-2-4-drag-and-gesture-action-confusion#
at least it solved same problem for me.

**Comment by taye** [comment]
@loverdrive Please try the unstable build again. I've made a change which might have solved this problem. If the problem persists, please make a demo that I can try when I get a chance with an iOS device.

**Comment by phamvansy** [comment]
try
interact(".className").on('down', function (event) {
...
 })

**Comment by gabriel-dehan** [comment]
Hello ! I am having the issue (currently testing in the Simulator on mac OS X, simulating an iPad 2). My drag events are not working in Safari. The only way to have them work so far has been "double tapping then drag". If I do just that it seems to work but it's pretty counter-intuitive. I have tried to use the unstable branch but there is an error about iterator3 or something. Also the SO answer did not work with the "down" handler did not work for me.

Any news on this ?

**Comment by nurevaSaeed** [comment]
Hi,

I'm having a similar issue. I'm using version 1.2.6. It happens on iPad-Safari more often. I register my "draggable" container for "onstart" but  sometimes (and randomly) it stops firing the event. Unfortunately I can't find a bunch of steps to reproduce it consistently. 
For some other operation in the code I have touch event listener on $window that enables/disables the "onstart" listener:

 interact('.myContainer').draggable({enabled: false});
...
 interact('.myContainer').draggable({enabled: true});

it doesn't force interact to fire "onstart" event either.

I appreciate any suggestions.

Cheers.

**Comment by taye** [comment]
This issue should now be reseolved by 9417152. You'll have to use the unstable branch (which is much less buggy than the current stable branch) to benefit from this fix. Thanks to everyone who provided info and sorry for taking so long to finally fix this.
