### ISSUE TITLE
gesture angle and da return bad values for large gestures

### ISSUE THREAD

**Issue by hauptmech** [taye/interact.js#305]
The gesture angle and da values are wrong as the gesture becomes large.

**Comment by hauptmech** [comment]
No notes attached to function touchAngle so it's hard to tell what the thinking was. Here's my notes:

```
dx = touches[0][sourceX] - touches[1][sourceX], 
```
It's more intuitive that the first finger down is the anchor, so it should be ```touches[1]-touches[0]```.
```
angle = 180 * Math.atan(dy /dx) / Math.PI;
```
It's always a bad idea to do calculations using degrees. Since trig functions are all radians it just invites errors.
atan->atan2 (this is the main cause of the bad values)
```
if (drClamped > 315) {
                angle -= 360 + (angle / 360)|0 * 360;
            }
            else if (drClamped > 135) {
                angle -= 180 + (angle / 360)|0 * 360;
            }
            else if (drClamped < -315) {
                angle += 360 + (angle / 360)|0 * 360;
            }
            else if (drClamped < -135) {
                angle += 180 + (angle / 360)|0 * 360;
```
Not needed with atan2. (Not sure it 'worked' in the first place.)

**Comment by taye** [comment]
>It's more intuitive that the first finger down is the anchor, so it should be ```touches[1]-touches[0]```.

That makes sense.

>Not needed with atan2. (Not sure it 'worked' in the first place.)

The values from `atan2` will be between -π and π so even with `atan2`, the angle values would not be continues.

I've been aware of these issues for a long time but I've felt that they're of a very low priority. I doubt that I'll be implementing a better fix for the angle wrapping soon. I'd be happy to accept a good pull request though.

**Comment by hauptmech** [comment]
Discontinuity is not the problem as trig functions work correctly with inputs outside of -PI to PI.  atan is just not the right function for this calculation. 

By fixing this I was able to use event.da and event.scale values directly for 2 finger scaling and rotating shapes in svg.

**Comment by taye** [comment]
>The gesture angle and da values are wrong as the gesture becomes large.

I misunderstood that to mean the *angle* getting large. I see the problem now.
