### ISSUE TITLE
Reassert Snap and Restrict constraints on tap?

### ISSUE THREAD

**Issue by craigsketchley** [taye/interact.js#306]
Hi,

Great library!

What's the best way to reassert the snap and restrict constraints on tap?

Basically, my interactive element is being swapped out for another when a user taps on it. This new element might have different dimensions but should have the same translation and resize scale. Whilst it's fairly easy to ensure the new element has the same translation and scale, I'm having trouble ensuring the new element adheres to the snap and restrict constraints. I'm thinking about firing some drag interaction event manually (to trick `interact.js` into asserting the constraints) but I'm struggling to figure out the best approach for this.

Let me know if that's not clear and I'll try my best to clarify. Any advice would be greatly appreciated, cheers.

**Comment by taye** [comment]
Starting actions without a pointer being held down is not supported. You'll have to find another way to fix the position of the new element.
