### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by andrewgleave** [taye/interact.js#31]
Just tried to integrate interact with a simple React component and although interact is initialised correctly and is receiving events, nothing is happening. I suspect the issue could be down to React's synthetic events system (http://facebook.github.io/react/docs/events.html) which which may be causing issues for interact.

I've created a Fiddle to illustrate the issue.
http://jsfiddle.net/G79D9/

This is a great library and I'd love to use it so I hope there's an easy fix ;)

**Comment by oisee** [comment]
taye, i've found that your fiddle doesn't work at all =(

**Comment by jai1331** [comment]
It's a great library and would like to implement on this in simple react component ! How do I do that ?

`
const Comp = (props) => {
 
   useEffect(() => {
       interact('.divCont')
        .resizable({
          edges: { left: true, right: true },
  
          modifiers: [
            // keep the edges inside the parent
            interact.modifiers.restrictEdges({
              outer: 'parent'
            }),
  
            // minimum size
            interact.modifiers.restrictSize({
              min: { width: 100, height: 50 }
            })
          ],
  
          inertia: true
        })
        .on('resizemove', function (event) {
            //clearTimeout(timerResize);
            var target = event.target;
            var x = (parseFloat(target.getAttribute('data-x')) || 0)
            var y = (parseFloat(target.getAttribute('data-y')) || 0)
    
            // update the element's style
            target.style.width = event.rect.width + 'px'
            target.style.height = event.rect.height + 'px'
    
            // translate when resizing from top or left edges
            x += event.deltaRect.left
            y += event.deltaRect.top
    
            target.style.webkitTransform = target.style.transform =
                'translate(' + x + 'px,' + y + 'px)'
    
            target.setAttribute('data-x', x)
            target.setAttribute('data-y', y)
            //target.textContent = Math.round(event.rect.width) + '\u00D7' + 
          Math.round(event.rect.height);
        })
        .on('resizeend', function (event) {
            const target = event.target;
            passDataToParent(target.style.width, target.style.height, target.style.transform, x, y, props.field.id) //here i will pass resize width, height to parent to set in state and interact js having the instance of last field only (props.field)
         })
}
`

Any idea on how to use interact js in react really helpful.

**Comment by pgonzalez-santiago** [comment]
@jai1331 how did you solve it?

Any ideas of how to use it with hooks?

**Comment by ubershmekel** [comment]
I've made a fiddle that does work:

http://jsfiddle.net/ubershmekel/sh7fqt0w/1/
