### ISSUE TITLE
Cleaning up

### ISSUE THREAD

**Issue by jeffijoe** [taye/interact.js#316]
In stuff like Backbone, when a view is destroyed, all third party plugins should be destroyed with it.

I've searched the source for "destroy", and didn't find anything, so I'm assuming it's not possible yet?

**Comment by taye** [comment]
There's an Interactable.unset() method for that
http://interactjs.io/api/#Interactable.unset
Il 18/nov/2015 10:25 PM, "Jeff Hansen" <notifications@github.com> ha
scritto:

**Comment by jeffijoe** [comment]
Awesome, thanks!
