### ISSUE TITLE
Thx !

### ISSUE THREAD

**Issue by lionelB** [taye/interact.js#318]
Hello,
Just wanna says a big thanks for you work on interact.

Lionel

**Comment by taye** [comment]
You're welcome!

**Comment by lionelB** [comment]
What's the prefered way to proceed if I have any question ? Stackoverflow? gH issue ?

**Comment by taye** [comment]
Github issues is meant for bugs. [Gitter](https://gitter.im/taye/interact.js) or Stackoverflow are better. I don't always have time to answer general questions.

**Comment by lionelB** [comment]
Great, didn't know there is a gitter.

> I don't always have time to answer general questions.

I fully understand that. Thx to take time to drive this project.
