### ISSUE TITLE
Snap to original position issue when inside a scrollable container

### ISSUE THREAD

**Issue by leonardolessa** [taye/interact.js#319]
Hi,
I'm sorry, the title is just a lucky guess, take a look:
http://jsfiddle.net/8yf4vssg/1/

Snapping doesn't work because somehow the difference of the scroll change the snap reference, probably some offset issue or something like that.

PS: Ignore the event bubbling of the scroll drag, I've solved in my project and the snap issues keeps the same.

**Comment by taye** [comment]
iscroll changes the `transform` style of the parent element and that messes things up for interact.js. That transformed value is the offset that you would need to consider when setting the snap point.
