### ISSUE TITLE
Resize Handle cursors not showing properly on rotated element

### ISSUE THREAD

**Issue by lionelB** [taye/interact.js#321]
Hello,

I currently use interact to handle user interactio (drag, rotate, resize and gesture) on a simple svg editor
It seems that cursors not showing on rotate element (I've made a gist to illustrate the problem)

https://jsbin.com/felare/edit?html,js,output

A workaround I've in mind is to add small square around the shape  that will trigger the resize (using a manual start) 
Could this be working or I miss the manual start thing ?

thanks for your help,

Lionel

**Comment by taye** [comment]
`manualStart` is probably the best way to do it. You could also use a custom [actionChecker](http://interactjs.io/api/#Interactable.actionChecker).
