### ISSUE TITLE
Drag a copy of the element

### ISSUE THREAD

**Issue by Govardhandamam** [taye/interact.js#322]
Hey, I would like to drag and drop the copy of the element on to the droppable container. Can anyone let me know how i can achieve this
Thanks.

**Comment by taye** [comment]
http://interactjs.io/docs/faq/#clone-target-draggable

**Comment by jordanboston** [comment]
This is great, I could not find this info earlier. That said, when doing this like the example it gives a 
`[interact.js] There are no listeners set for this action drag ` error.

Any thoughts on that?

**Comment by jordanboston** [comment]
@taye nevermind, got it worked out.  Thanks for all your work on this project!! 

```
    interact('.item').draggable({ manualStart: true, onmove: this.dragMoveListener })
      .on('move', (event)  => {
        const interaction = event.interaction;
        const dropZone = event.target;

        // if the pointer was moved while being held down
        // and an interaction hasn't started yet
        if (interaction.pointerIsDown && !interaction.interacting()) {
          // create a clone of the currentTarget element
          const clone = event.currentTarget.cloneNode(true);

          // insert the clone to the page
          dropZone.appendChild(clone);

          // start a drag interaction targeting the clone
          interaction.start({ name: 'drag' },
            event.interactable,
            clone);
        }
    });
```

I'm getting issues when duplicating a second time, but it's a start at least.  Too many duplicates after that every time.
