### ISSUE TITLE
Crashes if dragging is stopped

### ISSUE THREAD

**Issue by cheungkonghou** [taye/interact.js#323]
If user is dragging an element and the action is stopped by some reason (in my case, an overlay is shown programmatically to cover the whole screen), exception is thrown when user release the mouse button, and it keeps throwing exceptions afterwards.

**Comment by taye** [comment]
Please provide a minimal demo.

**Comment by taye** [comment]
A stack trace of the first error as well as your browser and interact.js version would also be useful.

**Comment by cheungkonghou** [comment]
interact-1.2.6.js line 4119: I enclosed the the function in a try catch so as to return false if exception thrown due to no dragRect is returned when element displaced or removed (line 4147).

**Comment by andrejpavlovic** [comment]
Yeah I get the same error. If I start dragging the element, and that element gets removed from DOM and unset before I drop it, the error "Uncaught TypeError: Cannot read property 'right' of undefined" keeps on getting triggered on mouse move. Interact doesn't clean up properly after itself if the element is in the middle of being dragged.

**Comment by andrejpavlovic** [comment]
Here is an example:
https://jsfiddle.net/9vjnd3xt/3/

// INSTRUCTIONS:
// 1. Open console log
// 2. Start dragging red box and don't let go
// 3. In a short amount of time all dom elements will be removed, don't let go of the mouse button and keep on dragging!
// 4. console log will show "Cannot read property 'right' of undefined" errors

Basically interact elements are unset() and removed from DOM just a bit after dragging starts. Check console for errors.

**Comment by taye** [comment]
@andrejpavlovic This is fixed in the latest unstable build: https://rawgit.com/taye/interact.js/unstable/dist/interact.js.

@cheungkonghou you should call `event.interaction.stop()` to stop the drag/resize/gesture before the overlay is shown.

**Comment by bummzack** [comment]
I have the same issue as @andrejpavlovic. Is this fixed in a stable release? What version should I use?
