### ISSUE TITLE
resize specific axis per resizable edge

### ISSUE THREAD

**Issue by sixinli** [taye/interact.js#324]
Hi,

I am playing around with the resize options a bit (@v1.2.6) and it seems like in order to turn on resizing for the left and top resizing I would need to use the `edges` option. However, there's no way to turn off resizing for a specific axis per resizable edge. For example, it would be great to say only resize on the x-axis if the left/right edge is being dragged. 

I am wondering if this could be supported, or if this is already being supported and I am just missing some config.

P.S. I am able to override the `axis` property in `actionChecker`, but it would be nice if it's actually configurable

Thanks,
Sixin

**Comment by taye** [comment]
Do you mean to allow resizing up/down from the left/right edges?

**Comment by sixinli** [comment]
By default, without the "edges" option, it's resizable along the right edge (horizontally only) and bottom edge (vertically only).

Turning on the "edges" option makes the it all edges resizable horizontally and vertically. It would be if there's a way to configure it such that it's resizable along the left&right edges (horizontally only) and top&bottom (vertically only). Maybe a "direction" option in "edges"?

**Comment by taye** [comment]
If you use the `edges` API, resize events have a `rect` property which has the resized dimensions of the target element. Look at the [resizing example](http://interactjs.io/#resizing) on the homepage.

```javascript
    target.style.width  = event.rect.width + 'px';
    target.style.height = event.rect.height + 'px';
```

**Comment by sixinli** [comment]
cool, thanks for pointing this out! It would be great if it's configurable, but this works too :)

**Comment by taye** [comment]
There's also an `event.deltaRect` property. So instead of `event.dx/dy` you can use `event.deltaRect.right/bottom`.
