### ISSUE TITLE
Snapping back to original position regardless of whether a Draggable is dropped inside of a drop zone or not?

### ISSUE THREAD

**Issue by mseymour** [taye/interact.js#325]
I have been trying to figure out how to properly do this for the past day. What I'm trying to do is when I click and drag an element, regardless of whether I drop it in a drop zone or not, it returns to its original position. (Or a "ghost"/outline/clone of the element, which may be more useful in this case.)

I've looked at solutions already in issues about snapping them to dropzones, but when I try to alter them to suit my needs, the dragged element flings itself to the upper-left-hand corner (probably because of setting `startPos` to either 0,0 or whatever the original coordinates are in `onstart`.)

**Comment by mseymour** [comment]
I managed to get the snapping back to position working using `onend`, however now the drop event no longer fires.

```javascript
var startPos = {x: 0, y: 0};

interact('.card')
    .draggable({
        onmove: dragMoveListener,
        onstart: dragStartListener,
        onend: dragEndListener,
        inertia: true,
        snap: {
            targets: [startPos],
            range: Infinity,
            relativePoints: [ { x: 0.5, y: 0.5 } ],
            endOnly: true
        }
    });

function dragMoveListener (event) {
    var target = event.target,
        // keep the dragged position in the data-x/data-y attributes
        x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
        y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

    // translate the element
    target.style.webkitTransform =
    target.style.transform =
      'translate(' + x + 'px, ' + y + 'px)';

    // update the posiion attributes
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
}

function dragStartListener (event) {
    var rect = interact.getElementRect(event.target);

    // record center point when starting a drag
    startPos.x = rect.left + rect.width  / 2;
    startPos.y = rect.top  + rect.height / 2;

    // snap to the start position
    event.interactable.draggable( { snap: { anchors: [startPos] } } );
}

function dragEndListener (event) {
    // snap back to the start position
    event.interactable.draggable( { snap: { anchors: [startPos] } } );
}
```

**Comment by mseymour** [comment]
Regarding above, I found that if I had `.card` elements in the dropzones, the `ondrop` event for the dropzone would fire. Since then I restricted it to the other container with the cards listed in it.

In that case, shouldn't I be able to set the `snap` coordinates on `.card` during the `ondropdeactivate` event for the dropzones? Or is there another way to have it snap back to the original position *while* still triggering `ondrop`?

**Comment by taye** [comment]
@mseymour There's a new `interaction.doMove` method that you can use to try to force a move after changing snap/restrct

```javascript
interact(target)
  .draggable(true)
  .on('dragmove', function (event) {
    if (someCondition) {
      // change the snap settings
      event.interactable.draggable({ snap: { targets: [] }});
      // try to fire another move event with re-calculated snap
      event.interaction.doMove();
    }
  });
```

You can use it if you link to the [unstable build](https://rawgit.com/taye/interact.js/unstable/dist/interact.js) which should be released soon.
