### ISSUE TITLE
Latest version of interact js breaks resize

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [taye/interact.js#326]
I have a demo here http://nicheacademyspa.vteamslabs.com/widget.php. Please lick on open button and you will see a resize button. The resize button does not work because of a console error : "pointers is undefined". It causes this error on 1.2.6 but not on 1.2.5.

**Comment by taye** [comment]
Using the latest `unstable` build solves this. https://rawgit.com/taye/interact.js/unstable/dist/interact.js
