### ISSUE TITLE
Unable to run tests: SyntaxError

### ISSUE THREAD

**Issue by jimf** [taye/interact.js#329]
Getting this when trying to run `gulp build karma`:

![image](https://cloud.githubusercontent.com/assets/413269/11932538/31eca55c-a7c4-11e5-9b25-fc30a67e021f.png)

Anything I'm missing / doing wrong?

**Comment by taye** [comment]
There's no proper test suite to run. The tests that exist in the `tests/` directory are years old and were never comprehensive.

**Comment by jimf** [comment]
Some tests are better than none, and this doesn't seem like its terribly far off from being runnable. Having no tests really sucks, especially for contribution.

**Comment by taye** [comment]
Yes it sucks but It'd be faster and better to start from scratch than to try to fix what's currently in `test/test.js` and I don't have the time or will to write tests right now. Smoke tests are working well enough until proper tests eventually happen.
