### ISSUE TITLE
actionChecker can't set preserveAspectratio

### ISSUE THREAD

**Issue by geohuz** [taye/interact.js#330]
In a group of html elements I need to set one whose aspect ratio  must be preserved, I use the following code:

```
.actionChecker(function (pointer, event, action, interactable, element, interaction) {
      if (interact.matchesSelector(event.target, '.aspect')) {
          // resize from the top and right edges
          action.name  = 'resize';
          action.preserveAspectRatio = true;
      }

      return action;
   })
```

But it doesn't work. The code from the API documentation does work though. (set the resize edges)

**Comment by taye** [comment]
`preserveAspectRatio` is gotten from the options set with the `resizable(options)` method. If you need to change the setting dynamically in the actionChecker you can enable or disable it with this:

```javascript
interactable.resizable({ preserveAspectRatio: bool });
```
