### ISSUE TITLE
Is it possible to slow down the resize dragging speed?

### ISSUE THREAD

**Issue by geohuz** [taye/interact.js#332]
I'm programming an interface which allows user to operate in a relative small area of screen, with group of resizable elements, some times I just feel the resize dragging speed is too fast as I've changed the snap to resize to every 20px increase/decrease, it feels like the change in size is too fast to capture, I would like to "slow down" the move so it will be easy to operate on. Does anybody have idea on this? 

Thanks!

**Comment by taye** [comment]
There's nothing built in for that. You could scale down the values that you use from the resize events or if you're using a grid or function for snapping targets, modify them so that the returned change in coordinates are smaller.

**Comment by geohuz** [comment]
Allright, thanks a lot!
