### ISSUE TITLE
issue about resizable width scrollbar

### ISSUE THREAD

**Issue by faller** [taye/interact.js#334]
When the element has a scrollbar, resizable can't work.
see http://jsfiddle.net/dowofk4a/

How can I achieve that? Thank for answering.

**Comment by taye** [comment]
I think you would have to 
 - disable scrolling with CSS `overflow: hidden` or something similar,
 - add a border to the right of the scrolling element
 - or use some sort of handle and [manualStart](http://interactjs.io/docs/#manualstart) for resizing
