### ISSUE TITLE
How to disable dropzone manually?

### ISSUE THREAD

**Issue by zhangyaqi1990** [taye/interact.js#335]
Does dropzone has a disable method to disable interactjs temporarily. For example, when I click a button I can drop something to the drop zone, and I click the button again, the drop zone doesn't allow a drop event.

**Comment by peterhodges** [comment]
Seen the checker callback that you can provide as a droppable option? (See deprecated notice here: http://interactjs.io/api/#Interactable.dropChecker)

Just return false if you don't wish to allow drops for whatever reason.

**Comment by taye** [comment]
You could also 

 - `interact(target).dropzone(false)` then call it again and pass `true` or 
 - use a target selector like `".dropzone:not([disabled])"` and add/remove the `disabled` attributes to dropzone elements to disable/enable them
