### ISSUE TITLE
Using draggable TypeError: interaction.prevEvent is null

### ISSUE THREAD

**Issue by cia05rf** [taye/interact.js#336]
Hi everyone. I've just started using interact.js and it is a great piece of script.

However i am having an issue that i can't see on any forums anywhere and wanted to see if i am the only one and if there is a solution to this.

When i use the below code i get the error "TypeError: interaction.prevEvent is null ......... on line 3463 of interact.js". I've looked into it and it's talking about inertia. The thing is the inertia parts all work fine when the "onstart" listener is not called.

Has anyone had this issue and/or knows how to solve it?

interact(".draggable").draggable({
				// enable inertial throwing
				inertia: true,
				// keep the element within the area of it"s parent
				lockAxis:"x",
				// enable autoScroll
				autoScroll: true,
				// call this function on every dragend event
				onstart: dragStartListener,
				// call this function on every dragmove event
				onmove: dragMoveListener,
				// call this function on every dragend event
				onend: dragEndListener
			});

**Comment by taye** [comment]
Can you provide the code of your `dragStartListener`?

Try updating to the latest [unstable version](https://rawgit.com/taye/interact.js/unstable/dist/interact.js).
