### ISSUE TITLE
Droppable uses order of elements in DOM and ignores zIndex

### ISSUE THREAD

**Issue by peterhodges** [taye/interact.js#337]
Draggable/Droppable relies on the order of elements in the DOM to determine which element should receive the drop.

```
 // get the most appropriate dropzone based on DOM depth and order
  const dropIndex = utils.indexOfDeepestElement(validDrops);
```

The indexOfDeepestElement method ignores z-index completely.

I know stacking contexts are hard to calculate but some basic awareness of z-index would be really useful. Even something in the documentation to mention this limitation would be great.
##

**Comment by taye** [comment]
Thanks for the feedback. I think comparing `style.zIndex` of elements for the deepest "family" of dropzone siblings would be fairly simple and should cover most use cases. That's the most I'm prepared to do at the moment anyway.

**Comment by emilkarl** [comment]
:+1:
