### ISSUE TITLE
Combination with Pointer Event polyfill?

### ISSUE THREAD

**Issue by peteruithoven** [taye/interact.js#338]
Could I use this in combination with a Pointer Event polyfill, like [jquery/PEP](https://github.com/jquery/PEP)? 
I'm asking because I see you're attempting to use Pointer Events: 
https://github.com/taye/interact.js/blob/master/src/Interaction.js#L501

**Comment by taye** [comment]
As long as you include the JavaScript for PEP before interact.js, there shouldn't be any trouble.
