### ISSUE TITLE
Scroll does not stop / limit itself to the scroll container content height

### ISSUE THREAD

**Issue by heymath** [taye/interact.js#340]
*I am having a problem and I don't know if it is the normal behavior or not ... I don't understand if the library provide a simple way to "fix it" or if I have to manage it myself.*

**I got a scrollable container for thumbnails, while I am dragging down a thumbnail to scroll to the end of my thumbnails to reorder them it scrolls to infinity :disappointed: 
Is there a way to avoid the AutoScroll to scroll farther than its content height & width?
Should it be the default behavior?**

Before scroll:
![before-scroll](https://cloud.githubusercontent.com/assets/1656697/12173891/c4180f78-b559-11e5-9b00-880d967c52ee.png)

Scroll a bit too far:
![scroll-bit-too-far](https://cloud.githubusercontent.com/assets/1656697/12173856/8545e6e4-b559-11e5-8035-5bf4b06c4c4d.png)

Scroll way too far:
![scroll-way-too-far](https://cloud.githubusercontent.com/assets/1656697/12173863/892db5e8-b559-11e5-806a-aa0184c97861.png)

PS: @taye Thanks for this very good library :smiley:

**Comment by heymath** [comment]
Never mind, I used position fixed instead of absolute then it no longer scroll to infinity.

**Comment by taye** [comment]
An suitable draggable restriction might also have helped but could be more complicated.
