### ISSUE TITLE
Plans for 1.3.0

### ISSUE THREAD

**Issue by marian-r** [taye/interact.js#341]
@taye is there anything more planned for 1.3.0 release or is it only about fixing bugs now?

I should be able to test the `master` version in production over the weekend, as I promised [long time ago](https://github.com/taye/interact.js/issues/251#issuecomment-154241222). If there will be no major issues, I will include it in my application. It has logging of client-side application errors in place, so I will be able to gather potential runtime errors in Interact.js. I will let you know.
##

**Comment by taye** [comment]
I'm mostly trying to fix bugs and am also reorganizing a few very small things in the code. There are no more significant or noticeable changes planned for this version.

Thanks for your help.

**Comment by marian-r** [comment]
First issue #344.

**Comment by marian-r** [comment]
For my usage, it seems like everything is working now when using the `unstable` branch. So, feel free to release 1.3.0 (if that is the next planned version).

**Comment by marian-r** [comment]
I should say that I use only drag & drop, specifically `dragstart`, `dragmove` & `dragend` for draggable and `ondragenter` & `ondragleave` for dropzone. Nothing really special, no restrictions or interia.

**Comment by mhelvens** [comment]
Will resize restrict and snap be fixed in the next version?

**Comment by taye** [comment]
@mhelvens most likely not.

**Comment by zbjornson** [comment]
#397 is also a new bug in 1.3.0/master. Looking forward to that release...

**Comment by taye** [comment]
I'm currently working on #455 which I hope to get done in the next couple of weeks. I plan on writing new tests, fixing the iPad issue #251 **if** I can get a Mac and iThing to debug with, and updating the docs. I'll also try to fix any little bugs that might pop up.

**Comment by taye** [comment]
@mhelvens yes, resize restrict and snap will likely be fixed by #455.
