### ISSUE TITLE
Could add a config to limit the size of drop zone items?

### ISSUE THREAD

**Issue by zdnet** [taye/interact.js#342]
it's not a bug but just a enhancement request, for example add "dragItemSize: 1" to limit the drop zone time count.
thanks!

 .dropzone({
                accept: accept,
                dragItemSize: 1,
                ondropactivate: function (event) {
                    addClass(event.relatedTarget, '-drop-possible');
                },
                ondropdeactivate: function (event) {
                    removeClass(event.relatedTarget, '-drop-possible');
                }
            })

**Comment by taye** [comment]
I don't think it's a good idea. Keeping track of all the drops that happen would be too much hassle since interact.js doesn't really know what your application is doing with the interaction information.
