### ISSUE TITLE
dragend is fired before dropend (BC break from 1.2.6?)

### ISSUE THREAD

**Issue by marian-r** [taye/interact.js#344]
I was testing the version from `unstable` branch and I found a breaking behaviour that the `dragend` is fire before the `dropend`. So now I'm not able to access the drop target in the `dragend` handler.

Example (working fine in 1.2.6):
```js
var dropTarget = null;
interact('.my-draggables').draggable({}).on({
  dragstart: (e) => { ... },
  dragmove: (e) => { ... },
  dragend: (e) => {
    console.log(dropTarget); // null
  }
});
interact('.my-dropzones').dropzone({
  ondrop: (event) => {
    dropTarget = event.target;
  }
});
```

**Comment by taye** [comment]
From the organisation of the code, I think it's better to keep it this way. I'll add a note about the issue to the changelog.

I can set the dropzone element as the `relatedTarget` property of `dragend` events so that you could do:

```javascript
  dragend: (e) => {
    console.log(e.dragEvent.relatedTarget); // undefined if there's no drop
  }
```

**Comment by taye** [comment]
That's done and I've updated the `unstable` branch.

**Comment by marian-r** [comment]
Thanks, it works :)
Just a slight difference that it is accessed via `e.relatedTarget` not `e.dragEvent.relatedTarget`. And could you please state it in the changelog?
