### ISSUE TITLE
Uncaught TypeError: e.getClientRects is not a function : domUtils.js:208

### ISSUE THREAD

**Issue by frankieloscavio** [taye/interact.js#345]
We are using the latest "interact": "https://github.com/taye/interact.js.git#unstable"

The issue we have is with the dropzone in which we get an error stating that "Uncaught TypeError: e.getClientRects is not a function : domUtils.js:208". 

_Initial loop on draggable objects:_

$.each(me.draggableOptions.data(), function(idxOption, droppable) {
                            var element = $('[data-uid="' + droppable.uid + '"]').find('.js-droppable');

_Our Drop Zone declared causing the issue with element passed in:_

interact = interact || window.exports.interact;
                                console.log(element);
                                interact(element).dropzone({
                                    accept: '.js-draggable',
                                    overlap: 0.1,
                                    ondragenter: onDragEnter,
                                    ondragleave: onDragLeave,
                                    ondrop: onDrop
                                });

_Stack Trace:_

Uncaught TypeError: e.getClientRects is not a function
                               a.getElementClientRect @ domUtils.js:208
                               a.getElementRect @ domUtils.js:221
                               e.getRect @ Interactable.js:126
                               f.dropCheck @ drop.js:360
                               s @ drop.js:164
                               (anonymous function) @ drop.js:47
                               e.fire @ Signals.js:35
                               e @ InteractEvent.js:92
                               (anonymous function) @ drag.js:74
                               e.fire @ Signals.js:35
                               e.doMove @ Interaction.js:252
                               e.pointerMove @ Interaction.js:212
                               (anonymous function) @ Interaction.js:420

![e getclientrects_00](https://cloud.githubusercontent.com/assets/2328121/12557824/9edf59dc-c35a-11e5-8eda-765a7acfbf15.png)

![e getclientrects_01](https://cloud.githubusercontent.com/assets/2328121/12557616/bf0140a0-c359-11e5-9a67-7c2f66588c15.png)
##

**Comment by frankieloscavio** [comment]
> activity

**Comment by taye** [comment]
Have you sorted this out?

**Comment by taye** [comment]
Should be fixed with commit bb503b5.
