### ISSUE TITLE
Events not firing correctly in Firefox v43

### ISSUE THREAD

**Issue by mwdchang** [taye/interact.js#347]
The bare-bone jsfiddle below uses a single div to capture events, printing out the down/up/tap pointer events to the console.

https://jsfiddle.net/0swx5rbp/3/ 

I have a Dell touchscreen, if I touch the div, I am expecting it to print out "down" but nothing happens. 
When I lift my finger however, both the *down* and *up* callbacks fire.

I get the expected behaviour in both Chrome and IE, so I am am unsure if this is a true bug or there are some custom settings in Firefox that need to be tweaked.

Thanks in advance, Daniel

**Comment by taye** [comment]
This is likely a problem with Firefox and not interact.js. Try adding normal `mouseup`, `mousedown` and `mousemove` event listeners to a blank document and see how those are fired.

**Comment by DreamLi1314** [comment]
I also encountered the problem that mousedown can not trigger in Firefox and IE. How did you solve this problem?
