### ISSUE TITLE
dinamically change snap grid

### ISSUE THREAD

**Issue by dearrbear** [taye/interact.js#349]
Hi, folks ! I have a question. Can i dinamically change snap grid (that i created with targets: [interact.createSnapGrid]) when I resize my browser ? (I mean, can I reinitializate the targets property?)

Thanks in advance.

**Comment by Paulie90** [comment]
I've found an workaround if anyone needs: 

```
**this.options.drag.snap.targets **= [
                        interact.createSnapGrid({
                            x : 10 / vBoxZoom,
                            y : 10 / vBoxZoom
                        })
                    ];
```

**Comment by EnKrypt** [comment]
Thanks @Paulie90 

For a project with poor documentation and outdated Typescript definitions, this one helped me out a lot.
