### ISSUE TITLE
Is on('scroll') in the latest release

### ISSUE THREAD

**Issue by scottfwalter** [taye/interact.js#352]
Hi,

I'm trying to get the on('scroll') to fire but nothing is happening.

 ```
 interact(myEl)
                .draggable({
                    onstart: dragStartListener,
                    onmove: dragOrMoveListener,
                    onend: dragEndListener,
                    autoScroll: {
                        container: $('.mycontainer')[0]
                    },
                    scroll: function() {
                        console.log('itScrolled');
                    }
                }).on('scroll', function() {
                console.log('here i am');
               })
```

It is autoscrolling properly just not notifying my scroll handler.  Any thoughts?

**Comment by sly7-7** [comment]
I just begin with interact, but from what I tried, the `on('scroll')` is working, but you should define it on the element which is scrolled, ie the container, in your case `$('.mycontainer')[0]`

**Comment by taye** [comment]
interact.js currently doesn't fire `scroll` events when auto scroll happens.
