### ISSUE TITLE
Training or How To for interact? - specifically draggable

### ISSUE THREAD

**Issue by schwook72** [taye/interact.js#354]
Hiya, Im relatively new to coding and want to use the SVG point handle functionality for something I am building.  I have it working for a single svg shape just by editing the demo code. However Im really not sure what it is I am doing and what it is I am reading with the javascript so I cant work out how to make the Point Handles and draggable code work for another polygon that is within the same svg. 

What I am trying to achieve is a number of shapes that have movable point handles, that are layered on top of each other. 

Is there some sort of training or 'How To' you could point me to that explains what the javascript is doing so I can understand and write something that does what I want?  

At the moment I have code that creates a new polygon on a button click, and the star.js will recognise that and place the point handles. However I cannot then get the code to recognise a second new polygon.

I have done a number of basic javascript training courses online however I dont know of any that teach me advanced concepts that would cover this sort of scripting. I am willing to learn, I just dont know where to start. Any pointers on this would also be gratefully received.

**Comment by Joeao** [comment]
Welcome to the crazy world of coding! Github issues are meant primarily to further develop the project, whereas if you ask around at StackOverflow or [Gitter](https://gitter.im/taye/interact.js), you'll get enthusiastic people happy to give detailed information on how to use the project. Many people do come to Github to ask questions, and whether or not it's accepted is generally up to the developers of the project. But asking elsewhere will likely give you a much more in-depth answer and will help you improve your development skills.

I've not used the SVG side of InteractJS, but just some general basics: You're going to want to make sure that each element you create has an ID, Class or something else to help you reference that exact element, then bind that element to interactJS. A basic way of doing this would be to add the class 'polygon' to each element that you want to bind, then use `interact('.polygon')`.

So yeah, I'd take this issue to StackOverflow or Gitter, and you'll be rolling in no time. It's good to hack up examples first until it becomes your own, so the way you're doing it is good. One tip would be try attempt what you're trying to achieve then post snippets of your code (cutting out irrelevant bits) and people should be able to push you in the right direction without holding your hand. The benefit being it'll improve your learning experience.

**Comment by schwook72** [comment]
Thank you. I have thrown it up on StackOverflow to see if anyone can help me.  And I will keep banging on myself...
