### ISSUE TITLE
svg star with draggable - suddenly not working in Internet Explorer 11

### ISSUE THREAD

**Issue by schwook72** [taye/interact.js#355]
OK is it just me or is svg with draggable no longer working in Internet Explorer?  

My own efforts no longer work and the demo "Use in SVG files" no longer works either.  It gives an error "Unable to get property 'a' of undefined or null reference"

Is this just my IE?  My work environment sometimes does ridiculous things with our settings and Im in a MOE. 
##

**Comment by taye** [comment]
Yes it was broken because I setup an event listener for `mousedown` and `touchstart`, but not `pointerdown`. https://github.com/interactjs/website/commit/ebb2e273fdc860177dad0f1435d453e693fafadf will fix it after the `1.3.0` release.
