### ISSUE TITLE
Right click can also trigger drag

### ISSUE THREAD

**Issue by Hengjie** [taye/interact.js#359]
If I right click into a draggable, key escape to remove the browser right click dialog. I can now drag the draggable anywhere I like. I tried looking for a way to disable this behavior but documentation does not say anything about right clicking, or dragging.

It seems like one method is to look at the event's `which` property, to see which button is depressed for mousedown.

**Comment by Joeao** [comment]
I catch this data on both start and move. And return false. It's not the perfect solution, but it works.
Another option is starting manually and not calling start if right click is used. However when trying this I had issues applying ignoreFrom.

**Comment by Hengjie** [comment]
Could you provide some code to how you do it with your first solution (the non starting manually solution)?

**Comment by Joeao** [comment]
Sure. I stripped out all the irrelevant bits
```js
interact(Element).draggable({
    onstart: function(e) {
        if(e.interaction.downEvent.button == 2) {
            return false;
        }
    },
    onmove: function(e) {
        if(e.interaction.downEvent.button == 2) {
            return false;
        }
    }
});
```

The optimal solution may be to use manualStart, assuming you have no issues. But this *works* for me.

**Comment by taye** [comment]
Use an [actionChecker](http://interactjs.io/api/#Interactable.actionChecker) to return `null` if `event.button !== 0`.

```javascript
interact(target).actionChecker(function (pointer, event, action) {
  if (event.button !== 0) {
    return null;
  }

  return action;
});
```
