### ISSUE TITLE
Swipe interaction

### ISSUE THREAD

**Issue by Galiabu** [taye/interact.js#360]
Hi,

Is there build in way to use 'swipe' interaction, similar to the one exists in Hammer.js?
If so, I will appreciate if you could publish a sample.

Thanks,
Galia
##

**Comment by ljachymczyk** [comment]
+1

**Comment by boynet** [comment]
there is this event.swipe event but it's undocumented, not sure of this reliability

**Comment by taye** [comment]
End events may have a `swipe` property with direction and velocity info (#35).

```javascript
interact(target).draggable({
  onend: function (event) {
    if (event.swipe) {
      console.log(event.swipe);
    }
  }
});
```
