### ISSUE TITLE
Drag unpredictably stops working on iOS

### ISSUE THREAD

**Issue by orokro** [taye/interact.js#361]
I'm testing with Safari on iOS 9.2.1. Everything will work fine at first. After awhile of playing around with the app the draggable parts stop working.

I checked the console and it says:

"TypeError: null is not an object (evaluating 'this.target._element')" On interact-1.2.6.min.js:49:277

I refreshed, caused the glitch to happen, and I was getting the same error again, with the exception of the line number being 1065.

What's strange is that, this breaks Interactjs globally. Other elements that have .draggable also stop working, with the same error. It's not clear how to reproduce the error, other than moving things around a lot until it breaks.

**Comment by taye** [comment]
Try the build in the [unstable branch](https://github.com/taye/interact.js/tree/unstable/dist). It likely has been fixed there.
