### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined in setEventXY

### ISSUE THREAD

**Issue by seckardt** [taye/interact.js#363]
The development version of `Interact.js` contains an issue in method `Interaction.start()` at line 1751. The method `Interaction.setEventXY()` is being invoked without required pointers, so later in line 606 an `Uncaught TypeError: Cannot read property 'length' of undefined` is being thrown due to the missing pointers.

**Comment by taye** [comment]
This is likely fixed in the latest [unstable](https://github.com/taye/interact.js/tree/unstable/dist) version.
