### ISSUE TITLE
Cursor move bug on dragging 

### ISSUE THREAD

**Issue by tastemeru** [taye/interact.js#364]
If you click on draggable element, but do not drag it, then we get a ```cursor: move``` freezed in the html tag. Btw currently fix it by ```styleCursor(false)``` and custom css style.
![Image of bug](https://api.monosnap.com/rpc/file/download?id=acFyX4vHtTOGNTv9EVgHtEzxabgkFM)

**Comment by taye** [comment]
This is fixed in the [unstable](https://github.com/taye/interact.js/tree/unstable/dist) branch.
