### ISSUE TITLE
Firefox 45.0.1 throws "TypeError: this.activeDrops.dropzones is null"

### ISSUE THREAD

**Issue by mzxgiant** [taye/interact.js#367]
On line 2455 of interact.js, an error is thrown in my implementation of interact.js (which has a LI being dragged into a single absolutely-positioned DIV with no content). This seems to be some odd behavior of Firefox, as the debugger suggests it is ignoring loop bounds and firing the drop events multiple times for some reason. Changing 2455 to the code below (to validate we have dropzones to fire on) fixes the problem, but I did not put this in as a PR because it seems like an unnecessarily dirty fix.

`if (dropEvents.deactivate && this.activeDrops.dropzones != null)
{
this.fireActiveDrops(dropEvents.deactivate); 
}`

**Comment by taye** [comment]
Try using the [unstable distributiton](http://interactjs.io/api/#Interactable.dropChecker). This issue may have been fixed there.

Does this error happen only in Firefox?
