### ISSUE TITLE
autoScroll with a fixed position that is not window

### ISSUE THREAD

**Issue by mikeycgto** [taye/interact.js#368]
![page dnd chrome](https://cloud.githubusercontent.com/assets/82063/14052091/eee45e74-f29d-11e5-85d7-eb5f76096b5e.gif)

Everything with our drag and drop and our `checker` method works fine, as seen here, until the scroll is hit. It seems like the calculated `rect` for the `dropElements` are not factoring in the scroll offsets. The odd part is, if you start off with scroll, it works fine until scroll occurs.

Any suggestions for how to fix this? Trying to deal with this case in `dropCheck` but I am stumped.

**Comment by mikeycgto** [comment]
I think I'm able to get the functionality I want with enabling `dynamicDrop` for this case.

**Comment by taye** [comment]
Yes `dynamicDrop` is the best solution.
