### ISSUE TITLE
Resizing from top or left border disabled by default

### ISSUE THREAD

**Issue by dduugg** [taye/interact.js#37]
It seems resizing an element is only enabled by default along the bottom and right borders. In other words, if the dotted lines in this image were element boundaries, the resize handles marked "X" would not work at all, and those marked "/" would only work along one dimension:

![image](https://cloud.githubusercontent.com/assets/697964/3394281/26238752-fcdc-11e3-964d-bd1c7042a6e6.png)

Is this behavior intentional, or am I doing something wrong? If the former, would you be amenable to a PR to enable resizing along all four borders?

**Comment by diegope** [comment]
+1 for this as well!

**Comment by railsjedi** [comment]
+1, this blocked me from using interact.js (had to switch to jquery ui). My app requires a sidebar on the right side of the page. Resizing would only work from the left edge.

**Comment by taye** [comment]
As noted above the previous two comments, four-direction resizing is being implemented in PR #145. You can try it out now; I don't think the API will change much before it's ready to be merged. I'd appreciate any feedback.

**Comment by railsjedi** [comment]
will do, thanks @taye!
