### ISSUE TITLE
Looking for a drag and drop only version

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [taye/interact.js#370]
Hey guys,

I really love interact, but I don't need a lot of the features it has lol. I just basically want the drag and drop stuff.

Things I don't need: 

Resizing
Multi-touch Rotation
Pinch-to-zoom
Use in SVG files
Tap, doubletap and hold

I am curious if someone can help me get:
Dragging
Drag and drop (kinda same thing lol)
Snapping

Heck, I don't even think I really need snapping. :P

But, I am willing to pay someone around 15 or 20$ USD over paypal if they can help me try to remove those from the source. Please let me know at: dillybob92@gmail.com or post here, thank you

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Did it myself guys, got it to about 40kb :) xD  Epic plugin ~

**Comment by loriensleafs** [comment]
@PokemonAshLovesMyTurkeyAndILikeYouTwo what did you do for the drag and drop only version?
