### ISSUE TITLE
Button inside of a draggable is not clickable on mobile browsers

### ISSUE THREAD

**Issue by peterklima** [taye/interact.js#371]
I'm experiencing an annoying issue on the mobile Safari 9.3.1 and Chrome 49.0.2623.109 on the iPad: When adding a button to a draggable object it is not clickable. However the button is working on modern desktop browsers (Safari, Chrome).

`<div class="draggable"><button onclick="alert('got ya')">click me</button></div>`

The alert is not shown on the iPad.

**Comment by taye** [comment]
You can use the [`ignoreFrom`](http://interactjs.io/api/#Interactable.ignoreFrom) setting to prevent actions from buttons or use interact.js' [`tap` event](http://interactjs.io/docs/#pointer-events) instead of `click`

**Comment by peterklima** [comment]
ok the tap-event worked for me. thanks!
