### ISSUE TITLE
support drag touch device surface pro edge

### ISSUE THREAD

**Issue by wgl85** [taye/interact.js#372]

**Comment by wgl85** [comment]
Is there a plan to support drag action on Microsoft touch device like Surface Pro using Edge browser? I have verified it works on Surface Pro Chrome browser, but it does not work on Surface Pro Edge browser.

**Comment by taye** [comment]
You need to set the `touch-action` CSS property appropriately. See http://interactjs.io/docs/faq/#touch-input-on-internet-explorer.
