### ISSUE TITLE
Cursor changes to Move when I double click an item placed on the dropZone

### ISSUE THREAD

**Issue by alyn000r** [taye/interact.js#373]
I drag an item and drop it at the drop zone. I then double click that item, the item goes back to the initial position but the cursor turns to move and it does not go back to normal unless I select an item to drop. 

I got it to work by going to the interact.js file and changing

Line 264 and 280 for  interact.js v1.2.6 - non minified

To say 'auto' instead of 'move'

I am not sure if this is an actual bug in the library or it is in my code. I am logging this if someone would like to investigate further. 

Thank You

**Comment by taye** [comment]
Duplicate of #364
