### ISSUE TITLE
Dragmove resets gesturemove

### ISSUE THREAD

**Issue by nsdonev** [taye/interact.js#380]
Hi i am trying to create object that is both scalable and rotateable. In the same time i want to have the ability to drag it. To do so i am using this piece of code.

```
       function manipulate(elementSelector) {
          var assetToManipulate = elementSelector;
          var angle = 0;
          var scale = 1;
          interact(assetToManipulate)
          .gesturable(true)
          .draggable(true)
          .on('dragmove gesturemove',dragMoveListener);

          function dragMoveListener (event) {
            console.log(event);
            var target = event.target;
            // keep the dragged position in the data-x/data-y attributes
            var x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
                y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;
                angle += event.da;
                scale = scale * (1 + event.ds);
                var rotateAndScale = 'rotate(' + angle + 'deg)' + 'scale(' + scale + ')';
                // translate the element
                target.style.webkitTransform =
                target.style.transform =
                'translate(' + x + 'px, ' + y + 'px)' + rotateAndScale;
                // update the posiion attributes
                target.setAttribute('data-x', x);
                target.setAttribute('data-y', y);
          }
        }
```

Everything works fine when scaling and rotating the object with two fingers.I can even drag it with two fingers. The problem comes when i use one finger and try to drag it. Then the object freeze and it somehow resets everything and the object becomes unresponsive to any action.
Maybe i am doing something wrong here.I am open to any advice on how to implement such functionality. 
Thanks!

**Comment by grmakowski** [comment]
Perhaps you are lacking a spacebar where you concat translate with rotateAndScale

**Comment by grmakowski** [comment]
This should work if you make `rotateAndScale` a global variable and initialize it as an empty string, and then only update it if the `event.ds` and/or `event.da` are not null. Might not pick up changes from single to multiple pointers, but starting a drag with one finger should still work without messing rotate and scale.

**Comment by taye** [comment]
I agree with @grmakowski.
