### ISSUE TITLE
Drag fails if the dragged element disapears

### ISSUE THREAD

**Issue by rsalvadorg** [taye/interact.js#383]
If some code removes the dragged element during the drag and drop process, if fails and keeps the Interact blocked throwing errors.

Very easy to solve on dropCheck,

replace: var dragRect = draggable.getRect(draggableElement);
with: var dragRect = draggable.getRect(draggableElement);
            if (dragRect == null)
                return false;
##

**Comment by taye** [comment]
If you know when the element will be removed, you can call `event.interaction.stop()` from a drag move event before it happens. This method is only available on the `unstable` version.

I'll try to implement something to better handle removed elements.

**Comment by taye** [comment]
Should be fixed with commit bb503b5.
