### ISSUE TITLE
iframe `Blocked a frame with origin` security issues with separate domains

### ISSUE THREAD

**Issue by sgarbesi** [taye/interact.js#388]
Why is the library attempting to gain access to the parental frame when it's loaded within a `iframe`? Is there a way to disable this?

This is causing a error in Safari.

---

**Demo:**

See the console for this URL in Safari:

- https://output.jsbin.com/rirojacasu

**Source:**

- JSBin: http://jsbin.com/rirojacasu/edit?html

- Plnkr: https://plnkr.co/edit/t9aDS5

**Comment by taye** [comment]
It was to try to allow drags to continue when the pointer is moved outside the iframe. Since https://github.com/taye/interact.js/pull/313 this is no longer done.
