### ISSUE TITLE
For 'tap' events, origin is not applied.

### ISSUE THREAD

**Issue by brettvitaz** [taye/interact.js#389]
I am creating a clickable track for input slider. I would like to consistently calculate position from the origin element and have set up my code:
```
    this._interactable = interact(this._track)
      .origin('self')
      .on('tap', (event) => { ... });
```

If nothing is above the interactable element, `layerX` does supply the correct value. If something is covering the interactable element, the `layerX` value is relative to the covering element. Unhelpfully, `x`, `clientX`, `screenX` are all the same value (position clicked on the window).

Can you help me here?

**Comment by taye** [comment]
This is intentional and is [mentioned in the docs](http://interactjs.io/docs/#pointer-events).  I've considered adding origin, snapping, etc. for pointer events but I don't know when I might have the time.
