### ISSUE TITLE
"tap" event does not work on Google Chrome

### ISSUE THREAD

**Issue by tolokoban** [taye/interact.js#393]
On windows seven with Google Chrome 50.0.2661.102 m, the "tap" event does nothing.
Tested on your "Tap, doubletap and hold" demo. "doubletap" does'nt work neither, but "hold" does.

By the way, your library is very good!

**Comment by tolokoban** [comment]
It works with Google Chrome 51.0.2704.84 on Linux.
Could be a Google Chrome bug.

**Comment by taye** [comment]
I am happy to believe that it's a Google Chrome bug.

**Comment by mhm-amaya** [comment]
On Win 7 64bits and latest Chrome 58.0 it is not working yet.
If it is a Chrome bug it is clear that it is here to stay :-/
Any workaround?

**Comment by taye** [comment]
@mhm-amaya You might need to increase the `pointerMoveTolerance`.

```javascript
interact.pointerMoveTolerace(2);
```

**Comment by mhm-amaya** [comment]
Many thanks @taye, but it doesn't seem to fix the problem. I tried even with larger values with no luck.
Approximately half the clicks gets ignored, and I can't guess any pattern.
