### ISSUE TITLE
Custom resizing handles for corners

### ISSUE THREAD

**Issue by nacgarg** [taye/interact.js#396]
Is it possible to have custom elements for corner handles like in the image below? Right now, it is only possible (to my knowledge) to set handles for `left`, `right`, `bottom`, and `top` in the edges option of `resizable`. 

![image](https://cloud.githubusercontent.com/assets/8907939/16207632/fe498ad6-36e2-11e6-8118-6fb7b5c221d3.png)

**Comment by bugss** [comment]
+1

**Comment by nacgarg** [comment]
@bugss: @Nic128 actually added functionality for this and submitted a pull request (#395) that hasn't been merged yet. I merged his branch with what was then (and I think still is) the current stable branch in [my fork](http://github.com/nacgarg/interact.js/tree/stable).

**Comment by taye** [comment]
Two edges make a corner. If you want an element to behave as a corner, let it match the selectors of two adjacent edges.

**Comment by nacgarg** [comment]
Thanks for the follow-up. That makes sense, but I don't think I saw it in the documentation anywhere. It would be nice if you added it :)

**Comment by taye** [comment]
I certainly will. Thanks for the feedback.
