### ISSUE TITLE
ignoreFrom broken in master

### ISSUE THREAD

**Issue by zbjornson** [taye/interact.js#397]
I think one of these two commits broke `ignoreFrom` in master:

https://github.com/taye/interact.js/commit/ab73f6d735555721e98a8cce8192dce244a0d889
https://github.com/taye/interact.js/commit/748f542644eda6ddf621419be7e0dbd6e361c8f1

No targets are ignored; all cause events.

**Comment by taye** [comment]
Thanks for bringing this up. I think I was planning on adding a separate `ignoreFrom` setting for pointerEvents like tap, move, etc but forgot about it. I'll try to fix this soon before releasing.
