### ISSUE TITLE
Drag Handle and Resize combo

### ISSUE THREAD

**Issue by ssilve1989** [taye/interact.js#402]
Is it possible to have both resize and dragging **with a handle** work together? I've tried various config combinations and it just ends up losing resize functionality. 

Here is what it currently looks like
```
interact(box)
			.resizable({
				preserveAspectRatio: true,
				edges              : { left: true, right: true, bottom: true, top: true }
			})
			.on('resizemove', function(event) {
                         ...
			})
			.draggable({
				onmove: dragMoveListener
			}) .allowFrom('.box-menu-bar');

```

**Comment by ssilve1989** [comment]
bump

**Comment by taye** [comment]
At the moment, `allowFrom` and `ignoreFrom` are useed for all actions. I plan on changing it so that you can set a different one for each action but for now, you'll have to use a custom [actionChecker](http://interactjs.io/api/#Interactable.actionChecker). Here's an example from a different issue:

```javascript
  // custom action checker
  interact(target).actionChecker(function (pointer, event, action, interactable, element) {
    // if the default checker got a resize action,
    // change it to a drag if the element doesn't have [rs] attribute
    if (action.name === 'resize' && (!element.hasAttribute('rs'))) {
      action.name = 'drag';
    }

    // return the action
    return action;
  })
```

**Comment by DutchKevv** [comment]
@taye 

Great library!


Running in the same kind of thing. Permitting a unique allowFrom per action would solve it for me.. 
useCase:

A box that can both be dragged and resized. The header is a (deep) child of the box and only that element can drag the whole box. But resizing should be possible everywhere, so allowFrom blocks the resize handles, as it allows only the header to be grabbed and therefore resized...

Have you found time to implement the 'allowFrom per action' feature??

**Comment by taye** [comment]
I thought I already did this. It's done now in the `master` branch.

**Comment by DutchKevv** [comment]
Hmm if I do the following: 

`
<div id="test">
        <div id="dragger"></div>
</div>    
var el = document.getElementById('test');

interact(el)
     .draggable({...etc})
    .allowFrom('#dragger')


interact(el)
    .resizable({...etc});`

The resizable only works on the #dragger, not on the entire box that is set as resizable. 
Am I doing it the wrong way?

**Comment by taye** [comment]
@DutchKevv I made a silly mistake with `git` commands. It's fixed now I think.

**Comment by ThePlastic** [comment]
this funcionality will be available in 1.3.0?

**Comment by DutchKevv** [comment]
No worries, still love your library! :)

Im gonna give it another try in a couple of days

**Comment by ThePlastic** [comment]
is drag handle and resize combo now working?

**Comment by taye** [comment]
@ThePlastic https://jsfiddle.net/taye/z0zdtobb/
