### ISSUE TITLE
Configure _holdDuration

### ISSUE THREAD

**Issue by acoquoin** [taye/interact.js#403]
Hello :)

Thank for interact.js, it's an amazing script :).
But i have a small issue, it is in any way, possibility to change the _holdDuration ?

600ms is to long for our product manager.

Thanks in advance :)

**Comment by taye** [comment]
With v1.2.6, you can do

```javascript
interact.debug().defaultOptions._holdDuration = timeInMilliseconds;
```

With the latest unstable version, there's no simple way. If you're using browserify, you can `require('interact.js/src/defaultOptions')._holdDuration = timeInMilliseconds;`

I hope to add a better way to do this.
