### ISSUE TITLE
How to disable draggable events?

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [taye/interact.js#404]
Hi,

I'm trying to remove the Event Listener for draggable.

My Listener:

`var interObj = interact('...').draggable(...);`

Later in my code I do the following to get rid of the draggable events like onstart, onmove and onend:
`interObj.draggable(false);`

I also tried
`interObj = null;`

But in both cases the dragEnd event still fires after this.
How can I disable it immediately?

Thanks in advance.
ScientiaEtVeritas

**Comment by acoquoin** [comment]
You can find how to do this in the FAQ :)
http://interactjs.io/docs/faq/#remove-an-interactable

**Comment by ScientiaEtVeritas** [comment]
It seems like this doesn't work either.

I'm working with ReactJS and it doesn't allow actions on umounted components.
Therefore best practice is that you remove listener before the component will unmount.
So I set the ``interact(ReactDOM.findDOMNode(this)).draggable(...)`` after the component mounted and before the component is unmounted I do ``interact(ReactDOM.findDOMNode(this)).unset();``

I also check it like ``console.log(interact.isSet(ReactDOM.findDOMNode(this)));`` if the Interactable is really removed. And it results in ``false``. 

And still AFTER this, the onend listener is still fired once after the component is umounted.

**Comment by taye** [comment]
If you want to remove the event listeners that you set wit the `interactable.draggable` method, you can do it by setting `interactable.ondragmove`, etc. to `null`.

```javascript
interact(target).draggable({ onmove: listener })
// equivalent to
interact(target).draggable(true);
interact(target).ondragmove = listener;
```

I hadn't considered it before but it would be a good idea to have `interactable.draggable(false)` remove evet listeners that are set with that method.

**Comment by Spomsoree** [comment]
There is a pretty clear answer in #157 if you try to disable it temporarily.
