### ISSUE TITLE
Manual drag start outside the draggable

### ISSUE THREAD

**Issue by vkomodey** [taye/interact.js#406]
Hi! 
I have a pretty simple drag'n'drop module in my app. I need this module working on touch devices so i use `interact(selector).draggable({manualStart: true,...}.on('move hold', basicOnMoveHandler)`. 
Here's the listener
```
    basicOnMoveHandler(event) {
        let interaction = event.interaction;

        if (interaction.interacting()) {
            return;
        }

        if (event.pointerType === 'mouse') {
            if (event.type !== 'move') {
                return;
            }
        } else if (event.type !== 'hold') {
            return;
        }

        if (interaction.pointerIsDown) {
            const original = $(event.currentTarget);

            const jobNumber = $(original).parent().find(SELECTORS.JOB_NUMBER_CLASS).text();

            const dragId = original.find(SELECTORS.SCHEDULER_EVENT_DRAG_ID).val();

            let helper = getSchedulerDraggableHelper(jobNumber, dragId);
            interaction.start({ name: 'drag' }, event.interactable, helper[0]);
        }
    }
```
And problem with this listener is that i can click/touch on different than draggable element place, then move cursor to the draggable element, and then dragging process would be triggered.
So i need dragging is performed ONLY when i click to this draggable(not outside) and then move, not outside. Are there some solutions inside interact? 
I think this can be implemented with native mousemove browser events, but it would not help with touch events

**Comment by taye** [comment]
I think it would work better if you used `'down'` instead of `'move'`.

**Comment by euqen** [comment]
@taye thanks it works!

**Comment by volodshulyk** [comment]
@taye why then in the FAQ section you wrote to use 'move'. If 'down' event is better (no issue described above), maybe DOCs should be updated?
