### ISSUE TITLE
The rotate seems not work

### ISSUE THREAD

**Issue by MichelleShieh** [taye/interact.js#407]
Hi,

The rotation animation doesn't work for me either on chrome or edge, and I am wondering if there is a way to rotate instead of multi touch? 

thanks in advance.
##

**Comment by taye** [comment]
There's no built-in way to do gestures with a mouse.

**Comment by jakenoble** [comment]
Was there a solution found for this?

**Comment by awingit** [comment]
It would be cool is a rotate handle was possible, instead of a gesture. This can be a solution for desktop. Just an icon positioned relative to the element being rotated.

Any thoughts?

**Comment by jakenoble** [comment]
I used https://greensock.com/ instead
