### ISSUE TITLE
Draggable element moves left when removing previously created draggable elements

### ISSUE THREAD

**Issue by dalareo** [taye/interact.js#409]
Hi, congratulations for your library!! It is simply great.

I am working on a productivity app that helps co-creating and co-designing tasks for people working together. It is kind of a digital replacement of analogic "designing tools" as big papers and post-it.

A static version of the project is hosted at https://github.com/dalareo/design-thinking

I've created a button that allow to dinamically create new boxes, and this boxes can be dragged inside canvas (Business model canvas in my first example). The created boxes are created with this function:

```
Template.main.events({
'click .createBox': function(){
var i=1;
mNewObj = document.createElement('div');
mNewObj.className = "draggable drag-drop";
mNewObj.id = "BOX" + i;
mNewObj.style.visibility="show";
mNewObj.innerText = document.getElementById("text").value;
var input = document.createElement("button");
input.type = "button";
input.className = "removebox close";
input.innerText = "x"
mNewObj.appendChild(input);
document.getElementById("backlog").appendChild(mNewObj);
//mNewObj.setAttribute("data-x", 0);
//mNewObj.setAttribute("data-y", 0);
document.getElementById("text").value = "";
i++;
}
});
```

Boxes are initially put inside a <div> named "backlog". Then boxes can be dragged inside the canvas freely but:

When I remove a box previously created all the next boxes are automatically moved left. How can I avoid this??
##

**Comment by taye** [comment]
Give the elements `position: absolute` styles so that they don't depend on the previous sibling elements.

**Comment by dalareo** [comment]
Thanks!!!
