### ISSUE TITLE
Draggable Elements once touch, stick together

### ISSUE THREAD

**Issue by P0SEID0N** [taye/interact.js#418]
First of all, I do apologize if this issue already exists, or a solution already exists I have went through many of the issues and couldnt really find one that fit this category... all the same if one does exist I do apologize for the replication.

If you look at the example on the interactjs page: http://interactjs.io/ the first example, whenever you drag one element over another, the first element starts sticking to the other whenever new drags are initiated.

At first I thought this was an issue with my own code, however my tests on chrome and firefox both see this happen even in the example provided on the interactJS page.

I am going to take a look into the interact code in a bit to see if there is something I can see that might be holding the two (or more) elements together.

Best,
~ Poseidon
##

**Comment by taye** [comment]
Hi Poseidonn,

I think this is fixed in the latest version on the `unstable` branch. You can get it from https://raw.githubusercontent.com/taye/interact.js/unstable/dist/interact.js. Sorry for responding so late.
