### ISSUE TITLE
tap: event.double is always false

### ISSUE THREAD

**Issue by jamesdixon** [taye/interact.js#419]
I'm trying to allow both the `tap` and `doubletap` events to occur, but unfortunately, it seems that `event.double` is always false. I've tried this on the latest version of Safari, Chrome and FF on Mac, with no luck.

``` js
    interactable.on('tap', (event) => {
      if (event.double) { return; }
      Ember.run(this, this._tap, event);
    });
```

Ref: #155 

Anyone else have this issue?

Thanks!
##

**Comment by taye** [comment]
Does the target of the event changing between each tap? If so that prevents the second tap from being counted as a double tap.
