### ISSUE TITLE
divs with contenteditable="true" are not editable

### ISSUE THREAD

**Issue by Nolski** [taye/interact.js#420]
In the following example:

``` html
<div class="draggable">
    <div id="edit" contenteditable="true"></div>
</div>
```

The div with `id="edit"` will not behave normally as a div with `contenteditable="true"` would. I think the click event is somehow getting intercepted by interact.js. However an `<input>` element will work just fine.
##

**Comment by bryantabaird** [comment]
I've recently discovered this same issue as well, and I'm wondering if you found a solution?

**Comment by dpekkle** [comment]
More of a workaround but i've just been using a handle. 
Don't know if that suits your use.

HTML:
```html
<div class="text-container drag-element">
    <div id="text1" class="handle text-handle">
        <!-- Handle contents -->
    </div>
    <div class="editdiv resize-element" contenteditable="true" style="width: 379px; height: 200px;">
    </div>
</div>
```
Javascript:
```javascript
interact('.drag-element')
	.draggable({
		inertia: false,
		restrict: {
		  restriction: "parent",
		  endOnly: false,
		  elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
		},
		autoScroll: true,
		onmove: dragMoveListener
	})
	.allowFrom('.handle');
interact('.resize-element')
	.resizable({
		edges: { left: true, right: true, bottom: true, top: false},
		onmove: resizeMoveListener
	});
```

**Comment by dpekkle** [comment]
Other approaches that may work are to chain .preventDefault('never') on your interactable, though this may well cause other issues.
