### ISSUE TITLE
Change the start position

### ISSUE THREAD

**Issue by jcarayacorrea** [taye/interact.js#421]
Hi,

I need some help, the situation is the point x:0 and y:0 start in the top left of the dragzone, how can i change that point to the bottom of the left side.

Thanks.
##

**Comment by awojtczyk** [comment]
That should help you.
```
$('.js-drag').each(function() {
        $(this).attr('data-x',$(this).position().top);
        $(this).attr('data-y',$(this).position().left);
    })
```

**Comment by taye** [comment]
I don't understand the problem. Can you make a jsfiddle or codepen demo?
