### ISSUE TITLE
Clicking on a draggable without dragging permanently switches the cursor to `drag`.

### ISSUE THREAD

**Issue by tailsu** [taye/interact.js#422]
This is also evident on the interact.js main page: click on a draggable box and move the cursor away from the box - 9 times out of 10 the cursor sticks to the drag-cursor. Eventually something prompts it to go back to normal.

In any case, this behavior of setting the cursor straight on the `body` DOM element makes it seem like the nuclear option was chosen here. Why not simply add/remove a class to the dragged element and modify the cursor through a stylesheet?
##

**Comment by gabriel-dehan** [comment]
👍  I agree that it needs to be improved. It's quite disturbing for end users.

**Comment by ssilve1989** [comment]
Updates on if this was merged?
