### ISSUE TITLE
Drag SVG element across Elements 

### ISSUE THREAD

**Issue by farrukhpisces** [taye/interact.js#425]
Is this possible to move (drag) svg element from one div or SVG to other.  I am trying but it only moves element inside SVG.
my drag-resize is 
`interact('.resize-drag')
  .draggable({
      onmove: window.dragMoveListener
  })
  .resizable({
      preserveAspectRatio: true,
      edges: { left: true, right: true, bottom: true, top: true }
  })

  .on('resizemove', function (event) {
      var target = event.target,
          x = (parseFloat(target.getAttribute('data-x')) || 0),
          y = (parseFloat(target.getAttribute('data-y')) || 0);

```
  // update the element's style
  target.style.width = event.rect.width + 'px';
  target.style.height = event.rect.height + 'px';

  // translate when resizing from top or left edges
  x += event.deltaRect.left;
  y += event.deltaRect.top;

  target.style.webkitTransform = target.style.transform =
      'translate(' + x + 'px,' + y + 'px)';

  target.setAttribute('data-x', x);
  target.setAttribute('data-y', y);
  target.textContent = Math.round(event.rect.width) + '×' + Math.round(event.rect.height);
```

  });

```
function dragMoveListener(event) {
    var target = event.target,
        // keep the dragged position in the data-x/data-y attributes
        x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
        y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;


    //alert(target.getAttribute('tagName'));

    // translate the element
    target.style.webkitTransform =
    target.style.transform =
      'translate(' + x + 'px, ' + y + 'px)';

    // update the posiion attributes
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
}

// this is used later in the resizing and gesture demos
window.dragMoveListener = dragMoveListener;
```

`
##

**Comment by taye** [comment]
I think you'd have to change the parent of the element and maybe also set the container's `overflow` CSS property to `visible` so that the dragged element is visible beyond the bounds of the container.
