### ISSUE TITLE
Drag an element under another element

### ISSUE THREAD

**Issue by julian0852** [taye/interact.js#427]
I have two divs - position:absolute directly over each other.
Div1 is zindex:1 contains an image of a face
Div2 is zindex:2 contains a png image of birthday card with transparent "hole"
Therefore the face is visible through the "hole"
I need to be able to drag the face around but leave the birthday card on top.
But when I make Div1 draggable it cannot be dragged because Div2 is on top and therefore cannot be touched.
Is there a way around this?
Maybe drag Div1 when Div2 is touched?
##

**Comment by dpekkle** [comment]
That may be the best way, as long as you're fine with the birthday card not being draggable.

Just make an interact targetting Div2 that makes changes to Div1.

**Comment by taye** [comment]
You can also set CSS `pointer-events: none` on the birthday card so that all pointer interactions go right through it and to the face.
