### ISSUE TITLE
Microsoft Edge: pen touch gives error, finger touch doesn't work.

### ISSUE THREAD

**Issue by dietergeerts** [taye/interact.js#428]
While a mouse click gives a tap event, using your finger does nothing and using the pen gives the following error:

```
SCRIPT5007: Unable to get property 'pageX' of undefined or null reference
interact.js (649, 9)
```

This is the same on both Microsoft Edge as IE11
##

**Comment by kumardeepakr3** [comment]
@dietergeerts I checked it on Edge. On Edge you need to enable Touch Events by going to "about:flags". Also the pen touch works for me. I'm using Lenovo X1 Yoga. It works fine for me. Let me know if this was the issue or is there an altogether different cause.

**Comment by dietergeerts** [comment]
@kumardeepakr3 , I'll check again. But just to be clear on the pen: I use a Microsoft Surface Pro tablet with the Wacom pen, I guess it behaves differently then other pens. I'll keep you posted

**Comment by taye** [comment]
Try using the [`unstable`](https://rawgit.com/taye/interact.js/unstable/dist/interact.js) version.

**Comment by dietergeerts** [comment]
I'm sorry, but I can't test it. I started working on other projects, and have no access anymore on the one where we had this problem. I asked if I could test this, but I got no answer.

**Comment by taye** [comment]
No problem at all.

**Comment by taye** [comment]
This issue is present on both the stable and unstable versions on all browsers that emit pointer events with "pen" `pointerType`s.
