### ISSUE TITLE
IE - Child node mouse event

### ISSUE THREAD

**Issue by lannex** [taye/interact.js#429]
Only 'IE' (test in IE11). Child node events (mouseup, mousedown, Etc) does not working.
(However, click event is work)

For example.

```
// interact
interact('.table-files li')
  .draggable({
    ...
  )}
  ...

// child node - '.table-files li button'
<button
  className="btn btn-table-files-more"
  onMouseDown={ Not working }
  onMouseUp={ Not working }
>
  ...
</button>
```

I use React and ES6.
##

**Comment by taye** [comment]
The problem *might* be that you're using camel case for the attribute names instead of all lower case.
