### ISSUE TITLE
Inertia

### ISSUE THREAD

**Issue by fatlard1993** [taye/interact.js#434]
Starting a new drag even whilst another element is still moving via inertia will cause the first element to move about, following the cursor after you have released from the second element. This is evident and reproducible on the homepage of your website in the first example. Simply flick the first element and move the second one before the first stops moving.

**Comment by taye** [comment]
I believe that this is fixed on the `unstable` branch. https://rawgit.com/taye/interact.js/unstable/dist/interact.js.

**Comment by JonathanPicques** [comment]
Indeed, I've made a fiddle to show the issue: https://jsfiddle.net/9Ljaannh/11/

PS: The unstable branch fixes the problem 🥇

@taye: Do you have by any chance an ETA for the unstable branch making it in the stable one? Thanks

**Comment by taye** [comment]
I've created a milestone for the next release: https://github.com/taye/interact.js/milestone/1. I consider the `unstable` version to be functional and certainly less buggy than the current `stable` version. I have a lot of documentation and tests to write, but won't have time for it for the next few weeks. I expected to have the release ready by now but I had some hardware issues and logistical mishaps which meant that I couldn't do much work in December.
