### ISSUE TITLE
div and sub div

### ISSUE THREAD

**Issue by htabech** [taye/interact.js#435]
1st i have to thank you about this library, amazing job
i am testing it in my website and works fine on click, dclick and hold with dragable and sizable all together, unless i add sub div then when ever i double click, it disables all dragable and sizabel and does not accept any clicking on the sub div at all, i even did event.preventDefault() but no luck same problem unless i remove the sub div and write my text without a sub div than it would work perfectly, also your example with div and sub div like ℗ paragraph div works fine on the demo but i tried that on my server it did not work with sub div, so if you can help me with that it will be apriciated . 
regards,

**Comment by htabech** [comment]
problem solved by adding `pointer-events:none;` in every sub div.

**Comment by taye** [comment]
You're welcome! I'm glad you found a solution.
