### ISSUE TITLE
 Failed to execute 'querySelector' on 'Document'

### ISSUE THREAD

**Issue by phuwin** [taye/interact.js#436]
Hi,
I am new to interact.js
Do you know how come this is an error? How do I fix this?
The error only happens with that specific id `3mMuMy07l6`.

```
angular.js:13424 Error: Failed to execute 'querySelector' on 'Document': '#3mMuMy07l6' is not a valid selector.
```

I tracked the error and it shown in these lines:

```
interact("#"+gridId).draggable(false).resizable(false);
interact("#"+gridId).draggable({...});
```
##

**Comment by taye** [comment]
Element IDs aren't allowed to start with numbers.
