### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property '_element' of null

### ISSUE THREAD

**Issue by JayEmAge** [taye/interact.js#438]
**Uncaught TypeError: Cannot read property '_element' of null**

In function `pointerDown` the code

`if(1<this.pointerIds.length&&this.target._element===this.element){`

should be replaced by

`if(1<this.pointerIds.length&&this.target&&this.target._element===this.element){`
##

**Comment by taye** [comment]
Use the [`unstable`](https://rawgit.com/taye/interact.js/unstable/dist/interact.js) version. A lot of that code has been changed.

**Comment by Smona** [comment]
This patch fixes the issue for me, but using unstable branch other things are broken. can we get a 1.2.10 patch with this fix?

**Comment by taye** [comment]
@Smona I think that things are so much better in the latest `1.4.0-alpha` versions that it would be worth while to try to update. I can try to make some time to help you with the migration as I really prefer not to go back to working on the 1.2 branch even if it's a small change.
