### ISSUE TITLE
In certain cases doOnInteractions gets called with a null event

### ISSUE THREAD

**Issue by sexybiggetje** [taye/interact.js#440]
I don't have a specific reproduction, but under certain conditions doOnInteractions appears to gets called.
It would be very simple to fix by checking the variable "event" for null and return if the condition matches.

Maybe you have more insight in a reproduction step, as I'm unable to share our codebase to debug.
##

**Comment by taye** [comment]
`doOnInteractions` returns a listener function which eventually gets added to the document with `document.addEventListener` [here](https://github.com/taye/interact.js/blob/master/src/Interaction.js#L469). Is it possible that something in your codebase changes `document.addEventListener` method and uses that to call the listner function with `null`? I can't think of another way that that might happen.
