### ISSUE TITLE
Pseudo-selector ":not" breaking interact

### ISSUE THREAD

**Issue by ultimagriever** [taye/interact.js#443]
I have an issue where I have numerous `.tag` divs and some of them should be interactable, while others shouldn't. They have other classes as well, and I'm trying to rule them out by using the `:not` pseudo-selector (i.e. `.tag:not('class*=text')`). The following code does not work:

```
interact('.tag:not("class*=text")')
  .draggable(...)
  .resizable(...)
```

**Comment by taye** [comment]
`.tag:not("class*=text")` is an invalid selector. If you meant to use `:not` and an attribute selector, try `.tag:not([class*="text"])`.
