### ISSUE TITLE
Stop Overlapping while dragging divs

### ISSUE THREAD

**Issue by chandrikas-optimus** [taye/interact.js#445]
Hi, 

First of all i would like to say thanks for giving us such a great library. It is helping me alot.

My requirement is to have multiple divs with resizable and draggable property. I can resize any of them and can place at any position. I am able to resize them and can drag them but they get overlapped.  I want to stop this overlapping. Also i cant give them a separate dropingzone so i have created a structure like a div and its two children div.
Refer my code:
JS CODE:

 interact('.resize-drag') //children
            .draggable({
                // enable inertial throwing
                inertia: true,
                // keep the element within the area of it's parent
                restrict: {
                    restriction: "parent",
                    endOnly: true,
                    elementRect: { top: 0, left: 0, bottom: 1, right: 1 },
                },
                // enable autoScroll
                autoScroll: true,

                // call this function on every dragmove event
                onmove: function (event) {
                    var target = event.target,
                        // keep the dragged position in the data-x/data-y attributes
                        x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
                        y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

                    // translate the element
                    target.style.webkitTransform =
                        target.style.transform =
                        'translate(' + x + 'px, ' + y + 'px)';

                    // update the posiion attributes
                    target.setAttribute('data-x', x);
                    target.setAttribute('data-y', y);
                },
                // call this function on every dragend event
                onend: function (event) {
                    var textEl = event.target.querySelector('p');

                    textEl && (textEl.textContent =
                        'moved a distance of '
                        + (Math.sqrt(event.dx * event.dx +
                            event.dy * event.dy) | 0) + 'px');
                }
            })
CSS CODE:
.resize-drag {
  background-color:white;
  color: black;
  font-size: 14px;
  font-family: sans-serif;
  padding: 20px;
  width: 100%;
  height: 100%;
  overflow: auto;
  min-width: 300px;
  min-height: 100px;
  box-sizing: border-box;
}

this is happening because my parent is same for both the divs. Please correct my code so that i can proceed.

**Comment by taye** [comment]
>Please correct my code so that i can proceed.

No.
