### ISSUE TITLE
Sorting and Ordering

### ISSUE THREAD

**Issue by adelemam** [taye/interact.js#446]
Hi there is there is anyway i can combine the features of interact with any library that do reordering and sorting , so I can have both option to free move elements in some containers or ordering them in another type of containers?, 

it would be great if such features implemented here!

**Comment by taye** [comment]
I'm not sure and I don't think it would be easy. Is there a particular library that you had in mind for sorting?

**Comment by adelemam** [comment]
yes sure, dragular and its angular 2 version  ng2-dragula

**Comment by taye** [comment]
Unfortunately, I don't think Dragula and interact.js can join forces easily. A sorting thing could be made using interact.js but I'm currently not interested in doing it.
