### ISSUE TITLE
PointerEvent problem when using interact in nwjs >= 0.18

### ISSUE THREAD

**Issue by mauvilsa** [taye/interact.js#447]
There are problems when using interact in [nwjs](http://nwjs.io/) version 0.18. This can be observed with the SVG star example from http://interactjs.io/. The corners are no longer draggable. It seems to be related with the PointerEvent support in chromium, see [nwjs issue 5467](https://github.com/nwjs/nw.js/issues/5467).

**Comment by taye** [comment]
This is really a bug in nwjs as PointerEvents should be disabled (as they are in Chrome) if they're not ready.

**Comment by taye** [comment]
This came back to bite me as Chrome followed suit: #457. Sorry for not being more proactive; I didn't have the time back then.
