### ISSUE TITLE
Interact Could Warn if Resize is Enabled But All Edges Are Disabled

### ISSUE THREAD

**Issue by machineghost** [taye/interact.js#448]
I'm an Interact.js n00b, and I just recently lost a bit of time because I made the mistake of enabling resizing, but not setting any edges.  Debugging this was tricky because the library still fired resize events ... but `rect` never changed and `deltaRect` was all 0's.

Eventually by experimenting with the options I figured the problem out, but as a convenience to newer users it might be nice to give some sort of warning when a resize event triggers and and `interact` instance has resizing enabled but does not have any edges enabled.  Since this is sort of a garbage case anyway (what's the point of turning resizing on if you can't resize?) this might even warrant throwing an exception.

Just a thought.  Regardless, thanks for writing Interact.js!

**Comment by taye** [comment]
I see the value in this but a lot of people are opposed to harmless warnings (#240, #277) so I'll have to refuse. I'll try to remember to add an entry to the FAQ or elsewhere in the docs though.

Thanks for bringing this up.

**Comment by machineghost** [comment]
Thanks, at least that's better than nothing.

Just out of curiosity, what is the legitimate use case for this scenario (ie. why not just make it throw an exception instead of a warning, if it's a case that should never occur)?

**Comment by taye** [comment]
Having all edges disabled could be used to intentionally disable resizing so it's worth allowing it to happen.
