### ISSUE TITLE
multiple div's inside eachother .on('hold...

### ISSUE THREAD

**Issue by htabech** [taye/interact.js#449]
is there a way to prevent trigering a div if we press and hold the one sitting on top of it?

**Comment by taye** [comment]
Do you mean that your selector targets both the child and it's parent but you don't want the event to bubble up to the parent? If so then you probably need to call `event.stopPropagation()` so the event listener isn't fired for any of the parent elements. Though that would be a problem if you want the event listener to be called for elements further up the tree.

**Comment by htabech** [comment]
thanks works perfectly, :)
you can goahead and close it
