### ISSUE TITLE
Dynamic height of dropzones offsets dragged element from pointer.

### ISSUE THREAD

**Issue by zenkkor** [taye/interact.js#453]
Hey!

First of all, thank you for the library, it has saved me a lot of development time and is a great library that works really good. Thank you!

I am running into a problem with the drag and drop functionality that happens if the dropzones height is dynamically changed. What happens is this: I start off with all the dropzones having a fixed height and then after the dragging has started, I change the dropzones height by adding an additional class. What happens after is that all the dropzones change height and the picked up elements initial position changes, and a pointer/element offset happens.

I have prepared a pen: http://codepen.io/anon/pen/MbroXM that illustrates the problem.

Any help with this issue or a piece of guidance on how to solve this would be very appreciated. 

Thanks for your help!

**Comment by taye** [comment]
Calling `interact.dynamicDrop(true)` should fix your problem. I don't think this solution is worth a bounty.

**Comment by zenkkor** [comment]
Hey @taye ,

Thanks for the quick response. 

This does not solve the problem I am experiencing (already using dynamicDrop for drop zones because of the changing/dynamic height, as the problem is not in the drop zones itself, but in dragged elements and their offset from the cursor center. When you pick an element up, it offsets the picked up element by the height change of all the drop zones combined (see image attached for reference). 
 
![image-demonstration](https://cloud.githubusercontent.com/assets/14157343/20904088/53af6e70-bb3e-11e6-8395-e481d634ee2f.jpg)

Thanks for any additional responses!

**Comment by taye** [comment]
Oh I see. Styling the dragged element with `position: absolute` or `position: fixed` with `top`, `left`, etc. should do it.
