### ISSUE TITLE
dragend being called before ondrop

### ISSUE THREAD

**Issue by davidlukerice** [taye/interact.js#458]
Just updated to the latest develop since we were having issues with 1.2.6 on chrome 55.
On dragstart we were setting data in e.interactable (similar to https://github.com/taye/interact.js/issues/286)
and then clearing it again on dragend.
In between the two events we utilized that data in a dropzone's ondrop handler.

After the update, however, the dragend gets called before ondrop, clearing the data before we can use it. Was this an intentional change?

**Comment by taye** [comment]
Yes, this was intentional. See #344 for a way to deal with this.

**Comment by davidlukerice** [comment]
Oh, cool. Didn't see that ticket.
