### ISSUE TITLE
Add new resizable element and start resize immeditly

### ISSUE THREAD

**Issue by emilkarl** [taye/interact.js#459]
Trying to add a new element (`.item`) on `mousedown` in `.container`. I would like the item to resize directly on add so you can add + resize in one motion and then release mouse.

Any ideas if that is possible? Trying to fire `hold` after element is added but that does not make it happen.

http://jsfiddle.net/kz12gwz9/31/

**Comment by emilkarl** [comment]
I need some serious help with this...would be awesome to make this work.

Resizing on added items work but there are problems when click->drag to add. The event are missing some vital data.

This works OK but there are multiple issues. 

* `event.rect` is missing when triggering `move` event. L39-63
* can't stop the move event L37
* Have not be able to start resize by some other event then move! L90-103
* Must include fix by @zorentsl https://github.com/taye/interact.js/issues/188#issuecomment-260472151

Fix available in branch here: https://rawgit.com/emilkarl/interact.js/fix--my-start-pointers/dist/interact.js

**Comment by taye** [comment]
You need to provide the `edges` property in the action object.

```javascript
interaction.start({ name: 'resize', edges: { right: true } }, interactable, element);
```
