### ISSUE TITLE
API validity 

### ISSUE THREAD

**Issue by Aminta** [taye/interact.js#461]
Hi!

I wonder if the methods listed in http://interactjs.io/api are still valid, because this page is not linked either in home or in documentation.

For example a method like "interact.getElementRect" it's crucial, but it's obsolete?

Thanks

**Comment by taye** [comment]
They're valid. It's not obvious, but the api page is linked from http://interactjs.io/docs/. I don't plan on removing `interact.getElementRect`.

**Comment by Aminta** [comment]
Thanks!

19 dic 2016, 20:37 +0100, taye <notifications@github.com>, ha scritto:
