### ISSUE TITLE
Documentation for unstable branch?

### ISSUE THREAD

**Issue by paulstraw** [taye/interact.js#462]
In researching the problem described in #457, I'm trying to upgrade an app to use the unstable branch. Unfortunately, I haven't been able to find any documentation for it, and the API seems to be quite different. Are there any docs available for the unstable branch, or use examples? I tried asking about this in the Gitter, but it doesn't seem like there's anyone active there, so I thought I'd give this a go. Thanks for the awesome library!

**Comment by taye** [comment]
The generated API docs are available at https://rawgit.com/taye/interact.js/unstable/dist/docs/index.html.

**Comment by taye** [comment]
Here's a quick upgrade guide: https://github.com/interactjs/docs/blob/v1.3/upgrade-v1.2-1.3.en.html.md

Here's the code for the updated versions of the demos on the homepage: https://github.com/interactjs/website/tree/v1.3/demos
