### ISSUE TITLE
Pinch-zoom no longer working on latest Android versions?

### ISSUE THREAD

**Issue by inkbleed** [taye/interact.js#465]
Hi,

We've been using interact.js for about a year with no problems. We noticed that our production version of the Android app's pinch-zoom no longer works on up-to-date Samsung S6s or One Plus Ones. It's working fine on desktop versions, and works fine on non-updated Samsung S5's. 

The specific issue seems to be that the interact.gesturable onend function is being called pre-emptively. 

For instance:

```javascript

interact(gestureArea)
  .gesturable({
    onstart: function (event) {
      clearTimeout(resetTimeout);
      scaleElement.classList.remove('reset');
    },
    onmove: function (event) {
      scale = scale * (1 + event.ds);

      scaleElement.style.webkitTransform =
      scaleElement.style.transform =
        'scale(' + scale + ')';

      dragMoveListener(event);
    },
    onend: function (event) {
      resetTimeout = setTimeout(reset, 1000);
      scaleElement.classList.add('reset');
    }
  })
  .draggable({ onmove: dragMoveListener });

```
In this instance, onend is being called almost instantaneously, where scale still equals zero. Whereas on the Samsung S5 or Chrome browser, the end function doesn't call until the gesture actually completes (meaning scale equals a value, and the transformation takes place). 

Any tips on a solution would be greatly appreciated! I'm going to have a play to see if I can figure out a solution. Thanks!

**Comment by abrbhat** [comment]
Having the same issue with draggable.onend. Only appears on newer android devices. The element gets dragged a little (10-15px) and then stops

**Comment by taye** [comment]
This is most likely the same problem in #457. Updating to `v1.2.8` is the solution.

**Comment by inkbleed** [comment]
Hi Taye,

Thanks a lot for the response.

For anyone else that needs it, while the 1.2.8 links aren't available from
the download page, you can grab there from here:
http://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.8/interact.min.js

I'll check this and confirm if resolved the issue. Thanks!

**Comment by abrbhat** [comment]
Hi Taye,
Yeah, updating to 1.2.8 resolved the issue. Thanks a lot!

As a side note, you are awesome! The quality of code and documentation is just top-notch. Kudos for the great work!

**Comment by inkbleed** [comment]
Thanks Taye for your help, this also resolved the issue for us :) Really appreciate it.
