### ISSUE TITLE
Any way to make an element only resizable from a corner?

### ISSUE THREAD

**Issue by Undust4able** [taye/interact.js#467]
Hey! Didn't really knew where to post this. Just looked into your library.

I'm making, say, a specific editor where you can only use three objects: image, text, or a button. All three can be moved and resized. Is there a way to make  them have a specific "corner", so you can only resize them from given corner?

Like this: 
![image](https://cloud.githubusercontent.com/assets/5834845/21468861/b4de25d0-ca3c-11e6-9193-66d0b4e96bc3.png)

**Comment by mikekloeden** [comment]
Use the resizable [edges](http://interactjs.io/docs/#resize-edges) property.

`interact(element).resizable({
    edges: {
        right: '.item__resizer',
        bottom: '.item__resizer'
    }
});`

Remember that the resize handle must be a child of the intractable you work with.

**Comment by MagnumDopus** [comment]
This has an issue, in that if you set a single element to two edges, e.g. right and bottom, only the first defined edge gets restricted if used in conjunction with a restricted space.
