### ISSUE TITLE
Cannot drag using drawing pad/pencil after updating from v1.2.6 to v1.3.0

### ISSUE THREAD

**Issue by chaozi712** [taye/interact.js#470]
Dear @taye ,

It appears to be an issue when using a drawing pad/pencil to drag elements under v1.3.0 (unstable branch), the drag does not happen. However, using the mouse is still OK. 

The OS is OSX, and Browser is Chrome 55+. Probably it's hard to test this one without a drawing pad/pencil. But it is working in v1.2.6 so it might have something to do with the #457 pointer events I think as before the switch over, it is working.

**Comment by taye** [comment]
#457 has been resolved. Is your issue sorted out now?

**Comment by taye** [comment]
You may also need set CSS `touch-action: none` on the target elements. See https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md.

**Comment by chaozi712** [comment]
Hi there, 

Sorry for the late reply, since its reported by user and we don't have a drawing pad to test the unstable branch again. We have reverted back to the official release which seems to be working again. 

Since we cannot test it I might just close the issue for now and when we get a chance to test with an actual drawing device and found the issue, we will open a ticket again :)

Thanks for the info.
