### ISSUE TITLE
[maybe expected?] onDrop won't fire if parent div uses flexbox

### ISSUE THREAD

**Issue by valgaze** [taye/interact.js#474]
Just started exploring this incredible library-- found some interesting behavior w/ drag & drop but not sure if this is behaving as expected.

Here's an example of this behavior (taken from demo 2 on **[main demo page](http://interactjs.io/)**): https://jsfiddle.net/valgaze/775zxxrk/

It appears that if a "draggable" feature is a child of a div with ```display:flex``` the onDrop callback never fires:
![interact](https://cloud.githubusercontent.com/assets/1396559/21820599/374881ba-d725-11e6-8216-ac951f99f417.gif)

If no flex container, the behavior is as expected
![works](https://cloud.githubusercontent.com/assets/1396559/21820701/a4e567f6-d725-11e6-968f-95f2a15be592.gif)

**Comment by taye** [comment]
It doesn't drop because you use `restriction: 'parent'` and in the demo with `display: flex`, the draggable and dropzone have different parent elements.
