### ISSUE TITLE
Snapping draggables to each other's edges

### ISSUE THREAD

**Issue by adiron** [taye/interact.js#475]
Hi there

I'm working with interact.js on a project. I found out that missing from the documentation (and maybe interact.js altogether?) is snapping objects not to a grid or a set of static points/rects, but relative to each other.

So firstly I think that it would be great if we had this option in the library itself. Secondly, I wonder if there's some solution that I can use in the meantime that is known to work?

**Comment by s-light** [comment]
Hi adiron, i just found this library. 
for my use case some similar snap-together feature would be cool - but i think -from reading the examples - this lib can't do this - during a move of an element it doesn't know where the other elements are?!
i currently have no alternative solution but will let you know if i find something.

**Comment by mwkling** [comment]
I've been working on a simple game that basically does this.  In the game there are various number tiles that can be dragged around and 'snapped' together to concatenate numbers.  To do this, the onend function for each draggable recalculates all the new snap targets (each time you finish dragging a tile).  If you want to look at the code, see the resetAllNumSnaps function in https://github.com/mwkling/make-n/blob/master/scripts/game.js
