### ISSUE TITLE
Doesn't work with the chrome device toolbar open

### ISSUE THREAD

**Issue by Michelemassari** [taye/interact.js#476]
Hey, thanks for this great library.
Unfortunately when the Chrome device toolbar is open, the drag and drop doesn't work.

Do you know why this happens?

**Steps to reproduce:**
- Open the Chrome inspector
- Click on the Device Icon (⌘ ⇧ M)
- Try to move draggable items around

**Comment by wakatanka** [comment]
Just tested on Mac OS X 10.11.6, Chrome 55.0.28 and device toolbar open (simulating iPad or iPhone) it works flawless.

**Comment by taye** [comment]
Duplicate of #472.
