### ISSUE TITLE
making getSwipe() configurable?

### ISSUE THREAD

**Issue by boynet** [taye/interact.js#478]
right now the condition for determining if swipe is:
`(interaction.prevEvent.speed < 600 || this.timeStamp - interaction.prevEvent.timeStamp > 150)`

is there an option to make this hard values into config?

**Comment by taye** [comment]
What are you using the swipe info for?

**Comment by boynet** [comment]
sorry I cant remember why i wanted it, I guess I tested it in mobile and found out its need too much of a move to be considered a swipe
