### ISSUE TITLE
Can't get basic demo to work on Windows 10 tablet

### ISSUE THREAD

**Issue by lordelph** [taye/interact.js#479]
If I view the basic dragging demo on http://interactjs.io/ using a Windows 10 tablet, I can drag the blocks easily with a touch.

If I extract the demo into a standalone HTML file, the blocks don't move with a touch. If I *hold*, I can move the blocks, but only around 16px or so, any further and the operation stops.

Here's the source I'm testing this with, lifted pretty much verbatim from the interactjs.io website:

https://gist.github.com/lordelph/4400148786b1fbd729d7de76f1eaf2e0

I've tried to spot differences between this code fragment and the demo, and not found anything obvious. 

Pointers gratefully received...

**Comment by lordelph** [comment]
Solved by looking at the examples in the repo - the draggable elements needed this CSS

```
-ms-touch-action: none;
touch-action: none;
```

**Comment by rico-ocepek** [comment]
Either this or a event.preventDefault() in your move callback function.
Seems more appropriate to me as I don't think the touch-action property should be a CSS feature.
