### ISSUE TITLE
Multitouch & multiple gestures on canvas possible?

### ISSUE THREAD

**Issue by s-light** [taye/interact.js#480]
Its a great library. I have managed to create an example combining interact.js and paper.js:
https://github.com/s-light/paper.js_tests/blob/master/js/multitouch.js
live view: https://cdn.rawgit.com/s-light/paper.js_tests/bb64d7628fa0c273f2e0b1ad52860a48acbbe433/multitouch.html

it also worked to switch from 'drag' to 'gesture' in my 'down' handler for the manualStart.
but i don't know how to get both things activated this way.
my 'start handler' looks like this:
```
    .on('down', function (event) {
        var interaction = event.interaction;
        var hit_item = getItemAtPoint(event.clientX, event.clientY);
        if (hit_item) {
            if (!interaction.interacting()) {
                interaction.start(
                    { name: 'drag' },
                    // { name: 'gesture' },
                    event.interactable,
                    hit_item
                 );
            }
        }
    })`
```
is it possible to activate both things? the lib as itself handles it nicely... (if i dont use the manualStart option..)

hope the way i have tried to make this work is the correct for the lib. please give me feedback! :-)

**Comment by taye** [comment]
2 pointers must be down before a gesture can start.

```javascript
if (hit_item) {
  if (interaction.interacting()) {
    // dragging before; end the drag while the first pointer is down
    interaction.end();
    // a new gesture can start now with the first (dragging) pointer and the current pointer
    interaction.start({ name: 'gesture', ... });
  }
  else {
    // first pointer goes down, start a drag
    interaction.start({ name: 'drag', ... });
  }
}
```

**Comment by s-light** [comment]
i first had to update my used interact.js - i used the download version 1.2.6 - there the end funciton is not available. now i have the current git master compiled with npm - that resulted in 1.3.0

i understand the idea - but it did not work for me - i get interaction.interacting() false for every down event:
(console log with Firefox WebIDE USB remote debugging)
```
40.219 down handl
40.242   event.interaction.interacting() false
40.321   hit_item.name rect1
40.370 down handl
40.376   event.interaction.interacting() false
40.417   hit_item.name rect1
41.392 onUpHandler:
41.400   event.target.name rect1
41.407 onUpHandler:
41.411   event.target.name rect1
```
https://github.com/s-light/paper.js_tests/blob/2f5aa44bcc1ba135138281594a0b7ea5bbc7222a/js/multitouch.js#L169

i have tried to search and understand how interaction.interacting() (or the internal this._interacting) is handled in the source - but could not find a place where it gets set to true?!
can you explain how it is designed to work? i would like to understand this... :-)

could this 'every-time false' have to do with my modification of the `event.currentTarget` attribute?

**Comment by taye** [comment]
I get the problem now. Sorry for the delayed response. interact.js assigns the second pointer to a new interaction because the first one is busy, so you can't start a gesture because there will be multiple interactions with one pointer each. You would have to remove the pointers from the new interaction and give it to the existing one. To do this you should store the first interaction somewhere, for example as `hit_item._interaction` and remove it on drag and gesture end. Then on the down event you'll have access to the existing drag interaction and the new, idle one.

```javascript
if (hit_item && hit_item.interaction && hit_item.interaction.interacting()) {
  // transfer the pointer from the idle interaction to the active one
  event.interaction.removePointer(event);
  hit_item.interaction.updatePointer(event);

  // restart action
  hit_item.interaction.end();
  hit_item.interaction.start(...);
}
```

**Comment by taye** [comment]
I plan to add a way to switch interactions and targets more easily.

**Comment by taye** [comment]
> I plan to add a way to switch interactions and targets more easily.

This won't happen very soon so I'm closing the issue and might reopen it much later.
