### ISSUE TITLE
Restrict resizing of elements

### ISSUE THREAD

**Issue by AlecRust** [taye/interact.js#482]
I see there is restriction documentation on confining an element to a certain area:

http://interactjs.io/docs/restriction/#restrict

However I can't find any mention of restricting the size of an element e.g. setting a minimum size element can be scaled to?

**Comment by AlecRust** [comment]
Looks like this may be added in https://github.com/taye/interact.js/pull/455.

**Comment by taye** [comment]
Yes, it's planned for the next release. I don't know when that will be but I hope to get it done within the next 2 months.

Closing as a duplicate of #84.

**Comment by jithinkradhakrishnan** [comment]
Can we restrict size of each item after we initiated interact resize
