### ISSUE TITLE
Snap the edges

### ISSUE THREAD

**Issue by NewInGit** [taye/interact.js#483]
Hi, thank you for interact.js , great job,
I have a question, I know I can use relativePoints, and set the snap point of an element to top-left corner or the center or any other points, but I need to snap the four edges of the rectangle, not some points of it. Is it possible?

I used
```
targets: [
      { x: 100, range: 50 },
      { y: 100, range: 50 },
    ],
relativePoints: [
      { x: 0  , y: 0   } ,
      { x: 1  , y: 0   } ,
      { x: 0  , y: 1  } ,
      { x: 1  , y: 1   },
    ]
```
It works, But when I bring the element near a snap line, it jumps to snap, but also has an unintentional movement in every four direction.

Here is the [fiddle](https://jsfiddle.net/coolesterman/n5auybzj/).

**Comment by taye** [comment]
There can only be one snap target, so it's not possible to snap both `x` and `y` when they're set independently in separate targets. You can get around this by adding a third target which snaps both `x` and `y` **before** the other two in the `targets` array.

```javascript
targets: [
  // order here is important
  { x: 100, y: 100, range: 20 },
  { x: 100, range: 20 },
  { y: 100, range: 20 },
],
```

https://jsfiddle.net/n5auybzj/13/

**Comment by NewInGit** [comment]
ooh! didn't know about the order. Thank you TAYE.
Sorry to bother, But What about my other question, "snapping the edges of a rectangle not some points of it?"
Instead of:
```
relativePoints: [
      { x: 0  , y: 0   } ,
      { x: 1  , y: 0   } ,
      { x: 0  , y: 1  } ,
      { x: 1  , y: 1   },
    ]
```
I need something like this:
```
relativePoints: [
      the four edges
    ]
```
![untitled-1](https://cloud.githubusercontent.com/assets/24973616/22401748/61d42492-e5f4-11e6-85f5-8c08326aac4b.png)

**Comment by taye** [comment]
I'm closing this issue, but leaving it in the roadmap so I don't forget about it.
