### ISSUE TITLE
Handle drag/resize

### ISSUE THREAD

**Issue by nathan30** [taye/interact.js#490]
Hi,

I try to understand the actionChecker behavior from here : http://interactjs.io/api/#Interactable.actionChecker

But I didn't figure it out how to makes it works. So here is my HTML : 

`<div class="dragHandle" data-x="0" data-y="0">
        <i class="fa fa-circle-thin" aria-hidden="true"></i>
    </div>
    <div id="containerYoutube"> 
        <?php
            include 'api/youtube.php';
        ?>
    </div>`

I want to use the .dragHandle to move the #containerYoutube, how can I do that ? I try this but didn't work...

`interact('#containerYoutube')
        .resizable(true)
        .draggable(true)
        .actionChecker(function (pointer, event, action, interactable, element, interaction) {

            if (interact.matchesSelector(event.target, '.dragHandle')) {
                // force drag with handle target
                action.name = drag;
            }
            else {
                // resize from the top and right edges
                action.name  = 'resize';
                action.edges = { top: true, right: true };
            }

            return action;
        });`

Thanks in advance

**Comment by taye** [comment]
If `<?php include 'api/youtube.php'; ?>` makes an iframe, you'll have to use some element to cover the iframe so that your page gets the pointer events instead of the youtube page. There's no other way for you to listen to mouse or touch events over iframes from different origins.
