### ISSUE TITLE
Dragging issue on new versions of Chrome and Touch devices

### ISSUE THREAD

**Issue by ElNinjaGaiden** [taye/interact.js#492]
I'm having a problem dragging elements on Chrome (Touch Mode) and Android web views. I found the problem 2 weeks ago on an hybrid mobile app I have on production. Dragging was working just fine but when my cel phone updated its web view 2 weeks ago dragging stopped to work normally. Now elements just drag a few pixels, then return to their initial position and sometimes it seems their loose the notion of its initial position and gets roughly moved to some other position.

I have the suspicious (I could be 100% wrong) [passive event listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners) released some versions of Chrome ago could be related to this issue but again, this is just a suspicious.

At the very beginning I thought the html5 framework I'm using on my app could also be "generating noise" into this issue but then I created a dummy/demo cordova app (without the framework) and I was able to reproduce the error. Beyond than that, I don't even need the cordova project to replicate this issue.

I have the dummy/demo app [here](https://github.com/ElNinjaGaiden/CordovaDrag). It's is just a copy/paste of your very first dragging example on your [home page](http://interactjs.io/). You just need to serve a web server on the `www` folder, run the app on Chrome, open Chrome Dev Tools and run the app on "touch mode" the replicate the problem.

Actually if you run the app on "non touch mode" it works fine. The problem is if you run the app on "touch mode".

I created a .gif to show you this steps and also to show the issue. You can find it [here](http://res.cloudinary.com/yoinbol-dgarcia/image/upload/v1486438126/ddBug_twrjco.gif)

### Expected behavior
Dragging works smoothly on touch devices

### Actual behavior
Draggin doesn't work as it used to on touch devices using latest versions of Chrome/Android web views

### System configuration
**interact.js 1.2.5 and superior**:
**Google Chrome 55.0.2883.95 and superior**:
**Mac OS X El Capitan 10.11.6 and Android 6.0.1**:

Any help will be very appreciated because again, I have an app on production which already use your amazing library to support drag and drop features.

**Comment by Joeao** [comment]
I actually detected this issue on my app yesterday, researched and found the same thing you did, but somehow fixed it today when updating from interact 1.2.6 to 1.2.8. I didn't change anything else.

**Comment by Joeao** [comment]
This [issue](https://github.com/taye/interact.js/issues/457) is probably related. Looks like you need to update to the latest version as it was fixed between 1.2.7 and 1.2.8, if you've tested on 1.2.8 then this issue is still valid.

**Comment by ElNinjaGaiden** [comment]
@joeao where can I get 1.2.8? The "official" version from the site is 1.2.6

**Comment by ElNinjaGaiden** [comment]
@joeae nevermind, I got it. Thanks, it seems to work!
