### ISSUE TITLE
Resize Only Starts After Dragging Past Width/Height When Using manualStart: true 

### ISSUE THREAD

**Issue by sqwk** [taye/interact.js#494]
When using `manualStart: true' on a resizable, the actual resize only starts after dragging past the initial width or height.

![untitled mov](https://cloud.githubusercontent.com/assets/1353312/22829417/d004a6e6-efa2-11e6-938e-28a5d63d3a93.gif)

I am starting the interaction like this:

    interaction.start({
        name: 'resize',
        edges: { left: true, right: true, bottom: true, top: true },
    }, event.interactable, event.currentTarget);

**Comment by taye** [comment]
You should check which edges the pointer is over and start with only those two to `true`.

**Comment by taye** [comment]
For further clarifications:

`edges` in the `interactable.resizable` options sets which edges the autoStart can decide to resize with. If you're using the `interaction.start` method directly, you'll need to determine which single edge or pair of edges you're starting with, then set those to true in the edges property of the action.
