### ISSUE TITLE
Cursor stuck on "move" after clicking a draggable

### ISSUE THREAD

**Issue by alexlitty** [taye/interact.js#497]
Looks like this was fixed in [this issue from last year,](https://github.com/taye/interact.js/issues/364) but I'm still able to reproduce it on my Debian box in:

* Chrome 51.0.2704.106
* Firefox 45.2.0

Behavior is identical to the original issue.

I'm also not seeing a documented way to disable the cursor styles, despite the readme implying otherwise.

**Comment by alexlitty** [comment]
Found the [generated docs about cursorStyle.](https://rawgit.com/taye/interact.js/unstable/dist/docs/index.html#Interactable.styleCursor)

For anyone else trying to workaround the issue, you can use `styleCursor` to disable cursor styles applied by interact.js:

`interact('.draggable', { /* ... */ }).cursorStyle(false);`

**Comment by koutsenko** [comment]
I confirm that problem. Chrome 57, just added a DOM breakpoint to html node. Interactions starting while mouse move over the some elements that can be draggable. It isn't triggered by my code...

**Comment by koutsenko** [comment]
Style workaround doesn't solve the problem, just masking it

**Comment by taye** [comment]
@koutsenko please make a demo.

**Comment by alexlitty** [comment]
@taye [Here's a reproduction](https://jsfiddle.net/efuoym1r/) if that's what you're looking for. Left-click on the draggable, release left-click without dragging, then move your mouse to behold.

Same behavior seems to occur with any combination of `draggable()` options, including no options.

**Comment by bkniffler** [comment]
I've had the same experience where a modal is shown on double click of an item, and since the mouse leave is not triggered, the move cursor will get stuck.

**Comment by taye** [comment]
This is fixed in `v1.3.0-alpha.1`. I don't want to put time into also fixing it for the `1.2` version. https://jsfiddle.net/efuoym1r/3/

**Comment by alexlitty** [comment]
@taye Unfortunately, I'm seeing no change in behavior.

Perhaps of importance: The problem in this fiddle is only visible when I move my mouse to the right of the picture, I can't reproduce it when I go above or below the picture vertically.

**Comment by jeroencornelissen** [comment]
@alexlitty That's because the .draggable div stretches over the complete width of the page.
Interact is applied to the .draggable div, not the image.

I've put a background-color on the div to make it more clear: 
https://jsfiddle.net/7v0h236w/

**Comment by alexlitty** [comment]
@jeroencornelissen ah, indeed!

I'll go back to web dev school now.
