### ISSUE TITLE
Resize a item rotated

### ISSUE THREAD

**Issue by mamzellejuu** [taye/interact.js#499]
Is it possible to resize (with width) a item rotate?

### Expected behavior
A item rotated will be resized by its corner

### Actual behavior
The resize point is not its corner actually when the item is rotated with transform.

### System configuration
**interact.js version**: Version 1.2.6
**Browser name and version**: Chrome
**Operating System**: Mac os X

**Comment by taye** [comment]
Duplicate of #137
