### ISSUE TITLE
Pinch doesnt Work

### ISSUE THREAD

**Issue by liorsharabi** [taye/interact.js#500]
hi

i'm doing exactly what the documentation says and still the onstart, onend, onmove events aren't triggering.
what am i doing wrong? 
JS:
`     let gestureArea = document.getElementById('gesture-area'),
            scaleElement = document.getElementById('scale-element');
        this.interactable = interact(gestureArea);

        this.interactable.gesturable({
            onstart: function (event) {
                window.alert("start");
            },
            onmove: function (event) {
                window.alert("move");
                scaleElement.setAttribute('width', (scaleElement.clientWidth * (1 + event.ds)).toString());
            },
            onend: function (event) {
                window.alert("end");
            }
        })`

html :
```
<div id="gesture-area">
            <div id="scale-element" style={{ height: 120, width: 120, backgroundColor: "blue" }} >lior</div>
        </div>
```

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net?
