### ISSUE TITLE
After a resize, cursor doesn't change anymore until mouse leaves interactable

### ISSUE THREAD

**Issue by no-chris** [taye/interact.js#501]
Hello,
Please find below a small bug report for this very cool library :-)
Thanks !

## Observed

- go to http://interactjs.io/
- scroll down to the **Resizing** demo
- hover the right edge of the blue box on the right: mouse cursor changes into a resize handle
- resize the blue box. When releasing mouse button, be careful not to move the mouse anymore
- cursor is now an arrow
- move the mouse **without leaving the interactable area** : get close to other edges, go to the center, etc. the mouse stays an arrow
- move the mouse out of the interactable
- hover again the interactable : the mouse cursor now changes as expected

This has been observed on latest Chrome & FF

## Expected
- After resizing, if the mouse is still on the edge of the interactable, mouse cursor should be an resize handle.
- After resizing, if I move the mouse on the interactable, mouse cursor should change according to the available action : dragging at the center, resize on the edges.

**Comment by taye** [comment]
This is fixed in `v1.3.0-alpha.0`.
