### ISSUE TITLE
Stopping interaction will throw errors

### ISSUE THREAD

**Issue by arggh** [taye/interact.js#503]
First, thank you for an amazing library!

I have a situation where I need to stop interaction in the `onstart`-event due to a competing gesture that has to lock down all other touch events in the app.

Even though it has the desired effect, calling `interaction.stop()` in the Draggable's `onstart`-event throws errors, which are currently filling the error logs of my app.

```
...
    onstart: function(event) {
    	event.interaction.stop();
    },
...
```

Reproduction:
https://jsfiddle.net/a8j9bta5/

Is this the appropriate way to stop the interaction? I couldn't find anything else in the API for the task.

### Expected behavior
Nothing should happen.

### Actual behavior
Dragging doesn't start (as it should), **but erros get thrown.** Seems that depending on browsers or other external variables the error thrown is a bit different.

```
Uncaught TypeError: Cannot read property 'options' of null
    at Ma (interact.min.js:9)
    at xa.setModifications (interact.min.js:52)
    at xa.pointerMove (interact.min.js:61)
    at HTMLDocument.<anonymous> (interact.min.js:16)
```

### System configuration
**interact.js version**: v1.2.8
**Browser name and version**: Chrome 56.0.2924.87, Safari 10.0, basically all browsers
**Operating System**: Os X 10.11.6, Android 5, iOS 10 ...

**Comment by arggh** [comment]
This seems to be fixed in the [unstable build](https://github.com/taye/interact.js/commit/a907dc1ce4494b3468d52e4d5383e8dbfeeea935).

**Comment by nikparo** [comment]
I've noticed this as well, since I only want to drag if the if `event.button == 0`. May I also suggest stopping the interaction if you `return false;` from a start event?

**Comment by taye** [comment]
Use `interaction.end()` instead.

**Comment by arggh** [comment]
Using `interaction.end()` will call the `end`-event handler, in my case that means writing unnecessary extra code to handle this situation.

I solved this a month ago by doing just that, but I wish I could just call `interaction.stop()` from the `start` handler and be done with it. The API for that exists, but using it causes errors.

Is `interaction.stop()` going to be deprecated?

**Comment by taye** [comment]
@nikparo from `v1.3.0-alpha.0` onwards, actions are started by default only with the left mouse button (54ebdc3).

@arggh sorry, I overlooked where the error was actually happening. I'm working on it now.

**Comment by arggh** [comment]
@taye I could still make Interact `1.4.1` throw when attempting to call `interaction.stop()` in `onstart`. Is there any new (undocumented?) way to prevent the interaction from even beginning, and thus preventing `onmove` and `onend` getting called?

```js
interact(el)
      .draggable({
        onstart: (event) => {
            event.interaction.stop();
        },
        onmove: () => {},
        onend: () => {}
      });
```

```
/node_modules/interactjs/dist/interact.js:2058 Uncaught TypeError: Cannot read property 'options' of null
    at ___default_53 (/node_modules/interactjs/dist/interact.js:2058)
    at new InteractEvent (/node_modules/interactjs/dist/interact.js:2146)
    at Interaction._createPreparedEvent (/node_modules/interactjs/dist/interact.js:1022)
    at Interaction._doPhase (/node_modules/interactjs/dist/interact.js:1047)
    at Interaction.move (/node_modules/interactjs/dist/interact.js:830)
    at Interaction.pointerMove (/node_modules/interactjs/dist/interact.js:792)
    at HTMLDocument.eval (/node_modules/interactjs/dist/interact.js:501)
```

**Comment by nikparo** [comment]
Can't remember where I got it from or whether it's documented or not, but I'm calling `interact.stop()` from a `dragstart` handler and it has been working just fine.
