### ISSUE TITLE
Cursor 'Move' is applied to the entire html after the Interactable element is removed from the DOM

### ISSUE THREAD

**Issue by Jashtezakonshem** [taye/interact.js#509]
Hi guys,
I would like to highlight this unexpected behaviour. Although I can't paste the code ( I'm developing for an enterprise), I'll try to be more eloquent as possible as I can.
the div with class 'fees' is the interactable one. it is inside a "ko - if" which conditionally create/remove element from DOM. 
When I first create the .fees Element, everything works fine.
When I close the div, I remove from the dom the .fees and the cursor move style is propagated somehow to the html.
I've tried some api to Obviate the problem, like Interactable.unset() just before removing from the DOM. 
Rightnow I fixed it with Jquery, forcing $('html').css('cursor','auto') and everything is working but I don't think this is an elegant solution.
Any tips? thank you in advance for your time

**Comment by Jashtezakonshem** [comment]
this a gif which can describe better the problem:
[https://giphy.com/gifs/xUPGctrmGXWvwpC5QQ](url)

**Comment by bkniffler** [comment]
Isn't this the same issue like https://github.com/taye/interact.js/issues/509
?

**Comment by Jashtezakonshem** [comment]
@bkniffler you're right, my bad.
