### ISSUE TITLE
Chrome warning: passive event handlers

### ISSUE THREAD

**Issue by ssilve1989** [taye/interact.js#512]
The latest versions of Chrome give the following warning

```Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.```
for the events `touchmove` and `touchstart`

**Comment by ArminMueller** [comment]
Chrome has now passive mode as default mode for all events. Now the preventDefault is no longer usable. 
Effect: scrolling is not disabled during drag and drop

**Comment by koutsenko** [comment]
@ArminMueller now how-to get **_only one_** event fired on child element click?
Case: both parent and child elements has ontap listeners.
Any preventDefault replacements?

**Comment by ArminMueller** [comment]
I add Touch-action: none to the parent element when activating the drag and drop

**Comment by koutsenko** [comment]
Like an workaround, but thanks...
What's happening in the browsers world?! :(
