### ISSUE TITLE
onMove triggers after onEnd

### ISSUE THREAD

**Issue by liorsharabi** [taye/interact.js#515]
hi

when you create a draggable object you can put draggableOptions that have "onStart" , "onMove" and onEnd" events.
i assume that the "onEnd" event suppose to trigger when the user drop the draggable element and the dragging action ended.
when im droping the draggable element while moving the mouse it calls, after the "onEnd" event, to "onMove".

it causes me some problems because, again, i assume that the "onEnd" event suppose to trigger when the dragging action ended.

is my assuming is wrong? or is it a bug?

thx

**Comment by taye** [comment]
That sounds like a bug. Which version of interact.js are you using? A small demo on jsfiddle would be very helpful.
