### ISSUE TITLE
e[qe] is not a function

### ISSUE THREAD

**Issue by Tlapi** [taye/interact.js#520]
Hi,

we are getting lots of "e[qe] is not a function" from our users.

on this line:
https://github.com/taye/interact.js/blob/48b5a09270e6dfac99cc6b29b94d30383e2537a6/src/utils/domUtils.js#L69

Any idea what might be a problem?

Thank you.

**Comment by Mike-Benoit** [comment]
We are seeing a ton of these too, may be related to the recent Chrome v59 release as that is the only browser that is triggering them.

**Comment by Tlapi** [comment]
From our log, i can see that it's not Chrome related. 

Firefox, Vivaldi, IE also on the list.

**Comment by catbadger** [comment]
We're seeing "element[prefixedMatchesSelector] is not a function" in a related capacity and same affected browsers.

**Comment by mrtwebdesign** [comment]
Same line with a slight variant "e[Gt] is not a function" on 1.2.8 from CDN

**Comment by jeroencornelissen** [comment]
We also get this error, "t[Xe] is not a function".
@taye  when will the fix be released?

**Comment by taye** [comment]
@jeroencornelissen yes, it should be solved in v1.2.9
