### ISSUE TITLE
Differences between minified and development dist versions in v1.2.8.

### ISSUE THREAD

**Issue by gonaumov** [taye/interact.js#524]
In bower version in unminified dist file there is v1.2.6 instead v1.2.8 as user expect. Perhaps it is just a typo. 
### Expected behavior
There must be v1.2.8 in dist/interact.js

### Actual behavior
There is v1.2.6 

### System configuration
Here I will describe how to reproduce it. 

- bower install interactjs --save
-  (head -n3 bower_components/interactjs/interact.js; head -n3 bower_components/interactjs/dist/interact.js; head -n1 bower_components/interactjs/dist/interact.min.js) | cat
- The result is:
```
/**
 * interact.js v1.2.8
 *
/**
 * interact.js v1.2.6
 *
/* interact.js v1.2.8 | https://raw.github.com/taye/interact.js/master/LICENSE */
```

**Comment by taye** [comment]
Yes, this is a typo. The rest of the contents should be up to date. The same mistake is also published to npm. Thanks for reporting, but there's not much I can do about this particular version. The next versions will have the numbers bumped by a script so this shouldn't happen again.

By the way, I recommend using `v1.3.0-alpha`. You can get it with `bower install interactjs@next`. It has many important bug fixes and though the documentation isn't complete, it's mostly backwards compatible and I'll try to stay active on https://gitter.im/taye/interact.js if you have questions.
