### ISSUE TITLE
TypeError: element[prefixedMatchesSelector] is not a function

### ISSUE THREAD

**Issue by Mike-Benoit** [taye/interact.js#525]
It seems in the last couple weeks we started getting thousands of the following JS errors, but they are only happening on Chrome v59.

Function called stacks: TypeError: element[prefixedMatchesSelector] is not a function
    at matchesSelector (/framework/interact.min.js:5903:42)
    at pushCurMatches (/framework/interact.min.js:1367:9)
    at Array.interactables.forEachSelector (/framework/interact.min.js:3874:14)
    at Interaction.pointerOver (/framework/interact.min.js:1381:19)
    at HTMLDocument.<anonymous> (/framework/interact.min.js:3357:24)

We haven't been able to reproduce the errors ourselves yet, but thought it was strange that they just started popping up all of sudden. 

The above is on our publicly facing website, we have some private facing installations that haven't been changed since January that started seeing the same errors at the end of March from Chrome v59 but mostly from Firefox v44+.

Here is stack trace from Firefox:
TypeError: element[prefixedMatchesSelector] is not a function in /framework/interact.min.js line 5894 
Function called stacks: matchesSelector@/framework/interact.min.js:5894:10
pushCurMatches@/framework/interact.min.js:1358:9
interactables.forEachSelector@/framework/interact.min.js:3865:14
pointerOver@/framework/interact.min.js:1372:5
doOnInteractions/<@/framework/interact.min.js:3348:5

Any ideas what might be happening here? We are using Interact v1.2.6

**Comment by mrtrandinhvn** [comment]
We're having similar problem. It seems it only occurs when you move the cursor from Chrome Developer Tool's console in the document.body and move the cursor back to the Console.

**Comment by anrananran** [comment]
yes, strange error
