### ISSUE TITLE
1.3.0 alpha 2 tap on iOS called twice with another event handler.

### ISSUE THREAD

**Issue by timothyallan** [taye/interact.js#526]
Heya, I have an element which has an onClick handler, and has a tap handler via interact. Interact fires 2 "tap" events on iOS, but on desktop Chrome, it only fires once, as I'd assume it should. JSFiddle created.

### Expected behavior
Tell us what should happen
Should get 1 tap notification and 1 click notification

### Actual behavior
Get 2 tap notifications and 1 click notification

### System configuration
1.3.0 alpha 2

iOS 10 Safari

https://jsfiddle.net/k2t7h13b/6/

**Comment by taye** [comment]
The alert messes things up at https://github.com/taye/interact.js/blob/v1.3.0-alpha.3/src/Interaction.js#L400-L406.

Either don't use alerts or call `interact(el).preventDefault('always')`.

https://jsfiddle.net/k2t7h13b/29/
