### ISSUE TITLE
Interaction is lost when changing a target DOM

### ISSUE THREAD

**Issue by Kamil1190** [taye/interact.js#528]
Hello every one. I have a problem with changing an target DOM to a new one during drag interaction, I want to do this when the orginal item is in the dragzone. 
So i try call `interaction.start({name: 'drag' }, event.interactable, newElement);` in "ondragenter" event. But this is not working and the interaction is lost. 

Any ideas how to do it?

Here is a simple example of the problem: https://jsfiddle.net/kamil1190/ygh0Lvx3/

**Comment by taye** [comment]
`interation.start()` only works if it's not currently in the middle of an action. You need to call `interaction.end()` or `interaction.stop()` first at `//CHANGE VIEW`.
