### ISSUE TITLE
Embedded dropzones with separate interact instances producing bizarre event firing

### ISSUE THREAD

**Issue by brentkelly** [taye/interact.js#529]
I am trying to implement a drag drop interface that allows one element to be dragged over another wrapper element, which will then dynamically display multiple appropriate dropzones (embedded as dom elements with the wrapper) for the dragged item.

An example of the first part of this setup (dynamically displaying the dropzones) can be seen at this codepen: https://codepen.io/brentkelly/pen/JJOKrw.

As shown above, this is working nicely when making using of the `interact.dynamicDrop(true);` setting with `ondragenter` and `ondragleave` events firing as expected.

However, if you try to take it to the next stage of making the embedded dropzones 'droppable' with their own set of `ondrag*` and `ondrop` events, the wheels seem to fall off. I create a new `interact` instance for the dropzone, and call the `dropzone` method, defining appropriate methods for the various events.

As you will see in the following codepen, the `dragenter` and `dragleave` events are fired off like crazy for both the inner and outer dropzones.  This is despite having set `dynamicDrop` to `true`. This is shown in this codepen here: https://codepen.io/brentkelly/pen/dRZXOr.

These pens are a simplified implementation to demonstrate the problem. In my project the problem presents itself slightly differently in that it appears to be firing off the `dragleave` event on the outer dropzone when leaving the inner dropzone.

One workaround I will try is to have just 1 dropzone on the entire element and then analyze the event target to determine which element's event I should actually fire off. But (assuming it works) this does seem like a bit of a hack to get around a flaw in the code.

### Expected behavior
The `drageenter` and `dragleave` events should only fire when dragging across the border of the appropriate element. The `dragleave` event should definitely not fire for the outer element when dragging out of the inner element - only when crossing the border of the outer element.

### Actual behavior
The `dragenter` and `dragleave` events fire off seemingly randomly when dragging across the inner dropzone.

### System configuration
**interact.js version**: 1.2.6
**jQuery**: 3.2.1
**Browser name and version**: Chrome 58.0.3029.110 (64-bit)
**Operating System**: Windows 10

**Comment by brentkelly** [comment]
Tried the workaround by calling interact's dropzone on both elements at the same time. Still doesn't support that behavior? Can you think of any way to achieve what I'm after. One approach could be to check on the `dragleave` method if we are still hovered over the element & if not, exit out of the dragleave. A bit of a hack tho?

**Comment by taye** [comment]
Sorry for such a late reply. The problem seems to be that you hide the `#inner1` dropzone when leaving `#outer`. After the `dragmove` on the draggable, a `dragleave` and then `dragenter` are fired on the dropzones.

Some solutions would be:

 - In the leave event listener, check `event.dragEvent.dragEnter`to see if the drag is entering the `#inner1` dropzone and decide wether or not to hide the `#outer` dropzone.

 - Always hide on `dragleave`, and in a `dragenter` listener, check if the `#inner1` should be shown again. https://codepen.io/anon/pen/jaXVaE?editors=1000
