### ISSUE TITLE
Error with unset(): Unable to get property 'selectors' of undefined or null reference

### ISSUE THREAD

**Issue by tkelly42** [taye/interact.js#530]
I receive the following error when calling unset() on an interactable:

SCRIPT5007: Unable to get property 'selectors' of undefined or null reference
interact.js (5307,1)

the issue appears to be around removing delegated events - the method finds a delegated event "mousedown" that is null and so error when trying to access .selectors

I can currently get round the issue by adding a null check in the delegated event for loop:
```
for (var type in delegatedEvents) {
    var delegated = delegatedEvents[type];
     **if (delegated == null)continue;**
```
The code is part of a frame based player and previously to this there would have been an interactable in existence that did use a mousedown event and that was subsequently unset() successfully.

### Expected behavior
That a call to unset should return succesfully and remove interactables

### Actual behavior
"Unable to get property 'selectors' of undefined or null reference
interact.js (5307,1)"

### System configuration
**interact.js version**:v1.2.8
**Browser name and version**:Chrome 59 and IE Edge
**Operating System**: Windows 64

**Comment by taye** [comment]
Please upgrade to v1.3.1 and and see if the same issue exists.
