### ISSUE TITLE
Events created with fire() do not support stopPropagation()

### ISSUE THREAD

**Issue by derwaldgeist** [taye/interact.js#531]
If you fire an event via fire(), the method stopPropagation() is not supported by the InteractEvent that is handed over to the event handler.

In the source code, I found these lines that seem to support this:

https://github.com/taye/interact.js/blob/stable/interact.js#L3613

But if you ask me, adding methods to a prototype just does not work this way, since you're trying to overwrite the whole prototype instead of adding methods to it. So I guess this is the reason why stopPropagation() is not working. 

### Expected behavior
The event fired by fire() should have a function property stopPropagation()

### Actual behavior
stopPropagation() is not available.

### System configuration
**interact.js version**: 1.2.9
**Browser name and version**: jsdom (running as unit test)
**Operating System**: NodeJS / macOS

**Comment by taye** [comment]
The `fire` method is used to fire objects that are real instances of `InteractEvent`s which should always have a `stopPropagation()` method. If you're using it to fire something that isn't an `InteractEvent`, your event listeners will receive the object that you fired, which doesn't necessarily have the properties that an `InteractEvent` should.

If you're using `npm` and can updgrade to `v1.3.0-alpha`, I recommend that you require/import the `'interactjs/src/InteractEvent'` (https://github.com/taye/interact.js/blob/master/src/InteractEvent.js) module and use that constructor to create your test events.
