### ISSUE TITLE
restrict drag and drop to containing element matched by class selector - not working

### ISSUE THREAD

**Issue by MikiAsh** [taye/interact.js#532]
Here is my configuration where I define ".dndRestrict" as class selector in restrict.restriction
// target elements with the "draggable" class
interact('.resizable-draggable')
  .draggable({
      // enable inertial throwing
      inertia: true,
      // keep the element within the area of it's parent
      restrict: {
          restriction: ".dndRestrict", //<= This is the class selector of the confining element
          endOnly: true,
          elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
      },
      // enable autoScroll
      autoScroll: true,

      // call this function on every dragmove event
      onmove: dragMoveListener,
      // call this function on every dragend event
      onend: function (event) {
          interactionEnd(event);
      }
  })

### Expected behavior
child element should be repositioned within the area of the matched element.
It is working just fine on 1.2.9

### Actual behavior
restriction does not occur at all and child element is allowed to "leave" its container borders.

### System configuration
**interact.js version**:v1.3.0-alpha.3, v1.3.0-alpha.4
**Browser name and version**: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
**Operating System**: Windows 10 Pro 64-bit

**Comment by taye** [comment]
It seems to still be working: https://jsfiddle.net/hn2of2h4/
