### ISSUE TITLE
Interactable nested inside draggable interactable instance throws exception on drag

### ISSUE THREAD

**Issue by kirschre** [taye/interact.js#533]
I'd like to use `draggable` handlers on a parent element, and also have a `tap` handler on one of the parent's children. I've restricted the drag axis to `'x'`, but now drag events in the `'y'` axis starting from the child throw an exception.

reproducer: http://jsfiddle.net/hs2kfe00/

To reproduce the error, start dragging vertically from inside the inner (green) box. Note the exception thrown in the console.

### Expected behavior
Dragging vertically from inside the child element should not throw an exception. In my use case I think I should be able to work around this by having the draggable and tap handlers on the same element, but it complicates the layout a bit.

### Actual behavior
```
Uncaught TypeError: Cannot read property 'name' of null
    at Interaction.pointerMove (interact.js:1853)
    at HTMLDocument.<anonymous> (interact.js:3349)
```

This doesn't seem to directly affect any behaviour that I've noticed - scrolling via vertical drag on touch devices still seems to work, for example. I'm not familiar enough with the code to know if there are other subtle side effects though, so I thought I'd point this out.

### System configuration
**interact.js version**: 1.2.8
**Browser name and version**: chrome 59
**Operating System**: windows 7

**Comment by zippos** [comment]
Hi. I'm getting this issue in 1.2.9. I use 3 nested dropzones like so:
Type 1 dropzone - accepts only type 2 draggable
Type 2 dropzone (which is also draggable) - accepts only type 3 draggable
Type 3 dropzone (wich is also dragable) - accepts only other draggable elements

It looks like a bootstrap grid. Where container is type 1, a row is type 2 and a column is type 3.

I remove and reinit a various element's drag event on each drop in a type 3 dropzone. So if if i have let's say 2 zones of type 3 dropzone and drop an elment in the 1st one, then move it in the 2nd, then move it back to the 1st one, when i try to move it again to the 2nd dropzone, it throws me the error mentioned above.

Any hints on how can i make this work? Thanks
