### ISSUE TITLE
Interact.off() not working with a function.bind

### ISSUE THREAD

**Issue by Addg14** [taye/interact.js#535]
In first place, thanks for your work with interactjs library.

I'm working in a Ionic 2 project and I'm having issues trying to remove a event listener from a interact element but I can't. 

Here's my code:

Event listener setup:
`interact('.element').on('hold', this.rotateElement.bind(this))`

Event listener unbinding:
`interact('.element').off('hold',  this.rotateElement.bind(this))`

When I call the interact.off() method nothing happens, event still active.

Then, each time the page is loaded a new event listener is added to the _iEvents stack. So when the event is fired it runs multiple times (One for each event in _iEvents stack).

Thanks in advance.

**Comment by taye** [comment]
`Function.bind()` returns a new function each time you call it. You would need to call `bind` once, store the result in a variable or object property and use the same function in the call to both `on` and `off`. See https://stackoverflow.com/a/22870717 for more info.
