### ISSUE TITLE
Slow scaling speed for large gesturables

### ISSUE THREAD

**Issue by ksullivan2** [taye/interact.js#537]
No codefiddle; this is reproducible on the pinch zoom demo on the [homepage](interactjs.io).

### Expected behavior
The gesturable scales linearly; a gesture of the same magnitude always changes the element's size by the same amount.

### Actual behavior
The responsiveness of the gesture depends on the size of the gesturable _when the gesture began_. 
Ex: scaling a very large image (>1000px) feels slow and unresponsive; scaling a smaller image feels very responsive, sometimes too much so. The larger the image, the more pronounced the effect is.

### To reproduce:
1) Scale the image on the homepage demo to a large size, notice that it probably only took you a single gesture
2) try to scale the image back down to its original size. notice that it took you many gestures.

It stems from [this code](https://github.com/taye/interact.js/blob/48b5a09270e6dfac99cc6b29b94d30383e2537a6/src/actions/gesture.js#L111), where the scale is set at the initiation of the gesture, not as an absolute.

### System configuration
**interact.js version: **: interact-1.3.0-alpha.4
**Browser name and version**: any (but not Chrome currently, the gesture support is buggy)
**Operating System**: any

**Comment by taye** [comment]
I've introduced another bug that I'll try to fix soon.

**Comment by taye** [comment]
Sorry, I commented on the wrong issue.
