### ISSUE TITLE
"passive: false" option for action-events not working

### ISSUE THREAD

**Issue by Manu-san** [taye/interact.js#538]
### System configuration
**interact.js version**: v1.3.0-alpha.4
**Browser name and version**: Chrome Version 60.0.3112.101 (Official Build) (64-bit)
**Operating System**: Windows 8

### Description

My current use case:
Having a scroll-container with overflow: scroll with a div in it which is larger than the container.
Over the div which acts as an canvas, there are other divs (cards) which should be draggable/resizable.
While dragging some cards, the scroll-container should not scroll.

If I am right, there is no other way as using an active event ({passive: false}) and callling preventDefault(), because I cannot dynamically set touch-action on "dragstart" and the scoll-container should stay scrollable, so it's neither an option to set "touch-action: none" on the canvas-div or the scroll-container.

So I wanted to force active events by setting options to {passive: false}.
The problem is that in the current Version the options-parameter seems to be ignored for action-events:
```javascript
  Interactable.on (eventType, listener, options) {
    if (this._onOffMultiple('on', eventType, listener, options)) {
      return this;
    }

    if (eventType === 'wheel') { eventType = wheelEvent; }

    if (contains(Interactable.eventTypes, eventType)) {
      this.events.on(eventType, listener);
    }
    // delegated event for selector
    else if (is.string(this.target)) {
      events.addDelegate(this.target, this._context, eventType, listener, options);
    }
    else {
      events.add(this.target, eventType, listener, options);
    }

    return this;
  }
...
  Eventable.on (eventType, listener) {
    // if this type of event was never bound
    if (this[eventType]) {
      this[eventType].push(listener);
    }
    else {
      this[eventType] = [listener];
    }
  }
```

Is there any solution to this?
Is it planned to extend the action-events to support non-passive events?

So as an example in this plunk:
[https://plnkr.co/edit/g81ZqmXFwAZXnqeijIEX?p=preview](https://plnkr.co/edit/g81ZqmXFwAZXnqeijIEX?p=preview)

How could it be possible to stay with scrollable container (with touch drag on resize-container) and drag/resize for the "resize me" cards?

Thanks

**Comment by Manu-san** [comment]
Ok, it works if I use the "down" and "up" events and set there my css "touch-action" in down to "none" and in up to default. 
I even think it's a bit more obvious what happens. If you would set the "dragstart" to `{passive: false}` and using event.preventDefault(), it has no specific target for prevention. In contrast, if I use the raw pointer "down" and "up" events, then I explicitly set the touch-action to my canvasElement/scrollContainer.
But it's more code to write and 2 additional listeners/handler.
So, I am not sure about this, any suggestions which way is the better/prefered one (as soon both ways are possible)?

**Comment by taye** [comment]
Sorry for taking so long to respond. I'd like to provide an option to add non passive events listeners to the document. There's currently an `interact.addDocument(document)` method which is normally called automatically when the first interactable is created. I'll add a second `options` argument which can be used to set the document-level event listener options.
