### ISSUE TITLE
Using Translate 50% for a starting position of draggable

### ISSUE THREAD

**Issue by JakeSchroeder** [taye/interact.js#541]
I am using transform: translateX(-50%) translateY(-50%); to position my .window div. That .window div is also a draggable. However, when I go to drag it, it seems to jump to a position further than normal.

### Expected behavior
The draggable item in this case the .window css selector should drag to the new position and mimic the usual behavior of a draggable item.

### Actual behavior
The draggable item jumps to the new draggable position but offset by a factor. Essentially it translates the draggable item by too much then the desired amount. I think this is due to the fact that I am using translateX(-50%) translateY(-50%) to position it initially. However, I have no idea the best way to position it in the center when using this library.

### System configuration
**interact.js latest**:
**Chrome Latest**:
**Mac**:

**Comment by JakeSchroeder** [comment]
update:
I fixed the issue by using flexbox to handle to positioning.
But now there is a different problem, flex box causes the resize function to behave in a different (unwanted) way.

Guess I will have to use tables :(

**Comment by taye** [comment]
You could use the [CSS `calc` function](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) the translation to add the dragged offset to the `50%` value.

```js
event.target.style.transform =
  `translateX( calc(-50% + ${x}px) ) translateY( calc(-50% + ${y}px) )`;
```
