### ISSUE TITLE
How can I make autoscroll work on ".resize-drag" component  under "Resizing" example?

### ISSUE THREAD

**Issue by yashvekaria** [taye/interact.js#542]
As shown in demo site (http://interactjs.io/#resizing) example. I wanted to add autoscroll feature along to my **.resize-drag** component. So basically I can drag ".resize-drag" component which could  allow easily to scroll over parent component (just like it scrolls down in Dragging example), but as soon i release drag it should stay there. 

[http://interactjs.io/#resizing]

**Comment by vinaynb** [comment]
Same issue. @taye can you help us out. Is this possible at all and if yes where should be start looking in the code to modify the behaviour ?

**Comment by taye** [comment]
Duplicate of #568
