### ISSUE TITLE
Latest typings are not published

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [taye/interact.js#543]
NPM has v1.0.22 which is obsolete.

**Comment by zuzusik** [comment]
The other thing is that 1.2.9 has typings listed in package.json files section, but actual typings files are not published as a part of a package.

Probably there is a reason in publishing 1.2.10 with typings?

**Comment by taye** [comment]
I hope the changes in #539 have resolved this for v1.3.0-alpha.5.

@zuzusik that's a mistake in the package.json file. There are typings available for v1.2 at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/interact.js/index.d.ts.

**Comment by zuzusik** [comment]
@taye I am aware about DT typings, but they are quite outdated (they are for 1.0.25, not for 1.2)

fixing mistake in package.json and releasing 1.2.10 shouldn't be a big deal, so why not going that way?

**Comment by taye** [comment]
@zuzusik I'm not sure how the DT typings work, but the typings file there [mentions 1.2.7](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5dc07fada8bc9f9dc5058324a078360c370a3653/types/interact.js/index.d.ts#L246-L254) so I assumed that it was up to date. Have you tried `npm install -D @types/interact.js`?

Removing `"interact.d.ts"` from the `files` field will probably make no difference. That field tells npm which files should be included in the published package, but the `interact.d.ts` file doesn't exist in the repo. I'll remove it, but won't publish a new version just yet.

**Comment by taye** [comment]
@ivanvoznyakovsky @zuzusik As I prepare for the release of `v1.3.0` I've written a short [migration doc](https://github.com/interactjs/docs/blob/v1.3/upgrade-v1.2-1.3.en.html.md) to hopefully make it easier to start using the new version. I'll close this issue but would be happy to review and accept a PR that fixes the typings for the older version.
