### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by prabhakar3** [taye/interact.js#546]
I have a requirement in my project. The dragged item will only appear in the dropzone. Any place outside the dropzone will not be permitted. Is it possible?

**Comment by ruben-aguilar** [comment]
You can use the event dragEnter from draggable item [http://interactjs.io/docs/#interactevents](http://interactjs.io/docs/#interactevents). 

When you get dragEnter set visibility to true and when you get dragLeave set visibility to false.
