### ISSUE TITLE
Interact.js randomly stops working on iOS

### ISSUE THREAD

**Issue by jiimmeh** [taye/interact.js#549]
Hi, i am currently working on an application that uses interact.js draggable and i noticed that interact.js breaks globally at random on iOS. I tried the demo and it seems that the problem is there too.

You can test this on the http://interactjs.io/ with an iPad or iPhone.

1. Go to http://interactjs.io
2. Drag around the draggable demo for abit
3. Try changing tabs (JS, HTML, CSS Demo only)
4. After a while you cant drag anymore and all other demos is broken

I have tried the following devices and the problem occured:
iPad iOS 9.0.2 - Safari
iPhone 6S+ iOS 10.3.3 - Safari & Chrome
Browserstack iPhone 6S - Safari

Browserstack devtools gave the following console error on http://interactjs.io

`index.bundle.js:1 ReferenceError: Can't find variable: _showTab @ index.bundle.js:1fire @ interact.min.js:111firePointers @ interact.min.js:90collectEventTargets @ interact.min.js:89pointerUp @ interact.min.js:71(anonymous function) @ interact.min.js:18`

I am using interactjs 1.2.9 on my own app but i dont get any errors on my console when the functionality breaks. 

**Update**

I tried v1.3.0-alpha.5 on my own app but the problem seems to persist on both my iPad and my iPhone.

**Comment by jiimmeh** [comment]
Found a solution here:
https://stackoverflow.com/questions/33033089/interact-js-1-2-4-drag-and-gesture-action-confusion#

` interact(document).on('down', function (event) {
            var interaction = event.interaction;
            var canGesture = interaction.target && interaction.target.options.gesture.enabled;
            var maxAllowedPointers = canGesture? 2 : 1;

            while (interaction.pointers.length > maxAllowedPointers) {
                interaction.removePointer(interaction.pointers[0]);
            }
          })`

This code fixed the problem for me, i have been testing around for 30 minutes on my own app without any problems in iOS.

**Comment by taye** [comment]
This is likely fixed in Please try `v1.3.3`. If not you can also try `v1.4.0-alpha`.

**Comment by nirmalspeed** [comment]
I'm seeing this issue on 1.3.4 in my app. No errors emitted. Not sure the best way to debug this but in the function `PointerEvent` the `interaction` objects `target` and `element` both end up being undefined.

**Comment by parox** [comment]
Same issue. Ipad doesn't work. tried with version 1.4.0-alpha.17

**Comment by shubh3695** [comment]
Ipad click is still blocked, tested with v1.4.0 doesn't let handle click/touch events. Any workaround?

**Comment by simonrl** [comment]
Also having this on v 1.5.4 & iPhone 8.

My workaround:

```
interact(...).on('down', function (event) {
        var t;
        // handle click events on iOS devices
        // https://github.com/taye/interact.js/issues/549
        if (event.target) {
            t = jQuery(event.target);
            if (t.hasClass('my-clickable-class')) {
                t.trigger('click');
            }
        }
    });
```
