### ISSUE TITLE
gesture sensitivity

### ISSUE THREAD

**Issue by jdewit** [taye/interact.js#55]
interact seems to favor dragging over gesturing. If you do not place two fingers on the screen at exactly the same time, it will call the draggable interact instead of the gesturable interact. 

use case: 
I'm using interact for the dragging/resizing of items in a grid. Each grid item has a draggable interact attached. The grid container has a gesturable interact that is used to resize the target item. 

It's a little frustrating having the item predominantly drag instead of gesture.

Tested on ipad3 w. safari

**Comment by 1c7** [comment]
`pointerMoveTolerance` affect both drag and 2 figure pinch. 
`interact.pointerMoveTolerance(200)` not helping my problem
my problem is a lot of time 2 figure pinch become drag

**Comment by 1c7** [comment]
I found a typo, lack `)`
http://interactjs.io/api/Interactable.html#actionChecker
![image](https://user-images.githubusercontent.com/1804755/48695546-67d33580-ec1a-11e8-8bbe-af6d07cb94e0.png)

(I don't have time for PR now)

**Comment by 1c7** [comment]
## Problem Solved

here is code for display how many finger on screen in real time

````
$("#camera-controller").on("touchstart", (e) => {
    var fingerOnScreen = e.originalEvent.targetTouches.length;
    $('#finger_count').text(fingerOnScreen);
});
$("#camera-controller").on("touchend", (e) => {
    var fingerOnScreen = e.originalEvent.targetTouches.length;
    $('#finger_count').text(fingerOnScreen);
});
````

**Comment by azumbrunnen** [comment]
This is still an issue and the jQuery solution above is clearly not how this framework is intended to be used.

Any chance we will see this solved as part of the framework? would be great to be able to drag and resize things at the same time…
