### ISSUE TITLE
Canned example of Pinch to Zoom doesn't work.

### ISSUE THREAD

**Issue by jgfet** [taye/interact.js#550]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**interact.js version**:
**Browser name and version**:
**Operating System**:
Just running examples in browser.. So whatever version you have there...
Using Chrome Version 61.0.3163.100 (Official Build) (64-bit)
on Mac OS/X 10.12.6
Also tried Safari Version 11.0 (12604.1.38.1.7)

**Comment by taye** [comment]
If you're trying to use multi-touch gestures with a laptop trackpad, that won't work. Gestures only work with Touch(screen) input.

**Comment by jgfet** [comment]
Jobmst_id           jobmst_prnt_id                jobmst_active
15922                    15921                                    Y


JEREMY FLOWERS

Senior Developer | Extra Technology

jeremy.flowers@extratechnology.com<mailto:jeremy.flowers@extratechnology.com%0a>

t +44 845 475 5550

m +44 784 315 2400

extratechnology.com<https://extratechnology.com>

[Extra Technology]<http://www.extratechnology.com/>

[Automation Anywhere]<http://www.automationanywhere.com/> [Computer Associates Advanced Partner] <http://www.ca.com/>

Disclaimer
This message and any files transmitted with it is intended for the addressee only and may contain information that is confidential or privileged. If you are not the addressee, please advise us of its receipt immediately and delete it. Unauthorised use is strictly prohibited and may be unlawful. If you are not the addressee, you should not read, copy, disclose or otherwise use this message, except for the purpose of delivery to the addressee.

**Comment by jgfet** [comment]
Hi Jeremy,
I am investigating the issue you indicated in the your spreadsheet, and will let you know about that later.

Node (agent server) operating system it is nodmst_ostype in nodmst table.

‘1’ for Windows.
‘2’ for Unix.

I am attaching Tidal Master database layout in case if you do not have it.

Thank you
Andrew Rybicki | Technical Specialist | Operations Support & Automation
________________________________________________________________
Scotiabank | Domestic & International Application Support & Automation
2201 Eglinton Avenue East, Toronto, Ontario, M1L 4S2
andrew.rybicki@scotiabank.com<mailto:andrew.rybicki@scotiabank.com>
www.scotiabank.com<http://www.scotiabank.com/>
*Scotiabank is a business name used by The Bank of Nova Scotia

From: Jeremy Flowers [mailto:jeremy.flowers@extratechnology.com]
Sent: Friday, July 06, 2018 10:09 AM
To: Andrew Rybicki; Andrew Au; taye/interact.js
Subject: Bad Data in the Jobmst file records pointing to prnt_id's that don't exist - one shows as active

Jobmst_id           jobmst_prnt_id                jobmst_active
15922                    15921                                    Y


JEREMY FLOWERS

Senior Developer | Extra Technology

jeremy.flowers@extratechnology.com<mailto:jeremy.flowers@extratechnology.com%0a>

t +44 845 475 5550

m +44 784 315 2400

extratechnology.com<https://extratechnology.com>

[Extra Technology]<http://www.extratechnology.com/>

[Automation Anywhere]<http://www.automationanywhere.com/> [Computer Associates Advanced Partner] <http://www.ca.com/>

Disclaimer
This message and any files transmitted with it is intended for the addressee only and may contain information that is confidential or privileged. If you are not the addressee, please advise us of its receipt immediately and delete it. Unauthorised use is strictly prohibited and may be unlawful. If you are not the addressee, you should not read, copy, disclose or otherwise use this message, except for the purpose of delivery to the addressee.



To unsubscribe from receiving further commercial electronic messages from The Bank of Nova Scotia in Canada, please click here: https://unsubscribe.scotiabank.com?entid=BNS&buid=SBNK

To unsubscribe from receiving further commercial electronic messages from certain other senders set out in the attached list, please click here: https://www.unsubscribe.gwm.scotiabank.com?page=gwm 

This email may contain confidential information the use of which by an unintended recipient is unauthorized. This email may also contain important disclosure information for the records of the intended recipient(s).  For details please click here: http://www.scotiabank.com/email_disclaimer/email_english.html

Pour vous désabonner et cesser de recevoir des messages électroniques commerciaux de La Banque de Nouvelle-Écosse, veuillez cliquer ici : https://desabonnement.banquescotia.com?entid=BNS&buid=SBNK

Pour vous désabonner et cesser de recevoir des messages électroniques commerciaux de certains autres expéditeurs figurant dans la liste ci-jointe, veuillez cliquer ici : https://www.unsubscribe.gwm.scotiabank.com?page=gwm&lang=fr 

Cette transmission peut contenir de l'information confidentielle et son utilisation par toute personne autre que la personne à laquelle cette transmission est destinée est interdite. Le présent courriel peut aussi contenir des renseignements importants pour les dossiers du ou des destinataires prévus.  Pour plus de détails, veuillez vous diriger vers: http://www.scotiabank.com/email_disclaimer/email_francais.html

Para dejar de recibir mensajes electrónicos comerciales de The Bank of Nova Scotia en Canadá, haga clic aquí: https://cancelarsuscripcion.scotiabank.com?entid=BNS&buid=SBNK

Para dejar de recibir mensajes electrónicos comerciales de otras entidades incluidas en la lista adjunta, haga clic aquí: https://www.unsubscribe.gwm.scotiabank.com?page=gwm&lang=es

Este correo electrónico puede contener información confidencial cuyo uso por parte de personas distintas de los destinatarios del mismo está prohibido. El mensaje puede tener también datos importantes para los archivos   del(de los) destinatario(s) a quien(es) está dirigido.  Para más detalles, por favor dirigirse a: http://www.scotiabank.com/email_disclaimer/email_espanol.html
