### ISSUE TITLE
Activate parent dropzone only after draggable leaves child dropzone

### ISSUE THREAD

**Issue by zuzusik** [taye/interact.js#552]
I have following conditions:

- I have nested dropzones, every has draggables. 

- I need to be able to drag and drop between these dropzones - from child to parent and vice versa. 

- I’ve added checkers - if dropzone has this draggable - dropping is not allowed - so when I pick up item that is already in dropzone - its own dropzone is not activated. 

But when I start dragging element in whatever nested dropzone - the parent dropzone is being activated.

Here is the picture illustrating this behavior: 
<img src="https://user-images.githubusercontent.com/4233080/32116948-d6849e42-bb4c-11e7-89c9-a2f6ebe12955.png" width=500 />

Is it possible to achieve the behavior when parent dropzone is being activated only when draggable leaves the current (disabled by checker) dropzone?

**Comment by taye** [comment]
A workaround would be to surround the child dropzone with 4 dropzones which
are all matched by a different selector to the child, then set the
activated class for all 4 when one is activated.

Am 27.10.2017 7:28 nachm. schrieb "Viktor Zozuliak" <
notifications@github.com>:

**Comment by zuzusik** [comment]
@taye hmm, not sure I am getting what you wanted to say here

I'll try to add bit more of explanation to my image:

The red ones are dropzones and blue ones are draggable.

I need to drag blue one from DZ3 to DZ2, but when I just start dragging it - DZ2 gets activated. This happens because DZ3 is disabled by checker, and so interact.js activates DZ2.

I need DZ2 to get activated only when blue one leaves DZ3.

**Comment by taye** [comment]
I meant to sort of cut the dropzones which have dropzones nested in them into four different elements which surround (but are not overlapped by) the child dropzone.

![screen](https://user-images.githubusercontent.com/1679746/32297064-38b7c6c0-bf4e-11e7-9956-853800a3f7b2.png)

You could also change the drop checker so that it allows drops to full elements, but do nothing when `dropactivate`, `dragenter` and `drop` events happen on full dropzones.

**Comment by taye** [comment]
@zuzusik I'm working on a `DropEvent.reject()` method in #613 that I think would solve your issue. With it you could allow the child dropzone to be activated, but then reject the dragenter and prevent a drop from happening.
