### ISSUE TITLE
Input text selection problem

### ISSUE THREAD

**Issue by talavivi03** [taye/interact.js#553]
I'm trying to use this component to drag and drop a complex element that contains an input element.
The draggable element is the parent of the input element. Due to this hierarchy, when I'm trying to highlight\select a text from the input (the child element) it drags the parent element. 
Is it possible to add exception element that will not drag the element? Or is there any other solution for this?

**Comment by taye** [comment]
If you're using `v1.3.0-rc`, there's the `ignoreFrom` option which takes a CSS selector or HTMLElement:

```js
interact(target).draggable({
  ignoreFrom: '.input-element',
});
```

**Comment by talavivi03** [comment]
Thanks!
