### ISSUE TITLE
Snap Grid snaps to incorrect places with restricting

### ISSUE THREAD

**Issue by Aetherpoint** [taye/interact.js#554]
Hi! Been really loving interact.js, thanks so much for providing it - it's clear and easy to use.

For some reason though when creating a snap grid with a restriction, the draggable item seems to fall outside the grid proportions. Have a fiddle here: http://jsfiddle.net/uhf0m1jj/.

Wasn't sure if I was just doing something wrong? This may be related to or a duplicate of  https://github.com/taye/interact.js/issues/208

Edit: Seems to be relating with any sort of shift in location of the drag area and `event.dx` returning odd values.

**Comment by taye** [comment]
The snapping of 30px divides neatly into the 300px `.container` so this issue isn't exactly the same as #208. The problem here is the offset of the `.interactable` caused by the `body`'s margin. The solution would be to add `origin: 'parent'` to the draggable options, but that doesn't work for `v1.2.9` so you'll _also_ have to upgrade to `v1.3.0-rc.0`. Unfortunately, moving outside the edge of the restriction is still buggy. I'll try to sort that out soon.

As a work around to the issue in the latest version, you can remove the restriction and instead set limits on the snap grid. https://jsfiddle.net/uhf0m1jj/13/

```js

interact(".interactable")
    .draggable({
    		// the top left corner of the element will be (0, 0)
    		origin: 'parent',
        snap: {
            targets: [
                interact.createSnapGrid({
                    x: 30,
                    y: 30,
                    // limit to the container dimensions
                    limits: {
                        left: 0,
                        top: 0,
                        right: 300 - 30,
                        bottom: 300 - 30,
                    },
                })
            ],
            relativePoints: [
            	{ x: 0, y: 0 }
            ]
        },
        restrict: {
            restriction: 'parent',
            elementRect: {top: 0, left: 0, bottom: 1, right: 1}
        },
    })
    .on('dragmove', function (event) {
        var target = event.target,
                // keep the dragged position in the data-x/data-y attributes
                x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
                y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

        // translate the element
        target.style.webkitTransform =
                target.style.transform =
                'translate(' + x + 'px,' + y + 'px)';

        // update the posiion attributes
        target.setAttribute('data-x', x);
        target.setAttribute('data-y', y);
    });
```

**Comment by taye** [comment]
The issue was easier to fix than I expected. https://jsfiddle.net/uhf0m1jj/14/

**Comment by Aetherpoint** [comment]
Awesome, thank you so much!

**Comment by darksnake747** [comment]
Incredibly helpful! Setting the origin to 'parent' fixed my issue as well. Such an easy fix. Thank you so much @taye for sharing!

**Comment by aderchox** [comment]
@taye In the current version of InteractJS, does this `origin` option still exist? I couldn't find it here: [draggable(): DraggableOptions](https://github.com/taye/interact.js/blob/24fdee86af07f895dd2e52240e346a78e8d71273/packages/%40interactjs/actions/drag/plugin.ts#L11). I couldn't find it in the docs too. (I'm not sure if this fixes my issue though.)

I've encountered an issue where if the parent container has some padding, then snap grid of `x: 50, y: 50` used in conjunction with `restrictRect` works but __violates the grid when moving the draggable towards the leftmost (start) position and also when dragging it towards the rightmost (ending) position inside the container.__ The padding gets ignored and the draggable reaches the border of its container (touches it).
I can make a demo of this if needed, but basically this is all I have:
```js
    draggableBox.draggable({
      lockAxis: "x",
      listeners: {
        move(event) {
          position.x += event.dx;
          position.y += event.dy;
          event.target.style.transform = `translate(${position.x}px, ${position.y}px)`;
        },
      },
      modifiers: [
        interact.modifiers.snap({
          targets: [
            interact.snappers.grid({
              x: 50,
              y: 50,
            }),
          ],
        }),
        interact.modifiers.restrictRect({
          restriction: ".board",
        }),
      ],
    });
  });
```
