### ISSUE TITLE
undefined is not an object (evaluating 'b[a+"X"]')

### ISSUE THREAD

**Issue by catbadger** [taye/interact.js#556]
### What's happening? 

I work on a very large app, and am unable to provide a minimal example that crashes like this every time as it seems intermittent. So my JavaScript exception backstop has caught the following error "undefined is not an object (evaluating 'b[a+"X"]')" (pretty consistently) from interact.min.js line 6 

### Expected behavior

vendor libs  shouldn't be throwing cryptic errors.

### System configuration
interact v1.2.9
browser that triggers it most often is Safari on Maxc

**Comment by catbadger** [comment]
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1

**Comment by taye** [comment]
Closing this as `v1.3.0` is now stable.
