### ISSUE TITLE
Browser warrning: interact.min.js.map include but not provided

### ISSUE THREAD

**Issue by lestcape** [taye/interact.js#558]
At less firefox 59 it complaint because of that. Where is the file `interact.min.js.map` then?

**Comment by taye** [comment]
How are you linking to the `interact.min.js` file from your html page and which version are you using?

**Comment by lestcape** [comment]
Good question... I have using it as a dependency of the jQuery-QueryBuilder: https://github.com/mistic100/jQuery-QueryBuilder So, i have not idea of how answer your question really.

**Comment by taye** [comment]
Without more info, I unfortunately can't help much 😕. If you find the version info in the header of the `interact.min.js` file, maybe you can download the map file for that version and save it in the same directory.

**Comment by lestcape** [comment]
The version is v1.2.9 with is not a real release... :( You get me the idea and I see that the map file is inside of all interact releases. So, this is not the problem of interact then. Sorry for disturb for nothing seriously thing and thanks for your help. I will try to replace the interact copy that i have with some valid release of interact. That will solve my problem.

Again thanks,

**Comment by taye** [comment]
You're welcome.
