### ISSUE TITLE
Demo page has some issue, it seems

### ISSUE THREAD

**Issue by PragmaticEd** [taye/interact.js#559]
This is not about the js it self, only the demo page seems to have a little bug :)

Screenshot:
![interact js - javascript drag and drop 2c resizing and gestures with inertia and snapping - google chrome 2017-11-27 11 20 20](https://user-images.githubusercontent.com/19263525/33259310-250cac82-d365-11e7-9a0e-cd5b3c44d065.png)

**Comment by taye** [comment]
Thanks for the report!
