### ISSUE TITLE
npm build is outdated

### ISSUE THREAD

**Issue by moraleja39** [taye/interact.js#566]
Hi. The [latest version available](https://www.npmjs.com/package/interactjs) in npm is 1.2.9.

Since it seems there have been some breaking changes in 1.3.0 and I didn't see any mention about it in the docs, guess who've been going nuts wondering why the resizable ignored half of the options.

An update would be appreciated 😃

**Comment by taye** [comment]
Done. Sorry about that. The version was published, but I updated it to the "next" tag instead of "latest".
