### ISSUE TITLE
allowFrom not working after interact.js change to v1.3.0

### ISSUE THREAD

**Issue by micvm** [taye/interact.js#570]
I have tried to migrate the allowFrom feature from the old 1.2.X way `interact(draggable).allowFrom(..)` to the new 1.3.0 way `interact(draggable).draggable({allowFrom: ....})`. 

### Expected behavior
I should be able to define a handle within a draggable which becomes thereby the only way to drag the element itself.

### Actual behavior
If I define a handle via allowFrom, the draggable can be dragged from all over the draggable area. I.e. it does not make any difference whether I define allowFrom or not. https://jsfiddle.net/twqb3pnc/1/ . If you try the same code with the old allowFrom method it works as expected.
Moreover, I have had also issues when I set an Element as handle instead of a CSS selector. Do not know if it is related. 

### System configuration
**interact.js version**: 1.3.0
**Browser name and version**: Chrome
**Operating System**: Ubuntu 16.04

**Comment by dannycoulombe** [comment]
I am using 1.3.2 and found out that there's a type in the function's name. Try "allowForm" insteand of "allowFrom".
