### ISSUE TITLE
1.3.0+ not working in IE11 with SystemJS

### ISSUE THREAD

**Issue by jrigsby** [taye/interact.js#573]
Im using this with an Aurelia project loading via systemjs.  1.2.8 works fine in all browsers but I had a bug in iOS with click event ignored on draggable (have it on a column header that is draggable and sortable on click) so needed to go to 1.3.0.  Loaded 1.3.2 and it fixed the click event in iOS but I found it completely breaks in IE11 11.125.16299.0.  I went back to 1.3.0 and that also is broken in IE11.

Chrome, Safari on iPad, Edge, Firefox all work fine.

IE11 shows the following as it tries to load my view which has to do with referencing interact in my scrollable-table code.  I assume simply attempting to load interact using IE11 in any project will recreate the issue.  I have no clue yet how to figure out what its really complaining about in order to give more feedback.  If I go back to 1.2.8 everything is fine but I lose out on the fix of the click in a draggable in a touch device.

ERROR [app-router] Error: (SystemJS) Syntax error
	SyntaxError: Syntax error
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Anonymous function (eval code:2:1)
	   at Anonymous function (eval code:1:31)
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/inertia.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0.js
	Error loading http://localhost:1761/dist/common/scrollabletable/scrollable-table.js
   "ERROR [app-router]"
   {
      [functions]: ,
      __proto__: { },
      __symbol:hasInstance0.7653421019584256: undefined,
      __symbol:isConcatSpreadable0.7653421019584257: undefined,
      __symbol:iterator0.7653421019584251: undefined,
      __symbol:match0.7653421019584252: undefined,
      __symbol:replace0.7653421019584253: undefined,
      __symbol:search0.7653421019584254: undefined,
      __symbol:species0.7653421019584259: undefined,
      __symbol:split0.7653421019584255: undefined,
      __symbol:toPrimitive0.76534210195842510: undefined,
      __symbol:toStringTag0.76534210195842511: undefined,
      __symbol:unscopables0.7653421019584258: undefined,
      description: "(SystemJS) Syntax error
	SyntaxError: Syntax error
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Anonymous function (eval code:2:1)
	   at Anonymous function (eval code:1:31)
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/inertia.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0.js
	Error loading http://localhost:1761/dist/common/scrollabletable/scrollable-table.js",
      message: "(SystemJS) Syntax error
	SyntaxError: Syntax error
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Anonymous function (eval code:2:1)
	   at Anonymous function (eval code:1:31)
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/inertia.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0.js
	Error loading http://localhost:1761/dist/common/scrollabletable/scrollable-table.js",
      name: "Error",
      originalErr: {
         [functions]: ,
         __proto__: { },
         __symbol:hasInstance0.7653421019584256: undefined,
         __symbol:isConcatSpreadable0.7653421019584257: undefined,
         __symbol:iterator0.7653421019584251: undefined,
         __symbol:match0.7653421019584252: undefined,
         __symbol:replace0.7653421019584253: undefined,
         __symbol:search0.7653421019584254: undefined,
         __symbol:species0.7653421019584259: undefined,
         __symbol:split0.7653421019584255: undefined,
         __symbol:toPrimitive0.76534210195842510: undefined,
         __symbol:toStringTag0.76534210195842511: undefined,
         __symbol:unscopables0.7653421019584258: undefined,
         description: "Syntax error",
         message: "Syntax error",
         name: "SyntaxError",
         number: -2146827286,
         stack: "SyntaxError: Syntax error
   at re (http://localhost:1761/jspm_packages/system.js:4:22195)
   at Function.prototype.call (http://localhost:1761/Research:700:48)
   at c.execute (http://localhost:1761/jspm_packages/system.js:5:17897)
   at Function.prototype.call (http://localhost:1761/Research:700:48)
   at c (http://localhost:1761/jspm_packages/system.js:5:6214)
   at d (http://localhost:1761/jspm_packages/system.js:5:5846)
   at Anonymous function (http://localhost:1761/jspm_packages/system.js:5:6301)
   at a (http://localhost:1761/jspm_packages/system.js:5:17229)
   at Anonymous function (eval code:2:1)
   at Anonymous function (eval code:1:31)"
      },
      stack: "(SystemJS) Syntax error
	SyntaxError: Syntax error
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Function.prototype.call (http://localhost:1761/Research:700:48)
	   at Anonymous function (eval code:2:1)
	   at Anonymous function (eval code:1:31)
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/inertia.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/src/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0/index.js
	Evaluating http://localhost:1761/jspm_packages/npm/interactjs@1.3.0.js
	Error loading http://localhost:1761/dist/common/scrollabletable/scrollable-table.js"
   }

**Comment by jrigsby** [comment]
I see I can fix my click issue in 1.2.8 setting draggable().ignoreFrom so I dont have to go to 1.3.0+ for now.  Obviously this issue is still a problem if I were to need to go up.

**Comment by yvettegraveline** [comment]
How do I unsubscribe from these emails?

**Comment by taye** [comment]
@yvettegraveline you're watching the repo so you receive notifications about everything. You can unsubscribe with the "Unwatch" dropdown in the top left.

![screenshot from 2018-01-02 19-03-01](https://user-images.githubusercontent.com/1679746/34496002-a0c7bd20-efef-11e7-9f63-26621d9ff84c.png)

**Comment by taye** [comment]
@jrigsby the problem is probably that IE11 doesn't support the ES6 syntax that's used in interact.js' source files. You'd need to use a transpiler with SystemJS.
