### ISSUE TITLE
Hope to update the index.d.ts

### ISSUE THREAD

**Issue by coloz** [taye/interact.js#574]
index.d.ts missing some parameters, such as enabled in  interface DraggableOptions

**Comment by coloz** [comment]
Another problem：
How to stop the event listener
thanks

**Comment by taye** [comment]
Duplicate of #572.

>How to stop the event listener in typescript

 - use `interactable.off(eventType, listenerFunction)` to remove an event listener
 - use `interactable.unset()` to remove an interactable and all it's events and actions
 - use `interact.removeDocument` to remove all listeners on a document
