### ISSUE TITLE
dropzone with svg element not working

### ISSUE THREAD

**Issue by rekna1** [taye/interact.js#575]
Perhaps I'm doing something wrong, but I can not seem to make drag and drop working between 2 svg elements.

### Expected behavior
I expect the drop  events to work on a svg element marked as dropzone

### Actual behavior
none of the events are triggered

### example (open console as I only use console.log to implement events )
try dragging top white box onto bottom white box.
drag events work: onstart en onend both output their message to the console
dropzone events: ondragenter ondrop do not seem to work
https://jsbin.com/yepusisitu/edit?html,js,console,output

**Comment by taye** [comment]
In that jsbin, you used the dropzone `accept` option incorrectly. It should be a selector for the draggables that will be accepted. There's also only one element with the "toolboxsvg" class, so `interact('.toolboxsvg')` which is both the draggable and the dropzone only works on the first `<rect>` which can't be dragged into itself.

Use `interact('.dropzone').dropzone({ accept: '.toolboxsvg', ... })` and it works.

https://jsbin.com/hujurijusa/edit?html,js,console,output
