### ISSUE TITLE
Not working with Edge at all

### ISSUE THREAD

**Issue by ygoe** [taye/interact.js#576]
Just found this by accident on a web search about how to properly implement touch for the Edge browser (because I couldn't figure that out yet), and wanted to let you know that none of your demos work properly in the Edge browser on Windows 10.1703. They do work for mouse and pen input, but touch input fails completely. I haven't tested other browsers, as I assume it works there. (Just a quick look with IE 11 and that works fine, also with multi-touch.) My own code also works everywhere but in Edge. You don't mention that browser in your description so I'm not sure you've seen it already. It's the replacement for IE in current Windows.

**Comment by Jeremy-Knudsen** [comment]
Works in Edge for me. I'm using:
Microsoft Edge 41.16299.551.0
Microsoft EdgeHTML 16.16299
