### ISSUE TITLE
Snapping Grid // dragging outside

### ISSUE THREAD

**Issue by marexx** [taye/interact.js#579]
### Expected behavior
I've created a little game:
http://mathelino.ph-freiburg.de/index.php?id=64
you can see the problem best with the squared-track-Cards (the last one).
When you add cards to the playground  and drop them near or over the end of the playground they align to the snapping grid, so i can start adding and moving some more and all should align correct edge to edge. An no card should overlap the other one.

### Actual behavior
if i place cards inside the playground everything is fine, but when i place it outside and it gets aligned automatically in the playground, it gets positioned on the nearest edge, but that's not the real grid, so if i add another one an try to place it beside it, it would overlap. Clear? But when i know move/drag the first item again, i can position it beside the second one... and so on.

### System configuration
**interact.js v1.2.6**:
**Chrome - latest**:
**OS X 10.13**:

**Comment by marexx** [comment]
After long research i managed it like that, maybe not the best solution, but time was up:
I figured out, that for each 10px the browser width changed, the element moved 5 px, so i calculated it that it fits.

  if($(window).width() > 1199){
     trackOffset = { x: (25+($(window).width() - 1200)*0.5), y: -17 };
     smallOffset = { x: (25+($(window).width() - 1200)*0.5), y: -10 };
     triangleOffset = { x: (25+($(window).width() - 1200)*0.5), y: -3 };
  }else if($(window).width() > 991 && $(window).width() < 1199){
    trackOffset = { x: (5+($(window).width() - 1200)*0.5), y: 68 };
    smallOffset = { x: (5+($(window).width() - 1200)*0.5), y: 75 };
    triangleOffset = { x: (5+($(window).width() - 1200)*0.5), y: 15 };
  }else{
    trackOffset = { x: (-5+($(window).width() - 1200)*0.5), y: 40 };
    smallOffset = { x: (-5+($(window).width() - 1200)*0.5), y: 100 };
    triangleOffset = { x: (-5+($(window).width() - 1200)*0.5), y: 32 };
  }

**Comment by taye** [comment]
instead of using a `restriction`, you can add a limit to your snap grid. https://jsfiddle.net/uhf0m1jj/17/

**Comment by taye** [comment]
If you upgrade to `v1.4.0-alpha.6` or higher, you can use an array of modifiers and have more control over how the snap and restrictions apply over each other. See #625
