### ISSUE TITLE
interactjs.io sample code broken on Chrome Android

### ISSUE THREAD

**Issue by idmadj** [taye/interact.js#580]
The "Dragging" sample on interactjs.io works properly on interactjs.io, but implementing the sample code in a clean project has the following issue:

### Expected behavior
An element should be dragged until released, with native scrolling disabled while dragging.

### Actual behavior
Native scrolling remains enabled. Element is dragged for a few pixels then the dragend event is called and the element is dropped.

**JSFiddle**: https://jsfiddle.net/y63s2nre/
**CodePen**: https://codepen.io/idmadj/pen/goXobQ

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Chrome Android 63.0.3239.111
**Operating System**: Android 8.1.0

**Comment by idmadj** [comment]
Seems like adding `touch-action: none` to the draggables CSS fixes the issue. Maybe just update the sample code to reflect this?

**CodePen:** https://codepen.io/idmadj/pen/baaGNa

**Comment by rpearce** [comment]
^ confirmed `touch-action: none` fixes the issue

**Comment by taye** [comment]
I'm closing this issue, but leaving the related issue #595 open.
