### ISSUE TITLE
Cannot GET /interact.js.map

### ISSUE THREAD

**Issue by EricSong8612** [taye/interact.js#581]
While everything works fine in Chrome, Firefox and Safari throw error: Cannot GET /interact.js.map. and all the tab and drag actions messed up in those two browser. Can anyone help me fix this problem? thank you.

**Comment by emilhem** [comment]
You don't need the `.map` file.
Source-maps can help with debugging though. MDN has an article here: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

You can download the source-map for `interact.min.js` here: http://code.interactjs.io/v1.3.3/interact.min.js.map
You can download the source-map for `interact.js` here: http://code.interactjs.io/v1.3.3/interact.js.map

**Comment by EricSong8612** [comment]
thank you!
