### ISSUE TITLE
Dragging and Resizing object shifts other object from previous location

### ISSUE THREAD

**Issue by gonzalovazquez** [taye/interact.js#585]
### Expected behavior

To reproduce: 
- Have three or more objects close to each other. 
- Drag the middle object and position it anywhere in the screen. 
- Resize the middle object 

The original position of the middle object pushes the other objects when the user is resizing it. 

### Actual behavior

Any resizing to the moved object should not push other objects since the moved object initial position changed.

https://jsfiddle.net/6s5kw5zv/1/

### System configuration
**interact.js version**: 1.2.5
**Browser name and version**: Chrome V.63
**Operating System**: macOS 10.13.2

Let me know if my ticket makes sense :)

**Comment by taye** [comment]
Use CSS `position: aboslute` or `position: fixed` on the target elements.

**Comment by devashishp1999** [comment]
<h3 align="center"  >Same issue occurred in my code after 4+ years.</h3>
<h4 align="center" >@gonzalovazquez @taye </h4>


<b>What's happening:</b> <br /> 
• I have 2 draggable "H2" elements (say element-1 & element-2), with contentEditable = true.
• When one of them is edited its width increases(default behaviour). And everything works fine.<br /><br />

<b>Where's the problem:</b> <br />
• When H1 element-1 is at center of container & H2 element-2 is placed at edge of the container. 
• The element-2 pushes the element-1 when the user is editing element-2 (Resizing as a cause of editing). 
• [Issue demo video](https://screen-recorder-bucket.s3.ap-south-1.amazonaws.com/ScreenRecorder_2022-07-07_2cb34fa6-67a7-4094-9d83-5d86ea36c499.webm).

**<h4>All my elements have CSS property `position: absolute` already.</h4>**

<h3>Actual behavior:</h3>
Any resizing to any object should not affect position of other objects(shapes in my case).

<h3>System configuration:</h3>
<b>InteractJs:</b> 1.10.14<br />
<b>Browser:</b> Chrome Version 103.0.5060.114 (Official Build) (64-bit)<br />
<b>OS:</b> Ubuntu 21.10 (64-bit)


**<h4> _Do let me know any solutions or suggestions that worked for you._ </h4>**
@taye & @gonzalovazquez
