### ISSUE TITLE
dropzone ondragenter not working

### ISSUE THREAD

**Issue by Davit-000** [taye/interact.js#588]
### Actual behavior
I have multiple dropzones which have fixed width 150px and have multiple draggable element and their withs can be 2, 3, 4, 5 .... time bigger then dropzones widths so when I am dragging them over dropzones the on dragenter event doesn't work .

### Expected behavior
 I want to implement think like when user dragging element over dropzones  those dropzones on whom they fall must be highlighted. 
And also the first dropzone  on whom they draggable fall must get get draggable element.

Her are jsfiddle [ https://jsfiddle.net/zoyz92k1/](url).

### System configuration
**interact.js version: 1.3.3**:
**Browser name and version: google chrome Version 63.0.3239.132 (Official Build) (64-bit)**:
**Operating System**: windows 8.1 64bit.

**Comment by taye** [comment]
You have `overlap: 0.55` in the [dropzone options](https://interactjs.io/docs/#dropzone-overlap). Change it to `'pointer'`. That should solve the issue of not getting dragenter or drop events.
