### ISSUE TITLE
Cannot find module './src/utils/window' 

### ISSUE THREAD

**Issue by c-aursu** [taye/interact.js#593]
### System configuration
**interact.js version**: latest
**Browser name and version**: CLI
**Operating System**: OSX

 gulp dashboard-cars-es6
[20:02:18] Using gulpfile ~/ContentAnalytics/Public_Html/tmeditor_git/gulpfile.js
[20:02:18] Starting 'dashboard-cars-es6'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './src/utils/window' from '/Users/andreiursu/ContentAnalytics/Public_Html/tmeditor_git/node_modules/interactjs/dist'
    at /Users/andreiursu/ContentAnalytics/Public_Html/tmeditor_git/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/andreiursu/ContentAnalytics/Public_Html/tmeditor_git/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/andreiursu/ContentAnalytics/Public_Html/tmeditor_git/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/andreiursu/ContentAnalytics/Public_Html/tmeditor_git/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

I was installing window already globaly / also was enter in interactionJs folder, and run "nmp install"
but interact.js can't find the file.
Is also in src/utils/window.js - file is there... but not loaded...

Help me please someone !)

**Comment by ismaxs** [comment]
Hello,

I am making use of interactjs through the angularjs module called angular-bootstrap-calendar.

For my compilation constructions I use GULP and I get the following problem when the browserify plugin goes into action in order to build the package of external dependencies:

> Error: Can not find module './src/utils/window' from 'E: \ xxx \ xx \ node_modules \ interactjs \ dist'
>      at E: \ xxx \ xx \ node_modules \ browser-resolve \ node_modules \ resolve \ lib \ async.js: 55: 21
>      at load (E: \ xxx \ xx \ node_modules \ browser-resolve \ node_modules \ resolve \ lib \ async.js: 69: 43)
>      at onex (E: \ xxx \ xx \ node_modules \ browser-resolve \ node_modules \ resolve \ lib \ async.js: 92: 31)
>      at E: \ xxx \ xx \ node_modules \ browser-resolve \ node_modules \ resolve \ lib \ async.js: 22: 47
>      at FSReqWrap.oncomplete (fs.js: 152: 21)

I can not find the solution to the problem because I am not clear at what point I am doing something wrong. Maybe it's browserify the cause?

**Comment by c-aursu** [comment]
Hi , remove folder DIST and all will work perfect ;)

**Comment by sly7-7** [comment]
Why do we have to remove the dist folder ? I mean I install interact via yarn, I don't want to manually remove the dist folder. Is there an other workaround ?

**Comment by c-aursu** [comment]
> Why do we have to remove the dist folder ? I mean I install interact via yarn, I don't want to manually remove the dist folder. Is there an other workaround ?

Person was asking me about how I solve the problem, I just answer him.

**Comment by sly7-7** [comment]
@c-aursu I have the same kind of issue, in an ember project, using ember-cli. The thing is that for me this workaround is not satisfactory.
I will try to investigate further, because I think in previous version it used to work out of the box.

**Comment by wooandoo** [comment]
we have the same issue with an Ember application
but it's work with the version 1.4.0.alpha-0

**Comment by sly7-7** [comment]
@wooandoo Thank you so much for the heads up. I will try it asap.

**Comment by builtbylane** [comment]
`import interact from 'interactjs/src/index';` will solve your problem.

**Comment by yftachman** [comment]
This still happens to me, any updates on what I should do? I'm depending on another library that uses interactjs as a peer depe and deleting my and each of my team members dist folder makes no sense.

**Comment by okayawright** [comment]
same here with the require npm along with browserify

**Comment by real-artswan** [comment]
Confirm the issue when using browserify

**Comment by taye** [comment]
@blimpmason @okayawright @real-artswan try the latest alpha version

```sh
npm install interactjs@next
```
