### ISSUE TITLE
Drag and resize areas interfere with each other

### ISSUE THREAD

**Issue by gotchoices** [taye/interact.js#594]
If I have an element configured as a drag handle, which overlays an area otherwise used for resizing,  neither function seems to be useable in that area.

JSFiddle demo at: https://jsfiddle.net/vaj7rgt7/9/

### Expected behavior
You should be able to use any part of the grey header to move the window around.  The blue outline area should work to resize the box.

### Actual behavior
The area of the drag handle that overlays the resizer area seems to be inactive.  Only the very bottom strip of the drag handle can be used to drag.

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Chrome 63.0.3239.84 and JSFiddle
**Operating System**: Mac Sierra

**Comment by taye** [comment]
Those elements are static, so they're positions are affected by the shapes of their previous sibling elements. You can use CSS `position: absolute` or `position: fixed` on the dragged elements to take them out of the normal flow of the document. https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by taye** [comment]
Sorry, I closed the wrong issue.

**Comment by taye** [comment]
Sorry this took so long, but you can use

```js
interact(target).resizable({
  // 2px resizing border
  margin: 2,
});
```
