### ISSUE TITLE
Draggable onend event parameter issue

### ISSUE THREAD

**Issue by celeneisip** [taye/interact.js#596]
Interact's draggable "onend" function's event.target has the information on where the target/object was and not where it currently is.

Eg. if i have a draggable object that was in Container A and I drag and drop the object to Container B. On draggable onend function. If i want to check the parent element of the dragged object, I was expecting to grab that information using "event.target.parentNode", with this i'm expecting that it will return the element Container B. But currently in version. 1.3.0 and above  "event.target.parentNode" is pointing to Container A, instead of Container B. Is this the new expected behaviour or this is a bug. (Note: the expected behaviour I described was working on version 1.2.8, but not on  version. 1.3.0 and above   )

### Expected behavior
- I'm expecting that the event target information will be related to where the target/dragged-dropped object is currently is and not where it was.

### Actual behavior
-On version. 1.3.0 and above, event target information is related to where the target/dragged-dropped object was previously located and not where it currently is.

### System configuration
interact.js v1.3.0
Firefox/Chrome/Safari
Mac

**Comment by londomloto** [comment]
I have such problem too

**Comment by taye** [comment]
`dragend` events are now fired *before* `drop` events. Use `dragendEvent.dropzone` to get the dropzone interactable and `dragendEvent.relatedTarget` to get the dropzone element if there was a drop event. If there was no drop, then those values will be null.

**Comment by taye** [comment]
I misunderstood the problem being described. interact.js doesn't do any re-parenting. It just provides the information that the element/pointer is in a position for dropping. You have to change the dragged element's parent yourself.

**Comment by scottie-uk** [comment]
This is an issue for me two. I have two drop zones A and B on my page both of which are dynamically created svgs. If I drop on to A, the related target is the draggable and the Target is B.  It always seems to be the B what takes over unless I do not add B, then A will work. Both are sized 100, 100 and stacked A fist then B second..
