### ISSUE TITLE
Cordova Android app has different behaviour than a regular website

### ISSUE THREAD

**Issue by emilhem** [taye/interact.js#597]
### Expected behavior
The Cordova app should act like the interact.js website.

### Actual behavior
You can only pull items a short distance before they are "dropped".
Cordova project demonstrating this: https://github.com/emilhem/interact-cordova-testing

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Cordova 8.0.0 with Android platform 7.0.0
**Operating System**: Android 7.1.2 (Android API 25)

![android_studio_sdk_platforms](https://user-images.githubusercontent.com/1503789/35735566-2daf7f26-081d-11e8-9d8a-64cd432c5f6d.png)
![android_studio_sdk_tools](https://user-images.githubusercontent.com/1503789/35735567-2dd0b1a0-081d-11e8-8a93-2fe2c03ff819.png)

**Comment by emilhem** [comment]
It seems like adding `touch-action: none;` like one of the answers in issue #580 mentions fixes this issue.

**Comment by taye** [comment]
Closing this and leaving #595 open.
