### ISSUE TITLE
No touch drag registered if touching screen on set.

### ISSUE THREAD

**Issue by BHuys** [taye/interact.js#600]
Hello, I have a question about the draggable functionality. I'm making a "Tinder"-like game for a client where is use interact draggable to animate, after each case I unset the interact because I show a feedback "view" with no interact functionality. The problem: when I touch/swipe on the exact moment I reset my Interact, it stops registering touch events, for the current case and all those that follow. Mouse-drag events are still registered properly. Is this a known bug?

### Expected behavior
1. Set: I can drag my element.
2. unset: I Can't drag my element anymore. (different view)
3. (re)set: I can drag my element again

### Actual behavior
1. works
2. works
3. Stops working on touch events when a user touches the screen while I'm setting draggable, it won't register touch drags anymore, if I drag with my mouse, it still works. When it stops working, it won't work again even on page reload, I need to hard-reset my application. Other touch events such as clicking on buttons, links, etc... still work.

###code enable
`swipeCaseEnable() {
        this.set('isIntroPlaying',false);
     
            interact('#touchScreen').draggable({
                onmove: this.onMoveListener,

                onend: (event) => {
                    if (event && event.swipe && event.swipe.left) {
                        this.swipeHandler(false);
                    }
                    else if (event && event.swipe && event.swipe.right) {
                        this.swipeHandler(true);
                    }
                    else {
                        this.animateSwipeReset();
                    }
                }
            });
            this.set('isSwipeEnabled',true);

    },`

###code disable
` swipeCaseDisable() {
        this.set('isSwipeEnabled',false);
        interact('#touchScreen').unset();
    },`

### System configuration
Ember application
**interact.js version**: 1.2.9
**Browser name and version**: Chromium 61.0.3163.79 (Official build) (64-bits)
**Operating System**: Windows 10

**Comment by taye** [comment]
Try using [`interaction.start(action, target, element)`](https://interactjs.io/api/Interaction.html#start) to manually start the action.

**Comment by taye** [comment]
It might be a better idea to disable just the drag action instead of unsetting the whole thing.

```js
interact('#touchScreen').draggable({ enabled: faslse });
```

**Comment by BHuys** [comment]
I already tried the "enabled"-property solution, but it didn't make a difference. After trying a few other options without succes, I updated my chromium to the newest version that was released this month and my issue was resolved. Thanks anyway for the reply.
