### ISSUE TITLE
Resizable does not snap width or height to multiples as documented

### ISSUE THREAD

**Issue by travislaynewilson** [taye/interact.js#601]
See [demo](https://jsfiddle.net/travislaynewilson/hwc9wrp2/).

### Expected behavior
Per the [snapping documentation about targets](http://interactjs.io/docs/snapping/), when resizing on either axis, `snapSize` should be causing the resizing to snap to widths or heights in multiples of 20.

### Actual behavior
The first target is snapping literally to 20x20. No other sizer is snapped when resized larger (ie. 40x20, 60x20, 80x20, 20x40, 20x60, 20x80, etc.)

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Chrome 63.0.3239.132
**Operating System**: Windows 10

**Comment by travislaynewilson** [comment]
I discovered that, despite the documentation, the best way to do this is to build a snap grid: 
```
snapSize: {
    targets: [
        interact.createSnapGrid({
            x: 16,
            y: 16,
            range: 16
        })
    ]
}
```

**Comment by Joeao** [comment]
Not sure if this behaviour changes in 1.4.0. If not, maybe this issue should remain open, proposed solution is working just fine.

**Comment by taye** [comment]
The documentation is very wrong so I'm reopening.
