### ISSUE TITLE
Toggling pointer-events:none on iframes causes scrolling issues in Chrome 63+ on Mac

### ISSUE THREAD

**Issue by jkupczak** [taye/interact.js#605]
### Expected behavior
After resizing a container that has an iframe, scrolling with a mouse wheel on that iframe scrolls normally.

### Actual behavior
After resizing a container that has an iframe, scrolling with a mousewheel or trackpad over the iframe doesn't work at all, or works sometimes when hovering over certain parts of the iframe (but not others).

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)
**Operating System**: macOS Sierra 10.12.6

Here is the jsfiddle: https://jsfiddle.net/w67gbL3o/44/
And here is a short video on YouTube showing the problem: https://youtu.be/5dbyi03DF8Y

While a resize handle is being interacted with I give all of the iframes on the page the `pointer-events:none` style by using `.on('resizestart')`. When it ends I am using `.on('resizeend')` to remove the class that applied `pointer-events:none`.

If you try to scroll through the iframe that was inside of the container being resized you'll find that scrolling with the mousewheel or trackpad only works some of the time or not at all. However, scrolling with arrow keys or the scrollbar continues to work.

If you use the resize handles to restore the container to its original full width or height it will continue to be broken. But if you double-click the resizer container or a resize handler, I run a function that removes all of the inlined styling that controls the width and height properties. At this point scrolling is restored.

I was unable to replicate this issue in the latest Firefox or Safari.

**Comment by jkupczak** [comment]
This appears to be fixed in Google Chrome 67.

**Comment by chanpory** [comment]
@jkupczak is there a Chromium bug which details the fix for this bug in Chrome 67? We're trying to troubleshoot a similar issue in our app. @bradvogel @wearhere @pricj004

**Comment by jkupczak** [comment]
@chanpory 

Not sure. Just today I thought to test this out in Canary and I was happy to see it was working just fine. I haven't tested Chrome 66 yet, but I know that the bug happens in Chrome 65 as well.

**Comment by chanpory** [comment]
@jkupczak Thanks for the extra info!
