### ISSUE TITLE
Move/Resize-icons are not shown for most HTML tag elements

### ISSUE THREAD

**Issue by timeraider4u** [taye/interact.js#607]
First, thank you for developing this great library. Unfortunately, I have found something weird which looks like a bug to me:

The move/resize icons are only shown for DIV, LABEL or IMG tags but not for BUTTONs/INPUT elements. The drag&drop and resize actions are working for all elements anyway.

### Steps to reproduce
Reproducibility: Always

Take any example from http://interactjs.io/ e.g.,  the resizing example.
In the HTML body replace
```html
<div class="resize-container">
  <div class="resize-drag">
     Resize from any edge or corner
  </div>
</div>
```
with
```html
<div class="resize-container">
  <button class="resize-drag">
     Resize from any edge or corner
  </button>
</div>
```

### Expected behavior
![image](https://user-images.githubusercontent.com/13469005/36835468-9d6703d8-1d36-11e8-8832-e2af4acc5852.png)
![image](https://user-images.githubusercontent.com/13469005/36835471-a2278ec4-1d36-11e8-8b78-fbfce21b82ac.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/13469005/36835484-aa21790a-1d36-11e8-8508-5b136660c641.png)
![image](https://user-images.githubusercontent.com/13469005/36835491-ad1f2350-1d36-11e8-834a-ad6773d66a05.png)

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**:  Google Chrome 64.0.3282.186, MS IE 11, Mozilla Firefox 58.0.2
**Operating System**: MS Windows 7 (64-bit)

**Comment by xtrimf** [comment]
Same problem v1.3.4
