### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by mesqueeb** [taye/interact.js#612]
Error:
> Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

### Expected behavior
I try and drag an element.

### Actual behavior
Nothing happens.

### System configuration
**interact.js version**: latest cdn
**Browser name and version**: Chrome 64.0.3282.186
**Operating System**: macOS 10.13.3（17D102)

**Comment by taye** [comment]
The readme was out of date and had links to outdated versions. I've updated the [links in the readme](https://github.com/taye/interact.js#installation) so please use one of those. You'll also need to use CSS `touch-action: none` on the target elements.
