### ISSUE TITLE
allowFrom does not seem to work with Element argument

### ISSUE THREAD

**Issue by ferrao** [taye/interact.js#629]
From what I can read in the docs, `allowFrom` should work with either a CSS selector or an element. I can get it to work with a CSS selector, but it does not seem to work with an actual element.

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by taye** [comment]
It won't work if the `allowFrom` element isn't a child of the interactable target. You'd need to make that handle element interactable and redirect the action listeners to the actual element.
