### ISSUE TITLE
Resizing issue for Parallelogram/Trapezoid CSS shape

### ISSUE THREAD

**Issue by mangaultime** [taye/interact.js#633]
Hello,

I have a issue when i resize Trapezoid or Parallelogram. 
If i resize the Height, the Width increase.

For Square and Circle i don't have any issue. If i resize the Heigth, the Width don't increase.

My shape is pure CSS

Trapezoid:
`div[id^=trapezoid] {
  position: absolute;
      top: 50px;
    left: 350px;
    height: 0px;
    width: 125px;
	border-bottom: 50px solid rgba(255, 0, 0, 1);
	border-left: 25px solid transparent;
	border-right: 25px solid transparent;
	max-width: calc(1920px - 50px)!important;
	max-height: 1080px!important;
}`

Parallelogram
`div[id^=parallelogram]{ 
    position: absolute;
    top: 50px;
    left: 200px;
    width: 150px;
    height: 100px; 
     -webkit-transform: skew(20deg); 
     -moz-transform: skew(20deg); 
     -o-transform: skew(20deg); 
     background: rgba(255, 0, 0, 1); 
 }`

This is a JSFilddle for the exemple.

[JSFilddle](http://jsfiddle.net/ckgpmofw/),

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Firefox 60
**Operating System**: Win7 64

Thanks in advance

**Comment by taye** [comment]
interact uses `Element.getClientRects()` to get the size of the elements and width from the returned rect is increased by the skew. You can set the that interact uses to get the element's rect.

```js
interact('.resize-drag').rectChecker(element => {
  const rect = interact.getElementRect(element);
  const correctedRect = { /* set adjusted the top, left, bottom, right, width and hight props */ };

  return correctedRect;
});
```
