### ISSUE TITLE
index.d.ts is too old in stable branch

### ISSUE THREAD

**Issue by andy-maca** [taye/interact.js#637]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
The latest version 1.3.4 is from 'stable' branch, but the index.d.ts in this branch is too old, and there's many problems there, while these problems seems fixed in 'master' branch, please merge it from master to stable branch for the next release.

### Actual behavior
index.d.ts in master brach should be merged to stable branch for the release.

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**:
**Operating System**:

**Comment by taye** [comment]
I don't think it's worth the effort, but I could try to find time to review a pull request to fix this. I consider the `unstable` branch to be the most stable as it's better tested and is now written in typescript.
