### ISSUE TITLE
Two questions about restirct

### ISSUE THREAD

**Issue by ttback** [taye/interact.js#64]
I am trying to restrict an element within the container (the boundary of inside div shouldn't go out or cross the container div's bounds) and not sure what the config would look like. 

On top of that, I don't know if snap() triggers any events. I tried .snap.on('end') but that didn't trigger anything. I need to update something on snap so.

**Comment by SunboX** [comment]
@ttback And the answer is how? Came across here for searching for the same thing. Luckily, you found it. 😢
