### ISSUE TITLE
Missing Documentation for Swipe

### ISSUE THREAD

**Issue by nirmalspeed** [taye/interact.js#641]
Noticed that there's no mention of the `swipe` property in the docs anywhere for this: https://github.com/taye/interact.js/blob/be95b89fc850b23d091ba5a6f310c8e0c31de558/packages/core/InteractEvent.js#L98 

Might be useful for someone who doesn't know about it.

**Comment by taye** [comment]
I'd like to replace the current `event.swipe` property with something more configurable. Do you have a use case I can try to model the new implementation around?

**Comment by filerun** [comment]
This is not fixed, the getSwipe() is not documented anywhere. The event.swipe property doesn't work.

**Comment by gotjoshua** [comment]
agreed. the example doesn't work as is, and the test seems to always return null cuz the prevEvent.speed is too low

workaround
```js
// #HACK  

const prevSpeed = event._interaction.prevEvent.speed
event._interaction.prevEvent.speed = 601
event.swipe = event.getSwipe()
event.swipe.speed = prevSpeed
```

@taye if you want to revive this, i can contribute in the coming weeks

**Comment by TBG-FR** [comment]
Swipe is definitely a must-have feature ! 😉

**Comment by katerlouis** [comment]
I'm confused; is Swipe included as a feature and just not mentioned in the docs or is Interact.js actually missing swipe detection?

**Comment by nkabar** [comment]
@taye hi there - is swipe gesture detection in the newest version included? :) thank you in advance!
