### ISSUE TITLE
Using dropzone while div is restricted to parent?

### ISSUE THREAD

**Issue by atkinsta** [taye/interact.js#642]
I'm trying to keep a draggable div restricted to a parent div so that users don't leave items laying around the page randomly. However, when a dropbox is outside of the parent div, the draggable div does not register a drop event in the dropzone. It registers a drag enter and drag leave even, but not the ondrop event. Is there a better way to handle this? Is there a way to get ondrop to register while a div is restricted to parent? Thanks for taking the time to look at this. 

### Expected behavior
Drag div into dropzone, let go, ondrop event fires, div returns to parent. 

### Actual behavior
Drag div into dropzone, drag enter registers, let go, div returns to parent, drag leave registers. 

### System configuration
most recent interact.js from CDN. 
Google Chrome
Windows 10

**Comment by rogix** [comment]
Hi, Ty! I got the same issue. Have you fixed it since then?

**Comment by atkinsta** [comment]
Hey @rogix , unfortunately not. I just used the on drag leave event as a trigger as a workaround.

**Comment by rogix** [comment]
Thanks, @atkinsta! It works if the restrict option is not used, but I have no idea why.

**Comment by taye** [comment]
I'll try to add a `dropEvent.reject()` method

**Comment by taye** [comment]
I won't have time to work on this feature. I'm closing the issue for now.
