### ISSUE TITLE
when resize a div from the left to right, it will move the div.

### ISSUE THREAD

**Issue by tiandian** [taye/interact.js#643]
please see the demo: https://codepen.io/anon/pen/YvvPKa

when i resize the div by draging the left border to the right, until the width to the smallest, you will see the div's right boder move to the right about 100px(2 x padding's width).
when i set the div.resize-drag's padding's width to 0px, then it will not move.

when resizing the div by draging the top border to the bottom has the same problem.

### Expected behavior
the div should not move to the right.

### Actual behavior
the div dose move to the right.

### System configuration
**interact.js version**:  interact.js-1.3, interact.js-1.4.0-alpha.6
**Browser name and version**: Chrome 67.0.3396.87.
**Operating System**: win7 x64

thanks!

**Comment by taye** [comment]
That's because of the element's paddding/border. Use restrictSize to set a minimum width/height.

```js
interact('.resize-drag')
  .resizable({
    restrictSize: {
      min: { width: 100, height: 100 },
    },
    // ...
  })
```
