### ISSUE TITLE
restrictEdges is not work in v1.4.0-alpha.6

### ISSUE THREAD

**Issue by tiandian** [taye/interact.js#644]
please see the demo: https://codepen.io/anon/pen/rKKaoG

when i resize the div by draging the top border to the top, until out the parent div, you will see the top border is out the  parent div, the .resizable's restrictEdges config doesn't work.

when resizing the div by draging the bottom border to the bottom has the same problem.

### Expected behavior
the div should not be dragged out the parent div.

### Actual behavior
the div is dragged out the parent div.

### System configuration
**interact.js version**:  interact.js-1.4.0-alpha.6
**Browser name and version**: Chrome 67.0.3396.87.
**Operating System**: win7 x64

thanks!

**Comment by taye** [comment]
Thanks for reporting. It's now fixed in `alpha.7`.
