### ISSUE TITLE
Elements appended to iframe cannot be dragged on Chrome

### ISSUE THREAD

**Issue by iwangbowen** [taye/interact.js#645]
The demo https://codepen.io/wangbowen/project/editor/ZQynoy

I want to append elements to iframe and expect them to be draggable but they don't work as expected on Chrome. The JavaScipt code on iframe is the sample code from the project's main page.

### Expected behavior
The elements appended on iframe should be draggable.

### Actual behavior
These elements cannot be dragged on Chrome but are draggable on Firefox and Edge. Not sure whether it's a compatible issue or not.

### System configuration
**interact.js v1.3.4**:
**Chrome 67.0.3396.99, Firefox 61.0**:
**Windows 10**:

**Comment by taye** [comment]
Use [document.adoptNode](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptNode) before appending into the iframe.
