### ISSUE TITLE
Cannot read property 'right' of undefined

### ISSUE THREAD

**Issue by KoeketieneDesign** [taye/interact.js#646]
Hi,

I'm user interactjs with Ember. It's a jigsaw puzzle where I have a dropzone and jigsaw pieces to fit in the puzzle.

Problem: When a user is playing a game and drags a jigsaw, it's possible that another user scans a RFID and the game will route to the menu (so the component where interactjs is instantiated is destroyed). When the component reinitialise, I get an error with "Cannot read property 'right' of undefined" on Interactable.dropCheck. 

I've found that the .unset function doesn't work. I'm trying to do the unset (interact('.puzzle__board').unset();) when my component will be destroyed. Unfortunately it doesn't work. Is there any way to stop the user drag when the component wil be destroyed?

Thanks for the support

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by geovie** [comment]
I'm experiencing a similar problem when an element is removed while the user interacts with it.
In my case if a user clicks and holds a drag-resizable border and does not move the mouse and then the element is removed, interact will throw the error `TypeError: start is undefined`.

@taye I made a small demo of the problem at https://jsfiddle.net/4ro2kwz3/1/
