### ISSUE TITLE
String causes bug

### ISSUE THREAD

**Issue by zsmith3** [taye/interact.js#649]
### Expected behavior
The box should resize slowly as I pull it, while snapping to the grid).

### Actual behavior
Upon attempting to resize a tiny amount, the box suddenly gains thousands of pixels in height.

![ezgif-4-c661c428e2](https://user-images.githubusercontent.com/16140240/43145905-e3a11972-8f57-11e8-9a55-d204112db647.gif)

### Cause of the bug
Under `restrictSize.min.height`, I accidentally put in a string instead of a number, so when this was added to a number in the line:
`arg.options.inner.bottom = rect.top + minSize.height;`
the addition produced a concatenated string, (148 + "25" = 14825 instead of 173). This resulted in the resizing error shown.

I appreciate this error was my own fault (and I have now fixed my bug), not necessarily an issue with Interact. However, it is easy to make this mistake in JS (where the types are often somewhat interchangeable), so I'd suggest a `parseFloat()` (or some kind of error thrown) would be good somewhere.

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Chrome 67
**Operating System**: Win10

**Comment by taye** [comment]
I prefer to leave this responsibility to the developer using the library. It would get messy and tedious to do this everywhere it's possible to happen.
