### ISSUE TITLE
Aspect ratio lost when resize block with min-width/min-height css attrs

### ISSUE THREAD

**Issue by ApaDoctor** [taye/interact.js#650]
When there are min-width and min-height set on block for resize and preserveAspectRatio + min size attrs in js - after gaining minimal css height - it starts to stop respect aspect ratio.
And when you resize image lower then minimals in js - it resizes image to incorect aspect ratio.
So you can't change it with resize to normal ratio(because there is still preserveAspectRatio parameter set

```
  .dragbox {
    min-height: 25px;
    min-width: 25px;
  } // for example it will be image with AR 1:2
```

```
  .resizable({
                preserveAspectRatio: true,
                squareResize: true,
                inertia: true,

                edges: {left: false, right: true, bottom: true, top: false},
                restrictEdges: {
                    outer: 'parent',
                    endOnly: true
                },
                restrictSize: {
                    restriction: 'parent',
                    endOnly: true,
                    min: {width: 70, height: 70}
                }
```
You can fix it removing css min-width & min-height but it's still a bug.

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?
