### ISSUE TITLE
The "height" and "translate Y property" overlap and give problems when resizing.

### ISSUE THREAD

**Issue by adriaroms** [taye/interact.js#653]
The "height" and "translate Y property" overlap and give problems when resizing.

### Expected behavior
Resize a box (black box) without problems (get out of the restriction), in an area restricted to the father (dark grey at the top).

### Actual behavior
When you resize, the values of the "height" and the "translate Y property" overlap or something like this, and it makes the object that we are resizing can get out of the restriction (the parent box).

* [19s video of the problem](https://drive.google.com/file/d/10mvF-GVYiZIV44DXvjiYnAJECBBLQv8f/view?usp=sharing)
* [Code (all the same except for some color and border-radius styles)](http://interactjs.io/#resizing)

### Notes
* The parent is the dark grey at the top of the video.
* We can see that the dragging does not get out the father, but when we resize it's leaves the father restriction, if we try to drag again the object returns to the father's restriction without leaving.

### System configuration
**interact.js version**: 1.3.4 (Source NPM)
**Browser name and version**: Google Chrome 68.0.3440.75 (Mac 64-bit) and Google Chrome 67.0.3396.99 (Windows 64-bit).
**Operating System**: MacOS 10.13.3 and Windows 10 Pro.

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?
