### ISSUE TITLE
Property 'restrictSize' not included in type definition

### ISSUE THREAD

**Issue by kreuzersteve** [taye/interact.js#657]
### Expected behavior
interact.js library compatible with Angular 5/6 since it also provides its own type definitons

### Actual behavior
Error when running a webpack prod build:

```
error TS2345: Argument of type '{ edges: { left: boolean; right: string; bottom: boolean; top: boolean; }; restrictSize: { min: {...' is not assignable to parameter of type 'ResizableOptions'.
--
18-Aug-2018 23:37:10 | Object literal may only specify known properties, and 'restrictSize' does not exist in type 'ResizableOptions'.
```
Used to work for me until an hour ago when the external type definitions for interact.js got deprecated: https://www.npmjs.com/package/@types/interact.js
Fix => integrate the `restrictSize` and `snapSize` properties to the ResizableOptions type definition;
I can provide a PR if that helps.
This issue probably related to #647 

### System configuration
interact.js 1.3.4
Chrome 68.0.3440.106
Win10

EDIT: Another error I'm getting since the deprecation of the alternative type definitions is:
`property rect does not exist on type 'InteractiveEvent'`
I used to use this for resizing:
```
target.style.width  = event.rect.width + 'px';
target.style.height = event.rect.height + 'px';
```

**Comment by garrettmaring** [comment]
Typings for interactjs are fairly incomplete and out of date sadly.

**Comment by devop911** [comment]
Counting on 1.4.0
