### ISSUE TITLE
Not working in Eclipse internal browser

### ISSUE THREAD

**Issue by iwangbowen** [taye/interact.js#659]
The examples on the official website work well on the IE 11 but none of them work on the Eclipse internal browser which happens to be IE 11. I have no any idea what is going wrong because I cannot use devtool in Eclipse. You can open the internal browser in Eclipse and check the official website to reproduce the problem. If it is some problem due to the internal browser limitations, could you please tell me what part of the source code could be the cause. Thanks a lot.

### Expected behavior
The examples on the official website should work as expected.
![qq 20180828134434](https://user-images.githubusercontent.com/26178681/44703006-8f59ac80-aac8-11e8-85b5-e5f45834a958.png)

### Actual behavior
All examples don't work at all.

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Eclipse internal browser and it's Internet Explorer 11.
**Operating System**: Windows 10 Pro

**Comment by taye** [comment]
Can you open a console for the browser to see if there are any errors?

**Comment by iwangbowen** [comment]
No, the console inside Eclipse browser which uses IE 11 internally cannot be opened but every example works as expected in the standalone IE 11.

**Comment by iwangbowen** [comment]
> Can you open a console for the browser to see if there are any errors?

No, the console inside Eclipse browser which uses IE 11 internally cannot be opened but every example works as expected in the standalone IE 11.

**Comment by taye** [comment]
Then it seems like it's a problem with Eclipse, so I'll close this issue.
