### ISSUE TITLE
Dragging by using a handle.

### ISSUE THREAD

**Issue by matula** [taye/interact.js#66]
This is a great library, thanks for the work and releasing it! 
I was wondering if there was a way to make an element draggable, but only by clicking a handle in the element? That way, the whole element isn't clickable.  Thanks!

**Comment by kevzlou7979** [comment]
Can you give a sample code snippet about the implementation? Thanks great framework

**Comment by dpekkle** [comment]
Here's an implementation based on someone elses jsfiddle.

http://jsfiddle.net/dw3xdhch/43/

You can only drag/drop using the handle provided due to 
line 2: allowFrom('.handle')

**Comment by tylercubell** [comment]
When there are two or more handles in a parent element and you need to know which one is being dragged, see https://jsfiddle.net/Lzzrfybg/.
