### ISSUE TITLE
allowFrom not working for draggable handle outside draggable element

### ISSUE THREAD

**Issue by ChrisRedButton** [taye/interact.js#660]
I have this fiddle:
https://jsfiddle.net/xpvt214o/700857/

As you can see, my handle is outside the element that should be dragged. When the element is inside the draggable element it is working (https://jsfiddle.net/xpvt214o/700871/).

How can I get the element outside the draggable element to drag the element?

**Comment by Shotkikk** [comment]
Grab this modified fiddle:
https://jsfiddle.net/0qbfje34

You need Your own function to handle this type of case. The library itself does not support the handle that is outside the movable container. I also added the possibility of moving several blocks at once. (I miss this functionality too)

**Comment by Shotkikk** [comment]
@taye Is it possible to handle this type of case inside interact based on my fiddle? I find it quite crucial... but my code isn't optimized enough and causes framerate drops!

**Comment by ddenev** [comment]
Dear @taye , could you please reopen this issue and follow up on it? Thank you.
