### ISSUE TITLE
resizable and draggable not working together

### ISSUE THREAD

**Issue by ChrisRedButton** [taye/interact.js#661]
I have created a fiddle of how my script looks: https://jsfiddle.net/xpvt214o/701253/
I have draggable and resizable for a single element.
The resizing works perfect, but draggable doesn't do a thing. They both work with different handles.
When I disable resizing then draggable comes to life as well but as soon as I enable resizing draggable is dead again (https://jsfiddle.net/xpvt214o/701281/).

What could the problemen be?

**Comment by quentinus95** [comment]
@taye do you have any suggestion for a workaround for this issue? I can also reproduce it on the demo page with a touch screen http://interactjs.io/

When using draggable with resizable, the draggable event wins on the resizable event. I guess a simple workaround would be to dectect how many touches are enabled and ignore the draggable event if multiple touches are found.
