### ISSUE TITLE
Resize doesn't work properly on html with dir="rtl"

### ISSUE THREAD

**Issue by gmsa** [taye/interact.js#662]
[JSFiddle](https://jsfiddle.net/gmsa/co8zyrnv/)

### Expected behavior
Resize should work the same way as dir="ltr"

### Actual behavior
Element gets moved when resizing, or is resized on the wrong side

### System configuration
**interact.js 1.3.4**:
**Firefox 61.0.2/Chrome 69.0.3497.81**:
**Windows 10**:

**Comment by taye** [comment]
You can set the direction of the parent of the resizable to `ltr` and then it works: https://jsfiddle.net/5c1szhrb/.
