### ISSUE TITLE
latest version (next) has dy/dx set as NaN

### ISSUE THREAD

**Issue by andy9775** [taye/interact.js#670]
I'm trying to replicate the examples page for a draggable component. 1.3.4 works fine (except for returning no implicit any error in typescript) hence I updated to the latest version. However in the latest version, `event.dx` and `event.dy` both return NaN. So do most other fields that should return a number

**Comment by taye** [comment]
Can you make a demo on jsfiddle.net?

**Comment by andy9775** [comment]
I attempted to create a second project but it ended up working. Reinstalling `interactjs@next` seemed to have done the trick oddly enough.
