### ISSUE TITLE
snap event?

### ISSUE THREAD

**Issue by theleprechaun33** [taye/interact.js#671]
Hi. Great library. Thank you!

Is there an event I can attach to that fires when one item snaps to another? I am trying to determine when a snap happens so I can pull data about the item that I am snapping to and make adjustments.

**Comment by taye** [comment]
I've opened PR #772 which adds an `event.modifiers` property which will contain info about each of the modifiers applied to the action. Right now, there's only info for snap events. Would this work for your use case?
