### ISSUE TITLE
Nested dropzones

### ISSUE THREAD

**Issue by seanchambo** [taye/interact.js#672]
### Expected behavior
When there are nested dropzones, entering a nested dropzone should not fire a `leave` event on the parent dropzone.

### Actual behavior
A `leave` event is being fired on the parent dropzone when dragging into a nested dropzone

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Chrome
**Operating System**: Ubuntu

**Comment by taye** [comment]
I'll try to address this in the next minor realease.

**Comment by paulm17** [comment]
I'm having trouble with nested dropzones in a vanilla js d&d I have created. 

Checking in to see whether this was added to interact.js, as then I will take a look to see whether it will resolve my issue.

Thanks!

**Comment by taye** [comment]
I won't have time to work on this issue. I'll close it now and I might come back to it much later.

**Comment by paulm17** [comment]
Just want to point out.  Nested dropzones do indeed work.

**Comment by yulafezmesi** [comment]
do you have any examples to show @paulm17 ?
