### ISSUE TITLE
Inconsistent snap destination

### ISSUE THREAD

**Issue by garrettmaring** [taye/interact.js#674]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
The "bottom" snap (0th height of the parent) should always be the target snap position.

### Actual behavior
It usually snaps fully to that position. However, sometimes it will not snap fully. It will stop 5-15 pixels away from reaching the snap destination.

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Chrome (latest)
**Operating System**: macOS

```javascript
      interact(shareNode)
        .resizable({
          // resize top only
          edges: { top: true },

          // keep the edges inside the parent
          // @ts-ignore
          restrictEdges: {
            outer: 'parent',
            endOnly: true,
          },

          // @ts-ignore
          snap: {
            targets: [
              // @ts-ignore
              () => {
                return this.withShare((shareNode) => {
                  const rect = getElementRect(shareNode.parentElement);
                  return { y: rect.bottom, range: 100 };
                });
              },
              // @ts-ignore
              () => {
                return this.withShare((shareNode) => {
                  const rect = getElementRect(shareNode.parentElement);
                  // @ts-ignore
                  return { y: rect.top, range: Infinity };
                });
              },
            ],

            // @ts-ignore
            endOnly: true,
          },

          inertia: {
            resistance: 10, // the lambda in exponential decay
            minSpeed: 100, // target speed must be above this for inertia to start
            endSpeed: 10, // the speed at which inertia is slow enough to stop
            allowResume: true, // allow resuming an action in inertia phase
            smoothEndDuration: 300, // animate to snap/restrict endOnly if there's no inertia
          },
        })
        .on("resizemove", function(event: interact.InteractEvent) {
          // @ts-ignore
          event.target.style.height = event.rect.height + "px"
        })

```

**Comment by garrettmaring** [comment]
I suspect something is incorrect with my snap configuration. I'm seeing the snap to the top to be consistently arriving at the value. However, the snap to the bottom never reaches a consistent/complete value. I've checked that `rect.bottom` is always returning the correct destination value.

**Comment by garrettmaring** [comment]
Another interesting note is that there are inconsistent snap destinations on the "top" target when I remove `restrictEdges`. For context, the goal here is a 500 height div. If resized above 250px it snaps to the top, if it below that it snaps back to 0. Dragging over the edge also snaps it back to 500.

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

snap and restrict modifiers don't always combine perfectly. With the new modifiers API in `v1.4.0-alpha`, you can specify an order for the modifiers which might make things behave more predictably. https://github.com/taye/interact.js/blob/master/guide/modifiers.md
