### ISSUE TITLE
Drag area is smaller than element

### ISSUE THREAD

**Issue by rockblock** [taye/interact.js#676]
We have a simple box, where it's head area is draggable. 

The head is a separate DIV container. It contains some input fields, which are excluded from dragging and it works fine. But on the right edge there is around 20px space, where dragging is not possible. In Chrome and FF there is nearly no drag area on the right side, in Safari the area is a bit bigger.

We're are using a standard JS setup and our HTML of the drag element looks like this

```
<div class="fv_fp_transcript_head">
<label>Autoscroll:</label>&nbsp;<input class="fv_fp_transcript_autoscroll" type="checkbox" checked=""><label>Search:</label>&nbsp;<input class="fv_fp_transcript_search" type="text"><input type="button" class="search_result_prev" value="<" disabled=""><input type="button" class="search_result_next" value=">" disabled="">
</div>
```

CSS goes like this:

```
.fv_fp_transcript_head {
    padding: .5em .5em 0;
    height: 46px;
    width: 100%;
    user-select: none;
}
```

I've tried to remove padding from this element and also other options, but none of them worked.

thanks
Viktor

**Comment by blexxed** [comment]
I also encounter the same scenario. I found out that it happens when I use both `resizable` and `draggable` in the same div. I works properly when I remove the `resizable` option

has undraggable area:
```
interact('.sample')
        .resizable({
          allowFrom: '.resize-handle',
          edges: {
            left: true,
            right: true,
            bottom: true,
            top: true,
          },
          onmove: handleResizeMove,
          onend: handleResizeEnd,
        })
        .draggable({
          onmove: handleDragMove,
          onend: handleDragEnd,
        });
```

works perfectly:
```
interact('.sample')
        .draggable({
          onmove: handleDragMove,
          onend: handleDragEnd,
        });
```

**Comment by blexxed** [comment]
A workaround that worked for me is separating the `draggable` and 'resizable` interactions.

```
interact('.sample--resizable')
        .resizable({
          allowFrom: '.resize-handle',
          edges: {
            left: true,
            right: true,
            bottom: true,
            top: true,
          },
          onmove: handleResizeMove,
          onend: handleResizeEnd,
        });

interact('.sample--draggable')
        .draggable({
          onmove: handleDragMove,
          onend: handleDragEnd,
        });
```

**Comment by rockblock** [comment]
Thanks for the workaround, I will check it out.

**Comment by rockblock** [comment]
Confirming it works, thank you.
