### ISSUE TITLE
Example files buggered

### ISSUE THREAD

**Issue by stevehomer** [taye/interact.js#678]
Forgive me but completely crap here (Git).

I zip downloaded interact just to have a further look at some examples.

Unfortunately all the examples seem to have:

<script src="../../dist/interact.js"></script>

but there is no dist folder. I may be being 100% stupid here but I have downloaded a myriad bits and bobs and not had this problem before.

It does look lovely however.

ATB Steve

**Comment by taye** [comment]
Hi Steve. Sorry for the late reply.

You need to have [node](https://nodejs.org/en/) installed and inside the repo directory, run:

```sh
npm run bootstrap; npm run build
```

**Comment by stevehomer** [comment]
Taye hi

Sorry not using node (nor composer, nor ... too many other things trying to get reasonable at!).

I have downloaded many things from GIT and not had a problem with zips. Normally u just download etc.

Ah well good luck with the project.
