### ISSUE TITLE
Draggable edges are not drag-sensitive on resize-exluded elements

### ISSUE THREAD

**Issue by vks-financial-com** [taye/interact.js#681]
Given is a draggable and resizable activated container. The container has semantic header, body and footer. Dragging is only allowed from the header. Resizing is allowed generally except from the header.
Please see the corresponding fiddle: https://jsfiddle.net/xra6oq4p/5/

My issue is the following: I excluded the header from resizing (ignoreFrom), so it doesn't respond to resizing attempts - this is correct. But the header also doesn't respond to dragging attempts on the edges - this should not happen, as I'd expect it to be drag-sensitive on its edges as well after resizing is deactived.

How do I solve this?

Also a bonus question: is it possible to define the size of the edges for resizing? Currently it's 20px I belive, which is a bit too wide for my use-case.

**Comment by taye** [comment]
Considering the `allowFrom` and `ignoreFrom` options when checking the `boolean` edges would be too complecated in my opinion. I think the best solution is to wrap the `.content` and .`footer` with an element which you make resizable separately from the draggable header.
