### ISSUE TITLE
iOS 11 Safari error with v1.4.0-alpha.17 

### ISSUE THREAD

**Issue by mrsweaters** [taye/interact.js#682]
On iOS 11 Safari I get the following error when upgrading from 1.3.4 to v1.4.0-alpha.17.

```
TypeError: Attempting to change value of a readonly property.
```

Stack trace says the error is in core.min.js line 8. Downgrading resolves the issue.

**Comment by timothyallan** [comment]
I had the same thing. Ended up searching for `makeModifier` and putting a try catch around this block. Haven't done any testing, but it at least runs my app now :) 
```
if (typeof name === 'string') {
      try {
        Object.defineProperty(modifier, 'name', {
          value: name,
        }); // for backwrads compatibility
      } catch (err) {}

      modifier._defaults = defaults;
      modifier._methods = methods;
    }
```

**Comment by timothyallan** [comment]
Thanks Mr Stale Bot. It's still in alpha 32

**Comment by taye** [comment]
@mrsweaters @timothyallan do you have a simple demo to reproduce this?

**Comment by alpritt** [comment]
I can see this problem on desktop Safari version 9. I can trigger the above error by simply importing it:

```
<!DOCTYPE HTML>
<html>
  <head>
    <script src="https://unpkg.com/interactjs/dist/interact.min.js"></script>
  <body>
  </body>
</html>
```

**Comment by AleColl** [comment]
These are the errors that I get on Ipad2 and Ipad mini when opening the interactjs site.

![screen](https://user-images.githubusercontent.com/16189135/58012849-ad06f000-7af5-11e9-80de-10c04e34f801.png)

**Comment by mrsweaters** [comment]
Thanks @taye!
