### ISSUE TITLE
After resize event, my target element's either width or height is automatically increasing

### ISSUE THREAD

**Issue by MattaAvinashReddy** [taye/interact.js#683]
I am trying to implement interact-draggable and interact-resizeable on same element
providing ActionOptions different( i tried same Action Options too).

My problem is after Resizing the element, sometimes my element's height or width is automatically increasing either width or height value.

Note: As per my observation, the reason for increase in Height or Width is due to increase in dx or dy value

Here is my code

-----------------------------
 <div style="height:50px"    interact-draggable.bind="draggableOption" 
                  interact-dragmove.delegate="dragMove($event)" 
                  interact-resizable.bind="resizeableOption" 
                  interact-resizemove.delegate="reizeMove($event)" > 
                      Resize
                  </div>

-----------------------TS Code---------------------
draggableOption = {
    action:{
      inertia: true,
    restrict: {
      restriction: "parent",
      endOnly: true,
      elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
    },
    autoScroll: true
  }
  }
// this is same ActionOption for both drag and resize interactable 
  totalOption ={
    action :{

      edges: { right: true, bottom: true, top: false, left: false },

      restrict: {
        restriction: "parent",
        endOnly: true,
        elementRect: { top: 0, left: 1, bottom: 1, right: 1 }
      },
      autoScroll: false
    }
  }
  resizeableOption = {
    action: {
     
      edges: { right: true, bottom: true, top: true, left: true },

      // keep the edges inside the parent
      restrict: {
        restriction: "parent",
        endOnly: true,
        elementRect: { top: 1, left: 1, bottom: 1, right: 1 }
      },
      inertia: true,
  }
  };

  reizeMove(customEvent){

    var event = customEvent.detail;
    var target = event.target, x = (parseFloat(target.getAttribute('data-x')) || 0), y = (parseFloat(target.getAttribute('data-y')) || 0);
                target.style.width = event.rect.width + 'px';
                target.style.height = event.rect.height + 'px';
                x += event.deltaRect.left;
                y += event.deltaRect.top;
                target.style.webkitTransform = target.style.transform =
                    'translate(' + x + 'px,' + y + 'px)';
                target.setAttribute('data-x', x);
                target.setAttribute('data-y', y);
                target.classList.add('getting--resized');
  }

  dragMove(customEvent){
    
    var event = customEvent.detail;
    var target = event.target, 
    x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx, 
    y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;
    target.style.transform = 'translate(' + x + 'px, ' + y + 'px)';
    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
    target.classList.add('getting--dragged');

  }

**Comment by jccalaguas7399** [comment]
sir do you run this code already? because my code is not working what is the first thing to do to run this code?

**Comment by jccalaguas7399** [comment]
//resize
const interact = require('interactjs');

interact('.items')
  .draggable({
    onmove: window.dragMoveListener,
    restrict: {
      restriction: 'parent',
      elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
    },
  })
  .resizable({
    // resize from all edges and corners
    edges: { left: true, right: true, bottom: true, top: true },

    // keep the edges inside the parent
    restrictEdges: {
      outer: 'parent',
      endOnly: true,
    },

    // minimum size
    restrictSize: {
      min: { width: 100, height: 50 },
    },

    inertia: true,
  })
  .on('resizemove', function (event) {
    var target = event.target,
        x = (parseFloat(target.getAttribute('data-x')) || 0),
        y = (parseFloat(target.getAttribute('data-y')) || 0);

    // update the element's style
    target.style.width  = event.rect.width + 'px';
    target.style.height = event.rect.height + 'px';

    // translate when resizing from top or left edges
    x += event.deltaRect.left;
    y += event.deltaRect.top;

    target.style.webkitTransform = target.style.transform =
        'translate(' + x + 'px,' + y + 'px)';

    target.setAttribute('data-x', x);
    target.setAttribute('data-y', y);
    target.textContent = Math.round(event.rect.width) + '\u00D7' + Math.round(event.rect.height);
  });

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by MattaAvinashReddy** [comment]
Sorry, I am using Aurelia-InteractJs(https://github.com/eriklieben/aurelia-interactjs)
which is built upon interact js. 
with Interactjs working fine, but when i use Aurelia-InteractJs frameWork i have this problem.
I will close this issue

**Comment by MattaAvinashReddy** [comment]
close #X
