### ISSUE TITLE
Control the thickness of resizing edge

### ISSUE THREAD

**Issue by YousefMMS** [taye/interact.js#685]
Hi,

I'm looking for a way to control the resizing edge thickness.

when you hover on the edge of a resizable element the cursor style changed to 'whatever-resize', sometimes this edge is very thick. I understand it may be a little bit thick for acceptability reasons like touch devices, but it'll be great if it's controllable.

**Comment by taye** [comment]
```js
interact(target).resizable({
   margin: 50,
})
```

**Comment by TabCrazy** [comment]
> ```js
> interact(target).resizable({
>    margin: 50,
> })
> ```

It's not easy to find it. There seems to be no update in the document

**Comment by dragon99k** [comment]
Hi, 
I'am looking for a way to control the resizing edge thickness.
I used the "margin", but it changed in inner direction.
I want to change the thickness to outer direction.
