### ISSUE TITLE
Draggables become hidden as the leave the dropzone with overflow: scroll

### ISSUE THREAD

**Issue by mrspinn** [taye/interact.js#687]
### Expected behavior
Draggables stay visible when dragging between dropzones

### Actual behavior
Draggables become hidden as the leave the origin dropzone.

I have two dropzones. One begins with all of the draggables in it and is scrollable. When dragging out of the origin dropzone, the draggables become hidden.

I've tried all of the suggested methods such as setting overflow: visible and position: absolute on the draggables. I've also tried almost every possible combination of z-indexes that could possibly make sense.

Here's a JSfiddle with the problem re-created: http://jsfiddle.net/L5g9prao/1/

Any assistance would be greatly appreciated. Thanks!

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Google Chrome | 71.0.3578.98
**Operating System**: Mac High Sierra 10.13.6

**Comment by marcdubs** [comment]
I'm also experiencing this same problem. The work-around I found was to move the target to a different place when the drag is started, but this is pretty messy. Hoping there is a better solution.

**Comment by mrspinn** [comment]
Excellent!!! That works perfectly for my problem! Thanks @marcdubs!!!

**Comment by calope03** [comment]
@mrspinn maybe you can close this issue
