### ISSUE TITLE
Draggable only works after resize

### ISSUE THREAD

**Issue by millertn** [taye/interact.js#688]
I have many divs with the same class that are draggable by clicking and dragging on a move handle and resizable when clicking and dragging on the edges.

### Expected behavior
The element can be dragged or resized in any order

### Actual behavior
 I get a 'Uncaught TypeError: Cannot read property 'start' of undefined' error when I attempt to drag before resizing. I can resize literally *any* element with the class before dragging and it fixes all of them, but unless I resize an element first it returns that error.

### System configuration
**interact.js version**:1.3.4

**Comment by taye** [comment]
Can you make a demo on codepen.io?
