### ISSUE TITLE
Dragging elements inside the cage

### ISSUE THREAD

**Issue by username1565** [taye/interact.js#689]
Is this possible, to dragging elements inside the cage, like here: http://jsfiddle.net/wfMLe/2/
If yes, can you add this as example to http://interactjs.io/ ?
I see your example "Snapping" but there is one element and this is dragging after area...
Need to using many elements, to change this positions in the cage, after gragging some element...

**Comment by taye** [comment]
This question is more suitable for stackoverflow.com
