### ISSUE TITLE
Fixed position container breaks draggable position on scroll

### ISSUE THREAD

**Issue by hoppities** [taye/interact.js#692]
[Fiddle](https://jsfiddle.net/fq7obtne/)

In the above fiddle, I have a fixed position container that has two draggable items. When I grab one to drag it up to the dropzone, everything works fine if I do not scroll. However, once the user scrolls, the position of the element changes and moves away from where the mouse position is.

### Expected behavior
An Element should always stay with the mouse while moving it around

### Actual behavior
On scroll, the element moves an offset based on how far the user scrolls

### System configuration
**interact.js version**: 1.2.9
**Browser name and version**: Chrome
**Operating System**: Windows

**Comment by vFire** [comment]
Same problem, when scrolling in a parent div, not the body or window, the problem occurs, possiblly maybe should add a xFix, or Yfix parameter could help developers fix it.
