### ISSUE TITLE
Gesture onmove events sent twice

### ISSUE THREAD

**Issue by stalb** [taye/interact.js#695]
Multi-touch gesture events are sent twice (once for each finger ??)

No codefiddle; this is reproducible on the multi-touch  demo on the [homepage](interactjs.io).

### Expected behavior
When moving, resizing and rotating an objet using a 2 fingers action, I would expect the object to follow the two fingers movements.
Moving my fingers to the right, should drag the object to the right by the same distance
Rotating my fingers by 90° should rotate the  object by 90°
etc.

### Actual behavior
When you move your 2 fingers to the right (for example by 100px), the amplitude of the object movement is twice bigger (e.g. 200px).
Same problem with rotation: if you make a 90° rotation, the objet rotation is 180°
For pinch to zoo see also bug #537 

### How to reproduce:
    1. On the homepage Multi-touch Rotation example, rotate your fingers 90°, the arrow rotates by 180° 
    2. On the homepage Pinch-to-zoom example, move your two fingers to the right, the image movement is twice the one of your fingers

### System configuration
**interact.js version**: interact-1.3+  (correct behavior up to version 1.2.9)
**Browser name and version**: any 
**Operating System**: any

**Comment by taye** [comment]
Thanks for reporting!

**Comment by taye** [comment]
I've introduced another bug that I'll try to fix soon.

**Comment by stalb** [comment]
Do you want a patch for the 1.3.x branch ?

**Comment by taye** [comment]
Yes, that would be nice. Please apply it to the `v1.3-bugfix` branch. However, I recommend using the alpha version. All that's missing there is some more documentation which I'm currently working on: https://github.com/taye/interact.js/tree/master/guide

By the way, I didn't introduce another bug, the demo on the homepage was just depending on the bug.
