### ISSUE TITLE
Dragging element  been released when it is underlying others 

### ISSUE THREAD

**Issue by iapyeh** [taye/interact.js#696]
Say, a &lt;DIV-A ;z-index=1&gt; is dragging around, when it is underlying another &lt;DIV-B; z-index=10&gt;, if the mouse been released, then the "dragend" event is not fired so that the &lt;DIV-A&gt; keeps to follow the mouse cursor without dragging.

### System configuration
**interact.js version**:  1.3.4
**Browser name and version**:  Chrome version is 71.0.3578.98
**Operating System**: Operating System: Mac OS (10.14.2) | Browser Engine: WebKit (537.36)

**Comment by taye** [comment]
Please make a codepen of jsfiddle deom.
