### ISSUE TITLE
Remove window size drawn on window from interact.js

### ISSUE THREAD

**Issue by coreybruce** [taye/interact.js#697]
Hey all just wanted to ask how do I remove the window size draw on the window when you resize the windows in interact.js as I don't need it and it removes anything inside the window.

**Comment by taye** [comment]
Can you make a codepen demo or post a screenshot/screencast?

**Comment by coreybruce** [comment]
Sure, here is the window by default with the text content in it 
http://i.imgur.com/hxPYfXy.png

and when I resize it the content inside is remove and replaced with a window size readout and will change to according to the window size and don't want it to do that or remove the window content.

http://i.imgur.com/ylMuzmE.png

**Comment by taye** [comment]
You should check your `resizemove` listener function. I guess you're using the code from the homepage.  Remove the line that has

```js
target.textContent = Math.round(event.rect.width) + '\u00D7' + Math.round(event.rect.height);
```

**Comment by coreybruce** [comment]
oh ok thank you very much
