### ISSUE TITLE
getCursor better be extendable

### ISSUE THREAD

**Issue by minzojian** [taye/interact.js#698]
sometimes, we use interact.js on a control element, eg. a rotate dot, and when hover on that element, we want the cursor to be another icon than the default 'move' cursor. (in 'actions/drag.ts' code, getCursor just return a fixed value 'move')

maybe it can add a new option in each action like 'customCursor' which can be a function, and set the Interactable object as context.

I try to write in my local code, but build failed, maybe someone can try it and pull a new request

     getCursor () {
        if(this.options.customCursor)
          return this.options.customCursor.apply(this);
        return 'move'
      },

**Comment by taye** [comment]
Great idea!
