### ISSUE TITLE
Dragging Glitches while using Bootstrap 4

### ISSUE THREAD

**Issue by webciter** [taye/interact.js#702]
Does anybody know why the dragging operation is glitching.

Video Demonstration of glitch
https://youtu.be/ywAoloUiGzc

Code
 interact(elements.item(i))
                              .draggable({

                                allowFrom: '.draggableHandle',
                                snap: {
                                  targets: [
                                    interact.createSnapGrid({ x: 10, y: 10 })
                                  ],
                                  range: Infinity,
                                  
                                },
                                inertia: true,

                                restrict: {
                                  restriction: parentElement,
                                  elementRect: { top: 1, left: 1, bottom: 1, right: 1 },
                                        endOnly: true
                                }
                              })
                              .on('dragmove', function (event) {
                                x += event.dx;
                                y += event.dy;

                                event.target.style.webkitTransform =
                                event.target.style.transform = 
                                    'translate(' + x + 'px, ' + y + 'px)';

                              }).on('dragend', function(event){
                                  console.log(event.currentTarget.style.transform);
                                  window.app.container.reorganizeContainerY("designer_zone", "draggableRow");

                              });

**Comment by jpatel888** [comment]
I had a similar issue, and I’m not totally sure why, but running the script that uses interact before interact itself solved the problem, no idea how, I could’ve just gotten lucky with browser caching, but play with the order of your script tags in html and see if that solves it.

**Comment by webciter** [comment]
sorted it now it was variable scope, my fault.

**Comment by Shmacked** [comment]
@webciter could you be a little bit more specific? I am having relatively the same issue.
