### ISSUE TITLE
recompile question

### ISSUE THREAD

**Issue by quasiperfect** [taye/interact.js#704]
hi

is there any documentation on recompiling the library to support for example only pointer events ?

thanks in advance for your help

**Comment by fuzzzerd** [comment]
I've been trying to build the library myself; and have been running into all kinds of trouble getting the dependencies working. I'm trying to setup a local environment so I can try to put together a PR to fix #703 but so far have not yet been able to get it running locally. 

I too would love some guidance on setting up a local build environment for interactjs.

**Comment by fuzzzerd** [comment]
I discovered that as-is the master branch (and most of the others) do not run/build on windows. I tried it on a ubuntu vm and it pretty much just worked. 

```
git clone
npm run bootstrap
npm run start
```
Creates a working local version of interactjs.

I suspect you could modify the lerna package dependencies to drop the other modules, but could be side effects of amputating packages that I'm unaware of, as I'm only just becoming familiar with the code base.

**Comment by taye** [comment]
@quasiperfect It's not stable yet, but you can import each of the [internal packages](https://github.com/taye/interact.js/tree/master/packages) selectively and set things up the way you need. Have a look at https://github.com/taye/interact.js/blob/master/packages/interact/index.ts for how it's done for the bundled library.

**Comment by quasiperfect** [comment]
thanks @taye i will give it a try

**Comment by taye** [comment]
Update: https://github.com/taye/interact.js/issues/800#issuecomment-596032510
