### ISSUE TITLE
Text select when resize

### ISSUE THREAD

**Issue by valentinsld** [taye/interact.js#705]
Hello,

I have a bug when I resize the div : the text is selected, which is rather annoying.
Is there a way to avoid this?

![bug](https://user-images.githubusercontent.com/43878560/54074996-ba079780-4299-11e9-90e0-94efa41f4e72.gif)
My code on [codepen](https://codepen.io/valmax72/pen/mowXbw)

**Comment by taye** [comment]
Use CSS `user-select: none`.
