### ISSUE TITLE
Build only some features of interact.js

### ISSUE THREAD

**Issue by dmo-odoo** [taye/interact.js#707]
Hello,

I am currently looking at integrating interact.js in our project. However, we are quite wary of the file size of libraries added to our assets files.

Considering we would only use some of the features of interact.js (draggable, dropzone and resize), is there a way we can selectively filter which features we want to be included in the file in order to have the smallest lib footprint ?

Best regards,
David

**Comment by taye** [comment]
@quasiperfect It's not stable yet, but you can import each of the [internal packages](https://github.com/taye/interact.js/tree/master/packages) selectively and set things up the way you need. Have a look at https://github.com/taye/interact.js/blob/master/packages/interact/index.ts for how it's done for the bundled library.

**Comment by gmsa** [comment]
@taye any example on how this can be done from an external project? Been trying for a few hours but can't get past this:

```
    import * as actions from "@interactjs/actions";
    import * as pointerEvents from "@interactjs/pointer-events";
    import interact from "@interactjs/interact";

    interact.use(pointerEvents);
    interact.use(actions);

```
> vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'signals' of undefined
    at Object.install (gesture.js?599a:43)
    at Scope.usePlugin (scope.js?a54e:78)
    at Module.install (index.js?86a8:6)
    at Scope.usePlugin (scope.js?a54e:78)

**Comment by taye** [comment]
@gmsa you should first call `scope.init(window)`.

**Comment by jayantbh** [comment]
Hi, @taye. Could you update the links in your comment above?
![image](https://user-images.githubusercontent.com/7949047/79019901-fd1af500-7b94-11ea-86f8-d80c55e4afbd.png)

**Comment by taye** [comment]
@jayantbh There's an update in https://github.com/taye/interact.js/issues/800#issuecomment-600860137
