### ISSUE TITLE
Overlap positions not updated when DOM changes while dragging ?

### ISSUE THREAD

**Issue by dmo-odoo** [taye/interact.js#708]
Hello,

We would like to remove our dependency to jQuery.ui and for this, I am currently trying to implement "sortable" using interact.js.

I am not asking for help to do this (you probably have better things to do ;-)), but I am facing an issue that makes me unsure about the possibility of my implementation.

In "sortable", when you drag an element over other elements, you want that the other elements move away from the element you are dragging to make room for it, to show where you are going to insert the element if you were to drop it now. To do this in my test implementation, I use a clone of the element I am dragging with half opacity.

The problem is that, since the elements positions are changed by the presence of the cloned placeholder, I have ondragenter events called on wrong elements. It looks like the overlap are computed using the old position of the elements rather than the new one.

I know the explanation is confusing, so I made a video:
https://drive.google.com/file/d/15ldc96EveG9qrTSMcJ7aI5scWuA1Tx7f/view?usp=sharing

For the first 6 seconds, everything works fine. I drag "Global Solutions: Furniture" over "Quote for 600 chairs" and it is pushed away as the placeholder moves below it. Same when I continue to drag it over "Info about services".

However, the problem arises when I go up from there. When I drag the element over "Info about services", ondragenter is called on "Quote for 600 chairs" instead of "Info about services". I checked with console.logs and ondragenter is not called on "Info about services" at all, so this is not two events happening very quickly. It is only calling ondragenter on "Quote for 600 chairs" even though I am not dragging over it at all. Since "Info about services" is at the spot where "Quote for 600 chairs" used to be at the start when I called interact dropzone on them, it leads me to believe that the overlap computation uses the position from the beginning and do not update them as the DOM changes.

Could you please help me shed some light on this ? Do you know if it should definitely work and I did something wrong ? Or if changing the DOM on drag events is not really supported by interact.js ?

Thank you,
David

EDIT: I made a small fiddle example to abstract the problem from our framework: https://jsfiddle.net/c1ft42ov/3/
And the video showing the issue on the fiddle: https://drive.google.com/file/d/1rOu-L1R-C9FVNgI1tEEJRl28NWIs_HsL/view

**Comment by taye** [comment]
Try using `interact.dynamicDrop(true)`.

**Comment by dmo-odoo** [comment]
That was it, thank you very much !
