### ISSUE TITLE
Missing hint in documentation of required touch style

### ISSUE THREAD

**Issue by Agent77326** [taye/interact.js#709]
To enable touch-dragging you need to set css-style to `touch-action: none;`. Otherwise dragging get's canceled after dragging it for about 10px. I did not further research into that, but I would appreciate it if @taye could add this as hint in his faq or documentation.

(Found this style-tag in your demo-code on the webpage)

**Comment by taye** [comment]
I've added this info to the docs and in the development (non minified build) `console.warn` hints will be shown when `touch-action` is missing.
