### ISSUE TITLE
Revert back to orginal position but with nice animation (works on .drop-drag but doesn't on .yes-drop)

### ISSUE THREAD

**Issue by niedobrymisko** [taye/interact.js#710]
Hi, I'm making quiz/game using puzzle mechanizm. Dropping wrong puzzle to drop zone it revert back to original position with nice smooth effect but when I drop correct puzzle but not in drop zone but somewhere else it revert to original position without animation. I have tried setting CSS in code, changing class and every draggable element with class .drag-drop works fine but this one droppable with id or class .yes-drop return to position without animation.

`var startPos = {x: 0, y: 0};

    function dragMoveListener (event) {
      var target = event.target;
          // keep the dragged position in the data-x/data-y attributes
          x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
          y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;
         
      // translate the element
      target.style.webkitTransform =
      target.style.transform =
        'translate(' + x + 'px, ' + y + 'px)';
  
      // update the posiion attributes
      target.setAttribute('data-x', x);
      target.setAttribute('data-y', y);
    }

    function dragStartListener(event){
      var target = event.target;
      var rect = interact.getElementRect(target);
      // record center point when starting the very first a drag
      startPos = {
        x: rect.left + rect.width  / 2,
        y: rect.top  + rect.height / 2
      }
      event.interactable.draggable({
        snap: {
            targets: [startPos],
            range: Infinity,
            relativePoints: [ { x: 0.5, y: 0.5 } ],
            endOnly: true 
        }
      })
    }

    function dragEndListener(event){
  
      var target = event.target;
// target.style.webkitTransition =
// target.style.transition = '2s ease-in-out'; <-- DOESN'T WORK
// target.classList.add('animate'); <-- DOESN'T WORK
     
    $('.yes-drop').animate({left:"+=300"}, 5000, function(){}); <-- IT WORKS BUT I'M LOOKING FOR MORE ELEGANT SOLUTION :)
      
    }

    interact('.drag-drop').draggable({
      snap: {
        targets: [startPos],
        range: Infinity,
        relativePoints: [ { x: 0.5, y: 0.5 } ],
        endOnly: true  
    }  
    })
    .on('dragmove', dragMoveListener)
    .on('dragstart', dragStartListener)
    .on('dragend', dragEndListener)

  // !!!!!!!  DROPZONE  !!!!!!!
  interact('.dropzone').dropzone({
    // only accept elements matching this CSS selector
    accept: '.yes-drop',
    // Require a 75% element overlap for a drop to be possible
    overlap: 0.40,
      ondragenter: function (event) {             // when element enter in the dropzone (and has the possibility of a drop)
          var draggableElement = event.relatedTarget,
              dropzoneElement  = event.target,
              dropRect         = interact.getElementRect(dropzoneElement),
              dropCenter       = {
                  x: dropRect.left + dropRect.width  / 2,
                  y: dropRect.top  + dropRect.height / 2
              };

          event.draggable.draggable({
              snap: {
                  targets: [dropCenter]
              }
          });     
      },
      ondragleave: function (event) {
         // when element is dragged out from dropzone
          event.draggable.draggable({
              snap: {
                  targets: [startPos]
              }
          });
          
      },
      ondropactivate: function (event){
        
        
      }
  })
  window.dragMoveListener = dragMoveListener;`

**Comment by patchthecode** [comment]
what did you do to get this working?
