### ISSUE TITLE
Cannot set property 'activeDrops' of undefined

### ISSUE THREAD

**Issue by johannes-z** [taye/interact.js#716]
### Actual behavior
I upgraded to `1.4.0` and now my app throws this error:

```
TypeError: Cannot set property 'activeDrops' of undefined
    at interact.js:408
    at Signals.fire (interact.js:7875)
    at Interaction.stop (interact.js:3835)
    at Interactable.unset (interact.js:4788)
```

### System configuration
**interact.js version**: 1.4.0
**Browser name and version**: Google Chrome Version 74.0.3729.108
**Operating System**: Windows 10

**Comment by jf-m** [comment]
Hi,

I've got the same behavior.
If needed the correction is in my pull request #715 for #713

Fix:
https://github.com/taye/interact.js/pull/715/commits/c9485766f0fd42dfe652376a4b701c045dd8d798

Cheers 🍺

**Comment by adrienbataille** [comment]
Having the same problem...

**Comment by dreamershl** [comment]
same here

**Comment by taye** [comment]
Thanks for the fix @jf-m!
