### ISSUE TITLE
Cannot prevent tap of parent in tap of child

### ISSUE THREAD

**Issue by Jetroid** [taye/interact.js#718]
When both parent and child have tap event, it is not possible to prevent default inside the child's event to prevent the parent's event. 

Fiddle here: https://jsfiddle.net/dptLms6n/11/

### Expected behavior
Prevent default in tap in child element should prevent tap of parent element.

In the fiddle:
Clicking the blue square (child element) should add just a '2' to the 'console'
Clicking the coral square (parent element) should add just a '1' to the 'console'

### Actual behavior
Prevent default does not prevent tap of parent element.

Clicking the blue square (child element) adds a '21' to the 'console'. (Because both events are called)

**Comment by Jetroid** [comment]
To anyone seeing this with the same problem:

I was able to work around this issue in my project by changing the `#parent` tap interaction to look like this:

```
interact('#image')
        .pointerEvents({ignoreFrom: '#child'})
        .on('tap', function(event){
                //blah blah
        })
```
(the `.pointerEvents` line)

But for some reason when I add this to the fiddle it stops the parent interacting at all.

**Comment by taye** [comment]
You can also use `event.stopPropagation()` or `event.stopImmediatePropagation()`
