### ISSUE TITLE
Stuck touch when element removed on iOS

### ISSUE THREAD

**Issue by calrsom** [taye/interact.js#723]
Bug repro: https://codepen.io/calrsom/pen/BeYrNN

### Steps to reproduce bug

 1. Open the pen on iOS Safari
 2. Drag the squares to see the expected interactjs behavior
 3. Tap and hold on the square on the right until it disappears
 4. Drag the squares again

### Expected behavior
Squares should move/translate as before

### Actual behavior
Squares scale as if a two-finger gesture is being triggered.

### Hypothesis

If you log out the interactjs interactions (`interact.debug().interactions.list`), there is an erroneous pointer (`interaction.pointers[0]`) that has a `downTarget` of the deleted element.  This appears even if no finger is touching the screen (if you say log from a timeout).

I believe when an element is deleted in Safari, any touches that originated on that element (touchstart) stop firing events.  Thus, I believe no touchend is fired.  interactjs gets this pointer stuck in memory.

### Possible fixes

I believe the touch events fire with a full list of current touches, so maybe compare the IDs of the touches to see if there are any obsolete pointers and delete them.

### Workaround

This bug is particularly nasty because once this "orphaned touch" is stuck inside interactjs, the only way to fix the behavior is to reload.  We are using interactjs inside a Cordova iPad app, so the user has to force close and relaunch the app.  The app is fairly large with multiple screens, and we only use interactjs to run a drag-and-drop feature on a single screen and only in an edit mode.  It is a React app with animated transitions, so it is pretty easy to trigger the bug by simply accidentally holding a finger on top of a transitioning element that then is not rendered so React removes from DOM.

The workaround I came up with is to call
```
 const interactions = Interact.debug().interactions.list;
 interactions.splice(0, interactions.length);
```
when the edit mode is activated to reset all interactions.  This feels very hacky though.

Is there a way to reset interactjs or turn it on and off? I looked through the API, but it wasn't clear if this is possible.  It would be nice to turn off, since I don't need it watching touch events until the app is in this edit state.

### System configuration
**interact.js version**: 1.4.2
**Browser name and version**: iOS Safari 12.2
**Operating System**: iOS 12.2

**Comment by taye** [comment]
Thanks for reporting and making a demo!

**Comment by calrsom** [comment]
Thank you very much for fixing and releasing this bug so quickly!

Out of curiosity, is there a way to turn interactjs on and off at all?
