### ISSUE TITLE
Cannot read property 'options' of null

### ISSUE THREAD

**Issue by arggh** [taye/interact.js#725]
After upgrading to `1.4.4` our logs are filling with errors from Interact.js:

`Cannot read property 'options' of null` or `null is not an object (evaluating 'e.options')`, depending on the browser.

It seems to only happen on touch screen devices, eg. Android & iOS.

Unfortunately, with our current build, we don't have proper stack traces to help debugging.

This didn't happen with the pre-1.4 versions.

**Comment by arggh** [comment]
It's actually this same issue: https://github.com/taye/interact.js/issues/503

```js
onstart: function(event) {
    event.interaction.stop();
}
```

...will still cause a ton of errors to be thrown.

**Comment by taye** [comment]
in what context do you call `interaction.stop()`?

**Comment by arggh** [comment]
Inside a draggable’s `onstart` handler, when I want to cancel or prevent the interaction due to some condition outside of interact’s domain - for example, a gesture with two fingers (zoom) where one finger happened to land on the draggable element by chance.

It works, but also generates a lot of errors in our logs.

For now I’ve just put everything inside `onmove` and `onend` into conditionals, which check whether or not the logic inside `onstart` was in favor of completing the interaction or not.

Sorry for any typos or mislabeled event handlers, I’m writing from mobile.
