### ISSUE TITLE
.On('hold') not responding on iOS Safari

### ISSUE THREAD

**Issue by saturnonearth** [taye/interact.js#730]
The .on('hold') event is not being caught at all on iOS. It seems to have broken on version 1.4.2. Using latest iOS version.

**Comment by taye** [comment]
Try updating to v1.4.10

**Comment by saturnonearth** [comment]
I have tried this, that is why I had to go back to 1.4.2

**Comment by Ladret** [comment]
I have the same problem with the latest release
