### ISSUE TITLE
TypeError: t.holdTimers[a] is undefined

### ISSUE THREAD

**Issue by bmarotta** [taye/interact.js#732]
The error happened on an user browser. More details can be found here:

https://sentry.io/share/issue/6dd9f3aeff784b2bbc0c74aec977165f/

### System configuration
**interact.js version**: 1.4.11
**Browser name and version**: Firefox 67.0
**Operating System**: Windows 10

**Comment by taye** [comment]
Are you sure you're using version 1.4.11? the "holdTimers" property isn't referenced at all in this version.

**Comment by taye** [comment]
I'm closing this issue as it's likely a problem with an old version.
