### ISSUE TITLE
Can not drag a layer if its width is less than 45px and it's re-sizable

### ISSUE THREAD

**Issue by CassiaHou** [taye/interact.js#733]
Hi,

Can not drag a layer if its width is less than 45px and it's re-sizable. And when hover on it ,it didn't shows the 'move' cursor.

### Expected behavior
It should can be dragged  

### Actual behavior
Can not drag it and no 'move' cursor

### System configuration
**interact.js version**: 1.4.4
**Browser name and version**: Chrome, 75.0.3770.100
**Operating System**: Windows

**Comment by taye** [comment]
The only options are to either reduce the size of the resize margin with

```js
interact(target).resizable({ margin: 10 })
```

or add a min `restrictSize` modifier



```js
interact(target).resizable({
  modifiers: [
    interact.modifiers.restrictSize({
      min: { width: 60, height: 60 },
    })
  ]
})
```

**Comment by CassiaHou** [comment]
@taye  Great! The first solution works for me!
