### ISSUE TITLE
Problem with Bootstrap "row"

### ISSUE THREAD

**Issue by tobias-schanze** [taye/interact.js#734]
Hello, i have the problem when i use interact in a bootstrap row or with display: flex that it doenst work.
have anybody an idea? i doenst have restricts..

Here the SourceCode
```
<template>
    <div>
        <div class="row">
            <dropzone class="drop_zone">
                <div slot="drop-zone">
                    <div class="col-3">
                        <div style="background-color: red;height:100px;width:100px">
                        </div>
                    </div>
                </div>
            </dropzone>
        </div>

    <draggable>
        <div slot="draggable-item">
            <div style="background-color: blue;height:50px;width:50px;"></div>
        </div>
    </draggable>
    </div>
</template>
```

Without "class:'row'" and without display flex it works. Have anybody an idea?

**Comment by taye** [comment]
can you make a demo on jsfiddle.net

**Comment by tobias-schanze** [comment]
Puh. We use it with VueJS...

**Comment by taye** [comment]
Can you make a demo without vue, but with HTML that's similar to the rendered output? That would be the best option.

**Comment by tobias-schanze** [comment]
I have send you an Link at your mail.

**Comment by tobias-schanze** [comment]
Hi,

here the fiddle: 

https://jsfiddle.net/o0astxre/

**Comment by taye** [comment]
Your dropzone requires `overlap: 0.75`, but the `.row`'s `display: flex` causes the dropzone to be too small for the draggable to overlap that much.
