### ISSUE TITLE
v.1.5.0 TypeError: u is null

### ISSUE THREAD

**Issue by jermlab** [taye/interact.js#737]
Hi Taye, 

Just thought I'd let you know that v.1.5.0 broke some of my draggables. Not sure why, but it must have to do with their restriction classes. 

https://jsfiddle.net/djxn3oct/1/

**Comment by taye** [comment]
Can you post a screenshot of the code at that line?

**Comment by jermlab** [comment]
I updated my original post with an example.  I'm pretty new to coding and still getting my bearings with Interact.js, so it's probably a mistake with my code. It works with the previous version though.

**Comment by philmorley** [comment]
This broke all restrictions for the draggables in my project. When specifying a class or tag name.
