### ISSUE TITLE
Multi-touch and SVG demos not working

### ISSUE THREAD

**Issue by stahlmanDesign** [taye/interact.js#740]
The two multi-touch demos and the SVG demo at https://interactjs.io do not work for me on iPad. Just bringing it to attention in case this was overlooked or not known.

- Mutli-touch rotation
- Pinch-to-zoom
- Use in SVG files

**Comment by stahlmanDesign** [comment]
When I paste the example code in a sandbox I am able to get the first multi-touch demo to work:
Multi-touch Rotation (touchscreen only)
https://jsfiddle.net/stahlmandesign/cdLvq9m5/3/

But not the second one:
Pinch-to-zoom (touchscreen only)
https://jsfiddle.net/stahlmandesign/bs95ze7m/3/

**Comment by taye** [comment]
This seems to be fixed now

**Comment by stahlmanDesign** [comment]
> This seems to be fixed now

Great, confirmed for multi-touch rotation and pinch-to-zoom.
SVG still not working

Thank you
