### ISSUE TITLE
IFrame Drag-Drop Event Capturing

### ISSUE THREAD

**Issue by shubh3695** [taye/interact.js#742]
Is there any way to handle **drag/drop events in an Iframe**? I tried some solutions but there was no possible mode via the interactjs events as they were not captured.
Also, I had a similar requirement as posted in #77 & #97 . Didn't find a better way to do it, other than the **transparent element container over the iframe** (middleware process). Any chances you'll be picking this as a milestone in the upcoming versions soon? or can you recommend anything?

### Expected behavior
Iframe should be capable to act as  a drop zone

### System configuration
**interact.js version**: 1.4.1
**Browser name and version**: Chrome 75 
**Operating System**: Windows

**Comment by lalwani52** [comment]
I'm in need of something similar, can't get the iframe to capture the drop without adding a transparent element. Is there a way to implement this in interact js?

**Comment by shubh3695** [comment]
Sorry I was able to fix that issue. @lalwani52  you can also try this via creating a directive in Angular. Thanks for the great library.

**Comment by taye** [comment]
I don't plan on fixing this for the open source library, but I'm considering implementing a solution as a paid feature. I can't say if or when this might happen.
