### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ted-collins** [taye/interact.js#743]
### Expected behavior
Using interactjs, under Rails and Webpack, SPA should open without errors in both "development" and "production" environments.

### Actual behavior
Simple SPA (hello-world) loads and works correctly if RoR is in "development" mode, but fails with the above error when promoted to "production" mode.

Console output is:

```
hello_react-9d5176c469c71fbe8e9e.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at e (hello_react-9d5176c469c71fbe8e9e.js:1)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
    at e (interact.js:11555)
```

### System configuration
**interact.js version**:

`interactjs@1.5.3`

**Browser name and version**:

`CHROME (Mac) Version 75.0.3770.142 (Official Build) (64-bit)`

**Operating System**:

Server: `Ubuntu 18.04` -- Served using Apache2 and Passenger

Client: `MacOS Mojave 10.14.5`

### Additional Notes

1. I can create a repo with the RoR environment, but perhaps a description might be helpful here . . . also, for those unfamiliar with RoR, perhaps I should just set up a server with everything configured.

a. Create an empty RoR (5.2.3) project

`rails new myapp --webpack=react`

b. Add a very simple hello-world

```
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'

import interactjs from 'interactjs'

const Hello = props => (
  <div>Hello World</div>
)

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <Hello />,
    document.body.appendChild(document.createElement('div')),
  )
})
```

c. Install packages with Yarn (package.json)

`{
  "name": "test_app",
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@rails/webpacker": "^4.0.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "interactjs": "^1.5.3",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.7.2"
  }
}`

d. Run webpack (webpack-server for development environment)

`[ubuntu:ted] -> ./bin/webpack-dev-server 
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/ted/test_app/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: Hash: 5d68eb73d8a5bb689950
Version: webpack 4.36.1
Time: 1430ms
Built at: 07/19/2019 7:38:30 PM
                                     Asset       Size       Chunks             Chunk Names
    js/application-d55e7ef8afa1f7e89918.js    386 KiB  application  [emitted]  application
js/application-d55e7ef8afa1f7e89918.js.map    435 KiB  application  [emitted]  application
    js/hello_react-05613aa11aa68c7db63d.js   1.68 MiB  hello_react  [emitted]  hello_react
js/hello_react-05613aa11aa68c7db63d.js.map   1.94 MiB  hello_react  [emitted]  hello_react
                             manifest.json  703 bytes               [emitted]  
ℹ ｢wdm｣: Compiled successfully.`

e. Works in development, when environment changed to production, compiles successfully, but fails when loaded in browser.

Any guidance on how to further isolate this problem would be greatly apprecaited!

**Comment by taye** [comment]
Can you make a repo with the minimum for reproducing this issue? I'm not familiar with rails so that would be a huge help.
