### ISSUE TITLE
Snapping/restriction is no longer working

### ISSUE THREAD

**Issue by oliversalzburg** [taye/interact.js#746]
### Expected behavior
Modifiers are no longer working as expected.

### Actual behavior
Check the "Snapping" example on https://interactjs.io/

This worked in 1.5.2

### System configuration
**interact.js version**: 1.5.3
**Browser name and version**: Chrome
**Operating System**: Windows

**Comment by oliversalzburg** [comment]
To resolve this, one has to add `enabled : true` to the construction options of modifieres.

**Comment by igoriok1994** [comment]
Aww, docs should be updated...

**Now I need to use "enabled:true" property for every modifier?**

**Comment by oliversalzburg** [comment]
@igoriok1994 It's actually already there: https://interactjs.io/docs/action-options#enabled

But it seems like a breaking change. So this was unexpected to happen in a minor/patch release.

And, yes, you need to add it explicitly to every modifier right now. Not sure if that's really intentional.
