### ISSUE TITLE
Type definition issues

### ISSUE THREAD

**Issue by oliversalzburg** [taye/interact.js#747]
### Expected behavior
Type definitions are accurate and usable.

### Actual behavior
- `edges` is missing on `Interact.ResizeEvent`
- Many of the examples modify `event.target.style`, but `event.target` is typed as `Element`, which has no `style` member.
- When using `interact.modifiers`, I get the error that `modifiers` does not exist on `InteractStatic`.
- `modifiers` is also missing from `DraggableOptions`.

### System configuration
**interact.js version**: 1.5.3
**Browser name and version**:
**Operating System**:

**Comment by oliversalzburg** [comment]
To work around the missing `edges`, one case use something like:
```js
/** @param {Interact.ResizeEvent & {edges: {left: boolean, right: boolean}}} event */
```

To work around the use of `Element`, one can wrap the code that has the failing type checks with `if( event.target instanceof HTMLElement )`.

**Comment by taye** [comment]
Can you make a sample project that demos the issues with missing props?

> Many of the examples modify event.target.style, but event.target is typed as Element, which has no style member.

I've changed the types to use `HTMLElement | SVGElement` instead of `Element`, so should be fixed in the next release.
