### ISSUE TITLE
dragend event doesn't fire when releasing mouse click

### ISSUE THREAD

**Issue by bogdanostojic** [taye/interact.js#748]
````
interact(target)
		.draggable({
			max: 1,
			min: 1,
			snap: {
			targets: [
				interact.createSnapGrid({ x: 1, y: 1 })
			],
			range: Infinity,
			relativePoints: [ { x: 0, y: 0 } ]
			},
			inertia: true,
			// autoScroll: true,
			restrict: {
				restriction: "html",
				elementRect: { top: 0, left: 0, bottom: 1, right: 1 },
				endOnly: true,
			}
		})
		.on('dragmove', event => {
			this.x_coordinate += event.dx;
			this.y_coordinate += event.dy;
                        event.target.style.transform ='translate(' + this.x_coordinate + 'px, ' + this.y_coordinate + 'px)';
		})
		.on('dragend',function(event) {
                     this.x_coordinate = 0;
		     this.y_coordinate = 0;
			}
		);
````
### Expected behavior
When i drag an element while holding click i should be able to release the mouse button and the dragend event should fire.

### Actual behavior
When I release the mouse button of the target while dragging it, the dragend event doesn't fire and when i hover over the target element it triggers the dragmove event

### System configuration
**interact.js version**: 1.5.4
**Browser name and version**: Chrome 75
**Operating System**: Windows 10

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by ProdigyView** [comment]
I have the same issue. Mouse is released but the dragend event is not called.
