### ISSUE TITLE
Unexpected behavior when removing draggable element

### ISSUE THREAD

**Issue by Keftaa** [taye/interact.js#749]
Hello, I have a problem that happens intermittently and I haven't been able to identify the cause. I'm writing it here in hopes that someone has already encountered a similar issue.
Here's a video recording with the problem (towards the end): https://youtu.be/ml4tBIzhM4I 

### Expected behavior
Draggable element should be removed normally

### Actual behavior
See video

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Google Chrome 76.0.3809.87 64-bit
**Operating System**: Windows 10 64-bit

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?
