### ISSUE TITLE
Resizing vertically doesn't work when `preserveAspectRation=true`

### ISSUE THREAD

**Issue by ljupcospeci** [taye/interact.js#750]
Resizing vertically doesn't work when `preserveAspectRation=true`.

https://codepen.io/KiriS19/pen/deLOjw

Repro steps:
1. Try to resize from the bottom right edge along the Y axis.

### Expected behavior
If the user drags from the bottom right or bottom left edge along the Y axis, the element should resize.

### Actual behavior
Trying to resize while dragging on the Y axis does not work.

### System configuration
**interact.js version**: 1.4.0-rc.13
**Browser name and version**: Chrome 76
**Operating System**: Windows

**Comment by taye** [comment]
Closing this as a wontfix. While the current behaviour isn't idea, resizing still works and the aspect ratio is preserved. I might revisit the issue later as part of #638
