### ISSUE TITLE
Can no longer tell resize direction from resizestart event

### ISSUE THREAD

**Issue by Truffula** [taye/interact.js#754]
Previous versions (1.3.4 at least) included a property `event.interaction.downEvent.target` in the `resizestart` event that could be used to work out the direction of resizing. At some point the `downEvent` was no longer included in the event, and given that the values in `event.deltaRect` are all zero, I cannot find any other way to determine the direction until the `resizemove` event.

See [jsFiddle](https://jsfiddle.net/truffula/1c74bw5h/20/).

### Expected behavior
`resizestart` event includes a `event.interaction.downEvent` with a `target` that is the resize handle element that was clicked.

### Actual behavior
The `downEvent` is missing.

### System configuration
**interact.js version**: 1.6.1
**Browser name and version**: Chrome 76.0
**Operating System**: MacOS

**Comment by taye** [comment]
Thanks for reporting! I've added a `resizestart.edges` property that you can use to check the resize direction now.

**Comment by Truffula** [comment]
Great, thank you!
