### ISSUE TITLE
Pinch-zoom broken on iOS13 Safari

### ISSUE THREAD

**Issue by renedekat** [taye/interact.js#757]
The Pinch-to-zoom (touchscreen only) demo on https://interactjs.io doesn't work any longer on iOS13. It worked fine on iOS12

### Expected behavior
Pinch to zoom and rotate works

### Actual behavior
It doesn't zoom nor rotate (bar a few degrees)

### System configuration
**interact.js version**: Latest
**Browser name and version**: Safari 
**Operating System**: iOS

**Comment by taye** [comment]
Which device are you using?

**Comment by taye** [comment]
I couldn't reproduce this issue on an iPad 6th Gen, iPhone 8 or iPhone 11 with the latest versions of iOS and iPadOS. Which version do you have?

**Comment by renedekat** [comment]
@taye It seems fixed now in later iOS updates.
