### ISSUE TITLE
Documentation request: Snapping to dropzone and back to start position.

### ISSUE THREAD

**Issue by wilkinsonjack1993** [taye/interact.js#759]
I have been trying to implement interact.js in a personal project where I aim to have drag and drop questions and answers: 
- The answers can be dragged to a question box where they will snap to a particular part of the box
- If answers are dragged to anywhere outside of the dropzone of a question box, they snap back to their original position.

Looking at the documentation, I have been struggling to work out a way of implementing this as the snap example covers snap grid and I can't quite work out from the API how this should work. 

An additional example in the docs covering this sort of use case would be amazing.

I have created a codepen which may help show what my use case is a bit better: https://codepen.io/wilkinsonjack1993/pen/eYYObNd

**Comment by kurtextrem** [comment]
Would be nice to have this. @wilkinsonjack1993 have you found any other plugin that does this?
