### ISSUE TITLE
TypeError: interactjs__WEBPACK_IMPORTED_MODULE_2___default.a.modifiers.restrictRect is not a function

### ISSUE THREAD

**Issue by roberttolton** [taye/interact.js#761]
### Expected behavior
Following the example in the docs, expected no errors.

### Actual behavior
Console log shows:
`TypeError: interactjs__WEBPACK_IMPORTED_MODULE_2___default.a.modifiers.restrictRect is not a function`

This is running inside a VueJS `2.6.10` app, inside the `mounted` hook:

```
import interact from 'interactjs';
```
```
mounted() {
  this.blockInteract = interact(`#block-${this.blockIndex}`);

  this.blockInteract.draggable({
    allowFrom: '.block-mover',
    modifiers: [
      interact.modifiers.restrictRect({
        restriction: 'parent',
        endOnly: true
      })
    ],
    onmove: (event) => {
      console.log(event);
    }
  });
}
```

### System configuration
**interact.js version**: `^1.4.0-rc.13`
**Browser name and version**: `Chrome (via Electron 6)`
**Operating System**: `macOS 10.14.6`

**Comment by baconck** [comment]
@roberttolton - I am having the same issue, were you able to solve? probably something simple, right?

**Comment by roberttolton** [comment]
@baconck Looking back at my code, it hasn't changed, but I am now using interact.js `^1.6.2` which may have something to do with it. I remember it being an annoyingly simple thing.
