### ISSUE TITLE
Cannot drag on iOS 13 with body overflow:hidden

### ISSUE THREAD

**Issue by cheungkonghou** [taye/interact.js#763]
On ipad iOS 13 with a page where body is overflow:hidden; dragging a draggable element drags the whole page together and dragging stops abruptly without releasing the finger.
**interact.js version**: latest 1.6.2
**Browser name and version**: iOS 13

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by cheungkonghou** [comment]
I managed to reproduce the problem at https://jsfiddle.net/0exm5tLu/1/ by copying your demo code and comment out the touch-action: none; from css. Not aware of this css property is for what purpose?

**Comment by nayfin** [comment]
`touch-action: none;` is required to keep conflicting mouse/touch events from colliding and breaking the drag behavior.

**Comment by cheungkonghou** [comment]
let's consider this closed then, thanks
