### ISSUE TITLE
Using interact.js with angularjs causes multiple events running

### ISSUE THREAD

**Issue by Asimov500** [taye/interact.js#764]
This happens in both firefox and chrome.
I am using interact 1.6.2

I am using angularjs and that means a page does not need to load inbetween pages.
So if I go to the page where I am runniing interact.js every time I go there it fires a new interact on my elements.

That means when you first go to the page it is fine, but if you come out of the page and go back it is then firing two events, which means the div I am moving suddenly moves faster than the mouse. Every time I do this it is firing more events, and the div moves further from the mouse

I thought I could destroy interact.js before I run it again so I put an unset in like this
`interact('.design-tool-workspace .layer').unset();`
And then I set up my draggable again
```
  interact('.design-tool-workspace .layer').draggable({
                    onmove: this.dragMoveListener
                  //  snap: true
                }).on('down', function(e) {
                    const layerHash = $(e.currentTarget).attr('layer-hash');
		e.preventDefault();			
                    return (() => {
                        const result = [];
                        for (let layer of Array.from($scope.textdesign.lettering_object.layers)) {
                            if (layer.uid == layerHash) {// Do not use ===
                                $scope.textdesign.selectLayer(layer);
                                result.push($scope.$apply());
                            } else {
                                result.push(undefined);
                            }
                        }
                        return result;
                    })();
                })

```
When I go to the page I need to destroy the interact before setting it up again. However unset does not seem to work, and I can't find any other way of resetting it on next page load.

**Comment by nayfin** [comment]
@Asimov500 I've built an Angular wrapper for interact and I have not had similar issues. I destroy my  connections to interact in my onDestroy lifecycle hook. I believe the newer versions of angularjs have this lifecycle hook, maybe you could try that. Also, unless you are tied to angularjs by a corporate overlord, you really should be dropping it like a bad habit. Angular proper is about to drop version 9, it's worth the upgrade. Regardless, I don't think this is an issue with the interact library, it seems more like you're missing something in your implementation with anglularjs.

**Comment by Asimov500** [comment]
Hi nayfin,
I hate angularjs with a passion, but it is what my company uses and I am not in charge of what system they use unfortunately. I have a function called bindLayers every time the page is loaded. This is what is running interact. The first time you go to the page everything works great, but the second time you go to the page the div starts running away from the mouse pointer because interact event is running twice. After 3 days of trying to solve this problem I have come up with a solution, but wish there was a better way. My solution is to store interact in $rootScope and then unset that when the page reloads. It is not elagant but it works. I didn't post my solution straight away because I was hoping someone would have a better way of killing interact on next page load, but not had many answers. Anyway here is my solution. Would be nice if there was a better way.
```
	bindLayers(){
		if(typeof $rootScope.textInteractStore!== 'undefined'){
			$rootScope.textInteractStore('.design-tool-workspace .layer').unset();
		}
		$rootScope.textInteractStore =interact;
             $rootScope.textInteractStore('.design-tool-workspace .layer').draggable({
                    onmove: this.dragMoveListener
                }).on('down', function(e) {
					const layerHash = $(e.currentTarget).attr('layer-hash');
					e.preventDefault();
                    return (() => {
                        const result = [];
                        for (let layer of Array.from($scope.textdesign.lettering_object.layers)) {
                            if (layer.uid == layerHash) {// Do not use ===
                                $scope.textdesign.selectLayer(layer);
                                result.push($scope.$apply());
                            } else {
                                result.push(undefined);
                            }
                        }
                        return result;
                    })();
                })
},
```

**Comment by nayfin** [comment]
@Asimov500 I've been there buddy, we got off it by highlighting the security issues and ranting about how it's losing support very soon. It's been a while but if you used a service (singleton) for your drag functions, interact shouldn't duplicate its events since it would only be instantiated once. Hope that helps. I think this issue could probably be closed, since it doesn't seem to be an issue with the `unset()` function but rather to angularjs wonkiness.

**Comment by Asimov500** [comment]
Yeh the singleton sounds like a plan. I will try and put it in a service and see if that helps.
I think I will put in the quick fix that I posted to get it working then work on the service. Thanks

**Comment by Kendrickphar893** [comment]
> Hi nayfin, I hate angularjs with a passion, but it is what my company uses and I am not in charge of what system they use unfortunately. I have a function called bindLayers every time the page is loaded. This is what is running interact. The first time you go to the page everything works great, but the second time you go to the page the div starts running away from the mouse pointer because interact event is running twice. After 3 days of trying to solve this problem I have come up with a solution, but wish there was a better way. My solution is to store interact in $rootScope and then unset that when the page reloads. It is not elagant but it works. I didn't post my solution straight away because I was hoping someone would have a better way of killing interact on next page load, but not had many answers. Anyway here is my solution. Would be nice if there was a better way.
> 
> ```
> bindLayers(){
> 	if(typeof $rootScope.textInteractStore!== 'undefined'){
> 		$rootScope.textInteractStore('.design-tool-workspace .layer').unset();
> 	}
> 	$rootScope.textInteractStore =interact;
>         $rootScope.textInteractStore('.design-tool-workspace .layer').draggable({
>             onmove: this.dragMoveListener
>          }).on('down', function(e) {
> 		const layerHash = $(e.currentTarget).attr('layer-hash');
> 		e.preventDefault();
>                 return (() => {
>                         const result = [];
>                         for (let layer of Array.from($scope.textdesign.lettering_object.layers)) {
>                             if (layer.uid == layerHash) {// Do not use ===
>                                 $scope.textdesign.selectLayer(layer);
>                                 result.push($scope.$apply());
>                             } else {
>                                 result.push(undefined);
>                             }
>                     }
>                     return result;
>              })();
>      })
> },
> ```





https://cinema19.github.io/t4MKw3pVFqYNmPVZ5Zb9b33cRYSD/
