### ISSUE TITLE
-user-select:none causing another element to be selected on iPad 13.1.3

### ISSUE THREAD

**Issue by alpritt** [taye/interact.js#766]
On iPad OS version 13.1.3 in Safari, `user-select: none;` or `-webkit-user-select: none;` stop the element it is applied to from being selected when the cursor is pressed down. This is as expected. However, the next element that does not have this applied is being selected instead.

I can see this on the https://interactjs.io/ page. For example, on the 'Tap, doubletap and hold' demo, if I hold down on the 'tap-target' the word 'By' in the page footer is randomly selected! In this case you have `-user-select: none` applied to the  '.live-demo__result' element.

Incidentally double tap is not working on that same demo on Safari in version 13.1.3 either. However, neither problem exists when using Chrome on the same OS version so it is specific to that browser.

**Comment by taye** [comment]
This seems to be a bug in Safari. I’m not sure if there’s any way to work around it. 😕

**Comment by alpritt** [comment]
Not that I've found. I suppose we can only put together a bug report for Apple.
