### ISSUE TITLE
Provide an ES6 module build

### ISSUE THREAD

**Issue by jdittrich** [taye/interact.js#769]
### Wished-for behavior
Having an [ES6-modules compatible](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/) build so that _interact.js_ can be cleanly used without a toolchain, too. 

### Actual behavior
There [seem to be builds](https://interactjs.io/docs/) for AMD, common.js and usage of a global, but no module for ES5 modules.

**Comment by taye** [comment]
You can now use

```html
<script type="module">
import interact from 'https://cdn.jsdelivr.net/npm/@interactjs/interactjs/index.js'
</script>
```

Unfortunately, specifying the version with `@[version spec]` in the jsdelivr url will only get the target file at that version. The imports in the files are all relative and will request dependencies without any version.

**Comment by taye** [comment]
with version `1.9.0` you can now do:

```js
<script type="module">
import 'https://cdn.jsdelivr.net/npm/@interactjs/actions/use/drag.js'
import 'https://cdn.jsdelivr.net/npm/@interactjs/modifiers/use/index.js'
import 'https://cdn.jsdelivr.net/npm/@interactjs/inertia/use/index.js'
import 'https://cdn.jsdelivr.net/npm/@interactjs/auto-start/use/index.js'
import interact from 'https://cdn.jsdelivr.net/npm/@interactjs/interact/index.js'

interact('.draggable').draggable({})
</script>
```

Please give it a try and let me know how it works for you. Those “use/*” files are auto-genated by [this script](https://github.com/taye/interact.js/blob/v1.9.0/scripts/add-use-modules.js).

**Comment by SamyCookie** [comment]
> with version `1.9.0` you can now do:
> 
> ```js
> <script type="module">
> import 'https://cdn.jsdelivr.net/npm/@interactjs/actions/use/drag.js'
> import 'https://cdn.jsdelivr.net/npm/@interactjs/modifiers/use/index.js'
> import 'https://cdn.jsdelivr.net/npm/@interactjs/inertia/use/index.js'
> import 'https://cdn.jsdelivr.net/npm/@interactjs/auto-start/use/index.js'
> import interact from 'https://cdn.jsdelivr.net/npm/@interactjs/interact/index.js'
> 
> interact('.draggable').draggable({})
> </script>
> ```
> 
> Please give it a try and let me know how it works for you. Those “use/*” files are auto-genated by [this script](https://github.com/taye/interact.js/blob/v1.9.0/scripts/add-use-modules.js).

Thanks for this, ES6 module import from source is working well.
However, I would prefer to use a all-in-one dist Javascript file deployed with ES6 compatibility (and without UMD loader and stuff). Is it possible to propose also this kind of build in the `dist` directory ?
