### ISSUE TITLE
Drag & Drop between frames

### ISSUE THREAD

**Issue by cjeriksson** [taye/interact.js#77]
I have draggables in the main window and drop-zones in an iframe (interact.js is loaded in both) - this does however not seem to work. Am I missing something or is interact-js not designed to handle this case ?
##

**Comment by sourcec0de** [comment]
@taye this is something I would also like to see.
Is there any update on this issues progress?

**Comment by taye** [comment]
I would like to work on this but it's a little complicated and I won't have time for it for a long while.

**Comment by shubh3695** [comment]
Hi Taye,
Huge Fan of **interactjs**, I had a similar requirement as **cjeriksson** had posted. Didn't find a better way to do it, other than the transparent element container over the iframe. Any chances you'll be picking this as a milestone in the upcoming versions soon?
