### ISSUE TITLE
Typescript compilation error on 1.7.0

### ISSUE THREAD

**Issue by dmitriigaidarji** [taye/interact.js#771]
### Actual behavior
```
ERROR in [at-loader] ./node_modules/interactjs/index.d.ts:1:22
    TS2307: Cannot find module '../interact/index'.

ERROR in [at-loader] ./node_modules/interactjs/index.d.ts:2:28
    TS2307: Cannot find module '../modifiers/index'.

ERROR in [at-loader] ./node_modules/interactjs/index.d.ts:3:26
    TS2307: Cannot find module '../modifiers/base'.

ERROR in [at-loader] ./node_modules/interactjs/index.d.ts:5:27
    TS2307: Cannot find module '../utils/snappers/index'.
```
### System configuration
**interact.js version**: 1.7.0.  typescript@^3.7.2:
```
"@interactjs/types@1.7.0":
  version "1.7.0"
  resolved "https://registry.yarnpkg.com/@interactjs/types/-/types-1.7.0.tgz#02accd00eaaa536d55a0fadad94170a127f96f6d"
  integrity sha512-0nk5GDdl8X+XwW0ihgkaLCahx25TRDs1IZtKIoCYYcm9DGqZrlTq4Z4muofOTS/Jp7sfGqQnWnz4JWwFiAb/Qg==
  dependencies:
    "@interactjs/actions" "1.7.0"
    "@interactjs/auto-scroll" "1.7.0"
    "@interactjs/auto-start" "1.7.0"
    "@interactjs/core" "1.7.0"
    "@interactjs/dev-tools" "1.7.0"
    "@interactjs/inertia" "1.7.0"
    "@interactjs/interact" "1.7.0"
    "@interactjs/modifiers" "1.7.0"
    "@interactjs/pointer-events" "1.7.0"
    "@interactjs/reflow" "1.7.0"
    "@interactjs/utils" "1.7.0"
```
**Browser name and version**: ?
**Operating System**: tested on CentOS 7 and Mac OS

**Comment by Zamiell** [comment]
Hey @taye , looks like the fix didn't work.

I'm testing this by having the following line in my packages.json file:

`"interactjs": "^1.8.0-alpha.1",`

After an `npm install`, my project compiles fine on Windows, but after an `npm install` on Ubuntu, I get the following error:

src/game/chat.ts:6:22 - error TS7016: Could not find a declaration file for module 'interactjs'. '/root/go/src/github.com/Zamiell/hanabi-live/public/js/node_modules/interactjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/interactjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'interactjs';`

6 import interact from 'interactjs';
                       ~~~~~~~~~~~~


Found 1 error.
```

**Comment by taye** [comment]
@Zamiell can you try adding `"./node_modules/@interactjs"` to the `compilerOptions.typeRoots` array  of your `tsconfig.json`?

```json
{
  "compilerOptions": {
    "typeRoots": ["./node_modules/@types", "./node_modules/@interactjs"]
  }
}
```

**Comment by Zamiell** [comment]
After adding that, I get the following errors:

```
error TS2688: Cannot find type definition file for 'actions'.
error TS2688: Cannot find type definition file for 'auto-scroll'.
error TS2688: Cannot find type definition file for 'auto-start'.
error TS2688: Cannot find type definition file for 'core'.
error TS2688: Cannot find type definition file for 'dev-tools'.
error TS2688: Cannot find type definition file for 'inertia'.
error TS2688: Cannot find type definition file for 'interact'.
error TS2688: Cannot find type definition file for 'interactjs'.
error TS2688: Cannot find type definition file for 'modifiers'.
error TS2688: Cannot find type definition file for 'pointer-events'.
error TS2688: Cannot find type definition file for 'reflow'.
error TS2688: Cannot find type definition file for 'types'.
error TS2688: Cannot find type definition file for 'utils'.

Found 13 errors.
```

**Comment by Zamiell** [comment]
I should also note that I got it working just fine with v1.7.2.

**Comment by taye** [comment]
I've published a new version. Could you try `npm install interactjs@next`?

**Comment by Zamiell** [comment]
Exact same errors as before.

**Comment by taye** [comment]
I've published another prerelease version. Can you try `npm isntall interactjs@next` again without the `compilerOptions.typeRoots` suggestion?

If that fails, I'm all out of ideas 😕

**Comment by Zamiell** [comment]
If it isn't too much trouble, can't you just test yourself with a Ubuntu VM in VirtualBox or something?

**Comment by Zamiell** [comment]
Or just use Travis, as it errors there as well. (I'm not sure what exact flavor of Linux that they use in their Docker container workers.)

**Comment by taye** [comment]
I've tired on Arch Linux with node 12, npm 6 and typescript 3.7 without issues. What versions are you using?

**Comment by Zamiell** [comment]
Looks like alpha 3 compiles without errors. For the record, I am on Ubuntu 16.04.
