### ISSUE TITLE
Couldn't find package "@interactjs/types" on the "npm" registry.

### ISSUE THREAD

**Issue by gramcha** [taye/interact.js#773]
### Expected behavior
@interactjs/types need to be in npm registry

### Actual behavior
Couldn't find package "@interactjs/types" on the "npm" registry error.

### System configuration
**interact.js version**:1.7.2
**Browser name and version**:
**Operating System**:

**Comment by gdemonie** [comment]
Same issue here. Couldn't find package "@interactjs/interactjs" on the "npm" registry.
yarn info interactjs is working however

**Comment by taye** [comment]
I've updated the `latest` tag on npm. Can you try removing the node_modules directory and reinstalling?
