### ISSUE TITLE
Could not resolve since 1.7.1

### ISSUE THREAD

**Issue by matt3224** [taye/interact.js#774]
![Screenshot 2019-11-23 at 11 24 06](https://user-images.githubusercontent.com/2401925/69477915-f78a6180-0de3-11ea-9220-4474ab588ed0.png)

I get this issue on any version above 1.7.0, 1.7.0 is the last known working version for me

**Comment by taye** [comment]
I made all imports within the internal @interactjs scoped packages to be relative for #769. I don't think this should be a problem if you're importing "interactjs" in your app.

What command causes that error?

**Comment by matt3224** [comment]
It seems even just will do it:
```js
import interact from 'interactjs';
```

**Comment by matt3224** [comment]
I'm using rollup and pnpm btw

**Comment by taye** [comment]
I'm not familiar with rollup, but you might need a plugin like https://github.com/rollup/rollup-plugin-node-resolve to get rollup to resolve to the `main` or `browser` fields in the `package.json` of dependencies

**Comment by matt3224** [comment]
As it happens i'm already using that, i'm using sapper/svelte which has all that setup

**Comment by matt3224** [comment]
It works totally fine at version 1.7.0 its just 1.7.1 and 1.7.2 that don't work

**Comment by taye** [comment]
How about 1.8.0-alpha.3? The main difference there is that I added a `main` field in addition to `browser`.

**Comment by taye** [comment]
If that doesn't work, could you give me a rollup setup to try out?

**Comment by matt3224** [comment]
Yes that works! Good job!

**Comment by kobaltz** [comment]
Had trouble doing a `yarn install interactjs`, but it does seem to be working now. Earlier today, I was getting `error Couldn't find package "@interactjs/interactjs" on the "npm" registry.`, but that is no longer the case.

**Comment by taye** [comment]
@matt3224 you're welcome!

@kobaltz yesterda's npm service disruption caused a CD job to fail and only publish a few packages, then I published manually, but set incorrect `@latest` tags until today.
