### ISSUE TITLE
typescript support is broken. 1.7.2, 1.8.0-alpha.6

### ISSUE THREAD

**Issue by xerosanyam** [taye/interact.js#775]
not working properly with typescript.
getting multiple errors of the form
core/BaseEvent.d.ts
![image](https://user-images.githubusercontent.com/3167278/69963304-f967c980-1535-11ea-98d5-1a53e6558ccf.png)

**Comment by ksumarine** [comment]
I am seeing this issue as well

**Comment by doronsever** [comment]
We cannot upgrade to TS 3.7.2 yet. With 3.5 it is broken
