### ISSUE TITLE
inertia: boolean => results in Typescript Error

### ISSUE THREAD

**Issue by Pestichen** [taye/interact.js#776]
Hi there,
I'm trying to implement interactjs in our vue app.
But already at the beginning i got the following type-error. That's why I have already raised Typescript to version 3.7.2, but the error unfortunately remains the same.

Error:
At Line 3:  **inertia: true,** 

{
	"resource": "/d:/git/manubes/Web/WebComponents/src/modules/component-designer/container/canvas/DragAndDropTest2.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{ inertia: boolean; modifiers: any[]; autoScroll: boolean; onmove: (event: any) => void; onend: (event: any) => void; }' is not assignable to parameter of type 'boolean | Partial<OrBoolean<DraggableOptions>>'.\n  Object literal may only specify known properties, and 'inertia' does not exist in type 'Partial<OrBoolean<DraggableOptions>>'.",
	"source": "Vetur",
	"startLineNumber": 174,
	"startColumn": 9,
	"endLineNumber": 174,
	"endColumn": 22
}

### Code
https://pastebin.com/nZ0NAmMk (Line3)

### Packages
    "typescript": "3.7.2",
    "interactjs": "^1.8.0-alpha.6",
    "vue": "2.6.10",
    "@interactjs/types": "^1.8.0-alpha.6",

### Expected behavior
There are no type errors anymoe

### Actual behavior
There are an type error

### System configuration
**interact.js version**:  "^1.8.0-alpha.6"
**Browser name and version**: Chrome 78
**Operating System**: Win10

**Comment by taye** [comment]
Fixed in v1.8.0-rc.0
