### ISSUE TITLE
Resizable error 

### ISSUE THREAD

**Issue by zssng** [taye/interact.js#779]
[sample ](https://codesandbox.io/s/wonderful-minsky-vlu5r)
### Expected behavior
should be able to resize the div 

### Actual behavior
mousemove event get nan size for corresponding resize direction

### System configuration
**interact.js version*1.7.2*:
**Browser name and version*chrome 79*:
**Operating System*windows 10*:

**Comment by taye** [comment]
Fixed in v1.8.0-rc.0
