### ISSUE TITLE
 Restrictind the area for clonned draggable element 

### ISSUE THREAD

**Issue by qubero** [taye/interact.js#784]
### Expected behavior
I want to use drag inside restricted area like in this [JSFilddle](https://jsfiddle.net/zhsjnvq9/) with page autoscroll. But I use a clone of element made in this way [JSFilddle](https://jsfiddle.net/swtnxLoc/3/)
### Actual behavior
Restricted area doesnt affect on clonned element

### System configuration
**Browser name and version**: all I tested (chrome, ff, safari, ...)

**Comment by taye** [comment]
The restriction selector only works for elements that are parents of the target element. Your demo works if you use `restriction: document.querySelector("#blub")`.

By the way, the version you're using in that demo is quite old. The latest version is 1.8.1 and I highly recommend migrating https://interactjs.io/docs/migrating.

**Comment by qubero** [comment]
Thanks a lot, works like a charm!
Really like your quick answers
