### ISSUE TITLE
Rollup with plugin cleanup enters in a infinite loop from version 1.8.0-alpha.4

### ISSUE THREAD

**Issue by Laincito** [taye/interact.js#785]
When we build the application using rollup and the cleanup plugin, rollup enters in a infinite loop from version 1.8.0-alpha.4 of Interactjs, keeping the problem in the latest version 1.8.1.

Files here:

https://stackblitz.com/edit/js-bwqqsn?file=README.md

### System configuration
**interact.js version**: 1.8.0-alpha.4
**Operating System**: Windows 10

**Comment by xerosanyam** [comment]
problem in latest interactjs also :-/

**Comment by xerosanyam** [comment]
1.3.4 works fine, but typescript errors
latest one, no typescript error but gets in infinite loop
stuck! :(

**Comment by xerosanyam** [comment]
1.4.0 is also going in infinite loop. 1.3.4 works fine

**Comment by taye** [comment]
You can exclude files in the `node_modules/interactjs/dist` folder to skip minifying the already minified bundle.

```js
cleanup({ exclude: '**/interactjs/dist/*' })
```

I think you should open an issue with rollup-plugin-cleanup since the problem seems to be from them.
