### ISSUE TITLE
LockAxis with clone (manual start)

### ISSUE THREAD

**Issue by qubero** [taye/interact.js#786]
Using manual start, interact clone. Is it possible to lockAxis with clone?
[Codepen](https://codepen.io/spierala/pen/PgoMPL)

**Comment by taye** [comment]
```js
interaction.start({ name: "drag", axis: "y" }, event.interactable, clone);
```

**Comment by rodrigo-fonseca** [comment]
> ```js
> interaction.start({ name: "drag", axis: "y" }, event.interactable, clone);
> ```

And for startAxis?
