### ISSUE TITLE
restrictEdges Offset

### ISSUE THREAD

**Issue by han-tyumi** [taye/interact.js#787]
### Expected behavior
The entire offset when used with restrictEdges should be taken into account.

### Actual behavior
The top and left offsets are only taken into account.
This doesn't appear consistent with restrictRect which will take the boundary and apply the offset to obtain a smaller inner rectangle boundary.

### System configuration
**interact.js version**:  1.8.1
**Browser name and version**: Firefox 68.2 ESR
**Operating System**: CentOS

To get around this I did the following:
```ts
// restrict to boundary
const restrictRect = interact.modifiers.restrictRect({
  restriction: boundary,
  offset
});

// restrict edges to boundary
const restrictEdges = interact.modifiers.restrictEdges({
  outer: boundary,
  offset
});

// fix bottom and right offsets
const set = restrictEdges.methods.set.bind({});
restrictEdges.methods.set = arg => {
  // call original method
  set(arg);

  // fix problems with bottom and right edges
  const { interaction, coords } = arg;
  if (interaction.edges.bottom) {
    coords.y -= offset.top + offset.bottom;
  }
  if (interaction.edges.right) {
    coords.x -= offset.left + offset.right;
  }
};
```

Otherwise I would be allowed to drag and move the element appropriately within the container, but also allowed to resize the element's bottom and right edges outside the container.

As a side note, I also seem to have lost the typings for the modifier functions after updating from 1.7.3.

**Comment by taye** [comment]
Can you make a demo that demonstrates the problem clearly?
