### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by Antarus66** [taye/interact.js#789]
ERROR in node_modules/@interactjs/types/types.d.ts(66,48): error TS2370: A rest parameter must be of an array type.
node_modules/@interactjs/types/types.d.ts(188,27): error TS2370: A rest parameter must be of an array type.
node_modules/@interactjs/utils/index.d.ts(5,55): error TS2370: A rest parameter must be of an array type.
node_modules/@interactjs/utils/is.d.ts(6,54): error TS2370: A rest parameter must be of an array type.

**Comment by taye** [comment]
What version of typescript are you using?
