### ISSUE TITLE
Resizing left edge makes element move out of place on v1.8.4

### ISSUE THREAD

**Issue by huycan** [taye/interact.js#792]
Hi Taye,

Just found your lib yesterday for my drag and resizing use case. It's awesome! Thanks for your hard work! I like the simplicity and how the library yields movement logic to users.

I just want to let you know that on latest version 1.8.4, the resizing functionality is broken when resizing with the left edge of the element. This can be verified quickly on your demo page <https://interactjs.io/> Resizing box. Just resize the left edge and you will see the weird behavior.

The same demo code works perfectly on v1.7.3.

### Expected behavior
When resizing the left edge, only the left edge should move, the right edge and the width of the element should remain unchanged.

### Actual behavior
The whole element moves / floats away from the cursor.

### System configuration
**interact.js version**: 1.8.4
**Browser name and version**: Latest Chrome
**Operating System**: Ubuntu 18.04

**Comment by taye** [comment]
I can't reproduce this. Can you post screencast?
