### ISSUE TITLE
Script error in a webbrowser control

### ISSUE THREAD

**Issue by bclothier** [taye/interact.js#793]
I'm trying to use interact.js in a embedded browser control. The browser control is set to use IE 11 mode, as [documented here](https://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version).

When my page is loaded in IE11 itself, it works without any errors. But load the same page in an embedded web browser control, I get a script error. It points to this line 434 in `interact.js`:

```
if (_domObjects["default"].PointerEvent) {
    docEvents = [{
      type: pEventTypes.down,
      listener: releasePointersOnRemovedEls
    }, {
      type: pEventTypes.down,
      listener: listeners.pointerDown
    }, {
      type: pEventTypes.move,
      listener: listeners.pointerMove
    }, {
      type: pEventTypes.up,
      listener: listeners.pointerUp
    }, {
      type: pEventTypes.cancel,
      listener: listeners.pointerUp
    }];
  }
```

With the error displayed:
![image](https://user-images.githubusercontent.com/2367644/74169098-63fd4b80-4bf0-11ea-9473-14bc9101a6e1.png)

It's not clear to me why `pEventTypes` would apparently be not be defined but only in the embedded scenario. I think it should work the same way whether it's running in IE 11 as its own process or embedded.

I've tried to rule out the possibility of security policy interfering but that does not seem to match the pattern when there is a security restriction. I've tried it both using CDN or using a local copy.

Note that this error happens as part of loading the `interact.js` / `interact.min.js`, before my own code gets to run. I verified that by adding a `alert` before my first use of `interact` object and the error shown above popped before my alert, before I got additional errors about `interact` object being undefined.

Using:
interact.js 1.8.4
Internet Explorer 11 (as an ActiveX control embedded)
Windows 10

**Comment by taye** [comment]
Can you try the suggestion here: https://github.com/taye/interact.js/issues/703#issuecomment-470799067

**Comment by bclothier** [comment]
I can confirm that this worked. Is there a reason why this can't be done within the `interact.js`? 

Note that I had to do this hack:

```
<script language="javascript" type="text/javascript">window.PointerEvent = window.MSPointerEvent = null;</script>
<script language="javascript" type="text/javascript" src="js/interact.js"></script>
```

because the error occurs as part of loading the `interact.js` script.

**Comment by taye** [comment]
I don't know how to determine if the page is loaded in an ActiveX control. If you can share a dependable way to do that, then I could add it in.
