### ISSUE TITLE
Using for scrolling

### ISSUE THREAD

**Issue by tryhardest** [taye/interact.js#797]
Can you explain why they 'really' is italics? It's confusing. Is it a sarcastic joke (meaning everyone needs scrolling)? Is it a warning to preferably not use this for scrolling? If so why not? 

Sorry but hard to read into that and know what it's implying but because you added italics it is implying something.

Thank you, cool lib.

![Screenshot_20200301-033739~2](https://user-images.githubusercontent.com/53920284/75625037-fbf6b100-5b6e-11ea-814c-dcc6ba1286e6.png)

**Comment by taye** [comment]
It's generally considered bad practise to [hijack scrolling](https://envato.com/blog/scroll-hijacking/), so "really" is in italics for

 - emphasising that you should do it only if it's very important
 - light comedic effect (I hoped)

Would it be clearer if I changed the text to "(if you _really_ need to) override browser scrolling"?

You're welcome :)
