### ISSUE TITLE
preserveAspectRatio stopped working after upgrading to 1.8.1

### ISSUE THREAD

**Issue by lolmaus** [taye/interact.js#798]
Hi!

I've upgraded `interactjs` from `1.4.11` to `1.8.1` and the `preserveAspectRatio` flag is no longer respected: image proportions can be distorted.

Had to downgrade.

**Comment by taye** [comment]
Hello. There's a new way to enforce the aspect ratio using modifiers. It has the advantage of cooperating with other modifiers like snap and restrict. https://interactjs.io/docs/resizable#aspect-ratio

**Comment by lolmaus** [comment]
СС @simonihmig
