### ISSUE TITLE
Edge compatibility issues

### ISSUE THREAD

**Issue by sebastiaan-de-vries** [taye/interact.js#799]
Hi,

I was considering using InteractJs for a new project that needs to support MS Edge. According to the docs it should be supported, however, on the InteractJs home/demo site there seem to be issues.

When I open [https://interactjs.io/](https://interactjs.io/) on Windows 10 - Edge 44 (= latest stable version?), the following issues occur:
- None of the interactions work
- There is no drag pointer when hovering over the interactions
- The top part of the page stays empty ([screenshot](https://drive.google.com/file/d/16QMjAXUPzM2oszp_ONDAn7hw92sBaW8R/view?usp=sharing)) further down the examples are rendered but do not work
- The Debug Console show the following errors:
  + SCRIPT1028: SCRIPT1028: Expected identifier, string or number ... chunk-vendors.a396a9f1.js (1,14929)
  + 0: Object expected ... star.js(47,2)

I am guessing this shouldn't happen, or am I doing something wrong?

Kind regards,
Sebastiaan

**Comment by taye** [comment]
The website isn't made for older browsers because I don't want to deal with compatibility issues there, but the library should still work. Try https://codepen.io/taye/pen/GgpxNq

**Comment by sebastiaan-de-vries** [comment]
Thanks for the quick response! All right, the codepen works on Edge. Did not know Edge was already considered to be an older browser ;-) I never use it but have to support it unfortunately...

**Comment by taye** [comment]
`s/older/compatibility-challenged/` :P
