### ISSUE TITLE
Element not given focus after drag end

### ISSUE THREAD

**Issue by mattlockyer** [taye/interact.js#8]
The dragged element (ex: textarea) has it's focus stolen after the drag, which means you can't type in it anymore.

This is fixed by calling textarea.focus(); in the onend callback, but I feel should happen automatically or be an option.

**Comment by mdee** [comment]
Just wanted to give a quick comment: I ran an into an issue where a draggable that contained an input was not responding to click / touch events. 

I solved the issue in 3 steps:

1. Calling preventDefault('never') when initially defining the interactable
2. Inside of the 'dragStart' override, calling preventDefault('auto') on event.interactable
3. Inside of the 'dragEnd' override, calling preventDefault('never') on event.interactable

Hope this is helpful for others going forward!
