### ISSUE TITLE
cant place caret on content editable div

### ISSUE THREAD

**Issue by sdraper69** [taye/interact.js#806]
I have a div which i can resize and drag that when i double click it becomes content editable = true;

works fine i can drag/resize as i wish and I can indeed edit it...

however I cannot place the caret wherever I want in the text, the cursor always shows the drag symbol, and the click seems to get picked up by interact rather than the content editable div

are there are suggestions for a fix / work around?

**Comment by taye** [comment]
You can use the `ignoreFrom` option to disable dragging on the editable element https://interactjs.io/docs/action-options/#ignorefrom
