### ISSUE TITLE
Resizing BL, L, TL, T, and TR edges and corners moves element. Dragging is also not 1:1

### ISSUE THREAD

**Issue by bxchang04** [taye/interact.js#808]
I don't get this bug in my CodePen, but when I run it locally using a local server (npm http-server) I get this behavior below. I've tried changing the resize border but that didn't help:

Video: https://youtu.be/iL8RLWGJ2rE

Any advice would be greatly appreciated!

CodePen: https://codepen.io/bxchang04/pen/XWmWbZQ

### Expected behavior
Tell us what should happen
Element should not move while being resized. Dragging should also be 1:1 with cursor movement.

### Actual behavior
Element moves while being resized in the BL, L, TL, T, and TR edges and corners. Dragging moves element faster than cursor.

### System configuration
**interact.js version**: 1.9.9
**Browser name and version**: Chrome 80.0.3987.163 (Official Build) (64-bit)
**Operating System**: Windows 10

**Comment by bxchang04** [comment]
Update: I noticed I do not get this issue when I open my index.html file locally.

However when I run a local server and open my app on localhost:8080, I get the behavior in the video above. I suspect this is being caused by http-server, and if this is a know issue, please let me know how to avoid this, thanks!

**Comment by taye** [comment]
It looks like the target element or one of its parents has a CSS transform applied that scales the element. Can you check if this is true?
