### ISSUE TITLE
retrieve event values from element

### ISSUE THREAD

**Issue by devozanges** [taye/interact.js#811]
the event objects are full of useful information, is it possible to retrieve the same type of object from a DOM element without going through an event ?

**Comment by taye** [comment]
What information do you need and can you provide an example?

**Comment by devozanges** [comment]
today I need to gather information on elements that I dynamically place in an area. (position, size, etc.)
I get this individual information through drag or resize events, it's ok.
but it would be very useful to be able to get information that is in the event about another element or all the elements involved in interact?
(in my case I would like the position of all the elements placed in a frame...)
otherwise I can do it with jquery but the event items are super complete and there's a lot of good info in them so I would have liked to get the info through them.

**Comment by taye** [comment]
I think it would be a lot of effort to maintain this as a feature so I'd rather not implement it, sorry.

**Comment by devozanges** [comment]
All right, thanks anyway.
