### ISSUE TITLE
Website direct links do not work

### ISSUE THREAD

**Issue by eltiare** [taye/interact.js#813]
Visiting a link from Google like this one does not work: [https://interactjs.io/docs/dropzone/](https://interactjs.io/docs/dropzone/)

![image](https://user-images.githubusercontent.com/3036/80636584-f4db0a80-8a1a-11ea-8de0-f880a29568f0.png)

You could probably click on the link above to get the same behavior.

**Comment by taye** [comment]
Fixed. Thanks for the heads up.
