### ISSUE TITLE
Reflow

### ISSUE THREAD

**Issue by GitNomster** [taye/interact.js#817]
Don't know is it bug or feature. When i using reflow resize interact element suddenly getting bigger. This happens since 1.8.5.

https://codepen.io/gitnomster/pen/mdeXQBK

### System configuration
**interact.js version**: 1.9.13
**Browser name and version**: Chrome 81.0.4044.129
**Operating System**: Win 10 x64

**Comment by taye** [comment]
This is a bug :grimacing:
