### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function in PRODUCTION

### ISSUE THREAD

**Issue by sauravkhdoolia** [taye/interact.js#818]
### Expected behavior
It fails in production, successful build but white page with console err
```
Uncaught TypeError: Super expression must either be null or a function
```

### Actual behavior
It should have worked.

### System configuration
**interact.js version**: 1.9.13
**Browser name and version**: Chrome 81
**Operating System**: Linux Mint

**Comment by zarincheg** [comment]
I've got the same problem. With production build (compressed version), uncompressed works well.

**Comment by bmtdh** [comment]
Same issue as well

**Comment by webdeveloper001** [comment]
I got that issue as well on 1.3.4

**Comment by taye** [comment]
What build setup do you have?

**Comment by webdeveloper001** [comment]
What do you mean?

**Comment by taye** [comment]
@zarincheg mentioned that

>With production build (compressed version), uncompressed works well.

@webdeveloper001 are you using a `<script src="[CDN URL]" />` tag?

**Comment by webdeveloper001** [comment]
I don't use interactjs directly. I am using react-calendar-timeline module which has interactjs as a dev dependency.

**Comment by JordanPawlett** [comment]
I'm experiencing the same issue, `interactjs` is being installed indirectly via `react-calendar-timeline`.
I can produce a successful build resolving the version to `1.3.4` in my applications root `package.json`.

`"resolutions": {
    "interactjs": "1.3.4"
  },`

**Comment by taye** [comment]
I'd appreciate minimal a jsfiddle or codesandbox, etc. demo that reproduces this error :slightly_smiling_face:

**Comment by JonathanPicques** [comment]
For those who are using React: bumping react-scripts to ```^3.4.1``` and babel-loader to ```^8.1.0``` did the trick.

**Comment by samir-lab** [comment]
> I've got the same problem. With production build (compressed version), uncompressed works well.

i got the same problem, have you got any solution?

**Comment by samir-lab** [comment]
i had print the error info with "+ e" in compressed code:
`et.DropEvent = void 0;
    var lt = function(t) { !
        function(t, e) {
            if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function" + e);
            t.prototype = Object.create(e && e.prototype, {
                constructor: {
                    value: t,
                    writable: !0,
                    configurable: !0
                }
            }),
            e && ot(t, e)
        } (i, t);`

then i got the below message:
`Uncaught TypeError: Super expression must either be null or a functionfunction e(t){!function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}(this,e),this.type=void 0,this.target=void 0,this.currentTarget=void 0,this.interactable=void 0,this._interaction=void 0,this.timeStamp=void 0,this.immediatePropagationStopped=!1,this.propagationStopped=!1,this._interaction=t}`

it's strange ! the 'e' is obviously a function

**Comment by sonicwang1989** [comment]
same on 1.9.20

**Comment by sunny920406** [comment]
same on 1.10.0

**Comment by sunny920406** [comment]
@zarincheg me too!

**Comment by samir-lab** [comment]
您好，邮件已收到，会尽快给您回复。
