### ISSUE TITLE
how to fire a dragstart

### ISSUE THREAD

**Issue by giorgiobeggiorasoprasteria** [taye/interact.js#826]
I tried to fire the dragstart, it fires but after that the element won't move

interact(element).fire({type: 'dragstart'});

Thanks

**Comment by taye** [comment]
the `fire` method doesn't actually start an interaction, it just calls listeners with the object you give it.

You can use start an interaction from a `down` event like this:

```js
interact(element).on('down', event => {
  event.interaction.start({ name: 'drag' }, event.interactable, event.currentTarget);
})
```

**Comment by giorgiobeggiorasoprasteria** [comment]
After that, does these wil work?

```
element.dispatchEvent(new Event('mousedown'));
element.dispatchEvent(new Event('touchstart'));
element.dispatchEvent(new Event('pointerdown'));
```

**Comment by taye** [comment]
Yeah, those should work.

**Comment by taye** [comment]
Are you firing these events for running tests?
