### ISSUE TITLE
What is the proper method of installing InteractJS via npm?

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#829]
The documentation says that we should use:
`npm install interactjs`

but there is [an issue](https://github.com/taye/interact.js/issues/800) that seems to talk about a new way of installing, which is not documented (at least I could not find the docs for it).

So how should we install the library and could you shine some more light on the differences b/w these two methods?

Best regards.

**Comment by ddenev** [comment]
it is strange to mark something automatically as `wontfix` just because there is no reply from the owner for 14 days...
anyway, I am still waiting for an answer... hence the rant :)

**Comment by taye** [comment]
I'm still working on the new installation methods and haven't written any docs yet. The benefit of the new method is that you can select which features to import. For now, the simplest way to use the library is through the `interactjs` package which has a bundle of all features and includes definitions for typescript. If you need to keep your download/bundle size minimal, then you can follow the advice in #800 and be prepared for some changes.

I set up stalebot to close issues where requests for further info weren't followed up on, for questions that I feel are more suited to sites like stackoverflow, and also to reduce pressure from having tens of open issues that I don't have time to address. I think two weeks is long enough that I or the reporter should be reminded about the issue, though I agree that the `wontfix` isn't a nice label to put on the issue.
