### ISSUE TITLE
Example Problem on page: Pinch-to-zoom (touchscreen only)

### ISSUE THREAD

**Issue by zeus1999** [taye/interact.js#830]
Hi,

i tried to reproduce the following example: Pinch-to-zoom (touchscreen only)

https://jsfiddle.net/wb7m8yoz/

On the first rotate it works pretty well, but on each try afterwards when i rotate it, it snaps back first.

I dont see the point.

What is wrong?

Is this a bug?

Cheers

**Comment by taye** [comment]
You're missing the `gestureend` listener:

```js
      end (event) {
        angleScale.angle = angleScale.angle + event.angle
        angleScale.scale = angleScale.scale * event.scale
      }
```
