### ISSUE TITLE
Docs: API navigation links lead to 404

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#831]
Links in the left panel of the API docs page lead to 404.

To reproduce:

1. Go to https://interactjs.io/
2. Select API from the Docs menu
3. Click on any link (except the ones under Interactable class)

It's not my browser cache, I checked (incognito, cleared cache, checked with Chrome and FF).

**Comment by ddenev** [comment]
Dear @taye , could you please have a look at the issue above? Do you plan to fix it or docs are not maintained anymore?
Thank you.

**Comment by taye** [comment]
I plan to fix it, but I haven't gotten around to it yet. I'll try to have it done before the end of the week.

For now, you can download the generated api docs with this link: [api.zip](https://github.com/taye/interact.js/files/4815344/api.zip).

**Comment by ddenev** [comment]
There is a typo in the 4th bullet of `docs/api/Interactable.html#dropzone` - `dragmove` should be `dropmove` I believe.

**Comment by ddenev** [comment]
Could you please also add the docs for the `Interaction` class? It is missing in the provided docs above.

The official API is still 404 btw :) It's very difficult to work with the library without proper docs.

**Comment by taye** [comment]
Fixed
