### ISSUE TITLE
Is it possible to configure an interactable element such that only touch events are used instead of pointer events?

### ISSUE THREAD

**Issue by CodeWithOz** [taye/interact.js#837]
We're considering some optimizations for our codebase and sometimes we see worse touch performance (not related to this library) when pointer events are used compared to regular touch events. So just wondering if it's possible to instantiate interactables that only use touch events. Thanks!

**Comment by tryhardest** [comment]
#21 maybe there is a way to explicitly target ignoreFrom on just the pointerEvent (for mobile) but not the touchStart @taye ? Does that even make sense not sure I am explaining well. I'd suggest pointer-event: none might work but that will only make the pointer event 'go-through' the element, it won't remove the ~10ms that the pointer event takes in out timeline on a scroll event, before the touchStart occurs. To keep in frame budget if we have 10-15ms pointer event occur, then 10ms touchStart (which we need for somethings) we are already exceeding. Maybe it's as simple as preventDefault() on the pointerEvent or pointerCancel?
https://javascript.info/pointer-events
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent
![image](https://user-images.githubusercontent.com/53920284/85624458-ce9ea900-b61e-11ea-89d5-c891b0e947a4.png)

**Comment by taye** [comment]
There's no option at the moment, but if you set `window.PointerEvent = null` before importing/requiring/`<script src/>`ing interact, then it will fall back to TouchEvents.

**Comment by CodeWithOz** [comment]
@taye removing pointer events appears to create another problem where the `dragend` handler doesn't get invoked. I've tried doing the same in a modified version of the sample codepen but the problem doesn't happen there. In my code the only thing I change is setting `window.PointerEvent` to `null` just as you described. Any ideas what may be causing this?

**Comment by taye** [comment]
Can you try saving the `window.PointerEvent` in a variable before setting it to null and restoring after interact is loaded?

**Comment by CodeWithOz** [comment]
@taye the problem was actually somewhere else in my code where `preventDefault` was called on the touch event in a vanilla JS listener. Fixed it by switching to interactjs's `tap` event. Thanks!
