### ISSUE TITLE
Possible to extend interact() to accept array of HTMLElement elements?

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#839]
Would it be possible to extend the `interact()` method to also accept an array of `HTMLElement` elements?

Currently it accepts a single element or a selector but for my use-case the selector is not the best approach.

I am creating a Vue 'Draggable' component for my project and I want this to be a functional component that would be used to wrap one ore more HTML elements or components in order to make them draggable, something like:
```
<draggable>
  <MyComponent />
  <MyComponent />
  ...
</draggable>
```
and I don't want to use selectors for that since I would like to have the "declarative" approach above.

I also wouldn't want to loop over the components and instantiate a separate interactable for each one since ... well, I guess - performance :)

**Comment by ddenev** [comment]
... or alternatively - allow adding new elements to an existing interactable.

**Comment by ddenev** [comment]
Oh, come on, @taye , what's with that stale bot and wontfix? This is so rude, especially when you ignore questions for almost a month!

Honestly and with all respect, I really want to like this library and am looking forward for the paid version but the way you (do not) handle questions and bug reports currently is not doing the paid version any favors. 

Please reconsider the approach.

Respectfully, best regards

**Comment by ddenev** [comment]
+1

**Comment by taye** [comment]
I'm working on this as one of the pro features so I don't want to add it to the open source packages yet.
