### ISSUE TITLE
Resize restriction is broken

### ISSUE THREAD

**Issue by adidahiya** [taye/interact.js#84]
Resizing restrictions seem broken, see [this jsFiddle](http://jsfiddle.net/o7abdshd/).

The issue seems to stem from [this line in interact.js](https://github.com/taye/interact.js/blob/master/interact.js#L2173), which is expecting `prepared` to be `"resize"` (because that's the object key under which the resize restriction is stored in the variable `restrict`), but the event type in `prepared` stored in is always `"resizex"` or `"resizey"`.

I can't get the restriction to work with any value - `"parent"`, `"self"`, or an object `{x: 0, y: 0, width: 500, height: 500}`.
##

**Comment by razvanphp** [comment]
In my case I cannot make resizable to be restricted to a minimum height of the object.

````javascript
.resizable({
    snap: {
        targets: [
          interact.createSnapGrid({
            x: 40,
            y: 40
          })
        ],
        relativePoints: [ { x: 0, y: 0 } ]
    },
    edges: {
      top   : false,
      left  : false,
      bottom: '.ui-resizable-s',
      right : false
    },
    restrict: {
        restriction: {
            x: 0,
            y: 0,
            width: 0,
            height: 19
        },
    },
})
````

I also tried with other values than 0 and with a `elementRect`, but it does not have the expected behaviour or it does not work at all. Am I using it wrong of this is not supported yet?
