### ISSUE TITLE
pointerDown going out of frame budget

### ISSUE THREAD

**Issue by Mapiac** [taye/interact.js#840]
Not a bug. Probably more like bad implementation and trying to understand what we are doing wrong.

Often the pointerDown before our touchStart is taking upwards of 200ms. This is a performance trace on a scroll attempt, but as you can see we haven't even begun to get to the scroll and we are blasting out our frame budget. This is on Android in a Cordova app. Is there something we are doing wrong that might cause interactJS to take so long here?

![image](https://user-images.githubusercontent.com/38844921/86040481-f6b05280-b9f8-11ea-8157-8af6b243f300.png)

**Comment by Mapiac** [comment]
We have a google maps (native) plugin sitting under a webview. It's listening to the touchEvents in the webview above it. Could this be the V8?

**Comment by Mapiac** [comment]
Darn no one has any ideas on this? Still seeing here...this is the trace and as you can see pointer down is 200ms and up

![image](https://user-images.githubusercontent.com/38844921/88003468-cd478b80-cab9-11ea-92f3-be15d087d02c.png)

**Comment by Mapiac** [comment]
![image](https://user-images.githubusercontent.com/38844921/88004367-bbff7e80-cabb-11ea-93d6-bcd1dfaf7900.png)

Would this presume that a pointerDown and pointerMove do have the delay?

![image](https://user-images.githubusercontent.com/38844921/88004421-da657a00-cabb-11ea-9dda-771b06889acf.png)

**Comment by taye** [comment]
I tried profiling, and I noticed that there seems to be some setup work that's done by Chrome which makes it look like the pointer down events are slower than they normally are. On subsequent pointer down and action starts, things appear to run much faster.

**Comment by Mapiac** [comment]
@taye sorry you mean the first use is slow, then you are seeing it faster? Which wouldn't work as a user expects touch to be fast everytime. What are you seeing can you screenshot? We have generally long-running each use consistently.

**Comment by taye** [comment]
I mean that it looks like most of the time is actually spent doing mysterious V8 stuff (V8.StackGuard, V8.HandleInterrupts). The time spent actually running interact event listeners is still tiny (7.6ms)

![Screenshot from 2020-08-09 15-10-51](https://user-images.githubusercontent.com/1679746/89733020-ed33f480-da52-11ea-9c86-5fd4052bb055.png)

When I try profiling https://interactjs.io, I see something similar on the first pointerDown. but the next actions during the same profiling run much faster according to the devtools.

![Screenshot from 2020-08-09 15-17-53](https://user-images.githubusercontent.com/1679746/89733120-94189080-da53-11ea-98ba-f75b7f19573f.png)

**Comment by Mapiac** [comment]
Thanks @taye for testing and sharing that. Is anyone else seeing this? It might extend my confusion in that if first pointerDown is long, well, to put it mildly that itself is a big deal and we don't want to gloss over that. Frame budget is a frame budget. When you disable pointer events do you still see? I recall there is a way to not use pointerEvents just touch events, and maybe then it can be a consistent <10ms per touchStart (depending on function).
