### ISSUE TITLE
[bug?] Dropzone - one 'dropmove' event is always fired before the 'dragenter' event

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#841]
When a draggable is entering a dropzone, there is always one `dropmove` event fired **before** the `dragenter` event. I believe this might be a bug and `dragenter` should always fire before any `dropmove` events.

There is no `dropmove` event fired after the `dragleave`, which would be the correct behavior if the above was intended.

Here is a jsfiddle - https://jsfiddle.net/ddenev/ow7sp3eL/ - just drag the green square over the pink one and observe the console.

**Comment by ddenev** [comment]
Any plans to fix this?

**Comment by ddenev** [comment]
Any plans to fix this?

**Comment by taye** [comment]
Yes, but likely not this week.

**Comment by ddenev** [comment]
@taye, thank you for fixing this!
