### ISSUE TITLE
Prevent snapping of a relative point and a target under certain conditions

### ISSUE THREAD

**Issue by podenemus** [taye/interact.js#843]
For a project I'm working on I'm looking for a way to hook into the snapping action just before the coordinates of the element are set to the target coordinates (at this point: https://github.com/taye/interact.js/blob/92e7d32fe81f933eecce83504868c32f95ef45af/packages/%40interactjs/modifiers/snap/pointer.ts#L174) or a way to set specific targets for each individual relative point of an element.

The reason for this is that in my case some relative points of an element should not be "allowed" to snap to some of the predefined targets. For example, a draggable element has 2 relative points, topLeft and topRight, and 2 targets (coordinates from another element), also topLeft and topRight. _topLeft_ of the draggable and _topLeft_ of the target element should not be able to snap, however, the _topLeft_ of the draggable should snap to _topRight_ of the target element. 

I've made a codepen example to illustrate what I'm trying to accomplish: https://codepen.io/podenemus/pen/yLeKvXB
Is there any way to achieve this?

Let me know if you need more information! Big thanks in advance :)

**Comment by taye** [comment]
Hello. One solution is to use two different snap modifiers - one for each target with a different relativePoint each.

```js
interact(element)
  .draggable({
    modifiers: [
      interact.modifiers.snap({
        targets: [target1],
        range: 30,
        relativePoints: [
          { x: 1, y: 0, name: "topRight" }
        ]
      }),
      interact.modifiers.snap({
        targets: [target2],
        range: 30,
        relativePoints: [
          { x: 0, y: 0, name: "topLeft" },
        ]
      })
    ]
  })
```

Another solution is to use [function targets](https://interactjs.io/docs/snapping#targets-option) and check which relativePoint is currently being used and return `null` instead of `target1` or `target2`. I'd recommend this solution since it avoids setting up multiple snap modifiers.

```js
var targetFunc1 = function (x, y, interaction, offset, index) {
  return offset.relativePoint.name === target1.name ? null : target1
}
var targetFunc2 = function (x, y, interaction, offset, index) {
  return offset.relativePoint.name === target2.name ? null : target2
}

interact(element)
  .draggable({
    modifiers: [
      interact.modifiers.snap({
        targets: [targetFunc1, targetFunc2],
        range: 30,
        relativePoints: [
          { x: 1, y: 0, name: "topRight" },
          { x: 0, y: 0, name: "topLeft" },
        ]
      })
    ]
  })
```

**Comment by podenemus** [comment]
That's perfect! Thank you very much for taking time for this!
