### ISSUE TITLE
cursorChecker doesn't work when manualStart is on

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#844]
https://jsfiddle.net/ddenev/znd2tj9f/

I need to have the same functionality, i.e. set initial cursor before start and change it during the drag, as with auto-start but I need the `manualStart` since I'm dragging a clone.

Can you please make it work?

**Comment by taye** [comment]
The `cursorChecker` option is a part of the `auto-start` module. I'll try to make that clearer in the docs. If `manualStart` is set, there's no way to know what action should be started. You can set the cursor with CSS instead.
