### ISSUE TITLE
2 different interactions on 2 different className of the same Element

### ISSUE THREAD

**Issue by monkeydioude** [taye/interact.js#846]
Odd behavior around `draggable`

 - `interact('.A').draggable{...}`
 - `interact('.B').resizable{...}`
 - `.A` and `.B` are classNames of the same Element
=> `draggable` works, `resizable` is ignored

 - `interact('.A').resizable{...}`
 - `interact('.B').draggable{...}`
 - `.A` and `.B` are classNames of the same Element
=> `resizable` works, `draggable` works as well

[Codepen example, try to swap interactions](https://codepen.io/monkeydioude/pen/BajPwqJ)

### Expected behavior
Both interactions should execute

### Actual behavior
Interaction after `draggable` is ignored

### System configuration
**interact.js version**: 1.9.19
**Browser name and version**: Brave 1.10.97,  Firefox 78.0.1
**Operating System**: Ubuntu 20.04

**Comment by taye** [comment]
I saw [on gitter](https://gitter.im/taye/interact.js?at=5f0c2d98a9378637e8c6e582) that you solved this. The order in which the interactables are created does indeed make a difference.

**Comment by monkeydioude** [comment]
Isn't it kind of weird that for this reason we can not have 2 interactions on 1 element, while this is possible when we swapt the order ?
This is causing some real issues on my end.
