### ISSUE TITLE
Bug or by design: Dragging element over other element fires "ondropdeactivate" and aborts the dragging

### ISSUE THREAD

**Issue by q2apro** [taye/interact.js#847]
Try it yourself: https://jsfiddle.net/kai_noack/xzdfkpm6/4/

1. Drag one elment to a dropzone
2. Drag second element and *hover the dragged element* over the previous dropped element
3. Drag is aborted

### Expected behavior
The dragged element should not be affected. The drag should continue.

### Actual behavior
The drag is aborted and the dragged element goes back to previous state.

### System configuration
**interact.js version**: 1.9.20
**Browser name and version**: Chrome 83.0.4103
**Operating System**: Windows 10

PS: Maybe my implementation is incorrect. Should I use the `checker` option? https://interactjs.io/docs/dropzone/ - Not sure. First time with interact.js 😃

**Comment by taye** [comment]
You set `.on('move', listener)` instead of `.on('dragmove, listener')` so when the pointer moves after activating, you end the interaction.

**Comment by q2apro** [comment]
Wow, such a simple fix! ❤ Amazing and thanks a lot 👍
