### ISSUE TITLE
Issues importing with ParcelJS

### ISSUE THREAD

**Issue by LukeTOBrien** [taye/interact.js#848]
Hello,

I would like the use your library but I can't seem to import it, I am using ParcelJS.  
I have tried every combination of import syntax, I have even tried `import "interactjs/dist/interact.js";` and that does not work either.  
Have you ever tested importing with ParcelJS?  
I must say I have had issue with package that import fine with WebPack and don't in Parcel, they use a different module thingy-me-jig I think? 🤔 

I either get `interact is not defined` or this error:
```
interact(...).draggable(...) is not a function
```

### Expected behavior
To be able to import and use correctly in a parcelJS project.

### Actual behavior
NAN

### System configuration
**interact.js version**: 1.9.20

**Comment by LukeTOBrien** [comment]
I have discovered you have another package [**@interactjs**](https://www.npmjs.com/package/@interactjs/interactjs) - From looking at the code it seems that the package **interactjs** imports from **@interactjs**.  
Unfortunately I still have the same issues now that I have the new package.

**Comment by LukeTOBrien** [comment]
This is solved now, it seems I needed to install both packages

**Comment by taye** [comment]
Related: #829
