### ISSUE TITLE
Multi-touch Rotation Demo value mutation unnormal when rotate with two forefinger

### ISSUE THREAD

**Issue by lizy0329** [taye/interact.js#849]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
deg is normal add or decrease

### Actual behavior
use two forefinger rotate the arrow，deg value change unnormal . Try to click and rotate alternately with left and right hands 

### System configuration
**interact.js version**: Multi-touch Rotation Demo
**Browser name and version**:  Chrome 84
**Operating System**: Android 10

**Comment by taye** [comment]
Gesture actions are only for 2-touch interactions. For single pointer rotation, have a look at this codepen: https://codepen.io/taye/pen/wrrxKb
