### ISSUE TITLE
dropzone ondrop doesn't fire if draggable is set to restrict

### ISSUE THREAD

**Issue by yosukehasumi** [taye/interact.js#85]
I understand the theory with restrict but if I'm correct it seems that a successful drop doesn't fire the drop action if the draggable is set to restrict.

In my current scenario I'd like the draggable element to restrict (always return to it's original position), but still want to _do stuff_ if the .draggable was successfully placed in the .dropzone

I've got it to work by listening to a mouseup listener set ondragenter and the listener removed ondragleave

``` javascript
  interact('.draggable').draggable(
    onmove: (event) -> 
      // blah blah
  ).inertia(true).restrict(
    drag: "parent",
    endOnly: true,
    elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
  )

  interact('.dropzone').dropzone(
    accept: '.draggable',  
    ondragenter: (event) ->
      $(event.relatedTarget).on('mouseup.yo', ->
        console.log('dooooo stuff')
      )
    ,
    ondragleave: (event) ->
      $(event.relatedTarget).off('mouseup.yo')
    ,
    ondrop: (event) ->
      // this will never fire
  )
```

**Comment by vdh** [comment]
```javascript
event.interactable.fire(storedDragEnter)
```

that fire doesn't work :(
