### ISSUE TITLE
Docs: "Intro" page produces 401 error

### ISSUE THREAD

**Issue by jantzeca** [taye/interact.js#851]
### Expected behavior

Intro documentation should be displayed

### Actual behavior

Blank shell of what the documentation would be with a 401 error in the console saying I'm not authenticated to see that page.
( response: {"type":"UnauthenticatedError","details":["You are not currently logged in."]} )

I see no place to make an account?

The rest of the documentation pages work though.

### System configuration

**Browser name and version**:
Google Chrome v84 and Firefox v79

**Comment by taye** [comment]
The `/account` request is related to a service I'm working on that lets people generate optimised bundles with only the desired features. I've fixed the documentation issue.
