### ISSUE TITLE
TypeError: Cannot read property 'fire' of null

### ISSUE THREAD

**Issue by HristoBrat** [taye/interact.js#854]
When upgrading from 1.9.20 to 1.9.21 if target is dropped an error is thrown in the browser console "TypeError: Cannot read property 'fire' of null".
From what I see in the stack this.interactable.fire(iEvent) -> interactable is null

### System configuration
**interact.js version 1.9.21**:
**Chrome Version 84.0.4147.135**:
**Mac iOS Catalina 10.15.6**:

**Comment by taye** [comment]
Can you make a demo on https://jsfiddle.net/?

**Comment by KTCopeland** [comment]
Getting the same issue. 
![image](https://user-images.githubusercontent.com/12620975/94355682-27357600-0054-11eb-9604-8e809478df38.png)

**Comment by chenbolan** [comment]
Getting the same issue.
![image](https://user-images.githubusercontent.com/17243308/106878567-1210d800-6715-11eb-8ecc-d900c1acce63.png)

**Comment by HristoBrat** [comment]
We had to change our code so it matches the requirements of 1.9.21.
For example
`interact(interactTarget)
      .resizable({
        onstart: [hanlder],
        onmove:[handler],
        onend:[handler]
	  })		
`
has to be changed to 
`interact(interactTarget)
      .resizable({
        listeners: {
          start: [handler],
          move: [handler],
          end: [handler],
        }
	  })		
`

I hope this helps.
