### ISSUE TITLE
Unable to test interact js with cypress end-to-end testing library

### ISSUE THREAD

**Issue by tktaofik** [taye/interact.js#856]
### Expected behavior
I should be able to trigger native events with [cypress](https://www.cypress.io/) [testing-dom__drag-drop](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__drag-drop) 

### Actual behavior
interact js does not pick up any trigger events from [cypress](https://www.cypress.io/)
### System configuration
**interact.js version**: 1.9.18
**Browser name and version**: Chrome
**Operating System**: macOS

**Comment by taye** [comment]
It's likely that because the cypress browser supports PointerEvents, interact is only listening to those and ignore the mouse events. Can you try triggering `pointerdown`, `pointermove`, etc.?

**Comment by tktaofik** [comment]
I tried `pointerdown`, `pointermove` but it didn't work. 
I want to mention i am using  `interact(".node").draggable` and the following is the event type i logged when i drag my element. I also tried `dragmove` and `dragstart` and it didn't work

<img width="365" alt="Screen Shot 2020-09-18 at 6 59 19 PM" src="https://user-images.githubusercontent.com/8204154/93651890-11370e00-f9e1-11ea-9f8f-46f0ba684e70.png">

**Comment by taye** [comment]
Could you make a repo with just enough set up to reproduce this?

**Comment by tktaofik** [comment]
> Could you make a repo with just enough set up to reproduce this?

I will set one up over soon. Thanks
