### ISSUE TITLE
Start drag without pointerdown event.

### ISSUE THREAD

**Issue by mikeyudin** [taye/interact.js#860]
Hello,

I'm looking for a way to create a new element that has draggable attached to it, and then automatically start dragging the element without the pointer being down.  Once the user clicks again, it stops the drag. I've tried firing a `pointerdown` and `mousedown` event on the element, but an actual mousedown and hold on the element is the only way to get it to start dragging.  Is there any way of dynamically starting a drag/drop interaction without the mouse being held down?

I feel like I've tried every combination of `manualStart: true/false`/`.on('move')`, but nothing seems to be working.  Hoping I'm just missing something obvious!

Thanks!

### Expected behavior

When a new element is added to the dom, I should be able to start an interaction without the mouse being held down.

### Actual behavior
I have an "Add Element" button that creates a new separate element that should be draggable without any mousedown, but instead the only way the drag starts is if the mouse is being held down on the element.

**Comment by amakh** [comment]
Hi @mikeyudin,
I was wondering if you managed to achieve this behavior?

**Comment by taye** [comment]
The best way might be to [create and dispatch](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events) a pointerdown on the target element, then use `interaction.start()`
