### ISSUE TITLE
Pro version timeline + questions related to Blazor

### ISSUE THREAD

**Issue by user72356** [taye/interact.js#861]
Any update on the pro version and when we can hope for at least a beta/preview version?

Also looking at Shopify/Draggable, but I like the purity of the interact.js approach. I'm going to use this in a Blazor project, so I can't have the JS lib modify the DOM, since Blazor keeps a local, virtual copy of it. In Blazor, like in React, external libs touching the DOM are a big no-no. Therefore I need to be able to receive events from the lib, and then use Blazor to Move/Remove/Add items according to the events (as the base/free version of interact.js already does).

Are the pro components going to let me modify the DOM in Blazor myself, or will they be making DOM manipulations directly? Ideally, the components would do all the heavy lifting, and then just letting me know about any changes to the DOM, but not making the changes.

**Comment by taye** [comment]
>Any update on the pro version and when we can hope for at least a beta/preview version?

Probably somewhen between 3 and 7 weeks for a preview.

>Are the pro components going to let me modify the DOM in Blazor myself, or will they be making DOM manipulations directly? Ideally, the components would do all the heavy lifting, and then just letting me know about any changes to the DOM, but not making the changes.

Right now, the sortable and swappable components change the DOM while the drag is happening and, when the drag ends, restore the DOM (removes mirror element, undoes position changes), and fire a callback with the new array order. The parent can then update state to use the new array order and re-render.

```js
const { Interactable, Sortable } = interact.react.components

ReactDOM.render(
  e(() => {
    return e('div', {}, data.lists.map(list => {
      const [items, setItems] = React.useState(list.items)

      return e('div', { className: 'box' }, [
        list.title,
        e('pre', {}, JSON.stringify(items, null, 2)),
        e(
          Sortable,
          { className: 'container', key: `list-${list.title}`, items, onUpdate: setItems },
          items.map(item => e(Interactable, { onTap: event => console.log(event), className: 'item card' }, e('div', { className: 'card-content' }, item)))
        )
      ])
    }))
  }),
  document.getElementById('react-app')
)
```

**Comment by user72356** [comment]
Thank you, looking forward to the announcement.
