### ISSUE TITLE
modifiers

### ISSUE THREAD

**Issue by rodrigo-fonseca** [taye/interact.js#867]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**interact.js version**:
**Browser name and version**:
**Operating System**:

**Comment by taye** [comment]
:eyes:

**Comment by rodrigo-fonseca** [comment]
> 👀

Sorry, I really don't know what happened here, I'm seeing this post now... My cellphone has a problem and it sometimes click everywhere. I'm replying this because I received a email about this post
