### ISSUE TITLE
How to propagate child drag event to parent?

### ISSUE THREAD

**Issue by Jungwoo-An** [taye/interact.js#869]
### Expected behavior

```html
<parent> // initialize interact
   ...
   <child> // initialize interact
   </child>
</parent>
```

I want to propagate child drag event to parent. What should I do?

### Actual behavior

Child drag events not propagated parent.

### System configuration
**interact.js version**: 1.10.0
**Browser name and version**: Chrome latest version
**Operating System**: Mac OS

**Comment by taye** [comment]
Sorry, but this isn't supported.
