### ISSUE TITLE
Moving HTML draggable element into target element

### ISSUE THREAD

**Issue by Erwann** [taye/interact.js#870]
Hello,
As the title indicates, I'd like to know if it is possible to move HTML draggable element into the target element.

### System configuration
**interact.js v1.9.20**:
**Chrome and Firefox**:
**Windows 10**:

**Comment by taye** [comment]
Do you mean reparenting a dragged element to the dropzone element? This isn't a built in feature, but It's possible with `dropEvent.target.appendChild(dropEvent.relatedTarget)`. The elements may jump around so you'll need to find a way to undo the drag transforms and/or move them to the right positions.
