### ISSUE TITLE
Unable to test interact js with cypress end-to-end testing library

### ISSUE THREAD

**Issue by TimVee** [taye/interact.js#871]
This issue is the same as #856. That issue was closed because it didn't have a reproducible example, but I've created one [here](https://github.com/TimVee/cypress-interact-js).

### Expected behavior
I should be able to automate interaction with [Cypress' trigger function](https://docs.cypress.io/api/commands/trigger.html), which programmatically creates events.

### Actual behavior
Interact js does not pick up any triggered events from [cypress](https://www.cypress.io).

### System configuration
**interact.js version**: 1.10.0
**Browser name and version**: Chrome 86, Firefox 81
**Operating System**: Windows 10

**Comment by TimVee** [comment]
It seems that Cypress by default creates an event of type Event, and not a more specific type like PointerEvent. Does interact.js use `instanceof` to check the type?

**Comment by TimVee** [comment]
I've tried with the more specific Event types like PointerEvent and MouseEvent, and that makes the reproducible test pass. This issue can be closed because it seems to be an issue with Cypress' default behavior.

**Comment by taye** [comment]
By default only the primary mouse button can be used for actions and this button is checked from [`event.buttons`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons). It looks like the lib you use for triggering pointer events [doesn't set the buttons property](https://github.com/4teamwork/cypress-drag-drop/blob/master/index.js#L31) on the events so it's probably initialized to `0`. You might have to open an issue/PR in that repo or trigger your own pointer events with `{ buttons: 1 }`.
