### ISSUE TITLE
Uncaught TypeError: can't access property "hold", interaction.pointers[pointerIndex] is undefined

### ISSUE THREAD

**Issue by SinBirb** [taye/interact.js#872]
I don't know how to reproduce this as we have a fairly complex application but sometimes this TypeScript error is logged on the console after quick clicking/holding and dragging. Maybe you have an idea why. I'll probably not have much time to investigate this issue and the application/interactjs doesn't break completely from it. In fact everything still seems to work after the bug is logged, but it still look concerning:

```
Uncaught TypeError: can't access property "hold", interaction.pointers[pointerIndex] is undefined
    targets interact.js:11025
    filter self-hosted:238
    collectEventTargets interact.js:11024
    fire interact.js:10931
    timeout interact.js:11136
    W XHRProxy-dbg.js:98
    (Async: setTimeout handler)
    setTimeout XHRProxy-dbg.js:110
    downAndStartHold interact.js:11135
    interactionsDown interact.js:10896
    fire interact.js:9051
    scopeFire interact.js:8529
    pointerDown interact.js:5543
    doOnInteractions interact.js:8655
    (Async: EventListener.handleEvent)
    add interact.js:7505
    onDocSignal interact.js:8705
    scopeAddDocument interact.js:8714
    fire interact.js:9051
    addDocument interact.js:9139
    _new interact.js:7274
    interact interact.js:7810
    mounted <redacted>.vue:375
```

More readable screenshot: 
![image](https://user-images.githubusercontent.com/5778042/99809758-0a448d00-2b43-11eb-813d-68e155dedad8.png)

### System configuration
**interact.js version**: 1.10.0
**Browser name and version**: Firefox Nightly
**Operating System**: Linux

**Comment by SinBirb** [comment]
I also have just reproduced it in Chromium. pointerIndex is always -1 and `interaction.pointers.length == 0`.

**Comment by taye** [comment]
It might have something to do with `XHRProxy-dbg.js`. That seems to mess with the usual `set/cancelTimeout`. Is it possible to reproduce the error without that file?

**Comment by SinBirb** [comment]
Yes, it's independent. I blocked the requests and could still reproduce it:

![image](https://user-images.githubusercontent.com/5778042/101337825-6fef8380-387c-11eb-86f6-9f318cd82d3f.png)
