### ISSUE TITLE
Drag-plugin not working in IE11

### ISSUE THREAD

**Issue by tkallsen** [taye/interact.js#876]
A few places in the @interactjs/actions drag-plugin doesn't seem to be compatible with IE11. 

Example, destructuring assignment in actions/drag/plugin.js:

```
const {
  actions,
  Interactable,
  defaults
} = scope;
 ```

gives this error in IE11/Win10:

"Expected identifier".

Other problems in the same file with:
```
function beforeMove({
  interaction
}) {
```

Package.json:
```
"@interactjs/interact": "^1.10.1",
"@interactjs/actions": "^1.10.1",
"@interactjs/auto-start": "^1.10.1",
```

Maybe related to https://github.com/taye/interact.js/issues/782

**Comment by taye** [comment]
Are you using the scoped `@interactjs/...` packages? Those are only distributed as ES6 modules. If you need to use the library with IE11, you'll have to use the pre-bundled `interactjs` package or compile/bundle the ES6 modules to ES5.

**Comment by tkallsen** [comment]
Yes, you're right, we are using just the packages above (not the bigger pre-bundled package) which I now see in the documentation is the package specified as ES5.

I guess I'll have to bite the bullet and use the main package, just using TS -> ES5 at the moment so don't want to introduce another transpiler.

Would be very nice if the scoped packages was available as ES5 as well, but I understand that it's probably not something that will be prioritized for the minority of a minority that are interested in it ;) Hopefully we'll be able to drop IE11-support soon as well.
