### ISSUE TITLE
Adding a parent restriction to both draggable and resizable breaks resizing when child fills too much of parent

### ISSUE THREAD

**Issue by mononym** [taye/interact.js#877]
### Expected behavior
I should be able to restrict the resizing/dragging of an element to its parent at the same time, while maintaining full ability to move and resize said element even to the full size of said parent.

### Actual behavior
If a restriction, to the parent node, is given for both draggable/resizable then the div will become partially/fully unresponsive to resizing once the inner div in question grows too large and gets too close to the edge of the parent. It might not resize in one direction or in either direction, depending on exactly how the parent and child div are sized and positioned.

### Reproduction steps

1. Go here: https://codepen.io/mononym-the-bold/pen/xxEXbxL
2. Drag blue box to a corner of red parent box and release it there.
3. Resize blue box to fit parent (it does not have to fill the whole thing for this to happen, but this pretty much makes sure you get the worst experience of not being able to resize in ANY direction) and release it.
4. Try to resize inner box.
5. Cry.

### System configuration
**interact.js version**: 1.10.1
**Browser name and version**: Chrome Version 87.0.4280.88 (Official Build) (64-bit), Firefox 84.0
**Operating System**: Ubuntu

### Notes
Removing snapping entirely changes nothing.

Removing the parent restriction to draggable or droppable makes everything work again, though obviously suddenly you don't have a restriction in place which alters the behavior.

**Comment by taye** [comment]
`restrictRect` is set up to work with dragging. For resizing, [`restrictEdges`](https://interactjs.io/docs/restriction#restrictedges) is probably what you need.

**Comment by mononym** [comment]
That solution does not work for me. I don't want to stop the element from resizing beyond a certain preset size. I want to be able to resize without having the edges go out past the parent div while resizing.

I've got a UI that will have 2-10 different windows, each of them resizable and moveable. I want to let the person choose where to place them and how big to make them. Maybe one window takes up 90% of the screen or maybe they are all evenly spaced.

I do not know the size of the outer parent div beforehand, and if I can avoid having to inject/change the parent dimensions on change that would be awesome.

The logic actually does work, sorta, for the other restrict, you can't resize by dragging the mouse outside of the parent div. It's just that when the edges of the two get too close together, for some reason the algorithm seems to hit a wall where it thinks it is supposed to not let the edge resize anymore. You can actually trigger this effect in either the x or the y dimension independently, so there seems to be a math check/comparison somewhere that gets hung up when the two values are too close.

When it comes to trying this suggested solution I can still resize the inner container outside of the parent one. The dimensions that are checked seem to be relative to the page/window, not the parent div which is what I actually need.

While I can thread the data through I need and probably manually update the restrictions, I'd really rather be able to just plop down that other restriction, which does not call out as being only for draggable, which doesn't even let me move the mouse outside the parent when resizing.

I accidentally overwrote the original paste with the suggestion you gave above, instead of beginning a new one, so if you go back to that link you can see the behavior I'm talking about with your suggested change.

**Comment by mononym** [comment]
Another interesting tidbit on the behavior when using restrictrect for both dragging and resizing. If you get the bug to trigger with resizing and still have room to drag the element around, you can get it to "reset" and let you begin to resize again.

Sometimes it will only 'reset' enough to let you resize downwards some portion of the size before hitting a wall again. Other times it will completely reset the div and you can then properly resize again within the confines of the parent.

It really feels like they are both using the algorithm in just...slightly different ways and there is an assumption buried somewhere that does not hold true for both things, and it only messes with resizing.

**Comment by mononym** [comment]
So you are correct in one sense, that I simply cannot use `restrictRect()` because it is designed specifically for dragging. You can tease that information out of a sentence in the description that ends with `while dragging.`

However right below that for the description of `elementRect` it has this line `restrictRect is identical to restrict` which I took to indicate that it could be used. In addition, at the very top, only `restrictSize` and `restrictEdges` are specifically called out as being restricted to a type of action. I think `(drag only)` needs to be added for `restrictRect`.

See: https://interactjs.io/docs/restriction

As to what I want to have to get the behavior I want, it's simply `restrict` with the parent option.
