### ISSUE TITLE
Angular 11 strict mode

### ISSUE THREAD

**Issue by georgstrieder** [taye/interact.js#882]
First: I love your lib! It really helped me to realize my project. So great job!

The Angular platform introduced a new strict mode in Angular 11 (https://angular.io/guide/strict-mode). It would be great if interact.js would comply with these stricter rules.

![Bildschirmfoto 2021-01-26 um 11 53 52](https://user-images.githubusercontent.com/681427/105837473-06b00500-5fcf-11eb-9e34-646add20b827.png)

**Comment by towify** [comment]
The same problem, I had to manually replace <null> -> "resize" | "drag" | ... in nodemodule  dirctory ：（
