### ISSUE TITLE
Babel plugin fails to resolve module paths

### ISSUE THREAD

**Issue by dsrkafuu** [taye/interact.js#885]
Building code with webpack and babel-loader failed, seems that the babel plugin cannot correctly replace the imported paths.

Issue demo repo: https://github.com/dsrkafuu/interactjs-babel-plugin-issue-demo

### Babel plugins and presents

`@babel/preset-env`, `@babel/plugin-transform-runtime` and `@interactjs/dev-tools/babel-plugin-prod`

### Module imported
```
import '@interactjs/auto-start';
...
import _interact from '@interactjs/interact';
```

### Actual behavior
Webpack throws an error that says like:
```
Module not found: Error: Can't resolve '@interactjs/E:\demo\node_modules\@interactjs\auto-start\index.prod' in 'E:\demo\src'
...
Module not found: Error: Can't resolve '@interactjs/E:\demo\node_modules\@interactjs\interact\index.prod' in 'E:\demo\src'
```

### Error logs

Checkout the `logs` folder of demo repo:

- Webpack: https://github.com/dsrkafuu/interactjs-babel-plugin-issue-demo/blob/main/logs/webpack-error.log
- npm: https://github.com/dsrkafuu/interactjs-babel-plugin-issue-demo/blob/main/logs/npm-error.log

### System configuration
**interact.js version**: `1.10.3`
**Operating System**: `Windows 10 20H2`
**Node.js version**: `14.15.5`

**Comment by taye** [comment]
Can you try with `v1.10.4`?

**Comment by dsrkafuu** [comment]
Works great now! 😄
