### ISSUE TITLE
Pro Status?

### ISSUE THREAD

**Issue by forrestmid** [taye/interact.js#886]
I was looking around for some updates on the timeline for your pro offering. I found some posts from 5-6 months back targeting a beta in 1-2 months from then, which would be three months ago now. 

Any updates or plans on releases for that? I'm specifically interested in your "snap to element" functionality.

**Comment by taye** [comment]
I underestimated the effect that the current pandemic would have on my motivation, but I've picked up the pace again. If you send me an email to the address on my profile, I can give you some more info and access.
