### ISSUE TITLE
dependencies version not found

### ISSUE THREAD

**Issue by z-eleven** [taye/interact.js#888]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:
![image](https://user-images.githubusercontent.com/7909420/109763525-291bea80-7c2d-11eb-81f9-f42ac59e0ba3.png)

![image](https://user-images.githubusercontent.com/7909420/109763579-3cc75100-7c2d-11eb-91b0-2b97fc16c3d6.png)

![image](https://user-images.githubusercontent.com/7909420/109763625-4e105d80-7c2d-11eb-863f-004426312106.png)

### Expected behavior
npmjs 中并没有找到v1.10.5版本的 @interactjs/vue，甚至其他依赖

### Actual behavior
希望在发布新版本时能够充分测试

### System configuration
**interact.js version**: 1.10.5
**Browser name and version**: -
**Operating System**: mac os

**Comment by Raunplaymore** [comment]
"resolutions": {
    "@interactjs/vue": "1.10.3",
    "@interactjs/react": "1.10.3",
    "@interactjs/multi-target": "1.10.3",
    "@interactjs/feedback": "1.10.3",
    "@interactjs/arrange": "1.10.3",
    "@interactjs/clone": "1.10.3"
  }

downgrade works

**Comment by z-eleven** [comment]
我直接使用的是 vue-grid-layout 这个包，依赖了@interactjs

**Comment by lizhongyue248** [comment]
> 我直接使用的是 vue-grid-layout 这个包，依赖了@interactjs

同样的问题

**Comment by Ryan2128** [comment]
I also encountered the same problem and hope to solve it as soon as possible.

**Comment by rahulshinde11** [comment]
I have the same issue, in my vue app
![image](https://user-images.githubusercontent.com/44699277/109770450-99bd0a00-7c21-11eb-985d-7f695b37b4d2.png)

**Comment by joepsyko** [comment]
I encountered the same error

**Comment by RenanRossiDias** [comment]
Same with @interactjs/arrange@1.10.5

We're grounded due to this issue.

**Comment by rahulshinde11** [comment]
For quick fix, manually install in the project.
` npm i @interactjs/interactjs@1.10.3`

**Comment by taye** [comment]
should be fixed in `v1.10.6`
