### ISSUE TITLE
Uncaught TypeError: interact.dynamicDrop is not a function

### ISSUE THREAD

**Issue by jkhulme** [taye/interact.js#896]
### Expected behavior
We're doing
`interact.dynamicDrop(true);`
It should work

### Actual behavior
We started getting this error
`Uncaught TypeError: interact.dynamicDrop is not a function`

### System configuration
**Interact version**:
I think version 1.10.10, but might be version 1.10.9
We're just pulling the latest from the CDN
`<script src="https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js"></script>`

**Browser name and version**:
Firefox 87

**Operating System**:
MacOS 11.2.3

**Comment by jkhulme** [comment]
I noticed this similar error - https://github.com/taye/interact.js/issues/895

**Comment by taye** [comment]
Can you try again with the latest version?

**Comment by jkhulme** [comment]
Tried with 1.10.11 and it's working.  thanks!
