### ISSUE TITLE
There should be a convenient way to work with transformed coordinates

### ISSUE THREAD

**Issue by taye** [taye/interact.js#90]
I have something like this http://stackoverflow.com/a/5223921 in mind but the user supplies the matrix to use.

Suggestions and use cases are welcome :).

**Comment by jdittrich** [comment]
did you continue to work/think about this issue? 
I suppose a user supplied matrix is fine; As well I assume that automatically getting the transforms at the first event and than caching these would be a reasonable compromise, too.

**Comment by taye** [comment]
See https://github.com/taye/interact.js/issues/137#issuecomment-158573651.
