### ISSUE TITLE
https://interactjs.io/ on mobile

### ISSUE THREAD

**Issue by guettli** [taye/interact.js#903]
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior

I want to see the examples via mobile phone: https://interactjs.io/

### Actual behavior

I see the code on my phone, but not the movable blue boxes like on desktop.

### System configuration

https://unpkg.com/interactjs@1.10.11/dist/interact.min.js

os: Android

**Comment by taye** [comment]
Fixed!
