### ISSUE TITLE
Type compilation error in angular7 

### ISSUE THREAD

**Issue by SammmmO** [taye/interact.js#907]
Angular : 7.2.11
typescript：3.2.4
interact:1.9.18 or 1.10.11

error: ERROR in node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1941,50): error TS1005: ']' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1941,80): error TS1131: Property or signature expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1941,86): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1942,23): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1942,39): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1943,72): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1943,88): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1943,180): error TS1005: '(' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1944,64): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1944,80): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1945,40): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1945,56): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1945,148): error TS1005: '(' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1946,36): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1946,52): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1946,144): error TS1005: '(' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(1949,1): error TS1128: Declaration or statement expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2140,36): error TS1005: ']' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2140,38): error TS1131: Property or signature expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2140,41): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2140,43): error TS1109: Expression expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2140,131): error TS1005: ';' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(2143,1): error TS1128: Declaration or statement expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(3389,51): error TS1005: ',' expected.
node_modules/interactjs/node_modules/@interactjs/types/index.d.ts(3389,52): error TS1005: ',' expected.
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**interact.js version**:
**Browser name and version**:
**Operating System**:

**Comment by taye** [comment]
You'll have to use at least typescript `3.8` which might require upgrading angular

**Comment by SammmmO** [comment]
@taye Thank you . So based on TypeScript: 3.2.4 Which version of interactJs should I use?

**Comment by taye** [comment]
`v1.9.16` seems to work, though you might find some bugs that have been fixed in newer versions
