### ISSUE TITLE
Idea: restrictEdges to have option of calling a function, similar to restrictRect.restriction.

### ISSUE THREAD

**Issue by cepm-nate** [taye/interact.js#910]
Thank you for this amazing library!

In my situation, I'm generating an area of "allowable ranges" (not dropzones) when the interactable's startresize() is fired.

The 'restricRect' modifier allows a function as the 'restriction' which is called during dragmove and resizemove events.  However, the concept is a little unclear on what 'left' means when dealing with a resize. Is that 'left' value the minimum? Maximum? In my testing it feels like a maximimum, but a minimum restriction also seems to be in play somewhere, but with no way to remove it.

Seeing as you already have well thought-out restrictEdges and restrictSize modifiers, it seems like it'd make sense to expand them to alternatively take a function that returns the same values as is already expected for restrictEdges and restrictSide.

Thoughts?

**Comment by cepm-nate** [comment]
Upon further testing, it looks like 'right' acts as the limit when dragging the left side, and 'left' acts as the other limit when dragging the right side. It feels a little odd, but can be played with here: https://jsfiddle.net/nathansutherland/knusdtrb/

**Comment by cepm-nate** [comment]
I've resorted to modifying the event directly, just before I update the GUI. I think it'd be smarter to use **restrictEdges()** as a function, but for now I can work around it. :-)

**Comment by taye** [comment]
You can already pass a function to `restrictEdges`' `inner` and `outer` options, and `restrictSize`'s `min` and `max`
