### ISSUE TITLE
Memory management - Detached HTML elements

### ISSUE THREAD

**Issue by jf-m** [taye/interact.js#911]
### Expected behavior
I'm using interactjs with VueJS in a SPA where I need to destroy/recreate several times an interact element.
When I need to destroy an interactable element I do the following:

```
        interact(element).unset();
        interact.removeDocument(document);
```

This call should be enough for the GC to collect and garbage all the retained memory by interactjs.

### Actual behavior
In the heap snapshots of Chrome there is multiple `Detached HTMLElement` stored and never released by `interactjs` every time I `unset()`.

Parts of this issue are regression probably due to the recent rework of interactjs. They were solved in an older version, cf #713 

Here is the list of all the variables I've detected that retains a reference to a DOM element in the latest version of interactjs:

1. `scope.interactions.list[0].inertia`

![Screenshot 2021-04-27 at 16 00 16](https://user-images.githubusercontent.com/9339799/116267744-98691300-a774-11eb-833d-79c5c5ede2a6.png)

2. `interaction.prevTap` inside `autoScroll`

![Screenshot 2021-04-27 at 15 08 38](https://user-images.githubusercontent.com/9339799/116267883-b33b8780-a774-11eb-9494-45863ac858c6.png)

3. `scope.interactions.list[0].downEvent`

![Screenshot 2021-04-27 at 15 03 24](https://user-images.githubusercontent.com/9339799/116267942-c0f10d00-a774-11eb-83eb-163a152b6d82.png)

4. `scope.interactions.list[0].prevTab.path`

![Screenshot 2021-04-27 at 14 55 52](https://user-images.githubusercontent.com/9339799/116268013-cfd7bf80-a774-11eb-982c-c80134bcec6f.png)

I guess that the destroy/unset procedure does not remove every references stored by interactjs.
I'm working on a proposed solution for this issue. I'll post the update here.

I can already see that the `unset` procedure currently implemented is not fully triggered at the moment, because of the following line : 

https://github.com/taye/interact.js/blob/72606e7bbc52e6388964f0762719084dbae19333/packages/%40interactjs/core/interactions.ts#L268-L270

When I'm using Chrome Debugger, it says that `interaction.interactable` is always null thus never equals to `interactable`, so the rest of the loop is actually never triggered (in my case). Neither the `stop()` nor the `destroy()`.

Secondly, the following line : 

https://github.com/taye/interact.js/blob/72606e7bbc52e6388964f0762719084dbae19333/packages/%40interactjs/core/interactions.ts#L276-L278

In my case, `scope.interactions.list` always contains 1 element. Therefore, the `list` is not purged, which is also problematic.

I'll try to dig further and I'll share the updates here.

### System configuration
**interact.js version**: 1.10.11
**Browser name and version**: Chrome 90
**Operating System**: MacOS Big Sur

**Comment by jf-m** [comment]
After further investigations, it appears that some plugins are missing a destroy procedure.

To sum up, here is what I would do to solve this issue : 

## A) Null proof destroy procedure

https://github.com/taye/interact.js/blob/72606e7bbc52e6388964f0762719084dbae19333/packages/%40interactjs/core/interactions.ts#L268-L270

Change this line into 
`interaction.interactable && interaction.interactable !== interactable`

However, I'm not sure of the impact of this change.

## B) Handle a list of one element

https://github.com/taye/interact.js/blob/72606e7bbc52e6388964f0762719084dbae19333/packages/%40interactjs/core/interactions.ts#L276-L278

Remove the condition and only do a `scope.interactions.list.splice(i, 1) ` every time.

However, I'm not sure to understand why this condition is here at the first place. Maybe it's not that easy to solve.

## C) Listen to `interactions:destroy` event in all the modules

Modules like `inertia` and `modifiers` should listen to the `interactions:destroy` event and remove any references to any DOM elements..

For example, I would add the following listener in the `inertia/plugin.ts`

```

  function destroy ({ interaction }: { interaction: Interaction }) {
    const state = interaction.inertia
    state.modifierArg = null
    state.modification.destroy()
  }

```

```
    'interactions:destroy':  destroy
```

## D) Set to null `prevTab`, `inertia` and `downEvent`

https://github.com/taye/interact.js/blob/d0a8b5f42ac509ba1ff93cca91a0f3b0d92e90ee/packages/%40interactjs/core/Interaction.ts#L573-L576

Add the following : 

```
        this.prevTap = null
        this.downEvent = null
        this.inertia = null
```




--- 

This said I'm once again not sure about the impact of all these changes. I would do a PR request if I could, but first I don't know why I cannot easily build the project right now. (I'm using node 16, npm 7.10, yarn 1.22.10, tsc 4.2.3, and I'm getting a lot of errors like `packages/@interactjs/actions/drag/index.ts(2,22): error TS2307: Cannot find module '@interactjs/interact/index' or its corresponding type declarations.` when I try to `yarn build`, so I cannot even test what I just said before).

But also, I am unfortunately lacking spare time right now to handle it properly. Regarding my project, I will probably go back to the version 1.4 until I have more time to help you out on this or until you have time to solve it.


Thank you very much for maintaining this awesome project by the way.

**Comment by v1talii-dev** [comment]
The problem is relevant when using the [vue-grid-layout](https://github.com/jbaysolutions/vue-grid-layout) package. Are there any updates on this task?

**Comment by jf-m** [comment]
No update from my side since then. I'm not sure I'll have time to look at it soon, I'll post here if I find some time to start a PR.

**Comment by timothyallan** [comment]
I just ran into this, not sure why it got closed. Loads of detached elements and memory leaks still in the latest version :|
