### ISSUE TITLE
Restrict a draggable within a div

### ISSUE THREAD

**Issue by adlaigordon** [taye/interact.js#92]
Hi,
I'd like to be able to restrict the dragging of an element to within a div, something like:

``` javascript
.restrict({
    drag: document.getElementById('container'),
})
```

Is there a way to do this?

**Comment by KarandeepSingh1** [comment]
Can you show the code so that i can also use it...

interact('.draggable')
      .draggable({
        onMove: function (event) {
          console.log("ecvent", event)
          restrict: {
            drag: event.getElementsByClassName('.userprofile-main')
          }
        }
      })


this is my code please help me where am i wrong. its not working

**Comment by talhakaanozkan** [comment]
©           

        ©
