### ISSUE TITLE
Resizable element on mobile device - is being resized when trying to scroll on the element

### ISSUE THREAD

**Issue by uriklar** [taye/interact.js#921]
I have an element defined as resizable. I've passed this as the edges prop:
```
 edges: { left: true, right: true, bottom: true, top: true }
 ```
 
 My problem is that on a mobile device, if I try to scroll the screen from the center of the element, the touch event makes it resize (see attached gif, you can't see my finger but what I'm doing is trying to scroll the page from the center of the element)

### Expected behavior
Element should only resize when touching one of the edges

### Actual behavior
Element resizes also when touching and scrolling on the center of the element

### System configuration
**interact.js version**: 1.9.20
**Browser name and version**: IOS Simulator
**Operating System**: MacOS

### What I've tried

**EDIT:** I actually tried recreating this in your docs page of the resizable and there it doesn't happen. So if anyone has an idea what could be causing this i'd be happy to hear. Thanks!

I've tried putting:
```
touch-action: none;
user-select: none;
```
On the resizable container

![resizer-bug](https://user-images.githubusercontent.com/2545447/120920618-65e1fc80-c6c8-11eb-8d36-08dfc4224657.gif)

**Comment by uriklar** [comment]
So my issue was caused by the entire edge being a trigger for the resize. So when I try to scroll I was actually grabbing the edge. What I wanted was the resizable to be resizable only via it's corners.
I was confused between the definitions of edge and corner. So FYI to anyone trying to achieve resize only via corners:
I saw in one of the comments on an issue here that "a corner is defined as an intersection of two edges"

So what I ended up doing is something like this:
```
// in my html I have these corners (the blue circles)
<div className="resizable-edge-top-left"/>
<div className="resizable-edge-top-right"/>
<div className="resizable-edge-bottom-left"/>
<div className="resizable-edge-bottom-right"/>
                    
```

And in my resizable init I pass in the edges like this:
```
edges: {
                    left:
                        '.resizable-edge-top-left, .resizable-edge-bottom-left',
                    right:
                        '.resizable-edge-top-right, .resizable-edge-bottom-right',
                    bottom:
                        '.resizable-edge-bottom-right, .resizable-edge-bottom-left',
                    top:
                        '.resizable-edge-top-left, .resizable-edge-top-right'
                },
```

Each "corner" selector is being matched by two edges, and this intersection makes it so that only the corner is resizable, not the entire edge

**Comment by JulCyan** [comment]
Thanks, this is usefully for me
