### ISSUE TITLE
touch drag aborted

### ISSUE THREAD

**Issue by saeldion** [taye/interact.js#927]
I'm trying to implement leaving a clone behind when dragging, following the [FAQ](https://interactjs.io/docs/faq/#clone-target-draggable) and have gotten it to work for the mouse.
But when I try to use touch events, the drag start as they should, my clone is created etc. But as soon as my finger leave the original interact target the `onend` event is triggered for some reason and my drag is "aborted".

I have no idea why this is happening. How does the mouse and touch events differ in a way to cause this to happen?

I'd appreciate any help if the error is on my end, or figure out if it's a bug.

The attached video shows the touch behaviour.

https://user-images.githubusercontent.com/2678144/125618604-57ab89ab-fb73-4745-af7f-0c0c8e28dc43.mov

The code:
```
const element = document.querySelector("...")

// other code inbetween

interact(element)
    .draggable({
        manualStart: true,
        onmove(e: DragEvent) {
            // update clone position
            updateClonePosition(e)
        },
        onend(e: DragEvent) {
            // remove the clone from the DOM
            cloneRef.remove()
        },
    })
    .on("move", (e: InteractEvent) => {
        const { interaction, currentTarget, interactable } = e
    
        if (interaction.pointerIsDown && !interaction.interacting()) {
            const { x, y } = currentTarget.getBoundingClientRect()
            initialPosition = { x, y }
    
            const clone = currentTarget.cloneNode(true)
            clone.classList.add("drag-clone")
    
            document.body.appendChild(clone)
    
            cloneRef = clone
    
            interaction.start({ name: "drag" }, interactable, clone)
        }
    })
```

**Comment by saeldion** [comment]
Threw together this [CodeSandbox demo](https://codesandbox.io/s/nice-meitner-t4bcr) showcasing the issue.
As you'll notice, the drag works in the browser using the mouse. But if tried on a touch device (Galaxy S9 for me) the drag event is ended as soon as the mouse exists the original target.

**Comment by saeldion** [comment]
Okay I think I've solved it. At least it seems to be working at the moment :)

The problem was React. React uses it's own synthetic events which interact.js understandably doesn't override. So while interact.js has overriden the normal touch events, Reacts touch events are still firing causing the page to pan.

So I solved it by overriding the touch events again, on the `ref` passed into `interact(...)`. Might have been a bit overzealous and overridden all touch  events I thought could be the culprit without narrowing it down. But this is the final code in the hook I'm using:
```
useEffect(() => {
    const element = elemRef.current!

    element.ontouchstart = e => {
        e.preventDefault()
    }
    element.ontouchmove = e => {
        e.preventDefault()
    }
    element.ontouchend = e => {
        e.preventDefault()
    }

    // Setup interactjs
    const interactObj = interact(elemRef.current!)
        .draggable({
            manualStart: true,
            onmove(e: DragEvent) {
                setClonePosition(e)
            },
            onend(e: DragEvent) {
                removeClone()
            },
        })
        .on("move", (e: InteractEvent) => {
            const interaction = e.interaction

            if (interaction.pointerIsDown && !interaction.interacting()) {
                const clone = e.currentTarget.cloneNode(true) as HTMLElement
                clone.classList.add("drag-clone")

                document.body.appendChild(clone)

                cloneContainer.current = clone

                interaction.start({ name: "drag" }, e.interactable, clone)
            }
        })

    return () => {
        interactObj.unset()
    }
}, [])
```

**Comment by fratzinger** [comment]
Just for somebody who comes here and looking for a solution for the problem.
The above method worked for me, finally!

Thanks @saeldion! Although I work with interactjs on Vue.js your solution helped for me. With your instructions I've added
```js
@touchmove="event => isDragging && event.preventDefault()"
```
to the template. With:

```ts
interact(".draggable")
        .draggable({
          enabled: true,
          inertia: true, // enable inertial throwing
          hold: 200,
          autoScroll: true,
          manualStart: true,
        })
        .on("hold", event => {
          const { interaction } = event;

          if (!interaction.interacting()) {
            interaction.start({ name: "drag" }, event.interactable, event.currentTarget);
          }
        })
        .on("dragstart", event => {
          isDragging.value = true
        })
        .on("dragmove", event => {
          const { dx, dy } = event;
          // work with dx & dy
        })
        .on("dragend", () => {
          isDragging.value = false
        })
        .on("contextmenu", event => {
          event.preventDefault();
        });
    });
```
in the script.

No `touch-action:none` needed at all!
