### ISSUE TITLE
restrictRect({...}) modifier doesn't allow resize to shrink object

### ISSUE THREAD

**Issue by Gkleinereva** [taye/interact.js#930]
### Expected behavior
The restrictRect({...}) modifier should be able to be used to restrict resizes within an element.  Resizes should work correctly so long as they are within the specified element.

### Actual behavior
When applying the restrictRect modifier to a call of interact(...).resizable(), I can correctly resize my object to be larger.  However, I cannot make the object smaller.  Thanks for your hard work and effort, please let me know if this isn't a bug and is a case of developer error.  :)

### Reproduction steps
1. Open this codepen: https://codepen.io/Gkleinerva/pen/ZEyLNdQ
2. Use the right side of the blue div to resize the div such that it is wider
3. Now, try to use the right side of the div to resize it such that it's narrower
4. Note that while the animation shows the div shrinking, it snaps back to its original shape

### System configuration
**interact.js version**: 1.10.11
**Browser name and version**: Chrome Version 92.0.4515.159 (Official Build) (64-bit)
**Operating System**: Windows 10 Home
**Machine**: Lenovo Legion (no touch screen)

**Comment by myspoonistoobig** [comment]
I'm having this exact same issue. I can possibly add some more clarity. 

I experience the issue when the element is touching one or more edge boundaries of the parent I am restricting it to. I have draggable turned on for my elements as well. If I drag the element away from the edge, I can resize it and then put it back in place. If I leave it at the edge it will not behave correctly.

Additionally, after I have dragged the element away from the edge, I can only shrink it by the amount of difference between the edge and the nearest element boundary on that axis.

**Comment by Gkleinereva** [comment]
I ended up switching it to restrictEdges() as they do in the "Resizing" example on their homepage https://interactjs.io/.    It fits my use case fine, although I still think this is a defect.

**Comment by myspoonistoobig** [comment]
Thanks! I just tested your solution and it will work in my case as well. I would also agree that it's still a defect.
