### ISSUE TITLE
Incorrect dropzone after scrolling

### ISSUE THREAD

**Issue by davek1979** [taye/interact.js#939]
To simplify the issue, I'm only talking about horizontal scrolling.
In a long horizontal list of dropzones in a scrollable container, dragging doesn't target correct dropzone if horizontal scrolling occurs.
This is without using the autoScroll feature.
Dropzone overlap is set to "pointer".
Scrolling is set to happen after getting cursor within some distance from each side.

### Expected behavior
All the way throughout dragging and possible scrolling of the parent container, target dropzone should be correctly identified under mouse cursor.

### Actual behavior
When dragging horizontally to the right, after scrolling past a few dropzones, instead of targeting the dropzone underneath the cursor Interact.js actually targets the last dropzone visible in the container before scrolling.
I believe this is because the internal pointer data ignores scrollLeft and scrollTop of the parent container - hence not targeting the correct dropzone.

### System configuration
**interact.js version**: '1.10.11'
**Browser name and version**: Chrome  95.0.4638.69
**Operating System**: Windows 10

**Comment by taye** [comment]
Calling `interact.dynamicDrop(true)` should fix this.
