### ISSUE TITLE
🐛 webcomponent slot drag element not subject to parent slot

### ISSUE THREAD

**Issue by duoduoObama** [taye/interact.js#950]
### Expected behavior
When the slot element of a web component is dragged, it should be based on the position of the parent element of the slot

### Actual behavior
webcomponent slot drag element not subject to parent slot 

### System configuration
**interact.js version**:1.10.11
**Browser name and version**:chrome 97
**Operating System**:win 10

webcomponent slot drag element not subject to parent slot 

https://stackblitz.com/edit/vitejs-vite-pppejv?file=src%2Fcomponents%2Findex.ts&terminal=dev

**Comment by taye** [comment]
The custom-element has `display: inline` by default so it doesn't have a size. It works if you give it CSS `display: inline-block`.

**Comment by duoduoObama** [comment]
Similar issues: https://github.com/daybrush/moveable/issues/684
