### ISSUE TITLE
Move a clone of the source

### ISSUE THREAD

**Issue by skerit** [taye/interact.js#96]
Is interact.js able of leaving the original element alone and moving a clone of it?

**Comment by dobromir-hristov** [comment]
I tried this but now the dropzone doesn't fire events when I drag the Clone over it... Any tips what I should do?

**Comment by taye** [comment]
@dobromir-hristov Here is a better method to do target cloning taken [from the faq](http://interactjs.io/docs/faq/#clone-target-draggable):

```javascript
interact('.item')
  .draggable({ manualStart: true })
  .on('move', function (event) {
    var interaction = event.interaction;

    // if the pointer was moved while being held down
    // and an interaction hasn't started yet
    if (interaction.pointerIsDown && !interaction.interacting()) {
      var original = event.currentTarget,
          // create a clone of the currentTarget element
          clone = event.currentTarget.cloneNode(true);

      // insert the clone to the page
      // TODO: position the clone appropriately
      document.body.appendChild(clone);

      // start a drag interaction targeting the clone
      interaction.start({ name: 'drag' },
                        event.interactable,
                        clone);
    }
  });
```

**Comment by dobromir-hristov** [comment]
Yes I saw that example, but I cannot get it to move on drag for the life of me. I tried with ondrag on move, and I get more and more messed it. 
Here is a fiddle:
http://jsfiddle.net/djdobro/jh6gofL4/3/
Allow From does not work too :(

At best I managed to make it move only when my mouse was over the image (not dragging, just over), but that is not what we want is it :(

**Comment by scattered** [comment]
@dobromir-hristov I came used this code to get basic cloning to work. It doesn't meet all your needs, but it should get you started.

http://jsfiddle.net/gv0f16nq/

Good luck!

**Comment by dobromir-hristov** [comment]
This is not helping much. It was what I had (just the whole "move it" part is inside the onmove param of draggable. I did not think that onmove and .on('move') were not the same....
Now I`m getting some serious weird things like:
If I have images inside the draggable, I get the image dragged instead of the "draggable" element. Ok I will use a handle, no problem. 
Same thing. Handle gets dragged on its own then when I drop the handle, then I get my clone following my mouse, but now I`m not holding my mouse button.... I will try and make a fiddle to explain my self.

**Comment by scattered** [comment]
@dobromir-hristov I might not 100% understand what your requirements are. Can you give a breakdown of what you're trying to achieve?

In any case, I've made another fiddle with a clone drag / drop.

http://jsfiddle.net/dw3xdhch/

**Comment by dobromir-hristov** [comment]
Haha you are using Chrome :) 
Try under firefox and see what I mean. The arrows and the Image it self are draggable elements, meaning they interfere with the dragging from the plugin it self. On Chrome it looks OK, but try on Firefox and see what I mean.

**Comment by scattered** [comment]
@dobromir-hristov You're right. I just tried in Firefox and it does exactly as you said. I'm busy for the rest of the day. Once I get some free time I'll try to look into this for you. 

If anyone else with more experience using this library is able to provided some advice, it would be appreciated.

**Comment by dobromir-hristov** [comment]
I`m still working on it. There are some issues like Chrome and Safari Selecting every text there is on the website while dragging.
Or Iphone triggering clicks on Anchor elements on drag end ?? Really strange stuff :D I will look more into it.

**Comment by taye** [comment]
@dobromir-hristov You need to prevent the browser's native drag events. The following should work in your case:

```javascript
// listen for HTML5 native drag and drop API dragstart event
document.addEventListener('dragstart', function (event) {
    // use interact.js' matchesSelector polyfil to
    // check for match with your draggable target
    if (interact.matchesSelector(event.target, '.drag-element, .drag-element *')) {
        // prevent and stop the event if it's on a draggable target
        event.preventDefault();
        event.stopPropagation();
    }
});
```

**Comment by dobromir-hristov** [comment]
Yes. This fixes quite allot of things with dragging :) Should be noted somewhere more visible.

**Comment by taye** [comment]
Yeah, I think it also makes sense to prevent native `dragstart` on interactable elements by default.

**Comment by dpekkle** [comment]
Any info on the
// TODO: position the clone appropriately
Haven't got a solution working yet.

**Comment by cawoodm** [comment]
It's interesting how hard this is to do with interact. Dragula offers clone functionality natively. Just sayin...

**Comment by noc2spam** [comment]
As for a hack, I did this:

	var draggedElement = null;
	var draggedFromParent = null;
	interact('.js-drag')
        .draggable({ inertia: true, 
		      max: Infinity, 
			  restrict: {
			  restriction: 'self',
			  elementRect: { left: 0, right: 0, top: 1, bottom: 1 },
			  endOnly: true
			}, 
		}).on('dragstart', function (event) {
				draggedFromParent = event.interaction.element.parentNode;
				draggedElement = event.interaction.element.cloneNode(true);
				// and other codes after this.
		 }).on('dragend', function (event) {
				draggedFromParent.appendChild(draggedElement);
				draggedElement = null;
				// and other codes after this.
			});
I would also love to have a `clone:true` option somehow.

**Comment by koutsenko** [comment]
@cawoodm i also stuck at missing clone feature, so dragula sounds interesting, they also have a react bindings

**Comment by koutsenko** [comment]
@taye Any info on the 
// TODO: position the clone appropriately
Haven't got a solution working yet.

**Comment by wislem** [comment]
I have tried all above solutions and am sad to say that none works properly on touch devices.
The cloned element behaves like its restriction is the original event.target and not what is specified on the initialization of the .draggable() function. Looks like cloneNode() does not clone the restrictions (on touch devices only?).

You can see what I mean by going here: http://jsfiddle.net/gv0f16nq/2/ and trying Chrome's device emulator.

@taye or anyone else, is there any work around on this?

Thanks in advance!

**Comment by dpekkle** [comment]
I looked a bit into it @wislem . I couldn't get it to work with touch screen even when entirely deleting all your cloning code, try out http://jsfiddle.net/gv0f16nq/41/

Haven't worked with this library in a while but it seems like that's a place to start.

**Comment by wislem** [comment]
Thanks for your time @dpekkle, but this has the exact same behavior. On my end, I'm cloning the draggable element and in no way can it move past the borders of the original element on touch screens. I guess I'll have to try dragula and see what it can do.

**Comment by dpekkle** [comment]
>but this has the exact same behavior

Well yeah, that's what I'm saying. But yes, I'd go with a different library this one has a lot of difficulties with manual start and events.

**Comment by odahcam** [comment]
I've successful made a "clone drag & drop" (https://codepen.io/odahcam/pen/gRqKJj?editors=0010), but its not working in touch devices as well.

If someone needs help to create the manipulation logic, feel free to use my code.
And, I would be glad if someone could help me on make this work in touch devices.

**Comment by mrrovot** [comment]
To make it work on touch devices use:

```
.dragging-container,
.dragging-container * {
  -ms-touch-action: none;
  touch-action: none;
}
```
found it on stackoverflow and works good

**Comment by BryanCalub** [comment]
hi sir odahcam how to fix this thanks
![untitled](https://user-images.githubusercontent.com/44012910/46712085-e6cf6880-cc81-11e8-89e8-e600797748af.png)

**Comment by tweet** [comment]
> @dobromir-hristov Here is a better method to do target cloning taken [from the faq](http://interactjs.io/docs/faq/#clone-target-draggable):
> 
> ```js
> interact('.item')
>   .draggable({ manualStart: true })
>   .on('move', function (event) {
>     var interaction = event.interaction;
> 
>     // if the pointer was moved while being held down
>     // and an interaction hasn't started yet
>     if (interaction.pointerIsDown && !interaction.interacting()) {
>       var original = event.currentTarget,
>           ... ...
> ```

@taye  When use ` .on('move', function (event) {`, `event.currentTarget` value is undefined, I find that `event`'s type is `PointerEvent`, but when I use `onmove` property, `event`'s type is `InteractEvent`, please help!
