### ISSUE TITLE
interactjs.io - Drag&Drop fails on Debian 11 KDE and Ubuntu 22 LTS

### ISSUE THREAD

**Issue by GwenDragon** [taye/interact.js#967]
1. Open https://interactjs.io 
1. Try to drag the blue boxes

### Expected behavior
Box moves

### Actual behavior
Box does not move

### System configuration
**interact.js version**: 
Not known
**Browsers:**
Chrome 101.0.4951.54
Chrome 102.0.5005.40
Chrome 103.0.5028.0 
Vivaldi 5.2.2623.41 
Vivaldi 5.3.2658.3
Debian 11 KDE / Ubuntu 22 LTS

**Comment by cheekybuddha** [comment]
Also fails with Debian 10 / Gnome and Vivaldi 5.3.2658.3 (Official Build) snapshot (64-bit)

**Comment by Aperrix** [comment]
Also fails on Fedora 35 with GNOME 41.6 (tested on chrome & firefox)
```Linux fedora 5.17.6-200.fc35.x86_64 #1 SMP PREEMPT Mon May 9 14:22:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by cheekybuddha** [comment]
Appears this issue is resolved now. 

Debian 11 / Gnome 3.38.6 / Vivaldi 5.5.2770.3 (Official Build) snapshot (64-bit)

**Comment by GwenDragon** [comment]
Fails with 
Vivaldi 5.5.2770.3 
Chrome 105.0.5195.102

OS: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-17-amd64

**Comment by holema** [comment]
First of all, thanks for the great library.
I have very different behaviour in linux systems:
Debian 11 with
1. Firefox works great as expected (Like in Win10 with Chrome)
2. Chrom: dragging and resize is possible but the icony for dragging and resizing are not shown

Ubuntu 20.04. with Mate-Desktop andLightDM. 
Chrome: 99.0.4844.84
No drag and drop possible. But when I __click__ the drag handle, the cursor changes to dragging symbol, but still no dragging is possible.

**Comment by holema** [comment]
@taye, can I support the bugfixing so we can use the library for out lunix projects as well.

**Comment by GwenDragon** [comment]
Works now on Linux :-) 
Thanks.

**Comment by frankie-zeng** [comment]
@GwenDragon Hi, can the lib work in linux?

**Comment by GwenDragon** [comment]
Yes, the lib woks in Linux Debian 11 now.

**Comment by frankie-zeng** [comment]
> Yes, the lib woks in Linux Debian 11 now.

My env:
electron: Chromium [112.0.5615.204](https://source.chromium.org/chromium/chromium/src/+/refs/tags/112.0.5615.204:)
ubuntu:22.04 LTS

still not ok,  any tips?

**Comment by Aperrix** [comment]
still not ok on fedora 37

**Comment by GwenDragon** [comment]
My tests were on Debian 11 on browsers and HTML+JS files:
Chromium 117
Vivaldi 6.2 (is Chromium 116)
Vivaldi 6.4 (is Chromium 118)
and all was o. for me.

**Comment by frankie-zeng** [comment]
Does this library use any special css tricks, is there a way to downgrade it? @taye
