### ISSUE TITLE
Resizing cannot assign elements for corner edges, only top, left, right and bottom edges available

### ISSUE THREAD

**Issue by ZaDarkSide** [taye/interact.js#977]
### Expected behavior

You should be able to assign CSS selectors for corner edges.

### Actual behavior

Cannot assign CSS selectors for corner edges.

```js

	interact(el).resizable({
		edges: { top: '.top', left: '.left', right: '.right', bottom: '.bottom' }, // <= here you cannot set corners (diagonals) for resizing
	})

```

### System configuration
**interact.js version**: 1.10.17
**Browser name and version**: Edge 103, Chrome 103
**Operating System**: Windows 10

**Comment by taye** [comment]
If an element matches selectors for two edges that meet at a corner, then it will resize both edges.

```html
<div class="top right">↗</div>
```
