### ISSUE TITLE
Interact Js not working on Linux based systems

### ISSUE THREAD

**Issue by holema** [taye/interact.js#983]
Hello @taye,

I know this issue is a duplicate of #967.

I have the same problem as described in the issu, that on some linux machines there is no way to drag the window.
Is it possible to support the project to get this bug fixed?

Best regards

**Comment by taye** [comment]
This is likely a distro-specific issue with Chrome/Chromium. I don't think there's much I can do on the side of this library.

**Comment by GwenDragon** [comment]
@taye You should add information on the project website and in documentation that the library does not work on Linux.
Would be good for users who want to use the lib on all OS.
Thanks.

**Comment by holema** [comment]
@GwenDragon,

I use https://github.com/daybrush/moveable as a alternative because I had a usecase where it has work on a linux based system.
There you have think different but it works almost as good as interact.js

**Comment by GwenDragon** [comment]
The lib does not on Linux with Chromium 108/109 or other Chromium-related browsers.
The issue is foxed now. Thanks to Taye.
